sprite $Active_Directory_Sm [96x84/16z] {
xPU9hfqm34GBiPt0_tzmYHbDS2N4uuAxdwulGiVcpjpjsn_4VqgPClLgPedwsJOaps_EbAKlvcYIVZ8mv_Z53AI52oIfcsHAMpyjOWlCITqaITqa9QcRPCeA
5sXIDycSjZv8wYOfITqaKqutYRxPpQo84QxgFg2-7h52h-h-skgh4Sys_6fMMrkMzcB45lNkNzwBk0o_wzs_lXRnDFGsz6jzAs8vR5-XZ_xoKhZgTjS7lqsF
kmb_epxuzPtrrTpkUlWVHmmzCEeNjIEFkqd_wZJJCA0yx2ReJznbzQUNnW7JqsvY_RRzgNNxL-C0UHekrhVkz_zWm9E8DUfzRVURtq0SyCxwxlV_LdKUH0nz
M1z-yuZZWEcZReees9GAFuR50V99DsM3ZquTVaF4dOyYHZU50x0m_BY1EE1-kBA3zUbdsd52kTrD0Mma_Nxouu3fzle0szBFGCZDYADU-6ZJpuw60VETRcfO
NuEV4KU_tkqcrwyYmS-8oOs89QxlJwt-R_GZT8A8RuShFKdf3F-ZY3Ng-ve2ejzlx3hYw_N7Jz4V8zQlHMpdwzF_869qCwvFjBKA8v_5dH3nLxk9J-DD23v0
s-46wdwLVJ5YYVhkhqE_7nqxMXLRrEk86MwKBHhrVdG0PyQ8BxiPPMiLtX2F5E3CZwuYnlfQYeYOMOr-etxumyZBYD7DqWSCFVmumH7zuogzZBX0lo7yCa7_
qFSZ-CF84F5PDuiZ_BHFlxPujFiRHru-YmNhEqRNAk3m1K050tZLObVFuXdh0uEhxmegJdX7gfLNNRvGwrZVgNIH_GWl61WGjsV4fzqSQ5lN1Zq7n1DLzICb
fn7xQOa88Ie1ZPn7p6v6v18Dd4JCRhuuuAoRpmSWulDkHZuQ42DMIq33-Wdm1iHIaFpzmIm9GFzB-Szt
}

