sprite $Active_Directory [96x83/16z] {
xPVHRlGe34QtmhPntl-1Lx784KoQpMO2T_skAgl_CVXu-3l_JCnVYibIlhcNXNXnTrk7__4zwoQadlbP9TVTpTnrdLpR-LxMoSq6jl3uPeiKQ-9RWpMxQJJG
LTF9BDZHml5HlERuQnGBU2wmHkuQnGf-WMBahfeGSWdFqCI7Pzq5m7ysa6boLJMPRkuJ5RERcWrqXzRgKoTaYMyNI7x47CNiPe_t6a43jtd7ruRV-TiqnV8h
VfkW6BaDxzxmy2SyGyhnjSF3H_4xkPcw9_7mNoisyAgsmni-td-AaKiC_3RfeVOyFl4jaXwcGmDzAvVpUspX4Qxw-g5cDqaDLukwzzcxlLPif-DhyhEHwhi_
9jXD4c6DR_dZqE3htIGULPFFp_fAiPocO_3pBdk-sr7aYi3FfO7l4PhvHZ6xANjK0SAddUeNEufSoI0NFkFg6zXZkTA2KFXK-WRwKAwGN7tu247_SyKv7SAq
uMEaRs0FvH9Gy57SyaXnxgOCnpSvynaQ3UoXN8vVqpByxhqZ3_wdAUDqB2AxZNnsbA3uuV4Zd3s5Z-AnWJtPJUGY0dwlcA3uiLpomRSlBg2VSbswm4VnHmEv
b-kZN3dpNoWU7nxamkV0tJDarZNG_oitJpCUNxFcDYXMCsfwfzZTfIIg_RdC-QdLOUXkMSpQlM9rjr9AeXeh5Fo16buUVi_k5UTkbhr1zrsbWWSLso_yGF5_
oYrxXYyJag5bpp_rHF7bmvDyKFdlZkCx-4t1Pp5_xrQnvNIIxmx-uFjOOnhqj9jFiQJSZ7QeOpvPwchPWUB6dL1y8JVvjOAg1v_QqNFdPosBSVCCQSfjwRwh
i9zTZHVRAEPuBXJpyC1NK5MEABMDadAZK2KyGwVT95fZQtZIQlcHeu6FU2PqBHV7KLsBzF6iVJv94MwmBtQKwPmYDr5oTG7aJcsWfzsypFC6AExbJcmmJgWW
Tre35DyVN-IbOl554Ow_8boWs28y0Yxpbty1
}

