sprite $CD_DVD_Sm [96x96/16z] {
xPgBihGu28Gdf2c2x__0MvR_T3b4qCpP-sxNxLoRBtHKr7dz8_I_16h3TurX2laThHlKjqckQB-7EyQMQk2dNR7jHYQ_3xgR0h8BW9h_V14oibQtLsjo2iNb
Yr2DvZB_yf2mXAr6ZVS_7ekFz1HRkDOagy9h7yBxRnSwxmSItGDz47mj1PGyRPReIe-q-DjsQI_IZoNeKtjl2_Hx0R671JJhJKv_IEi2jNrDVmYXG1gjhj5J
_JPa-PR-l0B9_VTTC5RfOm4lZrh_cfuXMzNyjaOVPSMnmr-jqrFTKqXRF2dCuYQoREyiqqVrhiaU6WlToUcbz-jDY6Hh7ihf8_wl1U0Alptrp-5tZGjKkJbr
FAC_X8i4B8GRzP2U2uXRYFYPdj8pWIdTLwadz9J7XCVzvPdsEJrbCM4cKaXWxfkxQKdFX4Dx_FxAHbbFw9C6wMsy27S0cjApGPgS6r9uV-iOxH9wxY3_R7zx
PiyA5kdp06HkVukxbzOie0az0v3p_zjyjJfVbjtd0hYcvo6CDDxs5d_j5mL6e4y3vZSd-bC5sayB2FOXO3lx8z9Je7qieD8h_n6sPp8fMEhl_Pd_HzWjobF_
hVRtu9_CETllw4_xqfy5iE2VJca_ysU-wHZrJV_1VBa_CtjPtp-W_-duJQSqJVr7YWyUN_HFPynU7By9FS1J0cUtX3vjq95VkwJlOAGyFoVqsGBu_qrcUi2v
vNbvpsTCdGjydD4bqeFNbzC6BMPCYmNY1QbzqeFR_nHmDI6FUFsTx_3bH8_1U1cmP_HiqL4ZVnhJo0_6Sme0vOIy8r6ER0RhRCyMnsSDz54mvpEjNEsz-ySq
8TpVMtK0UvTVfOJj2GrwF267REjRHUwWSJlVK_UZgbsKn1qz9ObpFesFOm4rVRw0-bQK2wZe7o-0wKuBS4dK9xKLV2v0S_ge4b-oPxQewUi5r8z9chD35Jsr
z129lxAKFagM7o8P8wZegQpvLaQpeQIl2upwHhHjB93Grn6Fk_jen0AredreVbf0dz2ZGuBzmmVGB50Bw65xH_kyW7MvfGSWSU6FNryuxka1X6Mll3lIalxW
H_zuORFsViUB2dYh4Tvb-VtKq9B-M03oYIWNlAe0IfqJqPeQ9pRJI4zpIzuFhhxVD4MaLntEDwZo_HjKQfY-PJP-fvVCeh_x--KeM66Er-yXw9YzX-9t_dp2
hmyex450Nly8_Q_V
}

