sprite $CD_DVD [96x96/16z] {
xPg9ikCu24KD657S___VMQXaK5uCKjflzZwrzt8vGbueAyV_2w8_9rTqcEE1sr2XxyiUZWjyo7U4svJePkO-LRDx9MWyaryRGgB3WM3G3wSRWg8FzAnXTCEz
xW0TH6e_Ma4HRQ4cFE3GW7wMphxwJnHa1PTFvKSJVj0CssTBC03UjfI-80x0zjB9KsPfdqrAfnu10EuDtc3cwAbinVlngVtlY6yKaAQFdNtG5UZZr_Q1BGhG
7VjdWMQJ_OvzuDtk6U0tx8D6KG7SiG-al7aOWDoo3xIASM3Sj0-ABYlWj-q3l-mG0BeT7-XLr5XqPnsV660NTzPD-qG0q9k-VbkyZBS5VAhVf3FBsmB6XvS-
j_eYNtVJWQDdsrwY05u2PVrsthSFxAKXrki7s_Q1lkmmzl8ZUcqVp96InHfu-7CkR-spGUkBFs53ujhP1pfTGGxGqJCYzW40Q-o34_1ilwydEfy1N6hx8AK5
6DlnMQ2nVzq01NJL7FyAOALzC02j7mvqqFpYz7S0RUpd3JQ0hY_tvz_x5V36FZROgeSFHVoZ1A78XrRs0U3bvKCJeyXtM6KVE93vpQJWy6i0AUpx_8XFKEUV
QT_cMsrFtEHh-E_dftqYJVv8-xu_fNsVhsdVvnVso_v8pJdbevinlSxluZFVWMxEiJBVk_XyG1l0TJmfK6vl7J-zWGSWpOnPDIXMJLNygS2OdyzKJcdN2tZ-
T-Bt-D_9vxC0riwOTbLWlgZVxSzpUi43te-m3hphqv4Gp_71TDKum5qyozS2UCeb_69_Ak3pV5B5Pm7CwSx76vJsqVunprTDV30GED1zUs89-wdz0O0sFXWE
13wE6dha0tYPFxIF3qHr31NXeuMZFN5D5WtY1c6HOm69Ptlo2jgUx_bO4EsP6C3uPBwdzJmvZXa0l6aVzF4C81Lo0NlswmuzTpSX0BosJ_Rri-JQFk6zxYS0
TDU-ts99_Ga5VDS-wBx_wlMgR6sVq8TVyGY0hksJ-YiUbtyZI_k4g-PhixBMVhq0RZ-XUb6WW2_trljF_xwqJ-Z27hIuyxonxpkq-G7TfRLFplF5TVi0mC_M
FkFFEUtC-FNnouxzxt2UvkqUKaK1axLzL9W_hpXzS3wbp4lxFpgauVJP-Ph9oZwWvnckVdnqQdLy8cneUjCk0NOsze4Q6lcEWV0QdVrZfXktJgzjd5VsEkpk
2VQXdhyOqBJNCSnp6Bs332GU837vP_q-eVzzXIExzJtPF_aL
}

