sprite $Cell_phone_Sm [96x205/16z] {
xTZPagCu48LXXo0tEVp-hpkTTWsdJ1gGaBDNd-k9xy-2eRTBvZxxxBFFoezbyjDzQRxZPmh5rto-h_HSnVTHQRtVrtpwJ4pSMkZL9o9Y18uBfKClhbDF0Ijj
ZuO8YUF2SdaHRNpuu8bHsFAhJ1udCVZdVeODNvccCXtwqpoNfH02A0puBmjCeN3QZuNu7ePyt_SF0Gbi7lA9Q5K80QQH-sbLm1YRH-xtuNkVmrj0uPIFGlWS
dXBJ6P-0KLaLU1NWCdA_O_WPNduDKxyF_G4L5E9xcBlz641X8YJEta_pYWy5l8R1vuE0qCO7zwRxHRmGVuP-7pny3w20p-6C3tvrlsyEXS7xuOS2tTVdWz_m
LHM5C_u6puA2JYZq-QxFH6Qo_eoWtuVFeVlv46cjrIJyxnCA62q-7TtlvrUVANpmkaoUBolb_cV4upzsklyrvH3GfM26GklkvyElffltcuzV7baQxbSKNWHG
e6Zml7t_ufSBVIz05-YFVMdbQpFnrEHVBeo2XFiH87niFkyr-Ky5wE1V1igbtTyk883NF4Dlz6CXtez0eGbIktyfeH02zUdkYTjy56GfHDrNxVivskx7Whsy
7_yziVJviG0Tllt_WJABIhSV2ok_FeudFkN7maj_6l9HyAru-A9dV1GKXGG_5iRzxKA2ZqAYxrQEZ_sLFk_xz1vVttK_UFYwuzEuBwhsL_kSVJzd-aoSwtFg
_Nv-hr_Xyw7FOtxw_SwFt__x-vMJ_MgKvOjL50xzskdxjABGuLE37me9z_i4XOJxyHfScTllTxxD5v5GEBnVtAyDlh0y5wODlvxp7VUXeDCRVH44D1J6V3oS
M2XDlXtuAruq54Pyu0YeBWKfGxxWyK1_1520Npjzv-FqiKNpFo3R6Tzr_t0jwA7mqdT-pvS7_sC6NbH2mHVzn_bxFkEBCWIW-tq3FhvO55Gnvmqg-6QVuJkm
UZfggyBP-tKfwBE_3FUVyMaM5333t1dmfsbLG00RyaC1ElW-dvzyB-ZtWgc-qG-5u_jLhS_t4VurfiMlVJuACL67_LX8y4CXmVV2ugNuiL2t_DhlnyAsV-tt
CGQRuAEGvgCGVUV7VHJwVHLjyQTPJjuF_s1szdvDzDK3VxBl6_Ilk_Sd-qFlb-7dF1_d4tt-atqydrlQ_R_Q5_NLH7_y_kilz-llUtyTll_lzsyx_iU_7lYM
xAkD-zUi--kXRsgMw9kPPlhuzocPKtm438Kk_xRl--fZnaa-2fBaey1z_lNGZuLcNzhyM4Zm4K1Xs2UphG8D-9XQMs7Rl-twCzpjGh-FgUqLb4RzsJO3AFJx
6CojmhpZNmzzsUPH6F2dBTvMXJuVs-3v8iwWiENxzdnvwTFZzONr-zChtYw-8Hy13NoxVuFVMgZlz540xzCMN-4VhYXydutwiI3WFT3WN-4t5YfcPTYF1JOG
zaOVOnW9le-oV1IoV1GinyTcQ_1ly0SAARvliYmVXHmVAvhbev3aeo2xFW_GA6pvD0IZmA_y2drylFRhD6p60lnoUVy8ltqcZVJ7Bh_TFlliiy_-0m
}

