sprite $Cell_Phone [96x216/16z] {
xTY7akEu3eLXCu04A5U__-Dk2IeFn1uUKsWjDnetRlh-OqwUnt_-FlUviDywFb7HIsiQaOYEGYqB2Y6H1evRyJpfABZykD_53t0ENDHVNsBN_kxqAb2wgbEv
NWY_0fUUa_HW0NyBY5TrLw7_gpczdN7IhnOsEUskcypUtgveO5RODYavnH1YobM03mhK5Q3FXNACcIeZ7nSiKD8DFmJyIgT2m7vww-US4onOe51mxZU_B-1N
2Z_qzHoVmUlZWdqns6VmlxyU4UM02iMEWdS_Bk1NyllAE3w3o_SN_Ez_kgum3dZtanPU3i7F07pFVZLcdy7__fqnBNZVd_hzgA21U_lDBxMC2eN8xv_dcrzH
mUzdidddG2rnz4hEzwSCzgF2ZVUXtjVh2dwVqFk_Zlk2p-y3XKO-Voli_wcNtvzobMe1uystWbsWg-z3hJKjeFVXSI6Qdw5FwcjXm9klzrj1VIq3NmDDJmll
VJaLmb58HF7uFqEVZlUHB4S1Fu_wiXSiO9TAGVlLVpoEWl1l0Uu3LeYn-vNFu97qzVFXlmgDLGVxzLvJGmhX4KBKhtSHlCzh_xT2vwF0BkDVWgbFvfyBrQxN
-q2m7xI7Fjb-M60xAzJp9uWFS6JxJvUiWFPRG9y6-cJ-e21ulpH-wANmyFjMWFkbrU-OnxV2UFx-5_k_dHdvfVTnGNh__F2bCdlsuuBv1kPQgsC_AFJxxO5Y
ANxV2dmKe4_5vUE2yCYFBrySFYfWdnq-BgpohR3Ajy8gNmjZl_fyVF7bD_FBpF_uol_C__Zbjbyd-rVwvKVxcsE_nqy-N-VJdx9VXduXAlVtwtpq_hxzJh-K
fVkLN-Wh_m_Stpg_Ob_ldfyS_hBzJUYUB-zyQLt1_pwCVRqgRJ_wwNxr6_11mRKV-xY0_URszTY-71n-h1VzMgeL7FjdlWLgHONxVjt_XGltzwkE2zXNVhvV
vyyAkRKcpUdRw-32t6-p_VqnDolSycr-xrlXfbzjlV5wOeLx-qVp-uBv3VZRmBUd0NvVyFlAInF0TmNi2_AFfzT_7FiihyBOP-mNVPsc9unubbUX-dp5rEyB
t9_eDJtajw5VQb5VCfyBly_Ny_gsNrAomdY-tWtV2jzv473wk23T8N-R-A00UB-F2i9JNpo-5IxkPwzl1TNvYjyylXLKN-1R0V0tVJsomWhV2cs13mhGtnm-
B1XlVfxwRFwiq4RxnUdZGXljz_kuWFOtXmyBOB_RnuML-xKWw_Rh5UHlo_oqsCyoyNcfpoltgyxt_GPzvhhGLtsfp_yAN_dL_XFu7x_z_Vx7VoxqjyNxjwNx
c_d_rVqV_xdGtnRlL_xly-KVxTFg_UsjB-etARVzhu6lFBTc1RTFxtpbxVTFVxx_2VUBYFmgb9_usxlz-YyzApZVPuFx3GU5k_v-eB1WVrVm-bzelpWAxlTn
5VpxKG0KlFjPN0NiFyVxISHH0Fw6toV8B605xEFz3vxmVS7lvxck1PhwNqF_KSLHyEz_XAbk1Uz-lJpdhU3RZr-eWHCU-igRF_j6qAGroVlLXW-_3oxOV3d-
0e31VdYXTEltYzZ7-_75Qe6ZaExlxmlyxSisk_t99RRtqO33_vhvzcjbktnZFofq0Rcn7nqX5FjFZm--LFtxyOMoShyMwa9VB_8g7nUm_wM-zv8itA-NPTL-
AwpShy3A_NfbiQ_V7B3_1BxdOftvJthSkiZ8t_aDw9vBZ7oW-mioyYKx2CytXwEPN82dy5XpjDIt7t_AAX_VvpxtkJy
}

