sprite $Cluster_server [96x95/16z] {
vTdPOkCg30PW0rh0pRp_wvw8tuumAClaz6vqr-sJBB3YukqVYLn8LBLMLH4gwJVj8dLVeahv3JiHx30gfVzP-O2tLX6jDV-kbkzrRYVTktw4zgZryKFwJgS3
gA2PY4h9fH0H8ycPel4NdMduKyEZ_P99XXIj_9sUr4ldZ6zPvIpCH4UwH6g133Nz1K-k2tMRP0XJXPALCMIWZtdrpaYsEedu7akAUmOU5a8_qrF3xID7zOKG
GGhQDaNKNbB-T66R7bQolXUAKwYcpT9uayfxlXVF5l2tOX6dO3HeIV093oXXvyGf38FlFQBtlFBeMwGW1VOe_351-On7t7tweJL5nvF-mFyqGGO_njt_S_lH
7CpLThlTu4y9yZE_WL_zlJKfoUr4slQVrKU2zeJNAoyM3x-gC9MISY4MqNhweci2VJeKglEuwVCx7xys9U20JttGUjIcztXRFqWTeiLBqFDUVFG_tPxxRTlw
RNpnrVeGTaTNt-RFpnFVUFEbxiiIKB1t6gy-s_oKq6zciFbJ_MfMkl9ypocHpmLFA7BrXGq0l_XgsDN7teby9j_sAMt9OaDaaSX7XvRoEVRHf3KITHk-o781
F7M_KkHx59TpWJtwyke2oF8HlVBJfIEo-Z9V05tsViFOZNtedY7qPTf2zNBh2bc4FlGaYfQcPxvC3ShZwX8YyA7Zhpr3vCkJBLfjTO-OVEZOvqk6nPVB1RIf
FOYB3zrtYsU8VRaqAFcd8dcuF-i0oYjVWXqas3rJWWgdJCyy-EvpVtmUaaVxbUO46Re_ZxYU9BtmPLa0jFyIq9Fdwna8QztQIr-cMpZZvXqYGPyUgQ1JRUwN
hGI-F1OWpykBs8A7DkX5g_l70gs-d7uvXazRV4zG_5kvFuh3XvwGTFO52umPAh6F30ZeOlpf7oC3QKZcW2-7NsS_bo73OSda9-vbIWd7dllgszDzbZF31clW
DVd7o_CCQjl-XIyAkbl6mn_rAODSuvLVpDVp5YRc0wgIef4XM-pNDtvhXXaFNr8qClftqxT-EdpewyY0BXJvkkoVo3-iv2F3Ct3NkRNdFY_xV_55E1mPNSV8
MFrpVrBaY_jiVZWoae-CsETm_i1NzqLa7XckWmzyp1zyF7BarzaVCoGV6R6F-HdCV_YfoE4RBzF860O4-9qZF_pyWdydCZzylVlCPmRe9FBAn-TNE43H7ywR
k1-E3EVXHzi72xpu-kY_m1z7HYhCyiOtT7d-SP_4jiyENzslVMGmJ-N3dzgVXkUtClcsEIA_3tzQol-17xKVZ-TKokYhjJyfV9tyj9I_-hYaeK6bb8klLQcE
lhY_bcy-n-r1Wrf10lXq_6ttzVJL_Ij_-7pPFVLwBiD84Flry2lyjVoRcC_hxa5OkcBXVgtjfU_yuFEwklx_8nAC_cw-GTtFHGv_BV_qULhTvGBASvymCk0x
V_NvA7yF_dz70lZruZVSqf8tsYSVlFkCpSF1-KD1cDzv-1qwbxms-CulFejPqT6U5iGJNwpzYmz-z6juJDalwkhtBcQ3kf-tBF3Nyl-uRujRdvnVaVjjzZ4o
PFB1ZxwVNmNdRuVF5xyTVgrAtL_BXxzqP-cGddvx-5toBNNnmO--dn_6Ht3Y_dxuRV7Nya_VQcmlJ_wb-stnsVZ91-y--FpwW5ZU-slvyFMZ0sw1lnz-btp9
1n-y-oiV9-1t_bm-_Fhn2mOLyAU_Tx_DFdZukYtLnv7DQ84F4lwbVFZjqnSygPhoqb_Bl_M_ITj78PwW-tsUI2VXJ-L3t-KlNpwsqwzvMtql__R5QrJ5tvXV
STK27lvGFlHTqrVlJ_666lv-yS7lY5Q-V_-hb0hrHN4VvU-_y8OPW9Qy-D_h7aL7gCUkMlVb_Vjlf5X3QVkDAAnjffjosNunKYOMxI5CEMt_IFm7
}

