sprite $Communication__Discussion [96x87/16z] {
xPL7SiKm34C1SgJHwFxtJK_uVxXm8PJgjxOVe8upNF2U5UgCN9wHopDgUqQjpuZjcRf-8xoa1xSRLFI1921ttvEWlmk8Km5RxGEM_PHz6cpN3yhpizGFOelY
1bgXH-elzkDC_vCNd5OVxFGZVQKCg3sHcp-Nx65Gjy-QmqjBR-E9PdipZksnDjvf25HRmCSD7OA4f9S580LmVC9HJq0m4WRX3cFsEyf4W6T_Xv0sCh_7ltv-
cFqDAlJxC-CBfuTEO5bzchi3jcZspPzXkZzrxL_8zp_L8xX_lyozdk0j4Wot-0kixyf6v0JwEwpl-iPGcf4qluNrKzNjlhJIlv5WzVd92K5i0i6jut4WOceu
PbVu8m4MKuC-fymVzuwzsNrEcJ_VR3Qcq1yqudrgrFuO0-UK-mEYNVxBV_al_-NV3D3x0-jQVuPDxSy9Od_6r_fZ8RA_GOIrv4_b9GiH_aw8yV27NOhrL_ym
B8ADSCTkBXu1
}

