sprite $Database_Partision_4 [96x57/16z] {
xPW7afuw40Q_YKY4-r_tiLF2Oso1_bZfkJUdRaR4MlmluByXV0HYCVUfXvk-N25Y5bNpNqnTdA6cAi-4IDJCFDtN2G4WKqCVRR1QupvXsA4f6IL810ZKnWcD
NvpEk5pRLVNOPM8cBArW_GG3xFrzqe6rOIhCPXP9rluKPhj7RBf0E_R40aB0rfc20VNKZGea-YTcRQd8J9ar4Wt5ZkP2zU5BVKwXmjec8Ma9ewOF9Xy6I7Qq
YmK21BbkR9wC0jAuAt3p4p7bneyI9_zW2fLZfS0I2pLkyCa_dW87CZYvE_vXGl632YFy39AxATBFp0yaEAzCCGy2lftYzxl7g82T40VdW-eYmSZ0CC5W3UmW
behD563viv7w35mb6AGdB1jcrZpYPmwzd08iB6VYzoBKJMH0tNEfx9TQbnoXCmNbvUyweKAn9-9NxTZuHSE_RV6HECafedr_MYIAW2IzyN6ho48ccZy-FfPG
na7TVlDlQqlp6H6cuPdN2-YwfJ-ehP1J01YSUSb93fj3cVuOON529dAS1nE7NCgwRZt_kYv5BnuBRnF2Z0RxlApAzSA_B7Cn0XAYRY7W7I8WvNN-KG1sxPzh
BKxeGD5AvGaIhxNEF_u5q3l_3Y1kmdW85lDIW_2lWDpx2o2bJ9ExcmepTQTX4RMub9NoeZymCzsHdz0EiqWx93te-Fablt0W8p-1lketw5Vzwx8DZnzxnx-E
_CNBMzk_tlc3T_m5z5M_0_Ezd-7l-MlwyUdZ9_q8QFcmVqBu5qAZVjPVWB9j5OdCd_HNe2oA4xPyphyAA_x2weVyIr5q8Qzl7vzr4jn0wc-SNyKOOqYyFEyl
Ba__Nsdi3qoOy294OGpIVtewUOD__0S
}

