sprite $Database_Partision_3 [96x57/16z] {
xPPNei8w30LrT2IdmlwN-umfkWwvnhJNvv-PA751_Wj0xy6drFIK6TAm9JaLRtX9ynH4O9inyfbve7A2xaNVJWI9FGazQIqA7qsW63qAvXzCW6RcLU7MsnPQ
3LVPGUr29AZkhXf3T4_1Eplj9nwDU6r-LqYT1P3XtoGWKNXg2gtq_3N1kk3T1Qtr-uaegFip2JU355Xe9ap3NoKyOvcSIAeAd9p8-lhbFquOoxTGPZG3pGcD
zP4IGvaQ_jOKyXDpbnjCoKuk8BVjjC_CtJNyZK9081whR90CCnPBDjrzOILx4beUcPbOl0_MBAwt1nycoXgg3f1cerwWPSfMWXf7I6-YVFq8D1ku7d_DWk_g
ou-rLK0yV7V28G9AnXR42BkDwoApxaHPcLYi-8-hILtOD01beJTH9hRrUF4VZoEg0czJg4IhCs5QNEFn6Fx3QbBFK0gAE9xw4aOKaQs7odyup2O5H0EnlJiI
8OVFMRZnh-kSK2LYStSb55BWkAphddzTbi4WbqQyBpvACFvTCStBilxgN-PvTCWD0Ar4EV7b1jCqPttRdndB0WiYLK16je0-pfaU_pIDuvYSeMa1q8VyWsbw
oZyEcPJSI6Hsfhdy0HuouvD-vt3nnnLBgYAZIbvNP4el-KSHxlWPzzM_nF-__ty_rc_vLqW9B5l_14dl-nV8XMdd_7dRFqd0-TF-nQJ2bye_lETVNBR0f_13
_0t_Q92WIho_VWP2VWSsJA_xHwSy1lGN_4CYf1-GdbA7F-CCzNFW18FYlu62V1B8Vum_
}

