sprite $Database_sm [96x65/16z] {
xTY5RiCm58NXYyRc_Lzt1UaMx2QcYPfFDFnFd0uBF--4ICJC8gfELKIOcGWH9X7VYa--mgdGS5jTmLS98pJ3MziSBHXbQhnkqpfX7CCUP7aON_22y0tBY_5J
kFe2YcbU-B91K28nFHk-IeeyivZPKvJtYFXEXZRgjudX2TciEmKLbyzzfpWOaEBwZV22Kp1K3Z1zesp0bG_mkbDuhm0D0yCFj-KDsiByAPIWK5qO-hQmUec8
9q-XWb0Ol4tbX33K12mcUaOiZg-L02Pl4UTEyH47Z5j-xM-sq72A0XF0Httxx6-NBENVFGqJXF1EycMhzIyvUuHFY4Z4LKIL3_SvNxxrhv9368QQSjxlvvIY
ubWyffHR-bUEe0kvUDNUZo4uHcY2v4A8lVqhxvK9SQUCnEfz2ADzTwCgV4DNI3TyPNzRh-XVsOHz0xJqp_xPF_lnF_eHZFn7N-0fhUydU1LNzoEyYslxbZT-
PTz3IVAgVXQemRYc7n6-89Tc-yaHx94mqmy2Xr3yM3yeGXiKrzjtWj07YKMF-ofCEF_aeULVNqE4ttRw0m
}

