sprite $Database_cube_Sm [96x105/16z] {
xTU9ijem38NXQtcJ3Rp_wtQ88_FR14Cdqxrdbhj_HuGgSRz-PlxdVzmFrNrAyOSrk92sHFVZT3Jy0Fs7DKnw2YD_FXAfdv7M3TH3Yd9UZK7GGFsUAEVqbjxW
iGXxefpKsS3PqN12PmDdFzaWOUBjoXmM-BFppu0_f_CrKFVyTD85bt0L7uAWWVfSXWilyQFtmNaVxkc82FKMx_13wDQmqBUqXeP0Ht3xWOw6XSw6OvqDrDSD
JKQ3i7hYGQ1WVVSMpyXSF-cC2v-jWpph_BJPlDz5GSD2PmDr2Ju4Db0VNuhpA_rXEEZsJkDRmisOjm-wnC77smbzI_01FwNEXZ4kbpJxiHdGKO06wcoWhlha
Jx_cns0RKC08TIsZxvhFWh41EXgeMx9k_En7yuaywO9F0tH8UkX7-1wxF-dzji6XX4TVsVbZF_dv32lYs1N61ayzwri_xdxAKLwiDXU2GihTBw_ybBgVSuBX
F886wbdfryNrsNWqO7es33hyyifFQVHLCr_1s22JdhNvErzNruT_WORZTKZvsQ-JBqqtV_WB5z10VVHrzqltcPMl6h7Kq5sKxclt6r_ayFHDNyqlfQIEGa_f
bLyYQ3GqFp_vR30zqbVwrCU6Gx-qiC65ZJ_qgSzny9L-YqhNHryVVZIAhk1siF1BtNxU-Ta7g77mSIXwwtU--GzU7_hbClbyzBk0Aqg_7lh6XwxNov7FmuLV
-iPd-D3haS-2JScV-ggQGvTguqVVcn_upONV-DtFDjLdVeYkDwpytFnakkZkNrxwUVDpxWs3NvlV-EwRdajvu-TilcgIrtxdir0t__B2p_JH8Fc5_xWoMNNj
DzryRSb-QAZcDnxzslZcD_uw-Zd3rvxCrp_wfdyblSUsMoxVuokF2ENXHzDn8AH_lOw-f6E_tE60XitlkWZzQlvMuEV_y1_uPVDBYRrXKqrl-siy_QiAR3J4
W_ddfrVNywPq_k53PoIDVh7vqG0zA_rg_f7-ECF2Bqg_rkoemo_qkyu47ZOvF_rQiq3FIhyst-AI7_oSSUytddvjiGCL_GBVzEjjzd6RTR7fQr_Djn-hTFrw
ctpTCZRGhszywfSxF_fHzqHyQ-qh_Ph59hllxkswyYtnXP-VV3m7v7hFSlxOdox1_4hVUFEpOBkbwKjV5SjqxEl3TwPVBis_NT_vfPGayEl2DxrUp7yxVz5I
S56zphxnYNhp_SxVX7uQ_JtgvuP2Fxckr-xBzMRpBtmBJfJmDxx_8uYryJR_RJL_6lt2ymTz763AwBVnuME1ov7l7a-NtU-wayqt_deVe-dj-C3uEr-E_3ez
luBfgVZcNnw-fpx6vtBirresU8YBMaR_kllL7-cjuTZV6joW9zLYll6RN-Hh4NVeMmDrBV1j_lSvz2tPcKxVTFZhXCvNyxbVslbA_zBQFslGnh_sI_Thyw5_
4gztVktNxjVqcSf8NlY5VetVZTi2hVpQV5thwuR9rzqly4_cs6zybJEmnPVPB-EHv7o3qj_v3Frq9CC_EB2VZql5_8L-Ah4qFtxzgFYllod_yp_V
}

