sprite $Database_Partision_5 [96x57/16z] {
xPLNWkig40LFz-a6bFQ_tJSWD6WkM8ult_foh3BH-B-Wlo3u2ABqu00OEzmeBskLDFDGA06BOzpDgFg4c-QDK3008LvZWlie_Kmu2hplTogl4zBaNQ9suWrC
iSyXSGiryyOeOQKmQg0WvR7hs5wuIW2w1yu5fyNeMMxjPHlRxoHG0z-Z2FkiU8nkiT4Ln1fN2G1iWU3OYKFOwUyc383LfV0GYe4UutL0IDfZ2G9mtsSb15Tw
wBHTG0iqu_7e-s5Ev8SaYvu2A0eI_BGMOt2292fcnqDf3zLTp_l1_HmO5_G9FzsroLNKwlNH8ZVycc6cFZ8pxbXcVtHC-pvLv-C-BZG_Usn0_R0Nz7lIMg8m
cd_oWGJB9yqFJANu2IXjE0f5HVb0uZZath3pIBh4UJleLO80RvyB5MHoZkV4eMTRup42G2zF7XNgRaLK6ow7sfRyKBGmjaDe7Tw17VFWsInBATgs6cuMaD47
xm_kEzXtxxfL_xPDKWjTGjhgFvGu_kfbshRcpqCew2cX49Bdcl5UmeYTUMl-4fZtGXl5UEFQa4Ckku70yjE_VZ47QOdwmH4sZgYWmBI6pby2wv9CqD3BOz6W
7cumpCkQ_VFGlynpydD2H6vNgAfo-ZJ3DC_BjV-BAJa5ErsgA0KTGf--xBi_TlxrxC-aw1nvHbrwJ5Fcy2_qTVpxcp-b66C8RgI83An2qhtSo2dzy6UsIxyp
PdyE1C-OrTaMgNz1nxqVN_43xFtK2k_wqxHTpNzwqv_w_VDHVmIcVxC_TVxry_xh_MDl-jEbFuNqZdyw_tvPX-VthVqVuvgTWemiHV-clp-_Yw0o_VhxAU5j
_uG6vq_kdw8o_C2NJ_eNHuTF7_8loJ14V7hV7uaBnEBqkZyvSH-Xl-1FWOB74TB3O_xWfE0rv0jMch-YyWNUuJT_
}

