sprite $Database_cube [96x105/16z] {
xTTfOkCg40HWiI_otF-wpwGB5JH4MVr-fMRtM5yHgqtmmVpbBoP4zq8zfcUYUvsElA31nMVIQngWpmt-jtNabtcCpTmGHVS_Au5XtXey_Qx_mfVXmpDp0yRJ
__Y5WguQeF_yJXleY947eVzabg2JPmFr7pI8tZBxhazhY0pzxnImmOjkjWrHTFCvsW4P6hovxhTV6_1GJCb_Rk5ia51lmM83TOxhVGD5FpGOFKthkBhXLeTx
NJKOeHnarR0Vrx3NmJDcAbuQrEPtts1Soxx0-BjnzP5XW_kmmK7VDqpZkZHuZUi6wCPvxzO6FERHeyOLQxzfeDx21gIR4jsmqOLZGzSfgd65ZdWs3BhXNt5L
3wsrGUdgBJVegNZwBLQzJlvsNCD-NAaNxOUnmRKi1UGt3IomJTT-Q1VSDQpZ6hpIkVQDty82DgWRRDZ0Wg4xvInydVpW-x1vDKpKj-CAlSU0rpw7EKJTCEfh
m_YwM_frz4FmWnzZi6nGkceOz9Xoyyl65vr-IcX0DiFa85DFkVcT7ttWzDKntsp7rStwvDTxVzrarmQZz9G_xQShH5J3kFQOj5_VyQFsBPsXmHr3uZFWl-pd
fv-3cHi6tThcfwJygdmF7NwQ_LmY6yoeXqW_Qp-l9-MuzTiL3KAe1_79b-OBd_G5hl5lVbhybcGNFSIjl-eMbsW_mqU36tJXcp_muaCVfY04XylsVa_sNR_n
e-Zrf3zyYrlzmjJwzXpoyC4t_n2zrDcF8Q9XyFENVNDqlPwZ7oNUo9V_AJ_29nzCrsVVn10HUuZm1HzyVnkM2dxqnuyAjZTaxLVnBNdwGQJ3re_y67h3wXVu
dK_DpnbpvOlj_hdtK_ElhTz_vAStFtMzNFwvznFyT5tpdX_fK__01wi_zvFNFlTld-KPyC-TdsOVzmpNAXyBYfxFkFMXmmT_DRYyzntqYuT_QX_wwXVB4sMb
3rsIkrzd_q4_BNwcdwmqq8UE-m-UFlY71G-IFldcoyOi3V03z3GTsE2Vgt-uUEUNajz04yMtNUU1RVMBrUSl-2CFlyNpyo9q-9s7BteUTMFG03_l_5eyB_1H
UEqxyQbZEe8qXEQJfu_f2LXxt1xOu4CFfwNVpxF6Aj_HRycOdyMlbv-WFnw3tnBnxqIUww-3xyYl_j7rnp_bSziaNzpMJzglajJrniy-Wj5JVjtvMVlHY7wU
ZN_i_Epx-C77wrCddyilubDlznVBf--wdflVjtxUtxhpy-JBP0LxMF2FnSyPVlzMxH9yuUcJXm-zdkxozVfp7lnI8XgKdtP-r-lPV2n_ye5tl-JnF4kU_dXW
Wzvu-jFw_UmN10tfpZVG6oy-bd_l8mdRflR1oxIPfjCNliNS-vXFDcWVirmxJr-oyOlsstbT5bdeDpvvx5VcytxP-hKFI87lcuxIop_f_qCE9e1lrEBNUfsC
iNu7lTpusS0UDuJcP-stu0rXyHlqKhj_qc_u8nvBNBxniS7qsAPVFeyCuf_XsCOcxLVnaMIxdld_Wtys_r_r57MCl_EnZRbyyV2XFvglTHtwjLJjHyoFylMH
vpx-AdZ79oz-rmlv-pXSVk_NsSzAlutDfRxhbyaNFfdZQp7f0x_2V-Bo-9SJF-VNS7mtGVc1Vks-FtwKUzyUFuujgmy-k-CtOlBYG_-jcBZuoHw_cZ3vmVok
Bcxtm_6IO7Eqn_-Kl_pbFm
}

