sprite $Database_server_Sm [96x99/16z] {
xTY7cgiw30HWMxOib-JzN_U6w3C21Ty3mgVkplRspso33zmVdUz4Il3pz93ebGG_K_zP3P1UeP_L09Wur8CmM_zP3O2lf8E6C4Ft4JcgOP8UaACRefkH47cz
Ra3lta6ueqDyHnM87dA16te8xAk6lXceb09s_PsF0j5p4T-eIq5KEkPymmU0SDJGDIJcnP_H41md4EM1RsuG7PBm9j_tbzi6qHDj_6hmGQRs1l1od9lW8-uQ
kkvZqhpLJqaQlEC4J1Fzb40TYP1zuU_vktCWHE75hpOVsNyvoNVzv_YbB0LXn9lzjFhBhpcE_JRBHqJ5t_9PAk8Fvi_sXP_e3-R_VByP_QJy0V-p_MRsGnZu
pD_qKtgV17FtH_FjVd0B-_Fyn0t8_X5_roTQvA7V-OVT9ueell0JVEONYlt1VBiFa3xym_b6__ryzJ_dt_KHbfSqyeMt-VtS7iHN_6sV6mQ-y3QVbkH29Bxm
atp6kg_dt_99_3hqcN_Ey1K_oIzZNtYB7uWvyOLN_eESsIz7ll2jeco_xUlvObjyuT--cb_pYijbsdgEHiGOGm00gm_Ro_38geGaASB0pyhVy7bhSzAuWX86
V-INWOzoZRFDe86JWlBpVh-ydRiUnJzL4RU-yDhlbtgSAnLfxvT37_cE6VjNAs3eotovSsEeGF7Bs0yzKJ9eq1LoLorhlwZzfeg-N-Rl_UfKmQMVKuBkbm-_
R7m7OAWGVkZNAaUSonMBe_nww7FWKWNozg7VtrI7pNCLSW0wusE3InLX_NHekFFhwfUj_tnMSESg8iXogC_dsESt6_lFHryo_7Nhymksn_E2_sZjmer9AAqz
DZxabHU_Ah_LId06frgR-9nuw3Vbbr8e-F_30vLIbC_1StxEH1W1FcT3HAASHxxpINpcAxb3dnA-4aC8_M-9xqRHqES0xNm2DyUNG5vzriT-tFauydL2MNpH
P-wNc-cYJzul-Hdx9Jz_l-J6VZZZatb_TgT2jlsQ7mTD-z6T3hGh-ott0R5Ssb_GS15RJkul1CuKmFp3_Ha5jmI0DRMVtmDYtuq7xps_vZruA_ET_m
}

