sprite $Database_server [96x123/16z] {
xThTTkig30HWMI01TlF-htiMIMOTmy942l7Tdikzss-ckCq__Ip_mhVg8QN4j-hfjWPEo1qDhAa9_rW7VqS3YwhUr03zhWOMWNz3mnP5PDx0o_guONq-z573
kXuY_Ak6GA_eLthDf255wALyfqyRe4ifRfzXNpP03pcxVSRuomRed3DyXrupRS1N9l35fyyRjfFkzFd98yC2fcSspU3jFZypQO1EafBRHq6uR80UKyVl0Fm_
GXZft_ZRl05wK0Nlyna4CVSL__yNRdbQtkQBWEakGwDh-jvl6vXRNHH-pzjzxHgWqnOL_9AlAkShVRgdEVbvnKy93Ti67VnmliqFy2iW_VtORBvnlpnz2DBS
5unyyD_vkKJe3VyxlzJJV_5nFj_kwz2Fd-OVVh_07v--tmypNrk_vpr-Qlrs_kr-ptjz6F1Dyt_fjxpJru5lc6_oO-_lsD_C_zeFGzzmF4k-uNYCVWJV-ARv
zlqoy0tphVkPjjZwtVmbNpLMCcZZVxZfSVcgmaJ4aalZWr_otuv68jhon0VlzS4aOO9lkhh7dy-l1dp3_1NVDlyRV-_zlEvBaAdVydwVYLXIRdp3yHXzF2sF
AHVujlaFcr-Trn-OmhVCD_g0D11HQdpmyFS5lr8IiTyst-Q3hqplvr_xEtp3rJNwQU0RZiVg9_YLWM-Ol-HRvllyFF3ppVw8X_zOyWtpVJvu-8PVpXN_mzLT
tlzflds_W3Vu3U_Q3mW--7LVckE1RxgwTZ-RVF0_y2tpxJwakG_UxUU1FxXVNFVttf_F_zijFlZ6pzV-aGDlP8xaYGyU_gviTUq-vYVORXzywxVp0n6oSGYl
9-2fHbL4OWoyuEUJBJNZTmqbyDWlKn_ZEOxV4UiwBlozzy7dqzjB8fOAxlmoyS77TyHI4Gm-vc_D6tl62ZdvuCT-URzz1TnQmV3BsCTyUVlM2lWHVYuctrk1
_GNGXQ-40bT5fAaF_kqJiwj2c5f_d_bei5P0l_R1m_TKX0fq_ZxtTmpQsehOfkBuob0S_kDHc93h2ju8-l4uq0F-x1Vmy1z_XvnleRbjOMOcPDFZxm6VICfk
yeyZ1ve5t74SZwUFwDZVUt_VoxnYarpgNHts8rkwz8_MBpaduQ7Dydu6YltdS6xyzdwnzNDAgiyxH2H44TMKu6F_gA7rXUZIHqE84VvuFyAbzQ7xVUplmsSV
-a_s8n4-z8aVVFlHK7teI_iDMJZ_ul3p5_k572dkyrTo9JlFHyWPyVWxapzIZ7uM-Ywidyy_2wz-9l5olmhmnLJrjHvtOyn--L_-0m
}

