sprite $Database_Partision_2 [96x57/16z] {
xPRhjgCW34QJV4caOll-ZplKciNo31IESx_i_zsRH6ML_WLO6dmdDM2-j365N3yne6h-OkdXmcgg4E5vDzI227GI828i1pgJ4DX7F0eV6_OKoXAC4toM3wPG
AcXZf0wY1LCBHbEW7lw4eMCFh4C4l3XiMHosTD2EVLWu6gYBcIamj3AUubZy07JqmuBiUY_C1HW5xT3MYtam3k1WiY34UdxQNJYE7mocqFthqzeQ327X7oJi
LG0HQUUDyf5_F0KJ4Qir0hs4rFqF4w22wDJz4TJtPrpO3rymcqu8rS0m8VKhiRahIYXWmRk444z_tBKH-jTYqOU923fPY8Hng3Npkn6aSVsDhq4ybLbt_sFJ
tI6jH3mV_Kn1-UdT7eV_yKYyUng9sDty5QMokzBZKVtth1I5cX00v-Ame61welb-yj_lgr9DnE9nOZH5oDdN8lpWtxRiJ2-am1J-kKJ82IblMyk_vPmq4lMp
62S0YP_1rvothh-GJAWMEDRL9kOC-IqNtlhNTRqb1mMdr05pI2i2JxTr7VfpyTyI4TnYwW4iC4-5swVyAIsBkvi28ipDFy1Gso_CbCA_pkod-dVCJ3Ms7T-W
QbmruRzs_ke_2WByJVxh-n_x_VBvNTCFtK_XD_JFxz-mVBVpy_QZti-DwOdaWV_Y-vE53jAFUFyJLP3h_h_FVhBI2SlVS__Pw2iiVIz_KceYVWi_wKN_ke3U
8Egf-9EdA-zFSj0OWL_vVXrCymXWFkTt0uIkmI6i_ixVaqlyvmi
}

