sprite $Data_jack_Sm [96x173/16z] {
xTU7QYjP48JXWSESCE__m2lAOIXQF-tREsVZRTiY-gkY5437F_r-t-zhk_tMTlkjRVLrMttTPlziRQklYAtzNpyR4fe5F9zWkgxjswSzdn3gFvnWzJSa13n9
gFVVat3N3tptX7f_qdllVphXNlzDGeU4qZwHV_qeuO7-xqwu9LHz_SJwJoGqQczyFQ6TsVowyVff5Tze3_0Rhskb_bZV-3vA2Jn_v2i9k0u6z5RnkRthkbRt
UPzQGkDrx4oVOrf2mNSyz9zpzlRS_a4VqnFO1vtc5w_-a53S9_RdXBo_1t1_9MH-r0s7_lSjIE3-SNsihu3LsUTnF83hwyx4p-fp_sK9x7Fzl3ydjC13_Qo_
hbNwnu42pmaDUPxVvX7F2Grm3aZuTQt6_JjyDd3_DKF0rT_wNReVhy_zoLS2rETzPk93UqWWFVULGFMTv_d5Hr_bWuq9q9_zhZ_r1vtulBzqQ2--9_Call5d
J_l3qvlsLuBRQug7-ZoF-sBVZREkQysmFlH7dxUvNXSI9l3i6-v-JE0F7-vlkll34ip-iQy3lnsT4dX-zwdz-F2FEm5V_Epd_O-GO05bVupnuLk2d_IQF-x-
klOcOSM0gzHVrqP8MAlgZzVFxNk2pL_pX_el-I41wfCFVEolCn_gkuyV-hc_IlvGGkglGlzx-zmtFlETp_lpFEnxUVPv7lQzUqzyg4z-VEMOFqvuVe4dVzoy
-VEQpNogpxxihsLwyAzhH7_-t1zUF_glEysFEll3xEYtZt-Sjy_retz-wPRWhnzzRgxRX_hONxXik_NbznUw5koJ-SAzk_UNFuxsvIzuzO1_szZ_r0lezg4-
-AR7_WfOvaUT_TD8y8zsPlqlwf_uVlAXFlIl-7Fjx0_rd-k_sGV-5_tvI_xwX_MV7_tNYRxpXVtdkfImmP_wKO0IdlNd_KNB4j2_SZ_MruCbFEJR5pbB0FzA
VCV5txeb57rVNhWYOeBvm9D_DpVR4zxvoVwyl0U8AVMV7pzfm0S5FFhJoakt1FkoM_3lyhPy2B037lhB5M_T_PlkBFeAK7MpGm3mcIzKE0Pe_Ael6sWO7tZq
pORnoxxf7C1ytbyt41TVzvDB-AgVjxz-wDS3Cb_NUWLtddqbZ2IWiWybCCxrsUU4V9vyVqzWdEkpdoIisfFBlkw4pykYpmdvEglcVxmTbd0ymyddXB7gwxZF
2Saw1TyJ2kExNqu0d7r-AK50mOU46Y-_cd2Lzk7hD7xTzsl3wzTzJe3sHPzVh5Trdpp1ngdxVEUMVJnXOtzTt-ehORD_jB7LLy9ENmbpgw-4dRuIraPVTwwj
lX8s-hg-rLV2PlzeOwUlXBdLLy9ENmbhgw-4ZRxkN5jz9MpqTNshhuJD_j66_9q9v_5Flz_t-_u
}

