sprite $Data_jack [96x173/16z] {
xTNjZYif38JXoA81S_yNl29YzbL2epeDyduUP_xcgHgtaxp-w_Dxp2pMJyairYSXnYSXnYSXqEy9KJu9mVwLBCGdW8GGFrqaXEpdwWcNnVKVOn5-Bqz2H7zu
aR3Xmuk4NP_rC1RLduHZVwtdFec4OtzEw1cN7VheCzwd98lO3mbbEy6mqrBFHIGelmSa4l2luVVPIh2L3fyxlvjWFpmwmtws4upoD_tXcVJGl-W_-LD2BRK-
IZ3e5Ly-fjOfGVWzu3uapmkgfJvAiEi2_whFTNxp96WVV0x8Sm1Jx5TyBcUnVdXy4hJFhDO_xqSduAljJFkH2ThNws6S1E7FzTVhWQ_ksJRsJt_1zodsoC_J
SIxtusEoFTo_VBgZ_fGW_SpwlzhVzcSk4_xqtI3NJm09kl-JzOy04fIVEKzuNP-4bG_FyOlwdPydwVrmFVByvsaau6EBzhf_QyqDVmuOnqDzSVwptnB-9qxz
ehP3VUsJmV5CxSNwXTzXU73-0H40Zx-uV8v7wDfdzVI79q2iN_ZS9lrr_Ifzv5Nxy_wP3Df_ucB_4u_VrK-S-hMgzjfdyvc4mRVcbVfx_RlAvccVt_wV2GjU
-syPdlhTzp8I5hhsXmu_kW__PVMTmCZrpFvt-LpmN-y4zuMk_GkTtUFtITxQJS0lzcS8AFWaRFMVsiFZzpkO4jRykZyy_XWhZOJgzDV-N1wVuPIehtrq7kxi
Ju_17--7yhS-2IwkP_BBpskz7sRuwCel933ANw_Vb_s9aBu_w3_9sjVNWz-TDvuV-DINFZVvm7TNwyTVJns-dVId-xA_fo_VDQ_xrz6_azNKVhG_3tvhsV3P
pfPF_OhVFE6h-jgllVsFdugFTuZ-pH_q7_j_J-dlk7vyF-vVt_o7N_6NzPKFt_LFtopHVzjdzvF_UadVXGzVFlrKXKzzuQFZz-cyydtjenTqVEQuF_FGRygl
unNYLyvcr_U5N_cZlF1bVVmwbT_pVU6FsfJVyjkwVn_eJvzV5kNxmgVupV3BijqVR9NW9E0h7h-8W9wG3dn69Qpzjklp6Ah5-TL9kFVzm2UXsBtVJlTJ1-FN
lU_2Vv203w_xQnnAr9zzpNyaYFfFVQS_e-hZQxuAdhdna-RTLNtHN_5Lr1Vz9Q_gx_PtRdFDR_S75_L5Vx4SmU_qv-hhHdtTdm39F-sF_SRrxIl_PUlsUZko
Vvya5YFgI_zb2Tr7mC7syKcuuC4bxzed0Hr2rjS-2RadE057F3vZvGUl4NvF09RyCvzZFUVnznEQQ_yWeMtrvrWrl-_hX7RWSwnY-ThVJ00NlawezxmV-3e1
G_jwakQrhnFWJtnzhEt4rmajmkTOMmlO3wSaIENhX2YVKuhoIOZoIOZoETOOduGSv9DGedoEDSed8ShdbA9y4g9y4g9yFWunFWdPOtmIIfJFiKRv94Jwd19-
J09-J09-L4AKpmSEFoOXumSb5Fp_wloUFm
}

