sprite $Database [96x65/16z] {
xPXdkjf034NrgO_B_hSRoX2UR0N67fFsVFvphgv4XtvE46a57gGcqGUc5b1Xt3yniuW6if0Bgi9Ck6Na1offG8vWYvnbWQObzaMGPEYM26uRlQE5Kcw_8VpB
16cFuDp-Ea5RMkG9n16fzDmYw1DwRw5F_HMcXRwxXGO_CL5d2Lj4KF273XstoFqne__SkJzFa9qH-EhzlVyM_FNj60cZdZQrq7K6n_Vx495lIhQq80WW9X7v
BQIXXS0AV42LZcTKs8rHIEXk8TLELlrpMNQWTOlMbnvZTPNvft-UAAwfwTonHPG3JVFJVw5MUDU24nRoElmS_TDKC8b8zvIq2DzFQ9YcbV_2o11foY34y1Y_
c7B_D8vEa91au0LOWJgEuol_E0n5O1-ePHZU-uTIYZ9kTBEMKePMV_4BnjYcDhzGDllTJ2-8r1C6aAY-6PXvd_y2CzUZNgXF8FdR_VRf-K__kVzp_t-zdp_b
PxZZdzc_mmF_nFmEJ-nuly5NQ3pMFn8ii2Ftxx26_A3vHoT8GHlw_Ixm0lOkVr64Tv3wllsx8BI1ebldLy4T_qos-5K8OJzLIC4VlaB_nPpy
}

