sprite $Documents_Sm [96x132/16z] {
xThPhfiX3CHnP2o8ylxlstLKBluDdI3StTVcDn_7S9Ij_Udrl_vNzb9-p3aA4s9-hX65lXBAV5NM-QgiybC1fuEEZAtVMd8CVWKMmcynpXCI2-ctbP27_ioj
trfNmiYtVLL_vQimQDldGleSW-yFBgJF1D_7GlegZM6CVCldGlggRem1_ek50pu6xVlVkwWnbiynZ16UlvaVdX7tpV0F5dOq6hwra6DmV2uScuNERQ3lpu-D
Xky_6k_RJCVt5_A-pMxwlAZse3sV2_r1M_xve6UQFXSQWzOM7F_ylgNX7uxXY_M-xxy26jRp-oV4z_s4lEnpqFsopp4S-c7-aKOS-S_deti9HtuyFzNZXtlu
vlSt_PPF9NZ-whJdEvHW-UhqV2GOlZejtqsGZqxVRu5rzDKvltGEosV2ZAs_4jBpcJ1s_ag8T_srzxdnLH7DyPdmM7k0Z_9z9XJuIBZZi_hNXApmbV0beCPN
mXq_ylKSsWL_3P9rnrU2vm_Vns5qV7LwFX8SNvs-ln8CNvsUZuJS-ZgsIl1zhDlugpCidmcvzLTd6hwHG5-lQfhlC-7E_Teaz09VbKeey95mqsV2eypNwxGe
yfKmsmLVomh___T2Ft0M2zw_AC7nrUdvI31yTLe-4jptB_tm_KilU__IpFSlgzFmdGJwwap3DnBegpDydmdtxg_nBk-6puGA7-zm2toyeBlcCo6gV2Mq6tx5
-nV_wxvpVyuiyF6vQO6Fhulk-Tp2w0K-4gxwJ8WhhnzOVILuFXlf-rzvqTUZm7U-x4_BLuBljyWrQC-VQVZ6KQBFpTBtlrIZtm8taxv_MEbpi_JzmqgVcvLl
9MZTo5S-7yNtEJ_wJ4ZRn_pWOxCgt-Vyw7Epli_vqUTcVP_pWuz7aN-S09y9ORiyh3FXcpzsymyhVAlyemI_845-MKAqeke3Va72Q9NLi_tfzR_-rqS
}

