sprite $Documents [96x143/16z] {
xThRRkKW38LX38ZiyFxlEuTKbJNzfILM9S-Pw_9Ps0vkbDt-yVL_ZH6LVB-kQnJwu_gsLg_qdmXHvwydmemgVyPyYr3bjnRhITAeyblhooYqxMUbLrJvxRqC
KUI_by5_tdeS-1d1BKFFj6h_auMUIAlmMsIX7PzffOz26puFJTyjTFe3QQLlb84-dX_uYBn46U0ZhVIzCj3Fj4gVPPYdFjEgVLoimcTQwLk5ffzfpGYnfC-B
LViP8Uzb-5wXwRlpYer1tqYhMGRwxhnYOz1tqweBJTzCgowqyEqoYCQ0BoA4NMZjSrwPPUZ2zmlDlv_dlb_e0TzDg-_xtUtxUg4Clc-KmVFDvwV0Hw5BV1RQ
zurvvVcnkbM6CFsvznL66KPhCGq_hhttwKMstlnz3oF__VKzWb2nQ-_zwaPznxttFS_zM1jP5Vvx1D5GoEeBMPL-YuL3Oo6hzpprUMZjyypQvw6vkEivSnpx
F3HzPhKV-BhGCgl3lNzOQBtByhELeiR7dL7WvvrHuAFGHVvpS--x5_WeT97FGa_V3unK5df-s1N-VDI5ZXzs1NeNFczoiUPg7_ozbpiVmvYFc7V2jo9aLfy8
pdoK4RWhdgTZdFaPuSJFfyEONyogzldyQHzPBPXVcTM2-OMiLioNpEeeyZD2h_7ptdpr8ZyZH8sVbyOL1JuY5FYu-2nVlz_nMg9VEhyoHj7yUlNozxjmt-_6
eP__jXZzC_6y2Z_FxBxVnQdFCsiVXyRYhcdCHnnQ-tpZrBukjCZgvRxVJVFzhizc-2XqoVlTbMajy57ealSx_2VqvxtVFOMkVRyhd8yO3WL-5hh4poSw2lnS
wrFptGZGV7yO7qiDt_ruO_ly-DaBV7mLz_mGlX-1_ZN3_5N93Ci71PyH39-zHv-jD4vzRj0-crNx3uODmiS6xRCpw7DXW_0HGVhSe7tsdlQvGVlS0D_yMagV
lQTzRj0-hx53FpUOlogvu5lDgdzLGjzl9VrVCNppUonzHi21ZMQ5pmtWZLQ2BvOVeS17izg-rwnHuADPFTzl9S_t8opFzrl9yVq8y0jQgRV25MEqVtpzNry1
}

