sprite $Domain_controller_Sm [96x130/16z] {
xTY7agGw30LGR2KRPlx_SoSohWl2s7x0IpjtyvewaXfrg9uml_bDU5ONCtfI_mezexELq4FwOnLORH-wKrTJUwe2YNx5bz1uX_uPNKlSNI7AJx00HiCTUdq6
lh2IiesAAo3XBXr7q1lqZqYjWkbbVKrz1e7DuJ6U2b-TGGWkJsbORrG0FLhE0tvadxtESBccFE078k961GxmXf3Ifv_xTMfKsEdWT-cD2g1FR8Nly4ECX66V
ZKvcQT1lLOXuMu47VwX2LGzgvlrBCv3x595wVKpSLM1oEgk1dtlyW2Fu6IXituc7VU9GVv1GZ_gH3VzLO6xv8jKAg8lk_JXDqkKVLq0zY1xm7x6vorVb_IgX
pghEr--ZBby_Gm1kTH7Ff_KAxVPDgNhkVVcftktZnnayFVRB5JBt-vOq77q4yZpShZpY9wWG6FYjRm3mc9-ph0SirVRZznKmRDEtucV7em-xgNodRwjVTfDL
GvUlVNxXfRmUyGM__l2iYwaVYJVvo5DfNrMk-hvzsxpYnSi-yh2Rwu6qVQtwllsoc-M8RlNBRfOp3IqV-8eFFBiN9chuMlTz-xRk9YvNkEGZNtPJi03_DT-t
ZpSN2uIM7mELbq_m_KjFA4SGbOR_TKvDFoM1ze4_VP9nUOwmytNZusxs3q3mB1Vd8rzsqqNZQVzO0NtT-B2RFg7Xcocj1LQVNVknjEz3JN-jmAN_NVkmcqC3
C116b7AUr_vtFkwc3_Vu7ydW8rzsivRGvUVYasvyMw_cciydVfZ8-RpXrzqCN2yGpvzVPCdxllsJ0bLVo_CN_GqVyVkFeG4OFfbppTVow9mLgFfMAiYn7_PV
3lK_oLWtN_XAyO4lDxTH89pvwQi2vzdxHzzjzUwec9NjD-QyyN6omDjq3i3WfvmFV8NsCNq3ICClkqbCxG9neF-Lb_gNSpqxAi0x7tRp8pqJn3C_RttSJIe5
6XLQ_hppfz9-tmXqx2VduyqDnM_VX33YAxJVEG6D-07QxvqWEB_mw6ztSs02xlLnDqScY2V-ZFxQIQWcVl_OnVlfqDVfSj3F6r_C-2u_7VZyi2_tFJx8esyQ
Qo58oqzL7mxol6PPbfSrhzzf-6dO1_w2t-17_Tpj0p_gp-0t-5vVWVbR_NJWB_3mtEFxzaTzPFhzryj-dH_tywZ_sky3xttFkmBp1R_T_Xodff-7V2mmqzIA
8ez-k_sPftOq7_lQQdz1VToNS_v5mEZovm5_SVgmhpj_0L-d_YZowFlsGN_41ttOdvr_n2ywZORx_KN3D9vWXN4-yek1FXHARH_ryL1k-4uVZUGZ7_JBqPgV
udHBWkrzq6y9fRsVQBerbD47_RPm_l4JJuz4ld_dwV-St_pc7G
}

