sprite $Domain_controller [96x130/16z] {
xTg7jgig58NX8B30xFB-ZtiZYV-Gm98opEthZ4xEDwS5tUtsZvh_nmGn7zGbF4RC9_LF9HWV61AkrwzFGFzOWXEHy8a4TFb80lh74gm7lp81VPiye18noI-U
oHAkrmae4vOvtRYNJK8rmlBK6zGVursU84M0uxcqhcDw6dmcIzZrcwoF6T3XIQXS1tGVuu1lh7kRQeBd3euHlqUtpkPwxJfuWxxpQvUUncM3pw0l8GxuPh7x
k2AZgiFt-4bdtdGYq8qaljStov85bDSXdQRbe5CVVpJXVT1zW6_xp7AQW7vp4ah_3ZEKG8JbXfU2R_d66It1sLnVH6PyHuAf7CDHXmyvt_2zpn8odHlUYnJr
eqYVBr9DG3UR3e-_fCVdlU7xpIyIZdfgKDQNRQtjx_yxkEDsoFIwdpxXxftz9OH3Wdd_AW8U__NXEE3pJaLttclrzu-C-376GyBYIXxVRdOwWAOlHt-D2xhJ
wwUl6TABSXdhlwvhEdHtu4i_bR2IlZWCfxwdF_wAhzQNL5_4RyIqxrNVx5zScordkd_91-eRlfWmKtwxVXeBfVcY-7fzH_t7pFjg_MtTYt00S-V7Q_ucMaz0
muSl_98FRAt3aZlrZq1i-MmjUrmpCxvQN_RwhFepNpfzwXiMMJRz_hhxMdt_kYcE2NxMr-ld0VOotrB_6E3dV7Zym58UO4zzQso7VzXQPS2flwIle4g_NPy0
f_fyyMDSUFhtgfzjhJB0dFZxCTnim8V7PsjL0xpYOpmFGl0hzGtron6Z-HXH5XDEVF_wUa-PKv_R1nyUt_3QgOwTy-5jgdyICEGNzGDlVIt0dlknwbD_eRuQ
eEylurg-K5zFS8gV3inAviEdUTsRhX5Wwdvu9YmI4u-lrTS35FynATiuVAL-8y2eVdWUX1H-uXqNjn5GymylFnkhVhXHln5WTP_BYyyAMwiTKFf1zVNwUe1z
zuFcaypMwWfG_AZwKQZVa-1olwo_-oIRZRVETWQOCJ_wL7yWOB2_UV9d2Ve16FWtd_ffQzaqlTT0yTUQ7sxKxpu2s-7llAN-G43XHyqNwkDt15ZTlx_yL_s5
-aC99lUZubD_DC1L_BNYqsDcyAFco-qVuETyvaUtl8tT_htFh1zPOUdhDT_Vtp-F-KrpxiS-_vu67RxbHyLNwjE-ipzyorVgT_iW-2fFGB-_bhv-Uj2lyKkU
W7c_KN-mFmh--StvVOMlr_z6x_FNqeyjduHvdmNbxFJwy0q_pRY_wduN7y_zLV6rlPiUFRy4H7CxzTUcVrTlVdJTh_3ugx9tuLVqYtpkJVH-7nw_u0b0d_OR
zUyBnAnVNbq2qBjzU7nzRtsXVy1NkW_xojd_ilqsFexkfq4VcA3v9Oy-D2RW7FrZBFhSB14-yub5dqvG-bFVpTiawFtzxOAnRpwyt2uQL_Ze5utaFlfbO-Je
V-GlRSFBHxyy8NqzqDB_d__d3m
}

