sprite $Fax_Sm [96x76/16z] {
xTQ7ckCW30HWa0G2xltVzo8I1NjiVNlUJQxFzi8_6EAI_gJy3ztoFbtwiAYyHUS-FEsTkgM-MASszk6NwZeEoM_Gtx52kO8hOwQ_XWUzK_AZeHVePUoZcvUH
f5A-fWledUVabwzQldgohZIsoOCF3P_NbU0SqsI-fUJBEeDURqJcpH-KKsBrGCDLtPQ0f9Go6xGApRslLUjd6jeExs9wUOJzd9Cw-JP6UpJGPrxnZLttC74f
rMAwvLe3RNcREnTCjRUfzv9IkTRGjpwjkKEcBibogK7WVCtdUdVzQaF7gt2WDqwMgmqqzg5qgki9KLT33HlgmPTOnpGlYAyQkkTxsliwOfrinxN2_34u_Ioo
qsiET9swlSNdCcMuugSabZ8JwodVTOlhH0UTcLDIdButr1j1yQuzz7Ku1NMBbPS-yRcAOl66DeRcyvkSphDQt6fzW9_v7ZA0XD8CYsKrm32BJDsoqMs69K7u
aOUTxOXabxd5dU4sr7PNLcdT-EbZo1lyczE6jKXyhlS1FX4qMCA6_dYuekOweOw-27_GW8iaHxsOxZpujZqP6-8ADQ23lk7HBpD2FxvAhTUDdaj37drBBTWG
L_WHkuxyD_IDhwiXVrJ0py7jZ3_pxs5eW0hGjI4_TV2NNbLLDgSS1kT-objqu-zvRmWsOkcghWCFFjTdy9dls41BZtZq2NYuYrAWXppw3BoFrQS6EYlmuy0t
0XzcVn-fl6dm5HEDUT3T1xttvz0coRFqa0VTVLYQSKjl_PxH9TIHHzrz1Lrr3EUjgu0UyQwZ3pgbnCPk1ilIGtxf6AfxtHyArcXxjGKywb63wnwoiUZ7FEeO
EJvPreCVdbKVwQIeMwY37_6NTKy17_ZBEYRhye47FSvwAiFa2ki3FEhn_1idJxY_m0TwrD1BfBlVW0_qU2KgR2pwYx-cBx7czNr7V_7NT3p5JE-I4dVmdGVz
QeFf_YFuTrv1ln9khdl3yliCw9UJyP3S1_rbaUu-w2ziCD_qTyLaqD-U__cVxm
}

