sprite $Fax [96x72/16z] {
xTTPTkGW38LXG0WXil_zjdMCLVWUeapEK-T_wT7VTU5CbVwhSkj7N7vB7xDEp-j5nfByakxrftMCdzFxs9MVqGdqJiLVmFEwKaeyV_kexlTCEcOb4Vr8LpoP
kUX-bKPFwMgIt1zmbQFwa6xHU6LFGkHx2mrq4tAjjY33wbpIUVlVMUYRJoLYvfEX-LXBQqr4-xcGFwrdtUiMNKmcDjx-wrpW_9sxRtPLuIKgH9NRfVUlBl2Y
z-8wDdLAcR-qG6E93hrkzJPrwxPGKbo7i-TTg-uBupCBDDOqfRhH-qt_qcleurPAn3NGyTkdIhn00tsgzRQmw1Zx6OcKuFRHzuLGftxUVnDf9VZ20C_NU1ke
iLvElRK6XnE-W99AdN6Lp-ZDTSAPN0W6D1s-ryVGijLbcCwcvzSYmV-YezldRyzsF1xRT4jOdlgHwzHr349-3kGggjgPqhnzZ_MGwbrlMrs7-x2Gqn9HlTTi
WPB7hjT5DzvzN2ZvzJmiMB3Ja8nwJQkk0tmyfK9BiC1zVbEeUzruy3DHlYrWcqDYlNG2tNZmQwrVMf1XeUxypcUknV_yuG9t5QwBpXtvjzNdCueNiBBemB-z
hJvxyKAW8x_tMriMIh00ElBl-XQbw56Zll33-RtVpaGuXmke8n_xy1sk89zTbu07Vxrxg_S62w1dbe2t-EQtEs_N2la2wiNrY7U_UN8sBtmjPD13tdNtaVSh
U_N_b5PTN0T-rT4NuCzymVMGTnrzv-t_g_Cwb3Fe0Uyw-79bNieorFsZbbsFUKcRikDThsz_fO_RrUb80Xvq6E1BxxI-n_EhtO_uNdQsBxZkrGjtF-11nwWF
AGbhu2C_Pf_GEUyV3VXRlbEeLzNw_lJYxtcDzQIZHTkB3xphSKNWwE5zbVic0wySs-vqskqEy86FzNY1J43VTTtfSQpBKRBhu3k_rUD8pujA6vqoRtpd8prU
gA_FD0RVUTU_ix1-fZ7uhZyMhxxhJyPw-QPBUZxMovUIVgMgwUYk__NNFm
}

