sprite $Firewall [96x157/16z] {
xTg7ZkCw5eHXCGVq-p_lMYosIZ9PmfYmTlU6CqYTll-8Wjm1i_sVpBzZWpTFwliyLJ0-z76FBVzlGHw-tVPn3nJW--SAy9yhm7-k0F-v0ln72_I33-7h1VWC
z88_5-otzWTdHE4R-t-vG9yw2qOKblspjtsfOCYV9aQpYSAAFnPUlllAAPd3ll2x7-Eau3yj68V0XG_mvmNpSG7ukFyN2iRWgv4OVHR2Ki5uXy95fu_2jbO0
F2d0vwIb0lpTPG5wUFTJBzXF2nOFBWgs5uxp8RzQC3lEHyT27_ob0losFto3hnQ-ABXx__Hv9ZWKu9C_Z_-iO7a-hUNmJkdddCKtKUK7-ZZHzkuRts_cpmjc
y2C-zywtsQk2tjyr7o9EwSRFkd3lXuY4vIMSTVgvw88-V-2y1ZUiJx-eWju_XlXUyDBVn-a20zoV-Bam-k1Ha3_CiC3zusqXl_aOUrSmAC2dBWlqtmjc-06g
qMWv-BD9fqA-xYyA87auA8ZzTpRQzYHg_rm0Pspt6PplVtfHCu5-UPzQpcx8_l1Py3CUlkdNSFZvtQ-rc0tZOhpwCSHMC5xwlwSKrVuLXPsC5p_Y7ml2_otO
kO_PXJUVJoqBvEddb7Ch_86VwFEPOc7gl_ZS2pR-iH_Zh138NtmMqi0Bd_Qr87nHq3vdB9nzyYoi-2ZWtYZ_1QAG5_reyCDGLFvUs3_3vLNV1nPsFrzy5cng
FFtmydFf_XQadz9He4-U1VVcH_fu0fH_5DxzKo7iXY_Qntk4tmjcC-FnOFAs6HO6tth3mk2piAKP3n-d50hzH3z65YO-VsfsIVg5XOaVOq1Xy3aM1UNN-bkO
-cCXlVaPf-J1J_oz077qMR2XyuF_ch2XKFB4RuLmuyVz7IWa-kHP6Cy7V2zetmI3zwJHLmNud5i_nbwu-fb-_xaytFinA_yedFt6S_3YhVtsU4a_zkS9_i2t
hpGeBFbyJOZIn-z79Ye_AJ_1v2ldo3U_b5wGVftw0C-5mS_mZy8d_WiR2tcwFmiV-DHLeHm-2rkyyKtNK_Cvea3_NB19-RY2jlVKJpcQ1f27pycEXPCVeAEG
X9ztbuMfNoiAUUhRVW9plw4ib8dVL1O6FqMFmipdone-T-gZO5i1VYxqTmQ5qS_qJR-6gS-2c_Zy1IjUzOj_d19yyfoq5oO-2svSd_xlJrFAHm5-7VmKMzsF
szFl1UtZ_gR1vpMm09a-F1HS5hponq8MFWiBFWlvtIyS5khdFWh69-spiE3p6cvy5XRyd79oxJkizbaed--_YsP3GVYOP5au-Rae7zl3zmu5xTTIXy9B53vt
Xn_wASMSIzZio4DD6mh2tqmuhtxnCmespds0vKMWCFfZ8L_ylM3tWh_rp_S1toSgpyUXW8CV_Omltip8qw-y3uEV8WhKwIE0WatZtQL_54O__HRc_laNQRt_
KHXyd38Bz3kF0g-1FFq-RGtJ_9_3ny6pSF4xnaAMFWhmh_jZ_CO2VLMeSt-yl-VN68S2_VaBGWQl_8pp6NtBKu9Fc8N-C9KRlvnyT_5v7-mMo8ylc_xMb_ld
es2sKCJWAtrPyLdOdFOT_w0nzUkDpuA9qg-b5uIlpfyJ30h2VqqlhFYDKTS0duNFVF2oG1-5PYWVWKIVUfyyALJucD8AGVWiq8Sk2lHPmA-fmiVumoUZ2XN-
kH1GEFi_y5be_gxf0dZwOm5-eNykx7wMZnGAz4L1-1XRrCJDyFTS-A8WVPoIz6t9A4nztkdThy97GVdbjm1V5epoCK7xfGFqnuBUdmNb7xz9Rqa6jCynOUPV
VvDE2xugmAUH7GhBFXyd-hMAmfBF0dqE2yB_4RugqDS5xUknKVeihFee9FgoiEwZKEcBmggFGjP-BNq9-bNvUiojpsjOyZ5P-uMdjEZZbAJF-x3eOroH_b5e
_W_ybOBsKLZTdmNjes2MVOmleyyHvxDGUCf7uJaV4ygJFWfF-YWywQFme8_2WpxcUJyyx6ycFkgZGF_dwpuAyFq3wwEGVlqA_O52yw4_ClXFplyVy-_y1m
}

