sprite $Firewall_Sm [96x155/16z] {
xTU7TlAw4a1Xh6wnylwlUwDSpPQK6SF2uDFdxoNVTX4Wt_uoyz-uQ_KOWxjE3p76omgRRpY52mF_5VGuBuLmIS65O1QsZ_d-cW9-6xFWju_u_h82ntz90P-9
5nJyn8VuqO8-_XW_Nl3eQ8xqMmLyLKWVBE179iMKRkyNy5KXuRzVsC1dlld1Io6-LN07nnzISbRXr1gDiux_kS9wU_7VBxYDWZx-3nHyyBtW2Qn-pgSA-344
EGVHLx_DwOB_kRVZ758q_L7mhnLyNpg1WkMVB_Z6B--RVl4p_a71FVDZ3E9l5F3XJnRyVAOnz48uy4l9smi5vSVK2uT-uQrF5vxx3UHES_cPqlrD5u8kQ3-b
kR255h3yait2SryctAHW-qVtuQdF-7uEqVQdmlQem3OXYSy42hPl5u8xUleINnLSWb_zVN-XuF7DWkqV53PLY2bOVkOg9TDV2a7uMVQk5xpfVm_dOFYzmBtK
1-_dUsxnhN3hXGD_h-CgeGy_KOYsprftUVRtuTUQPdIB4J-bc2ZuGzz9mVPxGPGiFg9Lo9CVk4e7FWKNe_9rGVj52eOlqnTxAifN1NZyGi5dVFZPpzhN1UtF
1NZbnvYKRnNowfS-sKlXbAyB-4oWSCOVXN3WKmW5_g6l2_A2LxwCft36J-FZuS3VfU2AxGCS-TvHm9y35C9k-yU5tFoGenHiVnJYRlh7XTplhjnfxQzlpLiq
_ED25d_i_Rtj5uGu-MNu8MogaF7RnAq3HtxsKkX-dlsKA7GTNoRTL66V_59BBwGVF_toVnSoFkFbCzBsgnHiVoravJSmKJ1z2jhlu-LEstufSIhiocy5P_ji
EIdWmwy5vVV9JtokaksFgvILp_ht3tpkG_ivmiyJAPpmntRAzDbVKJZXJoyeYo-PvnUV3_qzhtvE6Nyj5CiliHUAwPVPRtPAkVkgOFixXUT-mvk8hmlQ_vx-
7vIVykpxPgMS4xukc7uhTA8yy7awmRSBsjS5xLEm_L8ec7wjKWYxwLCmVLwo59I_52pVIK7vfVcgeFobeFsGV2_W4s2s6mLy-5O87JFydAM03p_vyfXd-XHC
VnHyKhhu8Sbc1H-SWkrR1Qu-VYczOFiKNCfbN_nUs7f1TEMFGi9Vf_mSOL5-7pyAnVGfR4dnhFzi-kjLqdwKZ_LCuNNVBk3lpPyAntxLFaD1-OrV2sVy8eMG
PnzU5LxmcvXBIL9GruUf55xm2mkJVnu-k2nELR1y3zvjV4V1yDcnKL0-6_UXvzcFxBl_x-_QhzsXWD-0gT1auV5BaKBpJRxk86duEpu5yCNdzVhGJuv2yylY
-ut2Bp-LCXTYKNptoxWFseybKZ1z2biwzBdJbbzK0P_2jXIgybcjbgyA-CpEETX-BuXV5rzzY2j_UaTm2NxofI3-VV7PTrF0XvyAMVdC4r_EeVlmKaWKplai
bJXyS5KuuHSf31-UBIU5C_ueU9ElO-TN3lpziKzXItBncRwoapo-dFDPJ5jKX__ZxrKA-KMVuNrfvSMlKZZhZwiKRNyKyYFVPUMhGe9VV0g-h7x5fx3wh7iA
yFYzSACm-NVyVfUKpyh9OyjPPv-954oVSrZzlUYjpexVQLLeViHVniVLduSFySMt2lRnC-FWry1ses3wF8BPny_axlyUTxi5NjFuQo68ln_utEcz67vakuPl
5po-NH1S-LKAh1zT4FyBtohOljuGcll_g7rTi7rTiFqx_j64edsPj56m_Lej_xXGwxUFfixXd3yA5NygU0g6VzU-NUWylbKuvrEeobU5CpuJT-NhmZcVWkNR
1VpTfEpP8huQSRPuncSU-auA-5-l-_xOByLBuQJFDRRzSHzE-nHiNmhDh_WVAE1JyFXdngK3dqAiT_mt2_ZCMpw5V9bFuJAVmcK-XUjy2hR_XVzsuIgVmbK-
SxtloeK-Mt_yE_x72_Xt_pcQ0dv5_tIX-JnhN53Wq_XVCF_D_m
}

