sprite $Folder__open__Sm [96x106/16z] {
xTU7hYCt38LXWbMQzt_Wp1qSNDcqcS9eaYt-KRTzXz0sN_f9-_I9LMxsLVbU7mjt-Yht-KZkyn7VwPkQAT_bOy3qplklv0OVFEBRxaVAktqY1e-5lRuGFIsu
cz2cH4qLKmhUtDrus_quTYtubUsvtt3_zu9VVdY44kB-Ut7-Cy-AWJF7ZtYCqFRz9daIzvyv4v56ZD5SOFnnV5a8P4Hn-MCEumttOo4U6rTpJkU6huJA1Tm_
pqAxxrClZCMV3UtUdsD_kdzbNJyddkz7pZjyB63WgIEawUS4hpEU_UFGbbylPD_t-5YOB_xe-3gjM4ZyMSSVwPSL2yVN0jDpB4q_B-1-fPIgllZ-wjVfUFIT
SdgMx_VIhnUEgw2SgEhJlU9U-rmk71D-3fyq5r7xfCUajsbvFp4-IEdwZjAFzISaPvLFQcWjo3_tQLG-5H_JjlbYAztg8tl8zM_wAd_RvmS-_UqgVNsOgdsa
3_nNyjU-7OVKVixIW6ts1RQZ26D2Cjl-2a-FYV1uND1_xpDeXxu-QwAsZzJzUo720yakdxvny6jXZo-BJoaHyfQFp3rmVRcWi--p-vBB1Mhxf3WzbxvOQVjK
dJzYf8MUBmMFPcZNH_R--FLnV2WXcGsVt_lGhq89MUdNQQ6FMNmrLFXb1GzxBNHzANYSlnQQFlbx_QMXFP_BuryNEZvfqXUUEuOqV89UNuzERdPygOxF_9as
V687ZkCB7bxjrqdKEFXv-RFdOw7cvu6qusDXZbgVyAFZ8urP3w3Pyv6E6aVQz96MZuEYxICjhaUpww_iFO-qxQ-iv47sVMHBJyqjFh7ZB-rBclnk7CVR8lcx
5sRojo_e5X_9A1ve-RiNvZOVwKmFbFoz2r1Z-TiNwCpWRr_00p7y_GjWvquVsNnu8FZR5_100d__mdeWfnjYnmFX_3iMhWSAea-VFlq1
}

