sprite $Folder_Sm [96x127/16z] {
xPY9RYGX30LZ0JOz___16pHiAWZJ0SrOvxozhthLnajQ-VgVJpxvH8BvAKaiF-SaiNmQOlWj4iYd8OvVSiaInUy59U8OeBSaYVHlUNU137GjcYNY2KhkUDKt
DSWFHT9l_vOaxnWC44dWdqbl6OlGm7nwv7qN3msgfCZh_B5XyFSEchzziFX9-3tONeFKQbds-VtUoJG83VD1YzMMBDlyqXS_Gv6iIaoDWzPgZNzLbHr-f_U6
uHY8VQVZijLdhklQQ4Z0lwEb-0tMKgHDnxh-jTMGWFU6F1sqgVLaqQx_nF_Ta1gK2kLkuw2RFga6deOr7tiMVrmbc_5j_3HOklM7xpPajV41yBzjW0_TNNdH
aGwUF6ho-T0xdiZSm7pgGF_-IeFlh-2TkoqfUE0KFBw_FguLNndEkW6yEw0MSVWwq_sxJN8lcEdDlYMv_ftkDzZlXiBmgpEVHvxv7GnzAh1XbRpfFFu_W3hy
eap7nTlKi9nFTVX-k9bxm--3TlRdcUk4Z_xKK2TyRv1zFlfpW-GwZxybdSvdJA6XZ0Kz-OHlyyLccGPr-7hc3vi6HY06ViNFT_epl8uDgRxYRpICD__l1kXd
_WmVkFVc8ELsFkbW-BmuZ0rwC7_i9tthzZr3mx6_GQS1_sVOTgcx_j1dEFWUFYJAjSytvt1_fWzzV74e-tpWpclFTFMRF47RV5lZqIVzqjdasqeU_UbcBjjy
OpFzwK3dnMUV3zjT_SjzBTdbMxUVySPuPlsD-OnidV2ilgj_pmVET4wc_-VyROCDVTwUF_X60N4FzrgzLjtpYMkF_vnDljuK-FSQ-g_uL_o1ZmKlyR77VwIV
-_ls4VxOGv-cVyn77ljbmJRVnsFlq3VvnQLRXRukEFM7tkp1Swqv-7r_wEWtkZ_xy_c0lrjxzFVzsVU9xi_-Z5_RDzmPFVPpmIPVr45pidK1tpXV6XgNGxtV
I_Gt-3Hq-BYMDxkpnIS9TRPcQKys-JGmcRg0d_aJIORyMX_u9fz8Vi9XB-mF-KHAXRxMF-OJqKQ_7VwX_zomOt_E9s8xykTyacnTy1AV1lTLd9povsJ_LdkL
JoHxU_ykFgk4_XlvD32Qj_DPLkXlvDFGz4FuV78aWazIc3yDKNp-EuJmYPGOFX6DujCGmoTYCNmYDOhFiaRnQOZXato5y8cK63uHZUBJ4CMd8OPFfC8t-Gg8
T7vDNt79GNGUekUJJpxv1m
}

