sprite $Folder [96x129/16z] {
xTY9akGe38JXXi08-_qVUDr4_GwvmRcKsyojlO_vCaUevlhuRURV_9iOv_ffIM6klv0moITXMlywSPe_Dm6TX7d-eyzmG24jCn9YYc5E0dvQ8b9q2NbFU68_
ExF_JaJq0Vc1XuwLtpcN0B-FI1ZrlzvzYA_okSuIlhaVnYKa0cJ2-7xQX3t0JGhVyC-J8ly--uZqYC_Ta-3dbSj4I-66xnD2TBpPAI5OAIv1-Y8X7NmsC_VG
LgpiiuGRFWyj4XOhTTQIu_j-VTaZONcjn-hKhrcoGi2wMhpXay13Lvw4QEXb_KmeAGpvwCrdDtf_nwbV-JfBU7S_vuI4VoHKVUUP70TyS9Tmd5B3qv-nEEZp
ZGC9F7HdF-SfIViids4Y2GJuvsNw3n4bp-MJ47EjJtzuXWJHV-Ux2SSfrVg2txPquMT-Q-lRFYGazdCLaBi-0UrmcYI4HTRVhEDJlRzzOuvJudbx_jRusGKm
33m9F3JNoU3l2T7xbVMwzkqu9IlhHVzqyZtU9XW-Kuw4P6kNvu7fp-QxEhYVaZcbqlNNimy_iXq-MSSfjUlV9pY_oa8d09y4ljtBRN__m97kedt_ctvB29wl
axplHZyk4SSt_KU2-VLeN_EKvyDbaOSM_GVv_ZVznobHVyo7b_L9u9IehtrqqVw5CnnhVcS_9lWcuNXeuSlwZCVzbCGp3FbsKPzf0pYbh7tVNcsVW2PXKJvw
l_rLVMOhmbSy2LVr6U5hdUNe-h8_kbsK5_omRmHSdBvL_Lv_TBKT-lVhAz_OE_RbxQoNwxcwduehNTy-_5N_5yv7giseiWtKx_kLv0_PNH_FTkLdjHYzV5__
qg-ZDizNG6zV-69UCZfyMr_xght9nqKNljA_jXVR5xu-U_MywCBNE3hsk_j90zq94BSl-ek7bQTpVpySVT6d0y-CxmUzEHrHVxn_uJVdYsyPnll3evjiZp_m
lggxRWykVOyRrStXihts-KKNS5vsh3rwrsTYziqBlCQfhtqIm3jt8tHmuJFf9ADNNDOVyaauhuPlSWG_s9-7XXxbrNv4marT-voIrdM0zZabpnUvVE6BILRn
_sklzoCdOGl-PdyUUYsJV1Bo07xJvvHqm7sVYQPFvxwl7tfxOZyaYEKyuFT-XV01NvmI-crVF_GsmIU1ze_wJ89_t6SMy0a-fpJDvvJc-JpqD9-4Ci_dbERv
dD8ydrEQvdDAqtmIR9xFAStpEQLvFWdpV4vfciyfpVAPQ5DzJWa_XqTj7lhbb_WnPnRx_1Ex-RNdt_oR_m
}

