sprite $Folder__open_ [96x104/16z] {
xTQ9ZjqW34PXBDj0yluFtF6TY1wboIXmeVklhUjthBbh-bttVxBOLzMrlfdAKZycYtrJMUd7T9c_jA26wLBVtKtN-2oiylsOoG9_GO6-YfbZDjSFJXZ8hfDz
5hBdZ-biduMOew0wmu_VldGFlnHlQYb5Htqtvnz485PU1KanAwNMeO86RudJbnzwBFvEIesD5DJTlDsFGicb5RoKqO863vy5hBPbwVGTFgPnV-E_5xODXH6V
1TxV0b6OuBDG2taKHdnESJzy54Pz5dX-2sm-mOyPps_ylkyeZFWia3_yM9tXiq0_9gbDzA6lLQyABpq2z8t_p_IHRxidZWNoiPAmgsyuzjnFulZn74kO60eT
zxDmzlNgmvoOU_Rym4U1_kaqEnSiU7_Wem1-BnUVXew2vTnrVqmo_Oi0laHft7_lvt9JkF4bhdS_5UxzRK_Nam8VKpju5ZfyIF0nQpeA8twwzWKw2jFyfCvb
poQFVDtqtkTE_CViYM-xF_EL_57GYNuoNd-is3nVuFl1ep3iyoT47Dy4NpCRyJdeH-18W7Z75t_nJloOowZF6M_FXO6ITT3d_AnpBc_xslmV-LhQj_0wwYV_
n3Dq1cgHJtNKbvplzTXH6FMJ0h_WOqLxVSuBVlJWmqTXs9UR-p4K-lrazpySVjkldmNPUlsKRtK6Ma5xVItdG2j0Hw7JJ_xrzS6ZqE_B1S_h6TWtxVQJKJyN
DYwmJNlzb9iE_9gFQQylr8bVyC7r-ic3ftv_VQpRJxI9L_9jrkqd--A9GvuU_Vv2eEIv3Xyp7d_Bnsp0P-6Avsglpq8SNozuJlfypcYJvspGPu7yUVKTdmNg
d0pud86_ce_xBEntguC-v-JFamv_fE0T_aYXpl1ZVli3eZ-_u1t-I67hy8SAIdz1mUalA6pqLnGK_eg2mrzHsE0lAMXA1VxqGax9uC-SumS4VsgX_O1oMZ8F
MFVTqwg5N2Jz0_k_Rm
}

