sprite $Generic_node [96x97/16z] {
xTHPafmm48HXBMY12T__kYRAMyMFIE4EzJnrpkleor8r4Fxbaq-srl8xTSkR6ahxcsqv7aizWuR5EXhMwsnOhgzlID3NDgHoPcq3zRSrvEAol25lPIiB6wYV
CNzL0tNBzGwZ3j4Wz741VTsWzVLtY4vtAGlkO7g6l_0Efbjk6cJ1l27_ovOVtK4tHDcWxp1lI66K92fK0pFMTOFUajPJNDUGdEI-mwuqljP0lU_5-QBX-IiN
lRvxtvBLmpIlW0vVDkWbKM-cqt_v3fozxqEVapo_m-PdxrE_wWO6kl7QhxMCNuYvxldZtg-jfca3TUFdVZN_pBmXEFtA2x_zIbQldDVj0Fal-1XVD6pd7_NM
N_5xByC6hzTckV3E9-zyrt3ceXV7E_-uyIjzYtzSgTUxxTpxZNxVgslmf-hjTk2hyUrSYzJ12p-JfszdUe8kjtEcOlvw7T_xnx5dz_zgE-Pp_gh7jzYHOf7R
iLJlL_3Idsw7VXMyyDLsl4-UuzEVZp_scnWVldpqwPFNlkI5BtZuUZjZlpKzFdsz7VfDyFJ9p_rsvJ6-z-VRiVnGlkVfgn_NyV3L-F3bThHFNlcQ5twV-lFj
m9SyVR4TxPFNlkBXWyVuzEVReQzv-cexsk_WjQzv-fgdt__7fwxzEkFf5-3awKz_NCxV6VBqzVZqouIdF-FfXzp0QrzlXxmbDQU3f_ze_1AGs2HFN_FKBR48
7hxQpbSEToaxUUrpVAbRSYT_zGLlkaxgu8MFxUmfF4bgX_R7u_SOdYOsvGz_t1eOdVBCbxfEkVClV16AIXxxs8xMTT9-zRiV_z3wFB6FVUFt71QaNdtZznGM
fGpyRlgg5FWjXiN9-p-_Gb-Js7_v9NnFFlda9m
}

