sprite $Generic_node_Med [96x97/16z] {
xTVNSZGh30HWWX1Wx_k_hWDrF6TfQNf-Yd9sNozVIsmEFoT_-KiiAk-d9nsHzzH7yZlff65RnwHtqD-b8HLmeM5NVucIXdrzju7hxzQG1_jU3La4-Bq6r4SM
6afSr7SRkFvU3H7qnGPPqVSRK7-9l5j3olzbko7I1jdS8IExlmFNztVW-luEgB_B3iB0kBa3wgLCd1I9Epk0BhtFVf5IP7q7Ny-z6x-CmATuv3iGlJ_O-L-Y
je7lOBREhNl-tUjWQGVKwnll-LfqXEx0zOD7dxzHx0vMJoywz_N_LATXv5oVUUkhbaD_ZR0TK5VWhQ_tyzSHEVbWGZsEntDVKHyfNeFLWRT-7iFRWjPAn8Oq
w-LuQEjt_kCylzMFeJJIltkrsl6vhvFF6egUyhEVJySVwJKvkgYw_k0VzSIlwlZTDeYUyjm7_ZZQ4XmW_99_76rfUZYx7VHHj_uu6KOYuRbVONpV3zSy-i3R
yUtywtwjm5EVyzQld2V-_C5mujUgljzydu-FViKW3pxdkO-yzVdjZDns_ElnRyRdFFYSjxu0l-uZZ_Dp7lphsy7v6MzzmXCVU7XnBlWtveFk-epdVYCy-fH7
7tNkyzlnVSwZRtdg0muy-lI3mVMRvRdFR-VQxzDfz7sU-tnwxYEFVaYLJey-Zi_vaQWmFV4lRwS4Bq9uwi_yGvvKlAQElFNP-3q5bgI6j_uvhp5SHavvxj-c
t_migG4FlZ--WC8IbVdE1uFtfF88yN7ycWX4hkd41vuzgJonCd_m3oLiHJp_6B_di9tKq7_ZMzhN1wYU3zU-5vdy5xvOVV-Q3b_2EoHg68d_zAJ-vIz_UGO
}

