sprite $Genereic_node_Sm [96x97/16z] {
xT9TqlGg20HWemAQUVU_tbFpIpbD-bXMvkfBt-S1sgH_95UkNCcgvOUww3tbbpfCE5d72UVhVCAwpYUiwwAYlvgGgpoY9qv0NKwz0NL-mwhk_De4hjypFQ8i
wVT87NHomuB-YnjogH1PlW5rvDTlGFsUcGbARg0-cL1dRgY9PYCJXDn0j-SJ-3k0Vku45THFls56BsLRlq7pyArgu8lKrGbVUk-nlpO1zMDV52QG4P7UElDL
L2MQKECRG6_S5xr7Pcz0lNNcwoSpDsoejyvyzG6cx0RKnTg4xp6penjAfBzvvgkA-_SSt13ePWE_HpxmPiroC07rh_Nt0r_1RpW1TLn_D_GhyE-jIeAyTGtv
q2_ejtVoWQvgKJjiV-VTxxqLr4KKrf_pWR-dVEk-Fl3Sn_LzWkka7UuR-k-aH-uuRMU_pVZ8x-xJTcxCjmcVjSDzv9lpxlDsY6ziVVTvExU_o0UU-AGTuXld
1z_O-dyjyCt3VT8EzJdl_l-s4_l0m_hkqtQOZppwf1tYoy1JdxT3zgUy-xmTih_pp2VhKv_pxWyyh4_z1ZpraQT-Oxpxf1tc3pZrUJltTEeZ3tx8SnzuuWVj
k4vymhjFrYVzfwoSTp_cNTzh2hE9yypd_qul0ueJEl2ZJzUtBV7KXlpe7vT_KzGnnMPyRAVND9ci8uy-jjEWTfPDaNSVs-6rnq_j_EX3ExiIdQIqs1_NvxNp
50lyWM-hkZyr-CvRNY3n8KQ_lmErhwPsz4djoq_jFgbzCTdSjv9-a4tJ8t96xLUkNBdo7m
}

