sprite $Generic_server [96x165/16z] {
xDQ7ReH030HGN1Vo_n-SM8ZOOcGsAA1waw9slDcvlhJvv1CT_AeUUQj1nX5-It-jWTrzE3GygMT1DZocxyT_eu6y90iUQY1pFnKuR7XE3nmtFAZxOuyqgPbd
msCRKW--hO0DT_KzmMC3FbdvdXu_Hq4x8IjakH6Dc9K6xofsN-_eeaSiS_KW59scEl_YQl7FPlUIfQaR_rNF3giRiA7g6_YD3XLG03glsyGdRG8R6ZtzMpey
Lr4VOOFVwVCDvfuIZNMzzab4vLe_JIYwhy4N7_M82ZH0nr4XUR6jwxLFB1m-JC3Ola7hjw7AXmzwH38w7L7rWJxgB9mBPWNrIHD97dtEv0Yew7Ky_XUU_z1h
mLptCV6XGM13grFemAEF6uIX07KxT3n--93cKQWDN7HtvD4dfQu1dapbKEgEVlBLjxuXHu2U_DItsa2mOK_HsVTSyDLNYpGDmg3RYP_veRkxjHk4wvF6l3b-
vny5har3rIlV7n_FlqUNKmFedR_rVhrgr8QJhWP-StpmwqMI3KLVr1h-dX-tvWN2PkZtVFKDV6XWG_u__hRL1bQrsV4dlf_zdmQgpzzxTy_y_97lTknjkMqG
Yi9mfGYGQEJtVziUTeXg_k8rh9okmcs7p_-mAKcyn5XZWLUNK_J3NyD_M_xFSNyfz4M-uMVb6_blyTDRydi_9zdlJPS-hm_zjqmNFgyFpuUywUSaV2lVxtzJ
VkzdwR_bSl9y37yct-ltB-V3_cBu8f_zoZUcAyx7yydh_epnmlSl9_qaVJlVwxUdQ_eR-3VwQLbJT_tHx-O_mr_ZDuKyzCdx_lNB-PhfR_PqWwUVNxy9MHBw
_Npwrtfglr3j4xxE7_kbj6FAmfVvqezzCUcjywsdH_knBssnjTBF1Y_y_Yi4Txg-xr_EX_xk-UIrNuQ-k9oMlwKiV3kV_XRFpy07_sOVpmzyQxhq-VpGz_Ff
1_3wzSDJWM_cZ_tOcjP_tx5N-5O-_UjwlWnYen_yc_sBZvMM9SCtdfwnNvf_xONlvf_inrRuzdIVJyEty-atViQVpU_yCk7hVFJ3Rpp6U_d-yPpinrxuxdHF
zBUzOz_EPt_ZXMzVpiulsVVrwVVziRDSFFofowdxaK_VlpmJVhtyuZvjxBzquJkNCzQD_OpJFddct-xwOxWpliuN_RloxQSdyc_evsxRH_wTloCV_TxbEV_l
ZtpHR-KtVjX_27_tfcluxjCJ-QVhwtnE5_q37hvn-j7l-FxjGJzu-FPqR-Rv-DEbp_mAtxoSscV_zDCJ-UD-yeRF_i3f7z8dBuzdt7yetv-kxg-TRq-NFdZu
_jD3F_OAtysdZthw_jD3dpnyx-dnVSqpt_VzoqcVF7r_kkVsm_TrVlH3d_55FlhHFlQhy2NV-izqoMEVytMcstIlV_IF3_9pYCglmXVvq9t-sSjPuCA73bzF
5xhgj_qudR80DVlrqzFfogypFlCFwAg_6hxGBL_b7oimwTTg-D35sgREd_dGvSel0dZfKzThoOsOzAkZnrhATJhqoOVkhsKVzk_qwoOGkTPZv7SyTFyJj2zq
wnFe2zrUsoC_EOh-1FfQzrVk_GdTN4k-zmtT-E_GV4FtrX9FE_IlMz_hU_q6
}

