sprite $Generic_server_Sm [96x164/16z] {
xTXPcjqg30JWWmq2tCF-bti_zrK6obBAbNbelVEhB3Y4pkDlhVTwhxtjFrAtthlzg0vRwsVze0x5zH_JeLGpwwPqq7NhGWTHztBVEspVWrzq7nBleEjUsA5y
syyfuA53Az-WDmiwU0FIWUjd9Hqw-GQkrrEFEtZ1DcjwhOrqwDv1_o5if-uDl98XcUbwgLvdW-fwkizLrfSYt_1DEapf-X6rB5FTRcqh5dP8z69p_pezxj3M
j6rEzpKTf-GDschLCOc_rRpmj5xrCS57FGz_FQoWxsCGl-pxNdc7Lj_ykYOpvzsFT2ze4NV0GpC6-87kFE-0UXlEWu-wLsKDDjnMmOSMLD_x8BwV7AYi0HmQ
0zvzri6tWUYRzKxy9Gpv1j1Bwy23JxO1lW7rQbtniGD-mrxmETHNVyP-WVDGeaz0VJTpVr2_jLh8KOfqwvb_e8zt2Mxq1dzTcCNnSn_lmW9wz8PEumT-q87e
bzrblbdKuV9ID8Wl-DORf2sXJdOtyBt15z-dM_KKD7wU_woMwCxp-BdlIshusYBn1TyxeEuyEPoflwpf-_Kzr9erUZYvxmlwny4xVdCyV3w-m8zghLutTpVs
dSzzVvRp-7b-xlFT_ThymVHx6lz9z8N3h_iaFeo7-YFmrVYIhyRF_Vw5_ChkXhvbldRreC_deyNNyzFuE1xHXzD3TpVsZUINulFyCvyFYv_cxx4lNZsnRwrM
yuNCv_6Vh_bFhCO-yjn_gk1RSolmctRrnFcjF5mBV34--jlo7nMbCP_7n_pdogK3-0O-Yn_aFvVQnmxzNE8-EPoX3_lhQpzrA8jludZ0tzfdqVpT1lcrtKNV
bb_lsQ4jlXeVv_Es56wtJxwqkt5-NnlxqjMJvoU-C9umVokb-cBmrTzkdF__g9tvF7wOlvktQe5FutFVUlrqEJWFlX0VVV_fVkeW-GVt3JeO-FnmylnBXmg-
DXxqkxd_wSz6yCdkChz_zBt31huO_oNsVMslTOG-ltgSJ_8lYnUVNZsGd_i7-D9uOd_4lhQxkg_6Vn5zFNxi3-RVZ4_z6VXAVD5dyRaVZGTyuN2glhgxiJ-8
ByL_HN_0Ul2Lg-Vah_b7xhF3oVC7umTV6iyh-huwyVNTHH_63xvuzPmy-CudlXh_zUeFvalnHL-FZtx4n_xa_elggx_TLz4NnnFa1nvy8JxDx_719_4Xl-hJ
gsUPlfwVZaUOp-G-ZWVZS_y0NuZlVEPFufFu93_nW_YOt_NCdyIdqsVvVJdw69-C7_rz4OXFhXuo7-h7yVtPaCqVuwFFusF-5kM_vn_aRiZcF_Fy_EfvNld-
4EQZtSokO_u9VEJpVtTHz_mEv3v_DdY3b-4cv9zp00y-Y-zwUMJ-JFtRyLqFvZC7y_chP6wFf7Q8Xpw_Ub17VmX-57_kJf7y1_73-4IdFea_gpFSFuWVN3q7
qxcVN3seS_zG_4KdLGVnezrzQe_xrP177-CVeBCgBVKXlkjobNxBbtIyvq8VueCkLPtKjy8GtY7tEzDvjTX_qpV1eHkD_aXqlRPnyOck7wNL7xjCy8rsNz2b
Qkwx_dlLUxtNU_q7
}

