sprite $Hard_disk [96x53/16z] {
xPRRTgmW44JxHeDevly_znn4BHb1StlCdjUiseiErK8_vGzc4RqYmlopND4Gl10z3d4t-R97r8AVY0v3byzBM2m4X4DHVeyIkaSiWAxZ2LSQmHfEE0ojun6N
RhgP1Gjlm162gGepYrfuicXdCeMhmOiXg5p__jRXV8q7hMA_6RnppFDEOStas_YJGNcxLEk4p4gnq2osiI2SujKkL0SZnBrLL8Vueu2ryXvlLk8jvMbAgQzO
1KE38B-lCA8uv_zCky8BrL0LHEDhgyW7R_bvcOjXgDZo8nIZV73EbsLPe4XLWJaniLUgjzi2-S-xeagKYDD7CNGL9S0SnDR01457iGb8yj9Jk37YM_3lXM2W
KDaAuZ5DULMaw6Km1UdkmUYEWa40HGiJG7lNOjpiMgC6bh5YMsndYwZQtQvLEk5HO1WeAggYQFU5Sph7cIgIOdA6OQIuqDsr7gH4fTVh5Mg-neB106uLeUVO
qmj-vCD0_70AlJYGhL8YP2hXo6VVCMpwhqqgcEuxM_9hHwWY3eEY5P3SAaeqLTWYqbyHITvWmYS93nNd9nohf_cZiCTdwZJ50qvIBD1SeLDqNfQbffTVOM6w
VY63GGBB41RpbEV2ie83H0B1so_yfV71EgFtc2ibVQxnks0M8fsEVgN8HANpsZXwhwfKc0hvO5w188TQ0JlTVyMNfg-u5-08ULq5zl7UBnU2ecSO7m62N5D2
RleLwzkurgiTL4UGuc12MxXEhmsbYlg1Gj4HZ0ymnS1r5ilhhG0GG079KB37Jwa--sluqQws0E8DxzMgvMrlr_QSFX8i7WMhL2aAR6s1Wy4o0D7JVBHhYyzC
BJeeLp1JxQviSuzfGdshePx1w8Ae3TlrNAzbHd-No8DrCYmm17q3Jh0afI7jaXZsTog2V0Xcd60o0a-AiM5AlGsKZEc9hzKB-JagVGtKQsYe0XJiYw1TPgi5
yJ7Mcuk6_GAhIdupyez_
}

