sprite $Hard_disk_Sm [96x54/16z] {
xPRPSkGW34MrWcd___-E6Jc3Z51Fg7vCJkKbspqikbJ3J-SNH2HY5X7Lqb4LOIP2nC-2MRHyKJEA46o3n5e2kKCPjx8lIX3K_bK_smYo3gB233c5uHqaEbDk
z47DKSolKqGN21F6GnJTC5YwCQSZ961gO9XXyUYG4Bo1Io8e21vaouyAj6iHBNeXOiqY10DBPk1dV6TXu9vUZwDUb2y5EuMalN0R9xwHcPxmUhNMXc9iWk0Y
hPw6V6FER-VvweeZAhf0itgNS3uB1GBmsRaLrIlOBi3Nso4mO2Cw62xgEIdCm7R-JuO37st936X-hQylGrSKOOGE5OsFrA82I4IyTB1lOAdjyC-Og1RLie13
tpky0Y61zC8CiuEcT3Ea2a8CRxZeODg58h20WvdCa2fi7X4jMaG3OnSCeEV9qtmI_4ynipG80L0VXZhowM8ODXGwE-mziN46mnyzuQR26-JlVsixZGf1u1IR
1oNsVznhSaFXCyxDhHW_pHNthTzbgEtLCKM11uYJ0cSvUsoO_BIMTj7JpQ0mWvF2XtWH8ZvhKEjXj8uv509H4KR_aIjQwi0Rsi50_EmN3eLtnEFkmSRqv8zT
A83O_Vf-8GI5TwnwLHQAAW1uBFk5iAc8ZjvUrFVzkjbMsCCjnw9V8uK81kbbH8Lz32CT_UBGhrs5yM_Nf6tKAnJ0funE1et75qpqS0KxAtvd-4T4n1VCvlBu
Nhs6mjKhm2ogMRz2_0TJ4-gLn-zFpS9H5I7ZSuKIl6U_maEX395zHT8lWfmFxbiaj6MV81dj-D7yyWS
}

