sprite $Home [96x95/16z] {
xTZfOgGW40HWZhvma_T_tMLIc26Y24R_fVxicQ-bcfaSxeRy9Qg5n_0WQSdXPtIofUI98_YbYhP7u_2SxqbpdlAZw5Va2J-mVeVkyXEjlOZM2RVuHksZb_pU
J-o1auWqllpEJnhBIbaGtOIk--zUIAgethI2iAvqatjMW0Jqqfl0rt5Yy6rkM47adA41uL8noCW4cUU9wnmCaCihW3z-19gzc9vvQaAOuCK2-fyO8CDwK3D5
GpCJUBHuotnqQ6XimimAvCM7zOPE7I6CTMDVLKOqD3D1Xhgnho9P2GDcIkA1Rl2MBF9rt40yTGGwwmRL--_ZHkAf8uIJRjI_K15PRnpHr16asmqsIrByrotr
H5D7u4utg9whA-rVAvYRG8VT65vKKlc2XgPA2WVTQC1B2dm9OS3K4NQxGVMHMMhVBA2XcIFmNZUCz_p6rzVKtW0-Mq5OgtVutxLV1XFr9_HNmAZUL_zNIyfe
J_q99ojOgy-HrZTSqgaZi6joo9kYeQaZX5rVTdsZPa1_0aVNXgNXLn-NT7G21xSNUMV3fsIuf2Cb4VIUhusV10sT3Y0FRDPFkAGd4yXrSiJ3JxYalGd1TTFm
MlD9iOAZ0GGzQjUdbb_zX4lQv8UU5klwMNWF4DRQNm8QQWT4xt8yfsKvytD84PCOMRvvF5fiVRoMl6Jzp4TvdbO_XzWAlopIDbIA2PB0_plsDSSXdZDV_1mp
-8j_3M_rg6dbptr4YhzMREM7MFKAeeUE0nPV1tshVCwnfHIqhY3K-ifVzkNjktSndiqC_3MVzlmGAttp-1yNVAxzu4g2MCEV-lx0bsy_HjGkgcPDEnyVqlML
VlYquuk7hhRJJjT7QElpnXUM0tx8DwNLhnw_zb_yGJldlkKeTVtEuv_vLeBVL7pbT_YkRtLwlXukDuU7_NJWTn__SzXFyC5N_j5omT_WTzgPy1DyRlnkEv-V
SSnFnLzvhVnEEuD-IXs_qqxN3rBpyBdrE-t0FuxdceTV-CPlsZdtCI6bljzj9u7lXUpjS_6ryZljc0SnDW6-dFiVY48VIRH3d_SV_v-ugKJDViNNViilxAOJ
TCZFF9Owdx3hRn_VWhiSp-1RVob-izJPyDPFbI-jFX-shGy-iRifqMeVl4LtOwBzyA7Vcg1lNuDx85xWYtSFnSVgw-V7yvU__0S
}

