sprite $Home_Sm [96x95/16z] {
xTc7kkeu30HWdCWguPxtVztTCAnmZ2CK0jldziAlU4JvlfFBFo7_PwPlucpBekKxUAcst6BqbMjVF7PvpdJMfy2VgkZqBR-Gt58-vilcqg6hy6TygwMzz2Rr
l6yoDpZBDdJILsfxuPO_lu9vqmiZdNzk1UsbytX0FOyJR_Ef5Q2Noi_vr0gcMi570_ZzIx-5Xpcz0kZx4ywje41EJYWdhZvJ4X-pjM2r-IFKl5vOLT1G_WZv
5KoYgbBmvCnEoA-WggfoyHsaI-9iDwgrUGxbZr2JtIZTRBnyinDIAo1TCzr-oyKRIXzXIdI3FQs6ho0zWSDkT0rZ4hC8QgAQdn2jeAfNFz-FE-FD_yWHQAyR
ULG_-yBG41qvmXHqW-gfUyOLEZHXlnjKNzdzHqEKBwdkTLF1rpkF53GK7o5U0MbJlJzWyxvBmOINAwYelk4RNybNa9zGjWC4xsTugdUyggyWA2bUmUJLLqPQ
tv-aqOHu1IYihddsbRsX_176d-Vi4VURXh8JwjJRk_KWnGSaIgAoz-wvS_bgpGhY8q0_x9k_JyGJK4pezpnyynKq2VIy3zwqeA7z2GGzy8FBDnCqj3V1Qu_z
2dxW6w6XFfrEiLzA1O-0lwUC1r1J3DdombzV1ixFn8sl87RrmhOihtnyFFxX_nvYDMGPFKdBHi_uFa7X4oQiZ-wVf9Fhiq2_nhxu0rWKFdOekZuU3KtFjQjP
mXTv-1K--3NYVddMdS_xkkjVIbDCWMu6_cf9dmF_qYnLLS6_vOFlVC_Csl77V6rzxVrPL1iV_AyNlimxFiFtSaWwFkLZWllWEv_B_IjO8pxXOqBdS-CB2_YH
ho_zss8VVkrzkMV8_yI-NnP-fP4VyYzytQQff_Vr3R_JJS4F_J5_nBV07_B7V6jyRlsedRnly6lWZ_WVoVaM-2rlpYTyQNdupelxGJk1txzbmQz3F-3XnnFC
GZzgv-SN9UxckD_m3pzevqh9MpgHlyiRzFm4RVYX3nw-pfSZeS0Vl7BVk3r6kkVt_9MX7mqv7_aBNTuDZVsMFtbRRnhu3Q_GJqwG7LzG--a9jF7llB7hfrEe
ypz_DvLO7xv-vrwjmfVvygKK_FGloV_vFxy1
}

