sprite $Home_page_Sm [96x81/16z] {
xTRPUkCs38PXaCH6flT_lHr02cmPaSE8wjxlU9xtby4k0nFzNqLQgxtJYzuGdlkYTrJVV7uVYtLLElERwhIp8Je6MDLaQmnLkSF7lzJ_t-Tc_VAQXUPx4_vI
ItuVkVxIUvzUmxrsgARAPnVygO6wuCyCbBhWJzvemPyQMFAzRmOMV29Y4L7jlvBJLxx9Ft_bQxxpHvzIFdV99ulbuFSKJVYvB_XXVgvUyYcES-BNw9fFI7pW
q_Ul-9vumG_1DB3k1sy-ekWn4LpoTUV3Vuug09JBlbezUFUnHGNsBlhi-Cw7ZmSU5Nr0fVtSVzR3ZmM08durW5fyxAe_NdpS_JQi7X3B1NzuuNDKDh-JAzLV
dd_aZoXywf7xszbBOzd26J-7ARjFnGtmVz7tsYMVib_0gyXU35pnyy2cbqR4aNWyupEbCb-HYF80plWsm6UHyusylD1cV2RI_dL-0Qw0TB9G9lppq4uZId0w
G9C-fVRJewgj5AIl5t3EPqevpweD004Qdlo4DkTpuktFYqg1mj9Y85-rJFYIekqs352P_HqHlrwW2L_xIxZTXW0QsRhje4Lv0B_rqusAtyPFJzklyoSu-Gbj
rey1050xFH3jlbQxqCb2UUEBv07_VZj9yA82KD3BHw9t_ic0HK--nXFadz3U--A4n_ByavzvxTiJv0NNt_hIS-h-uU-D1G1V1x26VkOVuyzx0G0x7xxw4qJx
l-EJFaV4P9bFjFFkT_8BHNwOMgVy_ChkG_K_W2JTQZPmqEK39_mqmEuB6S6YsFO5Gnolvg6EZpa_3uGFrNr4uZuQG7tyXR6Fer_E_Jpmy5Ntvnp3iEeMsOkC
3_SZ_K4dlbV9Ntoy-lM7lc3uHCJckouF_hVmlKOycVksKBK_-qIyyTrvzoycOXBrpUVDPvRuVFFhTLyjemZfuSlXynTzbux-WL_s--ORB-x7TTPzCjqYUlY7
ptT_8TmM-Cb_uJjuQmliVFYFwsY5vPeU_VZy3uPxQWT_vmV1RHNZmxVhT8HRA_Jfs-ThXVl3Jvz3lpjg00H_n_xlTm
}

