sprite $Home_page [96x81/16z] {
xTU7Ogiw381XMHjEt_zvh-L0H76SKE3kytUlJxNQBFZtLqGlXp3ExqXW5FiqNyuTHeaVPoJIoaajVd1grRVt-13XF2j4-X_pV_lU2YwQZlgNU-ztsJRjaov_
vwliucUq2mVzp1S-EE6wtm-usUy7tEpt0sxrC-a6NFRhkwfcvXuNeZp8d-j7L_taDVZLPzkdvttP_FghBwAIiJ2VzfkUwsd-jjFxYSBNv3i_kk9B-A6lsw_r
buJpVcIsyglVdQ2KitxFXo_J9YEebGk-U_BXRqEeeHI0axwlUl3fqn90aRXbf1ZWUieFFFZqSmBW_AZwfJmFSznFVUVpteyAM-s7VkBfHrlV0q6rblp4VyBf
YwtfmrUiEAijEVruFndNT8shRrKhf96jbSD-ndqXLmf5Mpb0J_ZIwr7Xfkyco0bVNbwqeXS3wBElAhiwliXIFm4F-2gYWqhe2DmDM2Ve8L_zPHOykK4Ew8uW
1tmTtAf1JTeK51bDe4_-Q036RimLW128XmFmWDzFQ3ov2m2h5c0UJT3oqUy7BBjn0f1g29HrG3z1Flk-IqlRZI4KQLjWG1uUWOxvvjiBFhKfsFWQ0l7m2FZU
xrO40DfMJxBw5XiQ7g4SyQEDJm2ykTibW3oS84Vy783jKWiY6zyf1_G_JIFVzDK0Y33vyBq0y-08NDxxtUDJVFYQ_ZGjVu9kWhpx_sceUL_rDVdm9mRi1yGo
t_gcWnLr_eH0dAqNy_B1D-rQVQvy-lC4vTi0gZHFyjv_EM7nbxiwojhysG1p09Psj-xN0RyViFXG2NEjg5hrPtmEG0Xzce_vDl2ZXy_jNf82415JrR7gmMzy
7llsmhUThx4WA8GbT9zgbT_uwCVR-iRf8zJ8_C6dt-BZVY16wSlYKocX9_ybS2wo6WFuTr_oyX3yDR_QvDF3LmkVD_mS_1UVzJqAoe9Ftsl9t-Lh-hcTwtv8
nfB-z-tKw8e_TVvkE-Tzu71MNnTVSZlfNvnWyitFxKG2LoAhriEtz8Dl_Y-1gw65h-ddTcQ6EqBT-i_jEC9TbSQdNtahS6Tbwy-p5BWzzTKN-7EYgVfEyEU5
KE1Sl_i3
}

