sprite $Input_Output_filter [96x143/16z] {
xTXHUkMe3WJW4aX8aDx_Uk_5n_e2rZ314_kjAw_ENv0sW1kR-PkKNjL5HDAh-ciD94C8BuJVREWUlTZ071gO7lNVRU0ZiU4v_zq6vdSRUCYqs7hoixwyq33n
ycX377zFR4ZF-FE_QtweWVdTXe2l6kYNFWk_qH1rJybFRDwyB2YbyBM1wRRlE8DuzdlIRni-Ed_MKGf-AJbiItVzhhDaT8a7tfD-qz3r_YCPKXb8mLUD3NdV
xpRBuRUc0FZgzmRwhmqVtVrM6Q29Bzgptn1z6NoVWapyq20t6rXuzXiw4tnlkBkrTZtwWBYl6mqxFg_yEGMXuLU-XiG6mZfosrUJ6rkhNFx-IXU_SBdmPh61
QMlybf1L1b-L0Gx-JaCSlp7IyUiy-o2P-5N33-DF8FzjFdtjFcSWZmMUU3pygmynk_f56TAK00xyLiFq3aZmzV1Ra-v4lnh_i2tDtIIJh-f-imnGvsV__uaD
mHyQaWP_M1Ui6ln5G_1ziMTrNoUVq9dezuH3D2ty8WJmseT6liVItC3HzrEbDwJkwvxl6Hi8di2Vrvvors_Dg3USUhReb-BXrFd9hvXz3Rut0A1YLvz1N8Re
x0jcdq6bNdnl09Vein-BxfV1BmJkvkW3f0FlOH1By4jXC05ftFVTrwuVoOCl_N4DlWI_7ARlCtaQVVS9sLKPV3qU9_t1BsU6VMOwjiItfUWtRzZtMsLS3fJi
cqRqlnlQhk_tdz0GVVS0aDtpWQAnOUq3zLU-Dwnzk_frr_Sa8ESNVUiDkxwvN_PzCqra6xwKfM-CgoyV_NAmdBunzlrQ4aXK9b_EvM1p3hzoVpvl-WJV2FBe
-xaRnd_enrQTer-Z3pOFZpxBqN3rSzVFIFJRu6lN4Y3_w4khiO7zwP_y4ofTGjBe-tVVs52h0f0TNpy_laWb-EFvoCF1Mth3XZ_6fn1zFz_Txn5lsFDz2jnz
NVZg_DGG_HPzzq2wvNi3IV1jy4COeBNl_DIGDtmkmnTYz1KBl_M6oI_HltndST8pzl4j8tryvxsbcrLoM_Ww-A2Y8Tsl359J6dn6KlTxDdocOGhZ-CLt0WPq
kFDdNVer-f0c09NWZ_l6u3FrXdR7RqO0oSZRzVvJF_7xLROxld_8dJbD90t-SB-oEtup0EH7rk6gRzt1xmtmXas_VR-svb42IV3T0v3ife_foFK_qj87wkot
dtsRam5P-x3HjmtVhWLAeBplVotywduC0z7dMtuLqEmh5pjJBP7DVY7G3Ry0Cjy3JVpMulBWAo6h2GM_JdxupfBPxwNHLoLlbYsVa5tbqHS1I6U-Je-R1F_B
_V2T5Vrc6M2RVNzyrzUCrVZFZIPF3Vxuhc-g2U25tvg_d9vZKactVEkwcHK2PE4tmZW5_p-jh3_vfstdWo1P-y2ttrEFXkWtzzrnhjD8klPjuB_dCFis-JhW
Vfkd7_msn0YWfK_5GfG02pw2FpH4_m-mRYXozIsv_-5h6KjCsj87I2rczWL9nVtpTPMnOVAh-vwqRAZTL_BNTlG1MVfVi-_lSUIxpyZVwwZpXrzuQ0Z-duiF
SCJDB-1cttuxVMqrD2pyLKE_nHRWv8FVGaFqrmr-GvRudUL-RqZUiEExD1yd1O14txsUClbjwVjog3xyQGvh7tNBz-Lmsg5XxTkUxmsTZ0sKdl5zeuyDJ_a0
nuPMXTlLv-3dBH_WA-yPV2LGy6jhVpPyG2Bl6UvNceF_vVv-Gml-Hp-IT_qOZNnFk5_TyUFBsg8FCNl23rzmlkyyClvrWzz-ejzk--Y32Z6VmmC-mCk6Pto0
swhX2Nzre1i1wI4VA2r62O_v86qnAkq9FxwiCTtlVFJta-nT7yZrNH_W-guFyCi-m2_xWBpi0-Lb7wJl-W3PkpwGx4tV5vpxNo_u05VtE_-y3_3W6zw8dBuH
NaeHv2tz_VpD_m
}

