sprite $Input_Output_filter_Sm [96x141/16z] {
xTU9pkEW3ePX76DiqDp_zPuI-gc6q8YfoDcjPTR_UUa6DFoFpF-7el2ZUXr-I6V1F5EeFeR-qmf4pnQE69ygm9yKuhO2lNWKQ6y1wt-m07zUuBq-2j4LjleY
-mkzlx_G-_iBHyVlBdXVd1T37NP_GvlMZ-5D1PxmAEpOD0xeJ4CXRIYuzUCL_V1fHw6jNweF2O4wrmB_j7wfFYGiVqVXE76fVapqUPB0e_3hniSd7q-_v7XA
x_LZLENt0bTSfFcb6EF9ICvNbUE70YZdbwAXJaoTZqA_QVpabp0452Cq5kXtdvr_LzZctnVM_Tpx2lzh8TBV-4BS-SAYqmBxmggln6h6pZz_s_5cAc6vuFrJ
hwFqyUl4pgyJ5pSDxnEflKTwFv1uVgtG-n82cyryFgKZmLyiZFvHLsdlqRUlrI-vIUBMlrpWxZKY6TQlrIz5srjczBF5ssq9_bY0h_1BQNjtqaxFULAWgTyN
i7w5Zy-Tc9zSH_ckqFieD5-zNzfJDF3p0iry72gnGMtv2tuTFRvzZ-QUb_Gkn8iV1Zz__58A2j0lVepkp8hnr9qlHDvNKVD-As2ET5pyy_Uf7uMVYDN4-KVT
D7eVx-90CUdKxmkAzJUzRKlmJoaQV8mse_UJIAh-zE0DWQhUHhsFWlVBouqltvn_yacmqQ2WM3z1xtqIGg7S-bLFrO_OQABp6O6BNqfw5sxzL7bfVd45VrgH
JlrIf1NodTz6-lEN13uACn-Vkg2zhzuN-FtzGNKiJ7qETOuRFztxll2OZy83VlA59J_T-OceyrzGKXoC4hNtSwIBBz_zBDXduElqN8GlnAQqx4Vi1EnyN81C
Hn_N9RduDlL3D8mudoZWMCRawX-CeYxu2SR5vrBRuL0VeEuellZvwilXTXhrFdODLkYM6NzSzZMvzv_qVYdj0KU0sOHGkFew-lg-vaSOWryddTkIVWvU5Exz
UE9Lhud4pO0_lpzKtnVk_VvZcevQa12_-5Y-Bzpw9pr-YUCRtvnVMk7URtDG-orUXjx7mSFZnQSLl9-cVkeE5JvIxmkn4lpNnC3Q_5fWNV7nBG83l-bcDS2D
psSBAWQ-MPdvkEEF_gdNqTwlV_eRFxu_H8CVkBi_vBTFXCAoZsyHudp2fd7nYnueZ7x-vfSY_SjW5V7tj_pnor20htT-CV_N5SMsTFMnQuIOr_tY_lxpDP5a
wkFyvPzym-2M-DK_Vl7DJJetcgs-v_4oRF1neeCzn7zR7tsZl_FrO8tUToTlLgRK-JcI28s-MRdwMltC95KI-lWuUJFsvOyl5Dkhl-WBGHNlu-7atbTov--A
7zWmwlosCPDaFpWPftukXIS-gM74-zWqzCE_75AR-phtSLZFV5o037nHt9OMV4py57JmiPK9V1GMVHImsyleutCNmRl2cdzgA5nzt1-QZmArmhrlUjAcdyAD
3zuNvZu2mEkWSEE3SeKRVxpQev16tuBtDMh190hH-MO5_jU2gVM-CGcTVe5pV0gv3FuV-2WacqwkVjDhbFoJvGlVVSmnBrI_wNMqyr4O_Gn_AEXa-Ja4Wjxx
f8n2vnFywx1U-EghJVrIK5Zq-q8--IpOLoT-NxZtCT6lluv552O-DdfPzb709H-5EFTnlg_u61BmVM7T_mF_Uo7F2ZlMZuy3vAwmv9S5tn-7E59gGKR_cFbu
VjOBvHpJqljAJ3_x_i35TBungPboxsVuAnEjyVdgvqZOE7xoKS3gHn-NiPzzZEIfhxR93oGNN_2Htk1V2xXnoGOVXJGlxF7dfw6XiC6lmtOfl1oItY_mznJY
gp3uV-3_C37F7WDF_8q5oHjzRABTRFK3oMC-2kan7mLzoiSS-fIFONlMHw7t_y3VCZ4_jtuK7bi_2W_xWUGn7uNK-HIs3obyh7xt77hw4XuRfl0_C_-VVm
}

