sprite $Internet_globe_Med [96x98/16z] {
xTg7kYCf34JXfaibYNd_1rwRreVCWDc-azFPEEalpCtX-3twLtc4LddqZMsqv1cl1EKRsIVaSrslldwZG5fe3Rgry5KJ0CQ1KNTtWU2B3o-IVbiOzMSA2CgN
wsXm_5T6dVaBvUCw6NB6LzqqXwaVN2ZavGyR3GzT-XDS0J75HmR0yCS2R_eLxH410i17xgQryDrD-VhoO1ONHTToZwSgbmz0WmR60GBYxiIT0L0r1jWTB8e1
DNFItEtM7K4rVGQp7SXdrni3HQEy8Q6yBfmdCeaRSdCNF2jxdZeE04Bk1kA67bq_t0-8ZduahUwtXVJPpi_u8VQNlnkGxey3Ubr_h65tEzi1f3yE3BwylI4n
s_a0K1gU0s6cJrAETR3qfu7aLmENBvTFh6z7RJDmyO-MleKlR2rlYDPQ-icl1zXzUORLyMtsTUIZfS_X1RtCljgx0K7gqq2m6Zi2j8tryPStXEJNVfnRmgzL
5mz0rxuozMpsu_ZDDq3a62lkwm49_DWyWC6NAe1Q6NscFmpmzVtD79Xy2H-W0JJZw9kl7u04VxNr8IG14uYP-UVNSmqegIy3Wl2Zzxu280KWmAS_N91SFlix
1GD_nwz4I-BuFboGDXwHwEKZ-5k-4v4stwVh8Ngqv6_TFskj5c_mxF9B-cW-044EN7fqms-n7z-HFlsH3k-9A85obfV6Py-rRm0jVAPliqy03o7D_SklNhxa
yTtIzzcNZN--yVFuhS-V-m647psDdP-yUB_zxjSo-Yxv0DA_Ttpsuslm2rzN_Zdp2ryNnqyVVXKlVkbV_Jylrdn0NevVqNtHyGKi_TQWB_qQFb-ENwNxW5WE
99-blkBPUD_uG1-Gz3TXFhu1hzTJsNt6GCk0w2wlir-7yvFI1nJ8zlpukk6J0i7FFWMGVdeP1_QyMFY4zECF_XaV2ccy4CZ-8M3a6Vpaby6d0E6F0rZfoOjV
VFY-y4luOFWnaAKzyLPdlwvy4Z0tnC2sv3Nuy7tlYxj0hcxnJFwJ0Hfyw-XHsry4r0deZG4P-5O5-EBxvAi0ve0GqjhpUJanGE35ryN7ZO0uaMrrMWq_Ce1v
FLXzr0xGLVPun9fy902xNuwCEG1ndoOaxOZM-QmAmCjNh3vkjmQRzyoCAKzwyZa0zMh0u9zgpxzCJGb0N_rOcFNaiqfWzI5OwA7Hnm6LFi30PpxowpG--hGU
0N_9MW88rSp3JNxEpQpwCOJEUpj-bgiI-8RFU8pfVFpzm9wlmSuFG22-790OI7wJlFtu6j39pu6RV3scJcifOFv-WCdlmhlFRpW1hvi1eOM-oOz5nTpSjhv9
V7Zc-u7pMCKdrVpt0ogu4ggz6x5ZMR7klnymfG0HrmlbM8Sd1EY3hszzqqUaj1MfDv-uUKC2wFO1c4OKW3Eln_lipe3s1AWtdlMpuhLU0_iRYhZmpsCNQWpS
k24APb-EVRmp48S789jdpQyS0A2svVTNHD_U483Kyt9kTFer0DhRWHLVp-DUHTix6034ntQybUDsyhmZ0l2n3S_Z8vrsVK3YFlQEz_FuOAYV1ApJm8glEBuW
0NJbJpoFBmpqgOdNSdnn1Q3j-AhdyNML0choWkGhlnRFXo5KSzSylRDyb--le59mflrBzw__
}

