sprite $Internet_globe [96x98/16z] {
xTc7bkog4WFGDfAgOFx_Wzy5qxLeW_sOiFBHpU5iqJAJNt-HVpcEb180aW1IEew_nD727aaYYVH7E7dLxOoOZj_XgRDlNuFkDG9-eJEEZHfUTSyEMVhXCCrb
1E1L_o-a0JzPYL8pH_-YdmCPG7nNXwHOdMZXvUoE5YDamlUcKVY8iE6Xc_e34MJkt1yfKTqdXcZKsHlTtK1txOy4MVS_eq6F2zkV0I7FjhcDcSQ2sDzRJ4tl
ELy0K6k5OsCRgndzkFwcTzMbGAfy1f3s-2W827FOCgm64Cy5XspqnoLGa_xBND1z0kJpHBI8MeAFLn0DKM1n_3Rb0u_GOo5AqJ0Li4MdRm3vM90q-RqaKlsf
m9eVhpKzhnDP-AZ-L23FpMUBUBkEFnSGE2e-5TY7BwpNCL_xKL3F7XbzUlYKfEL2Sdyk08xZM1VOXszSy71_A7ZpOyFWAtnLtp3x_kWtlcVXCsSd-8wuMEUf
W43g-hh0Eo_Yp8K_t6yBI02lOyZicy3kLsFoUUzNetswzkGBuPTI168w_hf0n57rbeS2eF7DTz3jc8w_B0Y-vS5dzraoQEuSVVExWdERoArFD5vGCJHk_5Kv
t_Z4iUSRSCxZ6Mp8yCiOlid60Y7yHS7ekxtzVlnimppvB101A0gCm6lNBm98w7tyd8VRask14IsqxhETVjSlJW0ksCdd-7N8BOnFHTGAsFJD_NCvut7yZ5UF
6ky0IKH1yD_o2Nlx5lCttq16WRbmf6RjtVyulgppsMF-sQSJALqBZbjVtIVZ-F40ZZpxiEv70b_nr7pyy5EE_Q_-MF3u_jaMnoyfhayBFmOYch7fvpZ-uFFq
sNsDFhgVjdZ5ySs3B_hqFVmpdNdcntaoQ3xxaESM0nP-clJPzvXdu8jr7-y60HZuoA17iBmzFlXVtHS9UgunoImAdZBozD9YiAKljO8UnqO1fkE77_pW3mLE
HFPuUlS5N_gz84xFgC0Ehz93Ul23JxN0uht4Sm46VdpN-GL-7FyhxcSBEFZt8-7AUxdpUVf9BOG6dnWpuy5RyCqF_kgR2A_xAmeUmylurRluY2zAPJApjX0f
zcpmCNxr37Ro_P-FxbkBh3rYmSQ2PrrU1j-XyVYb-wzgjn2U7Om2yb6dIl0jvEZxgwVhVI4173FX4Hlu5eTrlaRpbzM2SdPo8aSwjXdvba9u3Z-z_SCYF4_W
WpF1SVZW8vdm_dJBy1cwZGNCFNx6ec6bXny5ogNgmFeBTu4U1T60JprFV1G8C7T2zeeawt5pi_4Lz11XoppauCUu0C3h_96JzlQ7OE57150oQ-lUy97idh--
fgzVh4d3ySS20psNq6_vI1dzD4AMLmK2lUppvpmH6wOEV2xOvylTrzVWx4T1tkJZ-14DysmMV3t4NvSSuNj-Al0DFjurZr7uPUd7DJN__xozvhXdpzbGR-5j
WP6jmlDZmMiHLglvmIyAt5e5MiiThzSgVlhrvJ_uRZKY2J1ltCt8qImmbwU5t284yiR3ZM0eo3i50XSyNtUnAgyA_AQ0tBZwGzfxi5QmkH2tneySfQOLR2n4
W7lZHxWiM2z4oClErHo3Tu4_5Poyxp_RUIBOqq9hlXolZNWjo0Bbj_wIzm7PU0W4fe8dNW7iRLGCTmkj-BG1HwpwMlfhtlRSo97B5rcM1OHTz7nimv5KeEv7
rdn9hnybqMP_vlMhd--Rvo71_u4U5VBmF_cYsFrt5Q3CBtncu7-G8wK4ebxCOaBw6_jV_WS
}

