sprite $Internet_globe_Sm [96x98/16z] {
xPa9iYAx3aGffrAIU_yB_hzaIg30ndSWNaptz3oTb2NZQiFjF-AFFuxM0BHsV5xT6cJ04n6q3vQD8EtKW9-8kDUDG1vs2tuRqKRP6L7jvePVzGaI_WoGObTL
5Vmy0SosOo1FUbTS_AXBZPHmuW4VTh_y0l07Sm337wJeqPgnA3lppbW1lcK_65GxSCan67aOyFXMRm91GSoq_9wSVeRT7LyDE43L310W1oo2H8884BexlxgH
cb3Jdoea9O3dh0CW0pPw3HY4YCy1yXfWeto8x0CEqJlP85BUh417_QEDifq1jFWfGhuDOF5Zhq-OP834-Ly3r2tzku2cpnH_WF2tuXVpXv_ItkhDrWj8VGqG
FllV1eZPEY3iHnlK1QG__kAwV2l-4f35JmAq-DTddLemyu_Y_qy6r0Rb_ZbPbxy827qxWja2p3dA7_wsBd_Q8Kbz3KY_CayHdb5lowy1jVZWrI_8yhsl3Zgn
QO1Ww6-tkH-fF_tI7H1Ez8TE_GpxRL03Pdvs0TIEHNkIv_AFnzzU-4S0Jxy2DCEwFJM0qPkjdm26Nn2YINlyuRr-ZD4UwIy1nMzyFDruQbuQrDpTZ0Wu0fYZ
tVfTCOZo9mtYwHVWEK32_gNwtPsukc_cUgiS-J-c351U-dt_tNiW40s_7zKF7twH351ys-zHMFXH_NBvCo1svjs_s__oKhwp-ldYfyHnV6J2czSlNyfttVcb
-eFbzdyftstdH_XBmFhyV2dVlUYFony1INZM-lHxbf_-NZPG2xyBAgq6B9zVa_9xAtw8vWki-8DgJtrjZm9FvNSy--DlnjYbwYipVRQ7ETtmi_Zb2d1LtGS0
qztpL7xNuYTb1DGnxFLPVWVux6VrZu3Gswv5GEr-6Q_V_QZxPmHCXhosP_bblA5FVxdF0JBq8ii457sMdtw__6rwNsI-o0f5NlJiWt-ZFrb-hmSqbKeLm7nv
uS9CxvV_N-mVJ_-jG3s93X6Gaxq-cfz-1RBy5x-edX4nulp7Uxq-zFzYWwRVvlUYN43mpbxr9mGUVimlHWHeASX6JUtqeey9XtwCjwA36B6618bK-qoV2oZj
gGFE3aL0KHPtG0jFyNT0xdeiRuuy0ro1wscXajw4wbN_rA7UVVBkug7F0UwnrIm3QaBOgpuxD8xAuYu3i3D0FPW5aEOpVT29WAz-KTEGcLt-331UxqwgUTfJ
NnD4nFNLtyAjGsR5Vmt1WuM-WFNrBloUs8K0EELVqVjjml4mYTU0x95wt-Y3TfiHnwkv0Ppv8u3-1RtUveJTSxmPK8UmrVTZuOV7fWVCrm6Py6y5RolKx_u-
yGUC1FMqRuPRQUbV1YWbtofMt-_D2gk_1jI4mFV3hPYx0z9hmClLc38ov7MugLfsY82k0-hTtjVTMNTex7FV1X3GHNVMZ0b0_5s70ahujrk_WklTGDjqA7Pg
dtHdtw7kux1v5q10VDATFV1pkXcmw120lj3lE7GRCDixk7qP-0WGMmHCHjkgOhy45m0szHDWrVjn-nw8AnjiyQYHlZqpzqieJyhwj2zwFNxwwIDxzUUJ-9Vs
UkzExdhf7x57Ges8ZSdKEu-FVBuif9gvH-irvUsJduy3a7ocz4_9wq9QeocnK7-QF_xu7m
}

