sprite $Interface [96x50/16z] {
xPU7ZiD024GZc3Lc__z_h-5HEkSGh9fHk_gUXosAJqVd4mLKZc8lFYDksWqNmgb0PmqGVXb3DztNrMnTLwV2El23S5ji2nKT0WHy-Ss5O7KFGGVU5kP242Mi
3Tyl87wCWmJ47oGG3tmcc3z1aN_6vmAN4dxvnGDx1DN7To0LS0cqkBW3JmGqR0Mi_FYHH1052fidfX_unm8QIbj8VyUZkmG-vrBYGnKq98ADZ_bge1HaQq2-
L_Wx6f1lDRuYCLpoJ_fA1laN3V1OyCxwHf867NmW4P1VE5z3T4-3sXNjSvfGa2tox_cLskSIbHqDd1TqPK0N3VIH8COpglU_dWNFZhBNnXFtYGi5pyv1zVhV
3ho9f6jWazClnFyLsEHqAX4A7kvJud4gHv86kCJtDsZ1K_1ectRWAPY6cmRcypUZuRqnI6vG9XwT-7SZf3d3xt78sodXSi3RDME4DqO7KvdB9zy
}

