sprite $Internet_cloud_Med [96x61/16z] {
pTW72kiw60LXVRF_FR-IWWd_ZOXJu4vC3tEEK75PVnr-9gOxy5rv4p-m_o91p_4blTiryFvCuXwWH6uaNU6il0wu1K8aYOuGRyebM8j9X9HtPb91TaJY7Jto
2cczmbjoWdFb8wSuqTvvkopXfVhUuMfWNx_GctwgsDINlCUYaJ3hvst_PaSRydVfWk7_Ja2a6U0L-tB_RKWNJ3-nTryk-uZC09Ms-kLuVDWbf6P0FRKVpUyu
4dO13_zFskW7J_pDAIXBFM__9smIUXY0QgroEk6bDQIAP2-VMFl-ZfD1wOdV2VsSuMxWv00iQsU_-EtxBzOpNje2kg5p_MtNp_Hl9jYv09f--NHvxljl9i1o
fduv_6lOTwVRuTxLr_2FYCqWRBgZW_7SyvJbyVUKPFXVYc3ThnVr7X-ixFtBAzJ1VEwKjvdrvsDp-b3VetvEG5zgtrepeCYxZFRJ__uaPAqC_GWGEKsiOR-X
ZuUGrdBOjm5E1kHg7VPzGB1Ua2jP3lkaYR3M2teNCMk3OU_MXttp2-zyXt4F26Yqljlxx2kLwgxK8TRKxy6ZtIrOoM5_O9q32DkX_VuhsUy_yx6-YWwmVWFh
B-5V
}

