sprite $Internet_cloud_Sm [96x60/16z] {
vPY7Rkj03C14_ly_lra1FLIIOo762hj7oBFEcV5HGFA4t0DuJ9xmWFs10YeYxoiSEqYDx0AO05b0JZLaWwrT0UWFGH1aOnU1BD0Zl1muv7TOJDwt-qqc-Jv0
sZUSv_IiT-rtA1o3tmG05CRb8wm7v51uSVHnDI1HkkLZB_vwoozjMTNI3qxoI8YwC0LGdUJvEGDTGwG8C2m_jIV4U00Mywa8JdkVcEyNRkjf0kq1J1lR5OX-
1pYNWgL-X6v47W69wC_CcNu3DFKAOYDVhr-EMvvc_8k0nu2c6xQuudhz-KEp_9MUokyoi5y_18ljjVAp2GGb5dxbxXPmSVeOfnzk1GWQBFnzeGumJB_s8nLf
QhTstju8dGh9bpBVhkrQF6Rk2218zw07JOf7pJ8GsUcnq0Vk7zds0Ig_ikSmnJSy0hx3tpyhqhK-2din8H7sVjf7p_iPYKIWH8EMYOWNzKO4H8-dNGICwu2e
idaH0uYv89hwI-2qg_O1S-MTVaua-UiVPanIlqXGdy7A0wy2dGlVw-S3UyIUS4GW7W68p-0t
}

