sprite $Internet_cloud [96x61/16z] {
vPW7RXn130HPzVy_En470hizs9ln8gfiPQcQxBbSFmdm7y3xRc-yASzGh-0ItjAZobi9WCAqWm988t8Sm7qyslanWpWfn_9MTi2DYPEJavmvbmWWUZ0y4jrv
YqqzakmPGNQxGRROqBDlnwe2lkiUsQSDF8xF8LM0omXcTiaKyo_xNISmrMHr5TNqvrG8M5-ZP_eavsFj45900KYBiX_px8dOqoIGwa7Ci-U0UuBa0A8TWlnX
1T4GqEEdvX-u9fZF8Ec_iuSLl0JmAMXJtx1QW6gGgfFnynbuMG2rIi6eFrzWZXRI_F-x07FHFw__gXVKyGVxNZqF1w0DXmkG-W_-EFzPW65-KaE7_UVvvShH
zBZHFsVp9x_8bPFnqU1F2VLy1EIBJ_IJDs2l_Dlyv0LcXHNqluVZ3G_SOaav8DkZls684RdsN4zT_VI_673x5wV7WVpaaoMjZUQipqzQNCc1vCu1h9yz8_i8
LRVkqmcV1bGHx27W84BauwVkU5uHYAqDzdM02b3FTaIw7ce5OONUca1yCCNsYp18hGFiVzBwPmnqGAiGmFatr7Ui0bJ02Mev1w-XG7fvfrLZ3B-q1G3aqo5i
-08OeTw3O7yNm0Rg1_0R
}

