sprite $Interface_Sm [96x53/16z] {
xPTdSiOW34GpaYmat_--QUp7U1XSr-dP_tuFBMuyhUS__n7pdCFrG-3gEJyIBZVJ0L_aJeM3kMtWrzx7xrryHfGIiT2bteRFAEwb9h8vdCQ3FatkLG159w3m
Fht5XmRbyMMg0V-HAiZhU5lW1nEKu1gIXbyJ9DLGjEwt1ScqusOR0gQXkZQp3G7JaBpZ9piYoAltPfX1q1leXWBjRmdw0SIEv_qwirL1CxmFW3lYR6n3K238
na-2FnJmVDqIWC_qexfgS1Z0lxI_ki6VElx9LBxetWGaNtOdc0c-oRj0DmHnaU_r7qT4jqR0yltg-qr5P6iF_Ehx3GM5O08RTrJRKUBx8biJe1tc-sXR0hJ3
VD_JP63esg5-VmpuRWAk7GYM4_I2cD4EBHXjihF_Xn2C3Pxt_K33O6qJ9j21fmL88dDBsiUSlX3_zkSxHFpZw8Wj53Z3_x7yvmK
}

