sprite $Intranet__non_enclosing_ [96x61/16z] {
xPX5WiGm4CGY_V_HUnk63cXPju6emhPhcG1u3S1o12SpLvo-tEL-87uGmtOv0xP4e397bSH-Ofw0iWabivyIHlOgGTcD3dQ-E0Ja8AGvDoSqrOEcUj1K3rhg
hmEG03djFWasP-U4NfsTwWn9XkdkWwIxZxP-N6Zzr7v9yT__xz-1F_tvgjy_YvAX_Vj_AVtv-DlF7xepP3r_Q-UVvFFdC43pzKiOeENwKOdNl-twFUuVylwa
xt_w_cfUxfKLdudy14pwJpYal_NMEtHlAw2PcZy
}

