sprite $Key__permissions_Sm [96x71/16z] {
xPH9UlCu30KVI004uS_tlsvB5AXVZjeRWrubjSbS5JuD-4tyGImYNClN_BNAeE9x5DaXh8O6sFd24GeFHBW063CLh8E3kJwj7OadCc00787r-X3NPO5wrGTr
OU2cZureJO3kza7Sg6lcaHig15hn88IRItsfw1weiL3M7nQww3TaoKBniD98yDGFoeg5ohXRo9sn4VhW22853J-xo_nAJnZ87Y0sBkvEnrnwWU80MJ_1tGqx
BtuU1ohf6wX2zW01A7fbv7d11ORvXW0KPY7LrigUBmi6Ye01vpJIMcCG4v0gy7YMZa3_uMznminDH1e1TMzpdnR-4azWfi3nj08KNxGs_K80SQv0Ef0IhTR2
Fs02a2k8Ji8U_a2o1RhAx_vyeKxtpR-c4AwtVjjGGk9UqdV-i6SBf6_zmYiAz6P_imAm9GltWD8vZU1VeVTMFYsy1i9-5kJGzqH1xlRNGWzQ_QnGx_8cTi1x
eMSB7F990-WeT1E0ek3kdnViGW6EmcuT1TtrUy0jMsX2EA3OtdWKV2THgD8sUS65M2OAFZ7-h032u5PmxmoKzhy5GWhIOtbxBVHP86IXDfNtGY60AvAOlo-0
HGavg5-7B_QlK46YgaXIFRWL054rGHBnGTTu0EeiD43Dh299Yxt5VnGgs3QGfSV_sFqiZ4yxOFPuA1R1Vc05uBqWA9l_mLX4zw15WM2FZTK7E0iDsFHFmoBC
BuNZ-PN7y_d48gftPK8z2nkRtx0OlPo1deBbT0yK8Aod-0JVGUORwLlOk4U_1mb-5N_y1m
}

