sprite $Key__permissions [96x70/16z] {
xPM7ilCg30O_5KIPy_xFUurbnYRSzaTuwjdfARi1v80_u1TE7M6y0caQ2Dw2n0k4bnEoMwedJ01e-n94Br9I1g1x2xUzenYZn7lrcYu880-yelSbx0hGglU0
xWd8gkyG85iEUPLtBD5roeX1VsytC_OLQD3lHY6GF0BcWV0EpG-h3hspPOUwGG1M78XlpeLwKSD-8BKwLc0t10elG4z1QOryk-n1yXK90dG1mLepTDYUYAyl
Ui0CRgq9EcaA-Feuw5UW7W750TaJ0llxqGEc7iXq-nEfZr1G3p4plW9D07FKIu0o0CQtk8QkW07fwSy-LQ4XqX4ehUdy-tCUjrcWGDPX04G0t_vyO3x3eK9o
8NbizcUJS64uauZQvDzKIFP9pkw_q5Y15lliBoLOu5d-uI-TM44dUIU1Xdrm5lYxGdBrukzUoniAQVKFFQ0bNaYhtvMPy2maMWfV1THcPRoW-SPDav9IwTHQ
lotm8byBrR6l2fGMToR9Kw462sMcMsGK052gEmkCZXTgzO9rUUi42wR0G7nZHg7L5YY0KxukXBMWPw4vIo70Md1oBz2E0BGNMgjd8Qy5HXIjNUW5_YmG04MC
r1mlbBl0FXicY96RinR8Bn92ZDjOFWhaLorYqB3dgo2ZO81QAOeOElQxz8ey2WpqvvmHmvhHMCbKA83K0mIXwQozeBsGW5BhZs4FvFvHgESH7_uVmHwi3GgV
XGpOpy7c1Tm50RhVi8VKMis9TJnX7TteXzBOgBjGNR-L-hWFYB4TRWF1AzYzW7Se_f_w6jIAu4q8Vy8lVm4
}

