sprite $Laptop_client_Sm [96x107/16z] {
xTbNbkCW48LXKf4axt-xuqAtcrBZ812ypPsSlfzpc0VRKhFsVzewiqutZfvRM314wmfQhorePxbWLnMCSywgTGNjtDA2OVwfBYd09qUB2l1vAEZ91OFZhoeO
oPEVMe0lvsSNp1CHUbafk3a50re6mhH2zKEeV0Zp2XP-pYbuB4mic5__MH3yJy7Kmitp-sSXWfzNgBxI8USKGmt46BsvMQW-_oBnDGZ_Vi5GcN_wF8T2zLFo
-aR1ddsbAVyK8dmKBA6W1ttCb6iGVbCmtRuNFguXLbyMdDLAKu_F-jd7DKYUHrnuuY4bVTrddOGlh-7ivqHAKOonosVSDpwk8Ptyd9HYlS_tZI-leVNZ91_N
KFd9vw_N8Ft2vsu_LB-zXhpEhzUGgvzd-LWu-xdJ3pw4Zpu9F_MUdtdVu-VSvGVUTpylzNFr-STjkfyN-qdwsyhph_UtbNvUxc-3lhtkx_r-oZdQA_usu2EG
WxtaxmD-3B4Kp7GVEgyKz3T_x_BP1jyMMd_hzBM7ZfMN2Lv_y7VuLsTzb4kbG7Dy58BKaooq_jxZ6ra0NmjtVUkzjxAGn9XpmpvqVof05eLe1tqD_Lo8Bmlz
FlIsuCw5WWOh_VsxhosHnC-54m-smyTR_ak5B2VzX_vmTgmD40gQmFVwEFk7WX65_Cv_FAhVwXSB_hs_Lx_HUmeTvuT-iQ15eVKVhMySRw0GhlZ6iZvMCE6l
_u3Vw9q51yE63pxqcuNupjUMTwEWQg7n4PXMQ7qpes1_2gdu3-4xg-SM_lhkA9XP1NVsYJUrqFfSKBKm642XzMj1svi5CdzzxMOM2h5LltvwMkft2j1jEdJu
A7YCz601kex0fSzL-ldKdSR-Ar7HGzK3Ex9my8C5frdVVtM2VYu4p9LVNYzOrcd_vUdR-xY0YxvKSD3XxutU5cAyLe2kQ0FVwCqSwxmBXQg3txxfJBhpCuFt
1UXvF_WT-lS25JvzAHnwsh4C_LhXz7cxVLKmHT-WfmuTh_qmgjTG2vPr6xVjy9DjW8w2amMfWuzQ3Sq4l4AELXQimQiszeTr-SeC1LDroWU_XN7z_BgfG0Pw
0WzzIW4VEB1U-BmHzDk5X0B9TotGfnQyYlXS0FgqkL88YldfEWhm8yt7KGWA-fffgsRg__SF
}

