sprite $Laptop_client [96x109/16z] {
xTXd0giy3eLXv28til_jZi8X28SXmR7v-lbvo_FgbjHfsFuRtSjRx-rzkd7-ENDtmFqj2sJfrW8vTry1_fq5-DwFBwWFr4xx0WtsjM375kZ9OOm2hGLBGto_
1LYs5lom0lazFxvG--CBTE0vl1M6-AmBOLH1_PXJK5_6Pa11_PJpgn2mY89nNGNupEAZe7vyAvYVVVRY9qP1_I45yipB_N4o0GNbKUXwugEd3d_I0lmH1M9M
NvYOPJ7k_9IOgaA7huMzNnLiXu_PjQ2-5e1t-2YaB4jxFoTFsq_R3X_pMo5XEKjXmJact-DZv3CA6o-JkvTYju-VGU7TJsDyBTH-6kDZ9g2GR_7ruQ1--iKF
vpuU3hMVs_p07E2VB7RuHlWGFlkXzdFJ_OB_jVpSv9k_cf_lzykDVcxqwMOVzySMlnHkycE8BNx9JNuK_kadUzKlZNvS_9oZlSr784VptIy_-5e8vejVVlIr
G5_zkS6d44yA_VTZzX38J9_y6VTVdpiM_Ba_5_WjyyhBiYpv0VUJfRgG4431djn_rIV7pEvL82a0Hq0VSBK_NxoVB6DQOFMrSF1bV54_5lOy2gRsvmB_gevP
VJYil2wOojVxptNlcSyA9goyBbtseSi-5c8-xAeFlQ7Gv4E_Kh2ntOVUK6ZooJgdxdd1cwsGBlhGPPq5zK_qze9Bttte6cWjdFlGBVpMWZwrlliFhdGxh03_
eVSRwCs5unFVtg_kRohmnmBynmn_U26i_dO_sS458_vZLjyv54ndOL4mqNU-zzwy5rnNGSvNtyi65qIl_64512pywXbvUwZGxmNe51_ge-1OfWNRNb2TvyUy
-ZhotGLBbGvVPnWBhl7XWBrqsShFLd4j15dxmm4FBZylW-wdusp0MWgg5zKBzDD2R2YeZebkf_DvqPyBvbB1cUMih7g6VZhYYA50zhpmqjEy3VhL0dqkG8zb
BZEMe7-T2GWaFYz0Dx5iV3HjdtZJS_p__naiT2woLXspCM7-M81Ed4N7-GozhV3w4E7gmgRd8W7Ls-TJNfRiMb1z-Qdb-iBqcuuZzmKogeE7tZ6A-XdkDP_I
wkS-lVwS4aZ_uQ7xRXs5b36U9gg-71Wrcp5fBNo2Fd2kygETXizlFlJX8rvyrOUFn8V-jzX_-ny
}

