sprite $List__Library_Sm [96x134/16z] {
xPc9YkOm38Fhs1ZJzt_W3ViV0ifM44SxfpY7m6SXrNy2Stm2_IggXX9_JWadd0-bZg-TS48XuaCkvfzb6ZwK8ZwK8ZuKIZxsJS57qHe-b28-b0h-xdshsm4r
D7mehStF-ndPvbkUWWdW7ySW4xp9DtD5qU1FHIcA1d-maBBBfnDYaMyl_c0rUC__L909rkIxingwV3vXBN_mFOeKtV8_5SdshSMFAH9IsI8V0rWDI_c37toZ
M_vZPZnOqSlvF_XcmOfk-JUpGOjUoHzyFY4R_XydNcJ2UlxF4xRHtl8_HMiOY_dZXDLWBV_pY8MKY_dZADc4bdzwDqoDnVnnn6he-VTWTqEkvGy-cv1D__Js
wUN_EBCaozppF-uUtSdpv_mf_qSDjSN_pUtJo1_yczjdY_-RP_sc_9-7KLB_KrcA_0s7dWl-ZV0lptf5_ZYCqlZ7ORRovtoF5Fb7hhalVxlo7mDAvT_1P_bp
ljx_CZy4_C-N__75yxVV_3_zz__uIvU__tqkwdv_ZialJR_u1sTAyaV3P_dk_25xFAd7vdoWKPYmcuyEfbBm-uCrcAhOd3zahmcRyxdMi9iF-Nj2IFWeElRc
VwqXDty_qC24TZxtDQI8ZnfiS_xNVTFuHz4vH7pissX-FxpePlwyXkpcG_SjH7piculugC6R-VDzwtu_lEXcFhperF2nRzNDdnVTzS-BLl5HG_FxuViscldp
6cnpFb0y9wZukDz4V1JjpVpv_SRyzujMyR5lAZxkDv9_Vz-2-EyN7I8-zYr8FjrzErF4Hz4fukD-AmqV-wRYOz_yKCcoge3_nlhL7m
}

