sprite $List__Library [96x136/16z] {
xPg7gYHg28D_DI3w_kzxxxPm-Y-ia-sXd_8P4XoddJz1S2a-kok4xlkpqeJsloXbV2h5_2we-5IvaC-YHNmgPNmgnVokqF5Pj8xFebLyAcLy2W_bQugElYgt
HQChwZfXpJy6pGJoZ_cz1cpvPY4gcdoRGh8jtps76hPyluVKkUIF4mfRliUzXl8jFoA7ehVyc6fOymFt2LZonv0gjdnWcE1RFZ3KO4l-F67BZpFjsvO_tOQA
BTzi2CctVFEfw2NVnWVMBTzzg05RllkqqLl-698l-HxZHY_vCLoVpXr_lWs5BNyAgNp7doUah_ZpRMXi-TE4tF7dsv0BFWVuRGBM_d5kroSVmBzUdqVmRwzC
V94_-RTN9laO_yO9GhuxIijtpmVouns-H-hyy_fe-4-_pPBvv_LHvVzqVQJ-UQ8b-JzT7wb_0AdAdx_i3f5_yl4m__xTV5Vx_ytvhirVx_ytu4lp__tpYMvJ
yaytbFcVx9JwZsue-IUxNSctwe8eVoRK6GB_bEMN2G8-5PmWufyJrLqPWlmfT7T1vF-f1WZub7E2XCyQEY78dyANeY7mJsLpWeJFebF6vxufydzPj8dyF-sR
ZCyQGiRdllao_xa6aV-dVOECpts3Zi-Yb_dF-wRo_rIqZCzzInMVDHIM-S_x1f7_fnfqVDut7Pz5B_EVYqwH_wTzCn6VHHTCnMVHsES_tpSHd_iMCZxtJSVd
lidut3V8-2mQCZwBrl5Pj8xFedLytZSPdpNe-An1n6SDNnH7-fNyF3fP8EoC-gV_0G
}

