sprite $Mac_client [96x101/16z] {
xPW9GkCm34NhLPAv_tt7M4a-aMC4DBFpP--4znHPTbeUVrY-4sAEFv5UHdwM8POzyMVXVw8Xvbn-eY7aR0GbtCdF9K-676uTdPzdmEB-B4CgvQSQ5BamfEVv
Rt6rbDiDR_4zTniidwXEXlZSUA8xWzzpeo5kxBry5L0fDnZ0boOq-9KqeqtbEGF6drgF4F3t6VB6LuEs1tdAWF7XrjGXVERpP0XVvFULc0tSy-GzxCixPbNx
nAYUH-fPa3yz_j9u_wUyDV0USl3EUBP6k251cnYXKtj2-0oVMYju2GPcH8IEugDTQ7_yytberN32zt3DutdzYONEs_X4w-MpGKRAmECqJ2v_d6gT5UREgK70
D_YHul37XT8QNh669WT_nXFH-_SmhjFnlpAG6XHFh_tC-OplYMjy66T-syT_RNXDvyIZVE2PwteynsKO_pcwgVVsdBk3FPWSVdctXyedvKzupNMJSksnusdJ
_Njx9ZmTurKNoqiOpqL4-VsQDRw7mpMVp7ZQ1BGVV8FNpAlmUbdLqtEPf7nMlcq--AsrIT3fXF7nbZSu-AaFWNgyyI7bPrtUkVd0Jw0uhZBtPIF7-6GFtrx2
9Jyuouln0Hzuy5zU-3p-HExuH8pFeld0zyJJqYcVtUNLyLdZmHV3TyU7C3vUyr_i3M1ytENjrqG7hoc6xuqF3kVYDN_c--CJCJuEVi6NJ_2TxbX-sFYjhWqP
u_aXV9gsbxJt30Ny2JztX-tsTGqLu-yttmnAKZuCplYlyIW-sEsbuROmyC6FJlFJGF8rdtWOfAotLrhYKJmBsVxZauHS6Tfn-fVLsg9u4NCMn8DEV6a8sBvb
rNmKhtl96fWLVsM8u2yFpRONB-QeB44DIfyDUBYt0Bx5iyw1ldGgd-WmyCAGD_wu-WgFugMPyWCpEmRTllh--hBvA5wQBJ_oI7dC1jaCkhtQu5_WKRo-Ge-9
3qE2uVW24Vt5UhS6Z-8lt_vaPci00vIjhz7YjVY4L-npi31F1cNiEVZr_5yedjvUQ8z6q678oe1Xhwo0Z-9FznCDdrW_pXvzpqj36jM0HWgmxmqjls0XblUm
byR0YnPl5zk6cUrA2mp0wrplD1GFF9fl-162lRrRbygf_pg66YtUxeHmoMTAUw_qUcDe4tylVjveDW4zHpEDeU7cJV4ENhSl3A3F1js-f-8zlDrVLLXiXY6K
VVkYU0Tl3R8ARuR1JoZ-WtWCeb5WCaKDjVHIKBp1npKTUzm4koQR4yNY9JoyH5xWrP1GoUA8zWqquPdO62exdqS_OHXrnSCGfyUZxOsVS1XmG4OSFnO_5-yR
AhvOjfUEvzw4b_ZuVEhHMO9Wo2o-VXvkpXozVMfukWEFufyrfEdfwtNUJrA3xbyz00hmeDzX8FjqfCVpmV1ZV0JVPBlNeEEZzFYuCv7mTBcRZc_UwkalEETk
DYY_F7vQqlbJxNU-ymC
}

