sprite $Mac_client_Sm [96x101/16z] {
xPO7bkig44GvG2VD_lVx9JUu63TOZZ_N2I-CT6yBIcBIVox_9vTlmYlj-PgXr5hfIFuMlWieVmSFG_sq8LVa6uPAjNpJS05-xnaoURvbA4GhmuUMdvQ6yXd-
LmqZdOa71Nt4G6FuI31ySluzyY43wYcRoNL-EV890_YsRPifEzy5mcyRKF_Dew3F3FdLUlBMep8QLEYDLnfysSbatO2elc-WnjzDwWR3-7haLGFukaClUz4D
sWGj_CORtUgZAGM38b9xSdg9pwabIpSe1DY8Tj5pzTznDFmNNms8cIdLufLuOXjAgsVzBMq60_z8RXDvyZFrlBsurzN0TtmPleJvSNv2ei7nT8jduVfWFRUf
knimVgaZ_aX-YAy9cHdsN2xfUF2L7wcdBDTFEv-6lHtmU-XkFPaDzPoacFCpnX_mddo7Ju9wJkFpQtzQuC4tNjQV6VMS9ZjVV9g0x-sTJrYP6VMPfZgV-lA0
F-9j_WZaV4lhYFFBSVKQZqzauAC-qoYszouUtyWXx7mwtTxB4ouNlxqcUSO_gKz6VV8Ix_mV3JUpdDMdeZu5_2d-vuSYNqxgmwZFAVxd5bI43xwTRsyz-C3B
31yVe8e8cZNDXlf4l0BlsQPykhUzgC_zrV7aD8P4JkfJX_gSuYFVjxUi-JJmp_2HBywdDPzHpxfUV2JD-9lL5L-6Ugxmu4iAVB7jda5nU9skJdnD_OPx1aFz
p_0IooSI3ElwtyTZUAH8ZswNQ7s23po6htE-YiAmUhrMusFuR1I_RoBgzzd4KC3F2po65tDFC6XBDDIHFyTZU9j-o0gh1aEPlBuY4O_XsIoS8xdNI3tH87Xz
QV9YOVZf2IzqPb3dyp7WR7Kml4sEGLNjXZ8tA3uF4l0Otlz7K-JF3TODTk5VFk0HZ-7zVtBWUnY6iCBEBx_v_jzjU5t--fCx3iy01Woj5pVZz-5nPMoc8Wn3
myFWjm8_3e_BAF2hCX79ZQ62xoZdP-0n_83NDE5Va9cmIi7W2kSt6eOVy9PYI6i7hf-XprOR_xgF37peJhz24WGUIeDXt4jgE0m_LfNI9A9QauVGZdufuNR6
McFu4OzgXlfBwN-tFZB3i5sheRP7CNnuqMPy60Ir79_10STJ3c8wnUCXcu50dnZAmSVm3-7HJ5o_CXnW3Fy07Y6mruQq1yF7hJqnc4qLssOKfm6-RyrfwXn_
10QSGelNwjmGyJ1W-F3DUSb0APF1C3s_A3sJCXZQvugQO8hNd9vC5lFW4udFsuZ7y4yRSDX1SA1um6FuLmpn5w0QJaTERuItmL1Q2KUyvFHUl3c-2ktq1Lv1
VzyWrNwVZg2_cHtSeZYz_3pwi06d5wNFfkZMwuFJvUE6eqQWVpfP3pxe__Zyd__p1m
}

