sprite $Mainframe [96x92/16z] {
tTO9bjiW40JGXcPhvBd_TSChEJnH3iR4pbgpRxzwPB2G_pKXk5-eQse9lqhtCPtHNwV_gWONmF-I1kWjOqFq7-CL-cE3-vp-onfy67Xk2Eu35_vvmnkwXX3Y
ia5_NaSc1Mys-D33-6SMgzEj1hUd9_Th6wf5sMq8RiElrRlj1jtolUuqO7xL3R_1QF2BXdxzyHokEpuQrekrwuXk-2ysU75nPpjq7w2AYAC6qiFMOkq-iFQg
z42pll6yHtxJ4Mwuw3-u_-3RRkLtVjgWq2_fUi3_iFB1ztXgK16Dd1GLEg9FVU9J6XhKuUx6QRgkjpHyvjEb0NfuyDM9yjrXxW-vBZq77M5zSNTWd_cKKwGD
Tz7zuhcRVEQHd7CKQY1ztS1-6loiZku_JNSRHndocS_gSnYMqjvHXltq0pzdHSEfwyP1WtpcktzlW8x4rnhOPxxxfQ01_CiDVlJJa4n-Q_1x3Ue6d_YBN-v9
ub-um_4YWZ_Ox1zVHptzabzim4RMH3xftS_fTbJufIItRe3kYx7FF7pDHnA9jmg_PNdWmqh8nGQVUFRb-EwR6JMGxaGabc8pFvDVs6-9Ccd0mwgvaC_wtBTx
0ZT0nuN7UZRoYL_vBSeDq5qZxkDNybbdFyl9JnfKMa8wVIE_uvJopA-N1ZoipRcCV_7p90L-xlx8jnHSyLFtCMxw1Nwz7V7qhR1VYtX1N21-vPTSJh-KUXmt
-0Dlfr_pkHqY-qT-xfVlFXhOXmw_lKa8VVnyv-z-iExp-Dr7oA_iFupVV2G--h39D_9jzC6dw_Zm4VV8vuKFd7mQl_az-g2JRpRurSWVnXzyQcWsTFRBwDFy
F3xvI3XzX7qRvwz6VcI_yJVonSLIIcOV_E039v_uxbD30ig-5V9juOE7pt7vqJUa-y39fxqr-1IVoRVIVPgUV1h_g_iKBJsc2lFYWsMVnuTVH9ODvFVnoUVn
c_yr-9mmcx_BxDFup_r-nc2_siIdyTU-k6HcOV099nyyVF3iFyPbch_QpEUzjVOHV_4RXIpypiDVnfLN_0jF_ZgwutUU_7L3NVay_fV9oucWvZwFp_uwQUM3
9tydBZtp-_ZaRwLCVTvR-pxYRUBJuaIga_seJNmU__0xB3Ump-FVL7u-OU9t_XRblKJsh-FVahmTbycdKyE76hhVnozEFXLNo3yEy_B9UEj-uwkfV3gQkm_z
5-JkH_b5SRdvq7-HBrx-stm3
}

