sprite $Mainframe__host__mid_size__Sm [96x131/16z] {
x9NRbjqW34Dhi4pI___WKjQvA83IiDAyZURsnDuoYS_yUkKdFydXzYJzR_2CmHhzAODvS61Fq3b8Zz0v-J_H0GGUC31T6TnkqriUC13zL12mMtHM0CfmdquF
ugx1l0PQCGlI4jr10crOVrsJKrOLUOqk1A4tBlm4RYbx9hwU8HOMWkWrJWQQGLtJYg7nc-Bs39WRx6t8Vd68rQMskS1nCWEWxqZFCBqalxZKFa2jCv1YUH_o
T6NPG8zQpA0DJ6T-7bucLmfeHIB4beYFohVK6R9VdY5GG-Vpjk_CTwz_W6naM7mGnlIAtuV-g3ay2343o32bD_oi_ypGCWZOm4VCjsta0n_-T_l8u6gfUtek
Btp7f_xqxuXdK1-kcRit-iY77_f7AOL6a0k1zbeJlHJ2_oO-mFrV_3nP2CQFTAgl-F7jNuhRsUStto4Y15_tBpNTewQbPhgtCztrJFdHy5_-jc6w47Ri7fFw
_xwVrv4ol4nCTo1czHM_xx_rXfukwglxeVvqv6kW90TLkiQd_iSJDj9VU74z8v_gz_qRtm_qXjVNe_iNrN_VOL-wuwI-wj_nov5V3pM1Uukeh_aHUE6fl-IZ
PLfVyLikylzqMsShZCCm68NfQaaDVV-tdSKK4PcS_75c7zttoy4RvTLdl-Uddx_v-F63VkOFlh7FknklBVzOF-Qp_m0V-iNkWf-wxjVvkj-4d_dIVzR-wlk6
_v2xM_kVKpxSNV0xtFtKbQ_pgz_xhqE_QP_pD_glGt_XoM-37pj-ugfVvq_u_YTylRlLR-Wx-2B_n_ityy5liZy6N-U_RkctoVLHJy_OtxZVeL_iRkzdtuxx
TiPlDlXH_4Fv2_kMleElyvSTlrdw1Zxa2p_pHR_8L_tM_SBF-ijUl_B5xWhVij_Pr_diszWVWy_vsZThwJlvdA_xBVjznszoUQh_x7xc5p_81vvzQysotvNF
-TXlTiIN-TY_vGVud4--jMC-_EjHVkB53_0X_rVxoRzNles-x_gmk-YR6VO7-2A_-gtwRgxzoe_-UxVVqm_mJIvFzLlfF-ydlx3lbdwGh_FJxt3tKvU-wNpi
Tqy_mDVvrE_csXVv_GFKxoi_m9TFpnlwlVIZ3_dhmm_zxgl-cFQN_NvtM_c1ljpTRJzrvSl32RvF-F3qGB_F-xoxxz5t7_quuo_GVsa-ro_pg_-DRbFzCZ_z
d6-_kwruvND-zY-Nn7CRaXU-FfolNb_dylpm1_lvS4RgTIwF_ZFLBvR7hns3BqpxbLyiTPYxIv_pxP8Epys4J_ajTJ7NNH-U7j1Xf5-Nv_K47UVQ9lm7EpoN
HdxbG-fyNBKFbsdk2wEVl4_eU27GXyiq_uNgV_WvNL-8welZFZtLVyxh-aAaVrBN5wAxZzJ_W_aFvZ-Uhm
}

