sprite $Mainframe_Sm [96x92/16z] {
xTVROgCy40DWniSPxxx_y_wnApfGz3kGXRjg3rVf9mLCsooVvJT17jLBAUcn1ibb93wZfvmB4kxdO-vvgY5av946oHvlo7BVXS_FDKIOppG47yyRalpJfKdf
NK697-knywJXfgCKu3_Oa9vh4D9mvr5gzTc6rbfQUeGqy89urST5abCtEaf_itB9ZocSR4XT7pNN_4GQk2wP7wMvZo-UD41F5myhV02JevH2xxxwEC3FFTE6
heV3MOfomUSDqFs7cnTytMovugDX_pYuJczsbaj-oN5teuFG7sxGHvASzqlFsW0z7lZmuoZ5YP_XWn_9U1o6VZYiz2XTyN5LoPqcDvitSBzuQcQ7rNNQmFt4
-5VYuIq4eRyC-9lcFkThMe9u0pjAl87xZhkVgZyEaHmbsi3zifyFl_zFZjAq8HBVQV3kAxaFPnlW5yAxhsk3nBCD-Rol8_Nihp9uEcT-tVZQJ4T4vEH5Sftx
TU-_OiFNSgeXZbT5PRxhxkVIMXk-ea4c3JZEnOpxzU2dPQdmNydJ1kXPZVZWYPzNtymqyQFa5pvNvRxht3SremrRFTRE4n_wRByX6dyqT1sNflF49xfkV1lx
rxIsDYGaVklh_BRrAurotvhr4nLmM5sFOwMUyxLgzyrzdp_YlzcZAGyUVflwUDtOtqg0x_EH_OVpulEdFdJu0zlxtrb4nJ-Sx-V_ORxhzSlF_UNmVRxxhMa_
aryyVDlwKbz-9jVU_LwXjleDWOzVxtq-_3_TnobstyUFvDNNcS_cmqVIRZjq-9Y_-is8J-R3HqBnyHxVRwlVw7us7_wQk5xtIdnplp6Vp7VV6w0VVDFLRzHF
PBxxdkJwrhSH4V3K1qzzZoJYcy87Jtmol_iaad_wXapy37yt_-_28sNdctxxRUPN-E3XqqZT-dR2P_FXquHwoIVptUU9dRUDtyxus_dkyoIrZT-c_lxPOZu_
hDz-c_ja_jptxwpGvpwPJtoM27xka_d4fv7QJlXaFl5vWhxroNpkyqHzwolppoVPMn_yPHz9Cv_D_olBjRpnmRk_N8sK__FPVExF8vNxP7wLvPC49Nuvp5UY
ds_WliytffzFj8E_dMzn-TSaO_wOt_9oHzBEntpejqJoJn_wRP6ozLjhMPPx8_1hzmlqUwFmA_JR4_JbFwNZAdse_-O_
}

