sprite $Mainframe__host_mid_size_ [96x132/16z] {
xTI7SYqf30HGCXAs__ztjtXJLg4BQhXcywvSuSNJFPe1zu-P_yVd4luuFUJI9_oHEagursNY7w7_KGbHT91mgOE4MnrDkjNxb8mIhdKGS97Wkovp_mnOlqh0
kWpUKlRdUaef9no14x3UUHo04x0kywDd27jT-Ai4h4l4VOBeVT8guks44WmVHDmab30yGV_vdP-16aL9YCk0b9O1y3qCVcjUjgGZy9ik_GVr5rz-QoI0zu1F
clZUemJykQxr64S_vAWJKhIU0LwkeXDdxUUSljSKm98IUeJaHEV9xwCI-fmVkL4dDloY4r8ylpQYUoOJhNnvpXmb0NokbfxeuLU-79YNX0GEjLghpvMWdyiw
GVagGkkLa2zwgSKvd90bOD2hrCVzQodErmI-9RcO_A3h-WttzxLM-T_MvQfrgM_u9MkVYB9Aq07HVUkbpdu3_QluH4KIXWYjAzxofRxghnA603c5lTHKt-XV
LltxrA2VOT1p4L_N1_sLhnFSgAVSPwfl-i8_-w5XcAlJ4zB36_KdNwr_uNDmFenwIfglLTL7_IUVV_cnSNpq-EZQL_L1_rfClxNwwotB_QFM0tsr7kJtzdr0
_QK_yjqdwEFws2yx_wZ-nu_xfutVR5_-0_9DNljbwTSo-ppvUR-UD_epw6_Mj_eV-Q0-zkjH_xolVz4VN3t05ttoUVBt7wVbbmF_P3qt_L5zxDToxEFwQr_Q
4_HHVUoNbS_7ll1Blmg_yMT-xyTI1XxwqQYFVU6F_0BVxieVsckVZVtCzR5VPGZuqdzR_zFmQUllhvxEc_r9-RpnpVfc_wqFroFr3P_s_OtwsjVzVHprlO_h
zrdwyX_essUPAFvH_QLFjVxK5nxlXxJFQx_ktkwoFmcFVRWU2VYQ-nFms-IZiplxqdxqUTaVr0T-fGhyrYOVrl_wcleJx2--EkgW_ejFaw_vXG-t_vxVPX-l
vwG_Rttfe7ZSV-yRzLN_lQ_uoSTNpzUbZw-Ui_wCVLhveh_dDyC77_-jZy_kjO_hl-ctsSStvxrVXRVzUkWtip_WSNz6VjfUFS-GwVFeDyD7Lm_kpnj_U_NW
_hpnCxvwDZwBhtZT7ryzk3_l_8phGv-9jTyM_V7PnVrvxsTuzK2VMVd2Qn-i1_Td9kqt1ZxUZlZvyQMyyit-VEoxmDsNxeFVa8zvyVkau2BhSPxRM_xdnzgN
37hrkHc-h0VMB-vb8cc_0Lzu8-1JT2C1-Tkp-v4LgnB4Ry07Lu_eA07xi7wBGg64Sry5Y0ud4FJDguU3Evo0VEFg8U_U6OA-hc_eU48zzZyAr772x6iUwtXy
tVgjk9lnnVQxdczmIT2-r6VHBnDuvNEyOtN2w7UTj7uVeNmAxlUUmQ_U_G7Z-V4Bq2yJgBf_qFm_lm4
}

