sprite $Meeting [96x90/16z] {
xPdPTkGW30Kj2Hri_l-3fvT9vIWsDkgXPx-l3LMONAzP_hwOtsAo929QtBqC3QthCpvkyFLxx7hnwsTy0CsAMDG0FYS8K-hvKjQOajYSaIsgwvV89RwiCNNa
K4aPNZvP-j4TtuTtd-Z8iP8hlEmFESEl-VMNT-_Fp__x4i_tqp8xAlljEJV8xfonpD7U06PzWzgD9gd2rIz_Ahj7UdGpPKs3XV0mLAqh47uofbGzGulTVxRw
6EaAexT1_2fUQPkONenUH6z38hryTLXvZa0lgcoQIeSU5gkCz7rHoxfYq3r5ztIY8gB6EkH6F-BVuimrLH6Db0wVw0Bza8y1S4YSeLtw6PyxhfxHtHaIw0gz
oyUmdowKrTjcR19ohH0wVE8Q3KzeK_YjLMM4B9m5WtmCpDUj1VujpqrwqWlqApwfzdcAIcrjnszR2NDJV0pm8l-PAbo0CdnIxokqhVNuRUC2ckPpFW1xXQyV
pROUNrxYLqv2hdWJ-R7V62RnQwH7Gvu_GiVWUVu0FHho_3wzRyZpgq4VCAJuaPum3F0Jz618y0CzOHZY1thICC3tGCyQx98VwNd3SiBV3Fhh1l4EVolGvnZW
9-W90tofWJxBu0iHwBCC8T3d6w1FZxoH7jy1x4ru8c-YAwzMyeRDrre_Bdgtw7HwQvNBzao3y0GDdsl-nCi3_FwpGZxAzIpoUGgK7wQNhHtnULEJ6VJ8ds5G
Nhl2tIg-9_B6_78boLOuVUt0eAzLaZmWFKF1aAmaTEb_fikU3bIILBdukChfC5gQG5UGVGDLIbVIbfFui06wGQSq2GDbJLQo7pamw02TIgOCb3LH-Ao1iaPw
jv9v0sNj5puThKTLef93XSyR4eNF6AXIll2f_-Vb2fytoEAXabDI0dyo7GDyAZap3fzAJex3Xputua_-PjFH66xyCfFuFzy
}

