sprite $Modem_Sm [96x78/16z] {
xTRPUkCW38PX25h0S__tEodnxyXKVbJNPDReE7w_6D4b_U9vptioStwXJdeVVXLFkWwzH1VmhoWKkO-QATFreI1vtgMHRNHo0RfVu7nP9y7uXRaw2dEk4Z4B
lwnGk8-dNxwiqFt2zSkQ2VZS0dHYOhzmwR929mHE5hwY5yBm-G95F7GlSVqgMTq_98uN7Hnya8ZUeGG7Vwr0ntfn_7EBXfvTlLmkhAwqcwE7XQ5nf5Djy0V-
qZkiQxtTzRQCtzyjn8bFUjRsmLi_BiG_3fHmy9s7VrmWKmZNmDl1WxT-fZ8MqFXImUhWhP-8jiBvDK3F2dxqS__ykGBZ7R1MgJl-nzxl7oxdB-ksrZhmUx_p
toXi1p_oUvynGS7NR-hm1xw8-0KgZew3T_XZNzKj3BvPgylxldG_B41Ff3xl--33Wj5TtlTbvOD2mLh5vGzzOSlN-xY5RQtgyxulVTJoNW5w4Wtu9HjVX3l_
28XgrUeLdciT-JRmafBreVUXn1NJcYaa77p0GxV-_l-xOXz70H_MWAyv3Rxg-1-gF9x65AC7VCDY0v_9FhuMAE8NIiwmqMlLtFtXxn5zL0D-aUHFHk5nSwZx
zz7drUjlvVFm5TnXeQuNK_NXi-DxFDPwE5XTnS07x_dFU5zhECNmhKf--AKPV-IX4uomO1wNB6rfzuhnlMy_hZKkD4pt4yCVUL-F2qz-QTdu3k-iDIp0xqAZ
f_-9hxVqdQ5gZrS5_i07QuqAYvdkwuvlaguC7VZWeSyfm0UlMEkK0dpmMEkq0lo7JhDq5E1tNjBauGOV-ln2zsl3MkSN-j-lM_g7vZtl-Ga
}

