sprite $Modem [96x78/16z] {
xTZhTjmW30HW2qi8dFT_tnuSCbX7FcofjRtFlrxunYlH9l7sv-L_zlHEFMNLJE_IAUiPVeykYhoXWTLa3zPpLfiSsB3dCyQFMtJgkcyGYbXhHb0GjcXYqD4D
q7r3q5NQ1REPDkJqWtgBmsEkKcBfkUKVhe6WcuQWHHEts8R0HU_S8qZWeg6_Rj3rHIUsMH-Iq4nt2LmqOJJF6l943sYW-xMs13JizuFVUvuLOFJazO06N4wf
Pl38io6b3dAfrJvzHCF-nMcjyCCQSEUbwSUncP1lM2eG3BwSF7o4zWSDoOocyV0vsORr8M7mf1Nyy9dfKSCOV05lVK73-gAPe5zuwxEiDg20C7ZBVmmV7tDz
qHYyb6BvZu-B_rcHUNKDO_2UXt-vPaiDc2Yhv-tpD_uiK4tVkuOq1d_6yExvn__VcUODVl3kwPsVCmhGCFi_OyTPBNTFR_skwuXCrx0JHdFBUzz_FpbPD7IP
yl1lT2rQR0EIncZcF7olzuDtL-cYptdTu4D7Yfx7b6p3TV1plj26M5qeg-8O6kYYaxpWQzekKUltVu-rN-cCDPZHJFX3GD_x6xLp2Bjt15CUEkRZ_Et2suOa
BtYbLwyjkFcLENUy7Qy9W--vvt7bVCCufwdvv--Eys8cMJoFjKuRodaqzv7eEA_jyITFZxNE6d2i-mNdZLyS3tqQxkVAryMljHQfplSyrZeFIIcNIqFDRn_C
-9utQvs7j295QZrA-rtuLnv-bMqXIUl8uNpFo_fRlElDDxxbeQ-6Bq3buJiUQrqDTw2b9FYMDsjTRpX6kc_u8jkpIFK--2eHxvflVEWH8JM--QeMawJ6F_Mq
HIOL-8t7MkF2jVlGuni-VUZXIVwLnV_yppS
}

