sprite $Mtg__Wrkspc__site [96x94/16z] {
xTc9jYAh3iRnG4X2SB__yzvAYA9DsU1mp_m_esl1xwjjktg4hVuhVHuy3UjtOZWjrwy5PzLQzHiT3fxxslQhP4bhIXQt5dmx1kXpdy72rWIiFFnMA__T_Vzy
AHOVMh7eI_wwZtrTzTGNcYeH_bAUIjVoo_uya37FlUdlVmNvJJzQ3hphxm-ywqUuNdZ7n-CV6ed8TUaxVkUP-P3z1w766EMvTtoQ_UWhFdLV7dofK_A1Fnu_
V9OfVjjdldzyzqVllpynmC4J9W2Ky9yDO89TFnP2lzv3PNmwCF1DdmgBXN2KCSCHbMS3SIYzx9DVBCHiGrXGvjZuv8SeRVlalg5O_0K3f5AaJadoP-YVvRpl
rrhH-BXP2m2UVc_aJn-7v2K_zvjaDrKJf78oa03Ya9sYNLzKDKFsgUuJmDbtgF1mIDS-F_eSDvi0u3oG0N0SqfPVUtwx63SvdZyQpuztXzhsyxVMp9VRJGG0
qbzY04Wo3ickR_3XZ-z-53mMlYk1nRT33RVy2078ByPDrz9uUr8e-NP8u0NVhtE_s0WW8uBbV8aN_Liu3adQydqXGm_Poaw5t-ilidyPYVYe0EpuGyzcHAdh
mxzgyNtpUB7ocId4-_Uuwoa3S3JGF9x1hwnyFu7tXSwA01e192efrXzQ-V7kJ7fLyoao_sXQIB3XUtTwV5JDBr7tcHyNukxAnnHtXcvyE_5PU2pqmxpq2n6C
ICJz5dw25BxnLdxuJOqDdrdmgZDBFFu50U9fa_aSllyuvYMMgckVRZyS8G_UV2yc1g-galhfkktxfyK8yvs_P7T9sFydEn--DW1WUtoLt_ao-zTtXqEtAFc2
y_7L-LTKbxwOBrT_yA7xCuy5ZCSFtrwqBR-wprUVNIjioUF2ew_QwfQlxZiVEh8tBHJdtRV7lwnzllhEXquSpGiKljtQy-lDZyyAMQSBOB7xTkkovsltx_JL
GlVRvMV3hxL_R-DwAXGzMoZWvQfxliJtPfDkyVC5FlWjNu-AwrZ2NosW7w-NdnzT-gHAO67nNbZ8-aCtlvxuVYmD_TM5aTIJj6e6Bmz-Uu4HHgcUHg5Rqy1w
8SE8wjpGtrmei2m5_k92V8UnKvu6jXOc_RiBhkTAYtUdvBSM_5OIRIkVY71_8N8TMBMjVIllBSnwgsdflxY0O94QhtvjES3MpiBGdKVOANLVrWkXOzS9efq5
yNw_qFLSdMTufSnojv0U5sPTQuONoyxN-cG1q_jwX58jFLdeUfBE8xmP6dyK2uywSDS9FWYr9qwcEvtwD4FqsK9hiJ1qupd1vv4sAnRkz9hXEr7hoVYJwT2_
5SS20DJE8tmtllDL2RwVNFtGlruIyrKo_BzA0F2f_b__0m
}

