sprite $My_Sites [96x88/16z] {
xTU9TlGc3CLnMo0aQDx_UKi4Zk_HQ7pKf7jxss_BylkJsUVu6-p_5PRVOLpUyAo_rqA-gAhy7bFbDyUliF8o2dO6a_W749Nw72YvGCtv-K3U_pq2UJyVoFi-
a4ha_QXGvtYkpQtRd_Qv8H38-Hm4KZub_J00V3C-y2dfSut6pk-lFgNyA50OUEVZaZu_d1xzuNrA-XpupV6XJqcVlT-0V_8fwRFpGpxoAUcpyu5_zYdfi_T5
F3_z4WIIFgClWZpuKI3fywklo9iV1f8-Er-HttuSoFXOOBEH1x_ymEVjesuy-kK7FgFVWKU_vFqM1dZJoADVyduOu4X7lwJzC22Wntx9-c50K8_zalJ3W3Ww
yalg_jl2W3WtzClMZQ8d7mD-qjlRLqUcms8_3bmY-ELbYwTQwDcF0-Z70TFNutbzyEC0-d5WdluiKrzF5nJxpm7qVU0JBFlfI4ILGl-vWBulJ84MRtwNs7yE
UB_YyP7NtkkZ__RskLD-vt7Sl4o-ovCl_JVEVBxuwOznUb_Hrt3xm-8t_TFqpSU-W8yFHl7z5wy3BSVX-7wy-kBz5lXHe4wWDZ5zyQD5ldY_UP-301b0fb_y
AA4ltc_UPw-NSmlDzCtB4VlY_UPz3dGgT1oduQQFVaQ-pVlD-up-CNTUzp2zU2MGdI_URzvdxzFr-CbgOuIzR-khv08xoup-L-54xYo5Gd_T3Uq-FZ1mVNX-
N9Z1f-KGWFQlEGfySvnlWIjhFeDVwrtOAzSeyiq1tmAOjTgNpyntmO-2ssVeuuVP1ZutnWBgtWS7VRaVUOVo6lejAfps0N_xbyLxN-JANZv_-VjBTW4FNxGw
_-R1XySky7dxrvVimacNJgBT-xePvzyFBk2p-NW2sGNxlOg--3VZ_Ru_xdtt4yx2Mh533UVtpPWljmyV3dqucptwK5qtayWVUt87r3wSy_kOWMe_S-33v0xW
ny7dwIElnfk_Zuz-kEPdhlFXgjj-2_nq0Fq2FFhsWJ5-0JyVG5_sRdxwf_dT-Tb2vAltDUzByqFVy-PVnm_yR01zVUT_R9y3Fmm9LhQlm6z_Nxlcs_HR-_GL
UFJxG9--wPFZjw_B_p1_5qf--Bw5ZVU-yUX_VzIGH_yZuUSAcmT_yYa_NnZezwIVBuZtWVyz2-Qluyln-uuQ-ag_6um5yyVevVTqiM3dhySVDfh-UMJt_tu5
}

