sprite $Not_Secure_Sm [96x106/16z] {
xTY9SkiW38LXiGWmoVi_xoKcFfEgbIimkVi_srs_m-1EwmdP-j__N8Yjy2OyfbnwyGqwvrOv2k_GuM_RjdGXv6VWMswPdXBu5p-lkXhmy7jX1HzJUlKVlpdy
V5tt33vnyFtANUf-MN4tXn_e9TxzwfRnwIFbkn-MyCrdUTBouE5VvIF9UFTv3H_eKm7-6dwzh_7mwoK_27wrp-0LlrxoGzTpf67VHUGqtkrwIzslcX-OEHrf
nukv5ym-z1uMlXJSaqyqvhl8HrZWBnRuwNkR3prsNouu4Zrv9ZM_--73PEEL1V6WFOwlbnk_oQyQiQ0yQ3nTEekpFFtvGY2KS3sMu9iNSY_C-Ve2U_YbvKTy
3nYf3thNIvvuyqNwbvBmroyuuIzRKFoL2_E-SzO5HsN6Zu5C2uU_ZVenEDD2yoVUBjskU7r1-2roOSpdoESBqaySp3w0e2y8d_33mUHpPCk2ewtd2DypRFvH
IcSBy8bIpvjyZWnVB0W_xpnJuEu7Yyz8l7JBXQPnhRKuYimyxRTOMI1oh-you6r-Wgyk47ZePZyn-5P9wlSbRaNeTdyFVZbPW7x5RsMn87Js1jz31mzVB0Yz
53zmVlZounQdVN1Yz3iENlXVBtXELjy_U5RzdfV_9QLSocRpeKiUVgqUBs94FZO_MttNQV3Y-F0Tx_yYjI4UyJru_VWVVJ_fPwCVZkit-k0HUDNFGxxaZNwr
-rdmU-2xlm-C--3ruqk_Nx_H1ovutJ-ER_C1gyVlVbpZbzM-pal_CT3z1p_b5mJ-ityS_pRcItwzNvJZTpzUz2Ml-m_UxkkyzBdxn_77_A8TN_fy-FS1lqXU
zyEG7w1hFFpOVUxNVxFvlfiQ3v-wpq-_hl0twVEhVv_pXJxjewZmgj-l7xvrGUVn_WE_mXzQW0rUz-_mhGlWTP_7VHG5h_hz-k5FBTHJly8VNm0l_NqW7luT
_iH2tSxyRTB70dJLly6VANxZL_YpyNV-7VxL1VZxm7KVHTs_mL-n8FswoiU2z3jVQK7nyBtmcHOLuOUdVxlLG0kBmi-UrWTVuAlzD-PQzAVqlny
}

