sprite $Not_Secure [96x106/16z] {
xTU7TkKg38LX2IHXE6lU_tMlmUWKnP4X-FRvfoRn-hPBAlo5_Gx3tfzbHqvRA_uPEgUkvvmt-XFqbxztxpMm9EFdJBVfKKIKV_aPxz43owbVjdjkl3HU_VfF
zqjOvoEB-i8K4MhSVLhccQNx36_XrdnPvUd9HxDR-PBluiNUQMn-MUNLHx1jpSTRpfxXQrnguK_YVN-TN_THF7xTPuzVzuF3-pu-6pbzcFM9MJJoFY6tugGV
kNMv8AqaCEK7VYRYdI4rFQKmuwFQPk4hWZjUOnZtaTWa6gEzY-a87JzKFeCMYSXPCETsy0nUQUS9UjHxsTw3biEFu1RrxUhx2n4qFFWDOJWo0-w33bihmQH_
lO3lFa_xrmkCBpzE-57bWGUjVe29S7WXkFxwWk-lBwYVPtoAWmlDpwqfdmZF5zZsKv_YnOBruvpFnEGlg1_Ln-49LRm5wnEWI1ZrMOsh1LIVgo-CW_whu2rO
NuH7V2OUMb2_bBAxSaIN_WSlU_5qeVkb5G1PZgxzdlhEGe1Z807KlH_xAT7f0Y50e1W1K0_dAL_K_sQ10nozdlYyhp_Fyjb204GCvEYEBn--Bi370ZVRwFF-
TYHseVNIPHlpBQz-pkbieUkyRQl-NaAxW52ZUbGUzwLd-BqDJtyCgFoGRtdhbs8N0ikaBvw_zm4HJ_ZdlFKBG3ZUg7uQziNmINdhoxlV-35VBa_V-ZBig-oS
llgiFa_wbZ_tySDFpI_hVZdt3_xQTtdhI_Vb9txw4tsVLvzVVfhqa_A3VkSVbxxFd_kY_kFQLzqv_ILVPSkV-zBzDEahhnbUVLPV-Hb_C_oDli-hJqy_pVlR
d-flLxpwqdpbntnrbNTyhZxE-0QtlE__clUpurFt6z_yNpE-vJs_yVD-llHbqXUNN_S1nUEjpzLlHpRU-Ev2TlZkqyilweykv6NVNt3vviSftuR9y8vVZsYy
-dCBnV6v-m_rPq8nlFLfmTThAEk-l_2j7xkljr_zjGNruTr_BFYwiExx2zOFkq-Elx1WVBtzwgykg1_LVopxkh3k-udZvm0t94-_FO3TFsw_m5s9yNU-HBWp
gJw660y_8ToV-l-MVlS7
}

