sprite $PDA_Sm [96x172/16z] {
xTWDieCe40JWWJSC0yJxNtVZqqvDLX6Yih_f0tpTmHAhGdVccs--OKT3KugdWP5f6bfGfg45Cit9D2YkZFNZDDHtKzlt8OGVEXTT_LXV4EQSRF0hNnnLyXDU
-Ja_NuWQ1MWuDv-GUnlouNpdtBK6Ffp_myzuMXBED60-xxVFkTA0-Pag_iM6Wld7VWXeSEs6_la4daEZeJc_jNyEFdA-jq5MNgaImvzeS9ZlgRKVaKyQefdV
sWzVXAcpmKrht2T-iw7_NeOVsFgsuUUWmRVd4tZZjnlwxsNijtwZeN4lT_ks8UmrPCnl-Q76ntZGm1tpiR_gLnjQzpAou9gYyGrl6rom4NEnjSv7yZDnwoFY
jmsbQpvnu33xSrGgVbGqUF3Qd8_z0VupKIg-ceR--NP_H4F5DmrsVklx4CAoFv73AMrzNICE3TEQ64BmVJwHHyDcFfBMXlYQ_vjEdyX7D5JybCJUonAM-3xV
DkpxSmBXz3MyqkdRXesFWepvmQJjrnlU-LJiVCJt-8ZNF2Uj3Vlpou_XtT7-27_Ja7NhOxwG7T_sgmtwYkKBqKzDR_lsbFRdCv4pdnlVwzimViCQEv-9wAKx
qHE-QKYRuubcDAks_NQ3vNCcXAEUyX5EQyCpJne-hmSlyP9l6-py77zrbiLFfttRWFdvcNdnKx_3HuET3t_ch_b8CFEtlglwqkcJOluOtx_cR_rKzKNWTy_V
y_E-BoBO_-5y-B7XT-_FThxrzHQV3J_2ntmTusD-bZq_vQi-vlC0tywdF_dn7hzW_jRNoxxz7sE8xp3VZ_7ZQ_w-d_8btqsOl_7ZTT_-Zp74zvZlzdozx6E-
KCLFbtpCBrJrynK_O_wEBzTzP-QVtA_mZuw7QNU_NjtFkDW6-OBvntuvUpvn7Y-UwdxALtnLTeGCy96_nzUM7oNUuPVw_XYl-Ud8ZtCk-ldGbx7-dAzVnlaf
VtsRy3VuPRp_6EId_7VxNx-Cyr_pn_Ynryzki9_bj5yEVOsg-JTXm7vTalAS56xVhneF6je-vZVscmOUvQD1UPIF1wt-DbyKiJyXHz_lboFVgpORslwZwfDg
hK7S7Rvi-PJGS8Fljxvf2Dt-1BznG6dXKP32LJ-iS6J7MBzjgFkbuVj5T_IC4_1l3Tpm7_3h1oIqXDDxLeehldRumVeaUmNsbUPTVu9VEQ18Q_p6NnFzIP_U
VDhbqR3rIziFRxxk-8YuFV_HyFrCUbeJTtb4FlD1Qegqfig3_TmFixLUPzBoyvu_7VfkqII4C5SfFwFWh_iOZV3wd7E7NxfyPtcb9ThfF-1t_W2X9Vv6toKJ
MgFT_jJoAHgVpKsMHE8TFXi_uaSzUKz4tECh7IVjF87PcCDDNnqr4fCDhmyuuQHmHUl6V_BPKpFy_jf63hyeJkePfZcwyJDJJtnyyIQUeARr2EAx3xsxmV8O
JJnpI_oRBpJ7SMU3W4UIUw6q9hryH1wEEkFaLG05lZUlXVNvCKL2Fc-8y87uDv_pup7HPtblI4mkeSdibxbB7yymVPhmtl3sWK_cqI-t6o6d6n2DedaD4V6l
ptGgdF9H8bxVkUZk1diydiw7jUex8Z_xIiYj3JChiyzqCNwt8H1HBWNpRs_mHAwK4kcM-9ZVauY8Ytf2RcuG8bAcE-F4-A17DH0ofe7fFvfllldc3m
}

