sprite $PDA [96x177/16z] {
xThfWlic30HmWGK8l7d_rssYsCBi2aUBGwz_ffzw_MQClVI4t-UJJqAUoiVRBS_bfM0Apt6J-72Rwwzp_NYRwz_c-b5ywCKZ3dSxuGFeSHZk6Mr8Ex-UwSCD
NkOZQ65T6lolVThvt1iGcWe_Edy1w3OqySFphGrevfV-_0KHVRV1sVoyy_Jpi-4CDAZplJB_UeFCJ_0zEzysOFZDvueot_Nz1xaeFss6ZsdT-GYd_c13aFdG
zqN3RWE-cXzE_T66g5nicbyJqNKRNFylAsZqupts1fcVmRnVRT0_L_VYOjDvhK7_c5ATR_ObuMM3b_b-m4_ff06RUvb0Z_2wVzwWpjTzR7dnpnkoTZFe-ucY
jfyJlTwGkXURHFXI2aLbFuVq1krYw_jRWy8d8gs1b8jDzGFxMuFkQmqolmH_veUdZu4Rid8yMz9I6uxpE_Ut-CZ-0kxPG4drsmP0cKydr_Tp_kR3tf2JvhSD
GUxbizkRTV4V3L6UGV4vI_kNbHIaGFEnzQKXfuwVCot7Upb8d65_sw3xEHFUziJgey5N6XG_DozNuWs-qg3uCh-zCUn-RQ2p-L48_Q_EGVVr1l7ByM9p0KKt
-_s6ThxyeudeHbyQqhU6PZxjFwIY6_r-mt7-Mf0V0FRunUZt6uxpIybmY4-41b-9hmtD_EEVvIFHg5yRcldtHD5J6lTPe6T3msy7v4DYVjoNXdewrSSOh_hI
KETFy06IpCz7FxtBNsM-vcVTZsO_rldVVUhvCOHezUlfs_qGe_Zc-IKNenz3jEvtTRxPZnoRduJdL3zr_HY3sVToEgJxMVFj-sdt5th8hK-NVPcVGVPVzVNv
K_nbvmdwVe0sqUxdtVTJV9cVu8SVddw-uijyf_fqqSUTZp35btiPflXXvyCKN-QlqFEPBuE-tClOyUcIx-hDCCMN-Si4lva_nPVvVevFSh6T-Cnt_6JpVTVV
vw-Qds9A5Z_0WC-wnLyN6F0Pj-mdWBuVJ_oOBFiHNlcvjz_WPmSMlmpw2u3DNyTy-FVx-Kr-X3RfJJxpi_trd_8_Vfxlbzd--f_rqmkV9lhq-8Kk-W--jv-8
qhlyhny-lMt_glkSsVx7BpFzkC__uTFVvsSSzjDBd_YFnJc-51HQ9frFRS2H_TljSEvJLfx1kB-ikXzee47Pt_CzaQ5Xt8T4dGR_7X-9kWrsltHzHrg1D5Xz
vZKVakhl3UwoZoel3SbTz47ZbOPXFrOv1U6bG1ei_atn_OwZ0t19x6D3TCE-792yZsv3tsU-vuV61vUL0cbGVJhrNUj3L0gaOS27rFfUvHaBGpu--0mIdPU6
ld_JVSSVPJrUKdrfqFqlrPSJfuprl7HTIFojlpmaSkh-eZLakr_5j1MWmgkn-qlcHE-Sy_mmZmXlz6-Aht_pjFt6SjdNlvbbQxNxNozytyxV4Y_xwaUPOOkx
xglN6jQBnkxVD5z_nKckZeU1Y77Orn_07Gx8S_kv_xNv2Fr4xOJk17129Rl-ki1PiFAb9BUVZmDEOiuv0A_uyXTtKyFpeaJaqTkefVxlB5xp8rWIc6_Eu71K
UUlo-RkV_ME2hQ6qsOSbrfu9hS_FYAi366bmzLlT1TVuo8zq8p36jGsvlW0v0Mf_dultpyU1EQxvtfFuyXAnySFz1SjyOqCgDUJs3nGRVoia_lmzm7X3mDHy
JVduRlXso9fXRv2GTtK-yREmly10l3JeMVRvNmN6ukdLxUpPvwPtDmIv7LQRPM-Gj-lMzSvxk9H5RKXyhTzzkHdUsy2Zxpm9VwaXQsztMGl2cu9j0xiv0cT2
0pp2HpEbGOPFQd0mAo7BfVrVp2UV_0K
}

