sprite $Phone__telephony [96x77/16z] {
xPY7jkGe34IR80ay-__VkyXbqO3SptwXDywTd6xX4j0-y_WFy9lmNZqNUMT2AWqEtxLavN520TzAaEr0Jjen-Cjhhrkd1jzEXxuslsqY-NOqzwi9iMuBUMrd
0rzAeCsJXtRWp_IrX8YrBPJdtDM7gUVw-OGyMYNarS_I0fet70-pzK7a6_PGnZN7fblygUcb37r5UIQ4poo-PknIy-FAaKP1d17e290h_RXucYQXTHF7m8T_
apWlgpJk7waQsx9aEG7IsNDBUXWOyaN_WqwBdFrLYnu2C5QoVudbtprIiZmG0aacq9tUS17wziXqwpuWLLFMHq10JTWuy9QUKFV5wCgEuTOxzu7ACZLqWb7P
duM5RTLJWdBiJQdNzq4Dq2kQ12APteG2-Zr7Uq_NHsgN6Ia2uXtLrsX75dufEu9TTDKDGJ_1n43giRCY3md8I6ZXuhhPvqZ01UYokLUAcmrwiULxFu_LHwlU
9q2Vfm-nPm3RyNazMJnwoF0xk29_89bVzbQt4tzSFa5YLiWZwlB5Gf_DvFnrz8kzaEHJFVadXpxs7dvjhlmHMxzBA1ZzSbbLKJZehw1V_66KGv6DfVhrawEO
db03z8kV_4Tiz07Ytx127QiF6_JEZrZ_083oUVMOPM5caVsycFxQBtW00zKlsn92QNPcJ1PwS7VzuBHwWfwPCESRVjy_4Dm8VkDqVPtqVyp-ufUVHZssfTyu
J4oCoSxwnP_TyiDW9zm8VkEGVVQaHR_wKPvHmxHyGk94x7gT2Jdzu7Sde8IfVSQsz1k752pEwU6Ve0f8dpvzM3sPFcEoYzxvur9kJ8rUlNkNv7soZOJ9TZty
ODGfYnu1XAFcDmucE_LgzjKVuWpi23YPR2Xkij1xl-7SHjwhLP7VEDacwvVlv-i232fuCPisJivvcQpJKrUdMmabzNF8kQ61qUbdEyWvJMDm0RXyjafecqnF
Jk_iy1DT9l3kAfgY-iTh_Q_PZhSSb-02yb5JDhrulTcztoUaqmJLeyxgzB1xoE0u3Te504nsqeF9xloyWuGF0y9nKwrwipjYj-CLviE4z71wR_S9i2jbI701
q0lq1rTss7XuV-V7guI8oIxw3VOx2GNGi9KMVLpriDzAWFnL0gfVzB1_Eg59yZFXfTxPhuXY-fw005Glq7_D3eAe7PwQfa-tK9LlsP7mzDI8X839Aix-jGJt
_v44_VVjI9ZUXXOzx3-NGAE-mlu3iFcB-M7_ENZsm_wZqE27_QSX-65_2oJjcxV_vZT_0W
}

