sprite $Phone__telephony_Sm [96x78/16z] {
xPXf6jme34GH22IHtF-yymctAnZHq-liy_AhjrUui72Iz5VpF_zJwO_LgtuZWRZoJfFL-J21cdP7M_28wiS9RFr45qqL_JI11FOGa4L4rSw4pnOV0qWSwzti
tGJfAos1vdhjvhlpLaAs7Z1SG16dzvoe6Y9UI6YpjfrPlBGZjwr0n9C9MMSz4VnBEuIjGaybFQREtQXN1J_xgF5j-JK1xsa4q4CxwNLFQmViwbR5qTvbbf5r
LMsltPN6IVhL3zJJVoLeMFx3nLl5wyMF15m33trxQV5vkK-hdmfjIJ0XjAFqmdaWAL4vRbNekJKFK5qJf9k8jET7ojZlYUf7LrMdqT2tTXmBI3XU7M_GCoE5
iwPKfqotuAatwtE4l_8NRLpn7hBbf26k1qm7N9kZ8poBNH9KZkLBUQH7DolD_xY-OQ161AWfKI-FzUWc1ZJpy9CiI3YN7_nHNz5DmFMK9iY7Mw2dllLdkzxq
kUxHtYK-95ISHlvgwvVbY2_tzNMTzhEUUehAlSN3JynyfviSVceouBFa7y7VmZEgZ82eNwUVNTzSxxcbkpxwhL-fYTXvM7tjNNtUsgYUXpxwSr_Gb7Ymhnx8
gKVrhWz-xYjUq98GgoVrRXm-NZtjjmG_twq-swdFunNqZ_ti_OEZcvRYpZPFhWI5wn_sZtg0TyERdHtsEbxD-f-hFqdqB_gysTdgZEe5-hq_R-e7c-f9lHi7
rVzQ_S_eJxhERq50hDw5LWUUMphqWvsVfW0T-bAutAcUeP-gxx17FzqUVBZPoe7hqGsegFwoTT07F-LCrzUdlyKJmOM_gYTTzGwlUeTESZc1VjrPL6z1lrt_
Ghb5LEjTytPd6KCrwqV0ZvfMOiADTarWsrGF_TwkTPTGbWJiBCVg-yuEL9L_Bu6H8DqQEpIQ2kMuFQ9EsIIK9K6xLUXvqRjVA6tzJoRSzELeQjKlzk1NoJ6X
p0dAJbx_ZXtiqVyu0US5hV_oY_Re1yVtGW3q1KCrwnNs7Lb2mhrB6DV7YnxZyNR2HI-p7lO7q2MXhGbbCDvLiqclvON_Gve88ttJbuiUzcya7DMRlMu7LBS9
qDT9Rx2_dy186DKBz7XaVYdX62heOVyy0ILxzGRxXym9WkejsB-JK7tr3kpVW0N-S_bMqpSfSlLNIb-c2FomVp_1_R1_dImr_R5G-Wlud__v3G
}

