sprite $Printer [96x67/16z] {
xTNRaeGw28LXI0Y4pFk_x-xMLQ8JwNFlyt_VtveIow5_PF_7Aj_Kcrtwse8O-if2jLsLFbnHo5zPuAQgzgK5w1Zu_8Aeee8tA2hqRhMrfarLJKXScVMJ2wMj
gGfL7wFtHiKEATEhiO3NgpekzKj2zJCB5nqnwnZmbmMnGurVUV3mjL8RgAzPVNUXoAL55n8VuICht7ujFFNWKHEgVKGzKdvr8VJ6R6EVzrrj-ce8FL3T-C9w
mCtyxONGAudlR2bqINuj2DLddb7PU9mLDjDMjSE24JsiSxsswZYhA-nTRCCz_dvLqtX7I-TKHuApTgtf5zM7u_alcQuwctlYruqlfDuRxApcVj6ReattSUgN
6ZuHqoFn-caww3u6vpmg3tv0uEzq7_2pfu_u4Hr11t_cbsJXOLqx-7DVHFYPXIBujWhqu3CV2rJoXT2lRRhqu7E_NQgFBB2Wq0_ypy-9tv3CXxYba_I9l-Mh
wdo8ijFhfCzyxkjIcnToVUPpNzVCT3f4MGOFkftnYR_mi6r9Oc6VI8MUy9clrxhxSBDR2z0JFlLNlHTY7Tvj_RtY49EUyOZE_3wiR1zUj_N7Lc8XzDkyqDnL
PzeITyUlUyK2TBt3AysnGezgzos9NRt3TyxqgMB30NXRDpNdSzrScKvZ6viWH7h6Z-2zFAmZxiD1A17qX1_rMPrqm0W_uuVGd7cZlEOE0txAGt_A5myUViP3
FwcO2vrLkiz-mXlTgBfB-ju02R_FV6UwdRWn7MhGWOG_yrxeVWqBsruBVkzFl5TwA5PlyRngN7VCVl39wT937-yju2SVVAxdXpw-hpBxmJ-dmrCcD2t0zvLN
-b3YUn-yCNqkyV0NlHVwREBmux_PnnVWTw7l9Av4qByJqp-g__i3
}

