sprite $Printer_Sm [96x69/16z] {
xTK5ZkH038LXSy7U_xxRSLSxK74qa0Zd5opEznI6a_xw2-bHNKknvnQaU0yjiEDFBP2LRORtwchbaDwtW6fBJos8HNh_0bj4Y7Zp0gkQcYSWlHdTkK3gkOxS
Uc-r5aAvPm5byAgAL7jt_tJXvxh7QBs7_rwmtotmoWk8u-wF2X-FGU0RaNYk-ua_-Bu0OZzRSDrJyHC_-LuHu1yieAoHd_XvuESBo18nw4OsGG1frmiAr_66
HsvXCyA8wluW1EJBJmBnah3hL3ysx4DR5mp9RADJfMlT-vpugWGdnMagD5wjeRUM-SYRGCDEujfT7oczzSn7sl6Ksn62R7KiRQdJnRc9y6illqbllL-VdmY_
-l9ptThW4rzmMg2lwFhMwyh_e-IHfUagv0ki8mO0gLi-zVNB2ooorVTyxh_YBooGUA7l-Cnt_IiBA2C602uJd_ZwoKpWLRA0lD79zID_xTkIOh8mwS7tu2zz
yqevNI3cjuu0P0b_wLjflTTYfHGZNpZsrj5AokU-wrPxR_xJvMnXw1cV-qFtTwn_1JyBEEkNV86Jq1PK4RnOQ9N7GkXIBlcAfxo-G85HBBGbyOMt3cANV4lr
olFdexTNOnZV-YNV2KwYyj89vlpZtlgIWklNl2HVkMu8vqcF02pbSrrQx-fwiXqXNF86PzNU1R9ewE7dVCNq-4loJrZ6oGy_uLtFGZq_-sYBxa3u2Ty8aa9I
EAIkp_xCn_dDe-DL4DU33t_c9prTQ19wSppuy6VUuAjnwvN6Rve05WSE_e4l24dPhKJhWM2T_3rV4pqDTNz2iSv-y9NW-w5fye25tzunt1FLZH-ym7rH2t_I
Rrr0SDtW_gXz_8BmIDGMln8y5WE4_dn__VKV
}

