sprite $Router [96x74/16z] {
xPZR5gis34Hd9Fb2p___Rq6BHCJBW5BIjxFVWicMFDoDE_wYbe5u8vP3uLXD83WWDOMb_ONun7xgDs14VkXNpB0V-OjWZfIalrpWqPz0AvTa_8OhvAbVSGtj
aLyGa9WX3_p6ZnFIY0cMyrzFWENaJELzFbekCBgblk0N1rWJVcz2psuLMfxwvPLD88cJ9-atJYzJHZOPlvrGT3_wTSJhsXrtVdb7C7qUK9_vUOnW-aZWn7df
5_riVYKAZDZaKKbGJ_t7LACxjoT38bPaue-V_WUDtIwdKAAZy04oymjsHAElsodeg7EeHxz37A4vcGhST2k28w8h1p_6qNm1FspHNpZ2B-FGHhw2O0RbvPyC
vGiun3cSRU2NKp3aCUCh91j8J27ZD_qw944QjyXN8Ha1flt58G3c2WZ0faXIDhofN4X6G9SbxO_MziDmNK00jEKRVusftuPa1AIl-d--y0VDAvnFGG0Kr-Vz
TKTfRSLEG_BcsLt_N_m0Q-kzwnwI3NZpgzxzVz9-3J-u-NlZh09z-AN_Kv255lxUlK9bXFJH_Eft_SHFdC9QMzlzbNNJM4mXcj_rKxye724cQ6jLu7x0DasN
g22-nr4_-dbyViqgiBHUwNw0dd9_XKGVRlqT_ih2KHz-bL6-AMGLLFS3VN6Jrn9iOuE-3DaS_8wCmmBGUWz_sOBOxmB5zP7EfFdmcxDNY2sUGlKZwtxGAtI0
RT0NTs97vkzNBbpXnmPTBPNk1zXN7SVk5yATol2D_X3A-0fTjrF7_K1x-oFy5Yqfvk-VWSQl2CbD7_veVv6FbYJtVZxiPPk9uGzzuqIGzqT8QwVbxN_f5mLe
ziGVntcjOE5VLgBvIt-vnGZ0pyxTx_fo_GcPzoiSjeFVcvToHTOlUA7BxlVcOUKNVY9WTRyt3z0o_inE0JjH2dRawVgLu1hQ8x_W5ljV-uS-owSehk2p_1rv
kdvOhpcVWlve_Rbmdarzw0yqiSBzn5zjkaB_t1_8y7wNzglba8FUCYZk-Ck_
}

