sprite $Security__gen___Sm [96x123/16z] {
xTa7Tgqs58NXVPhQylp76n0741QoJRchvVtfxTkWwuJmZ6F_-XU9AjEdS5QR2y7u0xgO5qA8GGclnjhm8KuPlScRvtwDyLfwyADd7xpyDs-1t9ur4jlzbEp5
q-5rJeBpK_RQvGlsUFEplUKpsdJritt41uM5zu4tVK_Tp_OP7-f-rkT-2BqFonuzyaEDCHwm3_a-K0fzo8SjVdpeZ_zRaoP-YX_uiIOmEr5ayTCB_lcZCPQQ
tCILTl_qSw35Dzn9r7PVGpXRiEh7M_eKOV4LQdQou3UGRnoD7dqnsnO4UwM6g_7gcvzFzIrq2xdwTDCNGA89WQpMByJgysLVV83ykCnE5znNN1_O5kgMMR-W
cs-u78alUASBVC_tU3pW2zBvhoqyyra8jPyFIP1k-ggCtnS4-RQlvWiqNk3DLxheLuO62xrlmUYg__i2eMp-55_mROq6NqgTFuS_9hOLRFn14xtWXw2Z1VBp
bsT-Z7B-CGXivZF8xAOVgZzQ02G60TJVZc_wDJvP46fVa1ct_BYsVIcr2oowlUHSzqFhftr1srn_wgUfSFwbf8IBViyVtxb8fDCjNVH3vxUlBEHXYMEwu7Uy
-pL15uKOKxxZztmkcRzTlzbbFpX_vfSY8FE_AfKFCOrz8lhkXvzzRNqQ-gxLXB76OSoF_JpmYNYPKFes4CU-eviVtHz5TKAsWPxV_DBxeVhbX6MPu_MSbFQ1
U7BvOp-T-2Iwj9m-sPIG3npvt_tS-RJfSmf0cqFYyV6uRxiVJtpgdzUGPa1xllNLRs3aqn5tc9idXVtLz-C_-hBopO1YkUzbW0RydtpgU3yZskz0BlZvcy_E
Vuy0_ysKxNpl-y3inzuNl_8khWEwdL3gBl_SBqT_mLM8fBi3sKv83_pOJvqljb-bsg7cXAYx_B_wx9UQsCVMGX3GjctEd_frG41-_9qlO7zxrPsV8iXw0-py
cQ_V_2yqKVNLV_Y3MZui9-Ilq1tllko-7u_xtgo1rjTxNdIFwmtuTTpqrVp_i3EjSs7D_FPyOUCxtzpFlI_h0PKyGsoXQVjte5qeHzy_WCt_Qdq_SY2KgKWW
bnKMOsI8AM6BhFUbzKldhr_aqNyCodsfle448A5cOUodKrzy82o-jNxSJh1P24C_d_baFg2vs7e-KHUVVN-muBwQZNseNt3DgXvNFp062-v3H0x-L-Vx9PiG
oAhkVis62qUVPx-utz-0v_hc_t8FV_EfjOz-lw3DGdH_7c1G7lXWjqV-UA7plyvyg3D3FwKefwS4cWVSBoFViQ6VvYAVBt3lzzdGDud96zs3_Ex3Hhu0sqAk
2zmjaFpgKpZuGRQZCVA5F3TQ893pxdTPx4krK1To_d5Xyms3z4JtZ01DsKjwVWznyWF6SUZqOF720Xj-JhvTUco-ZLaNybQtyBTamPqdp9bVjr7x5Bw_iEfA
yFg5CdLtWJGwlcVvi52MidKBTwDjmP_2_GBXMOU5qYqG7XSctKaAnmKYG0KFYtadAHuNuAziJwBSajmiwFBqniEuj6IxGD0Gu-C1SzpojuK8n9You66pbwGE
-K9Q1WIIKiw4X-N8pRSTawmB6OWvbuYNqXdr1PaNRFdu3I-LIhimqOGuFsC8xoHbAzQ529huh_pk3UHbWG4Hc3-1NubB2ahWiYq0qmqal9mLNo20lWolbuiN
0SBxSV6owvyveIJuLCa_tqz5HlW_zQ__
}

