sprite $Secure [96x148/16z] {
xTZROgCy40DWRC-CRThtVzu_XAePi8q89LV_wcvFdyGfIpFzp_Cl8Od4y2ayYZvYPYhnG_XQi4J2dRf01syvQxgBZo8gZV-8X7l6Unx-6lcxBql0eo0Z6kux
zz2zNtAwVxxtIx7mfskhoDe47lwITDr_NLj1OUjVFmIi1uyApo_9rmg2ofP7eZgV5l3vqgdsVAcaWFYzAnWj_-gbiWBkjv5NGQK5t6yJrFart-WZCOE_KW3U
uBS96Vw5WXLNWpygg1SBLjpWznCM7h6t_1LtFY-8btoPpXQKF-td1RFSljyNp7EzsKS1_5blzP48VgxXBH_l2P6KPFYpdVSVjC4dXn70ptCuwpzj-EozK7_z
VCQMrYSDTKOYrPDgwvE6D2FAtqgwFgBzXWpVw1kdw6AeyuCPQmZm2zENU5-dAQZH1Xn09U-3VL_HW3GDYWCWF7pvuOkjVjCGT_yQVZpd9xmW6FupKzE3XWXV
Hdvw-V7t3SGamEyqfCu5rXF-4mrh3zubM0Dy8puA4F28xIAxHxYSyYKsFvwIXaflq2ZRXX3mEqegXFhOsesAoaPl2gYFXYJ3Yds8JnfOXQdfUtwAk0vTVNGP
uC_CTpTD_nYqQS0nAFM1HdQMseBL3zJ7atNOeAAT2Zdj-mPs24ZhM-pwMCWRTXqFFtg_-zgQt3p1hKGBuAUjZuRk_gQ1LJmeQNmpwVdD3tQ9FmwnzTi6wFXt
Pf7SIk9ytVc8zzilVD0Wep1Vjxvw_famRC3DTjx7N_T-9WsYilNBuVxUrs4QsAsKtETdUamPxd_DD-nVeknc3Ry7a1T9LNk-zlQlaV7DYe_5a6jPNppSF2Ml
2Hafqjoix7rZzn1Z_i0l9HrTwDZvsj6QMiHQVqayRW2EG6zzjSPV4yv_AaN0y0zv99C6bOqUkxxfqA_L9duCk5Ibz7tmFRzM7Tsio8zkfU-RzdpmhY6aWtjL
S-dwTZWVmSQHBhRygzhRRzptNrS57rmRCykbvvlZZ_tnjoL1jUU3P_FXpqq3eAx_nFtPP_wI_Gd2JbjF_zO7_fuVtTzMFt_l0nxpPSF3rzTVbmE_NS_dm_Vx
TUYFvtFViD_vTUH3x_jyl-7opdMmd_FELxyVVkdwq2_wUiBF0xuU-yRtOpoRp_VZz3T-7lET-V3LxyVylh-FvxclXtxEu_dSDxRVwPpdvwUsVhxa2mfMtyrd
lkS_u1SsV-iRyHdV-dp__F9jm7DVDlljzNJDNsEVyzxNhL-elz5F-dRUBsJ-7_UNm_biVyRJzTNwqFby-45Ga3V-tFY4fxxPZr_6VcbIosa_4xzmtVDy_xVt
IpUL-si1zhlJJ_rAUEzZF-OJ7mMt-PcS7F1t-Vpim4V1whkdwtlaGx_Y-_dVNsEVy6_xGjPVzn5rFk4RNxoFqmyV2TeT3vxuwlpP-xx16fxwQUkNle-4N2hX
h_feA8G_wN_3RnBBcpuA5Xyy_6uIuxsVkDz66C_z9TCuIlZBFX8o-4C_lYx0qyVJHNtSIZFpqywVkO_4udZg9-wt3VLJFYBrsCS5sFZVpgSHuYVdOxxtUVHJ
FXBontmqb96F2y1ytd3A1qzzVhF2JywVB_b8gc_uSvZUZxH-xFfVSReM7VW2_ydBT3d1zduI-3_pZH2i8VVy29_hlA4C_HBE4VncXH-T3_s6f9UVuCVfteI0
XjN_t-LV_WC
}

