sprite $Secure_Sm [96x148/16z] {
xTW9agCw40HGbMgHe6FkVzsFnP1X8LCKDFttZ7Msbsd14BJJFpp_v_ymqy_XMTIMw8-KP5PLG_XHd5vuvvSYzEJ13FwIfpu4guv-Y-K7U57Cx_mM-JQVmNVp
4VhsVF2TZyW3X-_vzJiVWLGHMf85FFnQvO7JKNmY7Vogtp-T_hSx_dx1daU8uJi5OT_umvM1ZuAR_i7pZD_vEkbDttbUohj_f-3iUKm6VeayvoCA7mLF-YYO
KF2mdnJy4dhUJ_RcbmTznC1FCp_e8pR1hp_Xes2UPtdIHmhywOOVU5MeAxz4h_cbPV69aXE6FrFSNsJuPah-2SrhobtVRSZmvnp3QV3T1fktM4HdpOFVeWVp
2FjhvArAzxuQyhb1Ddywqqbq2R_vilXg9mrrAo2VboKxNr_-MOE6BZ1BI_FjpHSzQ-3DP_Tia3VVDhzhs3bvypNgCwxlmOkkfBVGvblCfvJ85boP-ZTHEsZO
_7Bcem2F7V1UmuGRrFUHlFi1ps-0FwTeWMIYB40F6vGwdvANBFjeeC7n7scGY8zGjC7ndscuw1FTR63S_xulJ9UlmoLVXDEDXfmewejoGjWlG7gV7ByP7BuC
yFERpvQFRtrjoTSQ5hFppTZP7shmVJJiVLN4kvLSFpU_c020qtqXeodQa99q_fOy-8XPty1EGzIdRdwB-0tmDRHV4KFScnK-pdzA5_rIpXjomWlM-ZRZ-kFt
LVdaGWi-G4c904JyieRyXWKYgqKeuMN6ystmYxaDGcy8GcdmmSD7pBsLk64a1xhd8-fSQ55Xu7Y-3Bx7breb-5JY4OTlHtvzXGCDGkdODsT-YtkpzZeFlfdl
jv3JyAPhbRrlfkV-D1KwkfLosYAb3dwGNsB9JxPIHn-mxxUeevDQ2VZ5ywTPZdXHk-xNmLz_cAESUOcqR5zSV_RvqlnNVjyKjlrvkwLMlvxjB_Tz--opD__O
Nmks_nbPSJoJjxzSz4lRx_eyyWZuP_QNmFo3_JX-Pty9-zXRi1_p1p_AZxvXl-Ddy87vWr-s_URlBmv_vcD_FV2XE_DzdzKE_L8Stl4R2H_74_KF-TulD_tw
r_goymt7Fpj-X8VV2k1ZViYlF-mx_DulD_nwtSVnExx33_vQ01_p0tvrv_U-ZRuU-0xl-YMut-U3--Vvo_Tho2VP2h2_Rhvwli_3p_1jzN4ylb-3FjtogyD7
_Q_1TtZNbyx7yH_vSFtvyF41u4-ENnq-u8lZ0tVv-_jhTTR33-nl_E0Jz10F7mNDh_1_RJwIYyEV-xOUGfsmVmYN80-VUr_WOtyVzlYu_mN_k64A-YY0t-R3
7w8-x_iuVlXZoA23F_9vy9tz21MNl-yZkLxm1JwEt_5neS57VEryxFV2u0_zpDpxKsG_8k0VzX6Rh_jVy0EX4l1RmMz_XXyCLSVFlO_ZWHz9dXoV7JySdkB-
5_mh4TSN-BFZ-x6m_-iLIvTJHdyh67rDrqCbxbEw4wgVVO6_7h-akycJuplFvdYuyt50y4lwRiJnAwK7OdjVNhvE4wU7KZxu0lsHD1y7b91_Z9-e9RUav_D_
_iyV
}

