sprite $Server_farm [96x96/16z] {
vTdfWgog3WLW2263x__0ronY5RhLrjlzx-ICU_eM1Ob5TvN_IDN6egfcgYBSwb_QJMpvfqpQdwoRTRaiu_hBbK-uknlAtPTFwIzU1M_E2gjyIt4Gdr_at-bk
SYmTPVx_9v0VyMF07E7jdLvr_36LYz9ZWjONVFDx7G77XFQO5-XoN_fFWZpJAuP9kxm8KCCur2UyvtbLVXM0FqO_yeI5T48KlmZGHm7WDMgCFhy8m1wrd_dj
JygQqEHj0Fsqzy8zpbQvb0h_NO3JFSzhzTvvjOtWlmseLtxyQcySLGkf-V2vbiel0knch8GQSrj1COCVUXJrvm5ooZTCI6kXTpo0Lvz29wv8UDocxSptE1iA
a2LuS_G2mhHdmiE0UhuxhKPBTXc-jJ5Z-fs7_l1HeQUThptsedTS51HwzYe2C6uF0zf9xxXwgymhc5ffw5KaH4TT-tBS8J_m7CitPonO1V74g9m6Kh_nvVW2
-D_3_VeurjOQPur-tVn-cdBx0h3yz0L-9MgP41sbjlcTolbZwUO5OFSPFawt5FeaqAefnY5ywEKyuVe548Qkzl05FlU6X8gkpt50RAciV9vmsKAAjzjMB7o5
Bog4QEwIo_S27S1vmlm2vXc8tMTPYTbNY_zop-LRtqYz7eVT2wZpwOuEv8hPJTy9xGGVEdt7JGZ-PK2Gq_OeQw-nFy0-Fi3jyLFvCswhNkNCbsc3RDeUvjYF
vSGNqJxcuJjkhPH-DGxJ1aqFvihXBKowzx7yqCSqe1hcOHg7oYS1tmxgqQoibhx1ZzC8N-0ZO2HW7lRZS4ZuR91yjpzydtoy_yBNy1jb0iKyVCQX3feE2Ti6
sUVPmuKjVHk-QfzybbunRd26Rzzn60bz2fWEeEBIClk--iJc2z7KhbBp_K3XCtHOMuBi0hO980JruE5ZPwMLAk7hD0vrUtSOUcdzCmwzxdmPVilfygzlwQks
2lzi7A3JTnnMdMJpcKU0vuJruNlwaHE-ON_qnEVZECImcGwVQvxrfu441ot13tyPlW_VZkFMjsu5ZuPbC_ZGjtw5d-qv-JxxRVFvEsvzUlUPni5AWKwI_MhX
dlWBV4lVSjmAmnVu3Gav3dExbjg_tNJmbwE_m1_j6lq4NyFlmaZOhaV1qx5VE_PzywiCtnt7hUQRx_1LPVRHGzius7PP-lOhrzd7BvF2NvpBrxVq2uddECZm
JGlbE0ozVVjrrHlF-uDpAcHCnYLAFVriLw52mxVLHtjxQMFvkyiIvsN9ElpiJsPkU5YXlnhy9Vri9-6TRyCN6HlLrjfVbbZXZ_dQdklGcO_-F6wpZ-NprA_J
POar-v_XenhqoMVpuxZ1xpk_jYrXrLlsQyFp8PzlF5NwI_hBvBVqLr9MduCFF_jrkooXwHgUR_byxbU-7ySjrq-5qpVugfoNfUqonfyRoah8qI-C_S6_0mn-
ybL5Lr_Intae-cbRFlpfUZ9LdhJ0Toc7ST3O7pOFNoVVfijOB1dZDJVGCQ4AiTHouiTcoF3D-kpBny_7vza1ewXa4U_7JKjLLUwhhmT_sfwezhrV2Lya41_7
0NuGuTlmE_nf-QZfVcXyLZNqdU-dFleL_hnytTrlRseUjmN-6EkEjQu--XN-l7pUty_l_UNIbrB7XIVxrVomFMX5l_KvVHy-ZE5x-EZNyEVbw_xhetxdbwhm
WwzV7zZger-jz9tVZb_VNLU-_H3dsw0vV46EZ7xLrV-Sxl4Br9RV-RciOAaswF0N-1ZKx2Vu9wUBYi1s5_2zsRHI_U3ZlE7Fop--0BaFsDx2PzztlkJoTLx-
V0Bt0ToODtz9VqdV9z_cvSyjf0q1zpNxFdooz8DtHwkTVd-fFmbeUA30Hmpl_OMdtZyUCJy9YEFopTTQ2WM_-cFSmgadFYrF0sh1H1TrnJxC_lbthr0zZw0z
E898A1rJqGhvvhlfpGS1-ZXW98JEVUS7OUMg_6a0zyyu31-iOlLUB_tw8g1p2ttdU_9_4e22NsJuQ5Vw-MClvJS1U7ntNqp1F_huvLq0J7xs0Km6z1S1sADs
l_V7DbsKNmNeuy-dSj0M5tuS83XPUVdXfdV-iL9__H6dB0yJe6Fnxufi9EYzhaCtAg-h-O8okT85QvYsvcs2BGcezEEsOEN8d_ItHJ9_lc-Aijtd-rH-LqsN
or8kVr6KnpYNQwVoXrKfzXmbdQcM_qZz3m
}

