sprite $Shadowed_router [96x118/16z] {
xPZfWl8g44JJ2mrntlzzhyfO8PAE4F3kzUqBfyPkykDa-UVb_mX_ayuMe_4twOy4-WQTGaHqFbtZBZ9vhHRVOZoJVa_yLWC7owaQ0isYUmqwkbRGlGOPeIlm
I9pN8E4HApDnqHnovZU0xZICNoLMe9iRj6UjLUOjcWJuxWPk6SqZLnkC6-XEm_YYMO0VQ52NBj9Uu3UOizQSuO_0XtGMPAX1tD60Vhq1eoU7ZWgL2msuEhgM
z08_CYHSVKdhdiyor53JR-3FQi3WRRtZRxUtspFOK0m-uy4_Rr0Kd3M4SZGP3xxoDgIBY-PjDC1lV5KUMWEU9rk1t_53KBhUWC4duFVye04DxXgy1Wm-0b_n
SzHTjFz4RuDFm3lySf3KjcW18bNu7_3BQomzQo3SIU1Nu7z-ZlXcpLTf6_mn7lo2tjvG3Dx1U_mOZJujkXYyYmU_XCCEJni8et7nUxv1Jopcb9TLzjcDniU3
VoGdAINdAXLq3-_p8_YFL8i67QFnyRQySaJFYUyD1Fe7VA850TxoQYqc78xbel5x-u1VPIco_-93_kmuR5WqxcGynzzqsIL_wRRn5zgT3aiPYUTuq94Gopnf
E9qZ6zq-u8sSTow8Fld2eJY-CbvmdE8JVNXryNjhyksNk9qF3tmymsEjXv5yD1-sp5ziEs_WEtWCtel6c93CJpWFleU_MOCo5lpdnR-VJs7T-3xUgErDndOw
wKAFNnwZ0z_1lzPA_B71jlCft05fkGVyGppMAYt-orPS_DkUd_RyJDVNmTRN41pNukPJoQ_nLZz3uND3oe1dGQZum6Ej55hzjpI4toG1Vu_7qwhDho4OdqsV
V0Hyu1FMUY3OHgx_eY6iDH_uRQsXstyPbxNchpc69wRFVvq6y3CTQzK3_ms-_peDu6VyDlW3_xLM_qK3H_1tT1xsNyBZ07xIalxUyAgc-Ew_TDuWAVEnLfta
lupFKAoCvCn_9NNvBzSNRRB_iljQ594n_-MDBWS2h20v_gj1gQM1vCn_nVDV3V3Vqwl4b_qtDxJRAHgamN_3JFzTJ_mtcF4b_utJ_5Th_oNhz5_gyb_jzz_G
xhzopNzr-PB_MkM__0t_JGt-gnVz5mrnp7-fmt_ftN_jklzowRzMNYKUyryxzDymxB_usj_zTyt7jSj_V-mlzbzvybLifl_6G_zDy_nNKV3FzT-GaDNw_3Vs
-M_gz5zP6iEs7O--_wRAVvl3iSz_iTRcIEc_gS5_koC5OLNNVx7M_cYvFVRyLvRh2UV-YxLU3ZNuxqZE_PV6yRx_OgtZuUZuxxHmglntSYI1ZxNEZQwPRpGT
NValyd_-pny
}

