sprite $Shadowed_router_Sm [96x122/16z] {
xTZPshCe40HW6hfPdFk_tp4EdnMm5Vh1sVywvwqacgtSNvnV-HKIeJzJJtlap-8vrV2VeOUO47vVhtnD36_gFXvf6_nhkkosra1lw0JzqY2qh3De522oV5aH
lO4NTDapRWWB-bH330lwN8EtwPw1AmsBDoj1DpG8pUeC_x4XTGqyemS-eXR8yirQTQrWxMQ5ljWGRtLV-QM6SA_lMMtW-yjQiz8WFvYgBpTKbajGzEK6Ns-H
N3hV1oNMWb3rL4hPbCU_zXIuGb8-FFnt6gGgN0uU_ae3GbNFbMzyOh_MuF72LxxpUQMXIhJhu7zhVNj3hqjk-Dx7qpGrS3t2EPUQW-zzEOA6kGAcdnU-vriV
TvgfmKDl-Nj_prG3T9BSyueFFgQfXe0NNk5LF-93_Ba1UaWAF_H73O6WAxpgnmX-q43uewVmcgzzYUQiDtZeUFZW1tw2dpCQVASxJZgFKEU3ZpYRSzE0ophY
1Jhyy_UNf7oUHWCkwuXFv5eV-k7lHCRnJErViH6Fhrxu_T-fYEDD0t4QyCeN5y667-NxU6tWDE8PBFpO-F7mznR9EBzz3ig8bvbT8IS-_BqudVmcy3KUb_M-
0MTZEdmN5L_bSLdruAQkWRyrliQFTNnU8LBzKE3VyPj06JNWl1o-Smc-mkz-cg3LJ_HSjjrtiVewdyXPmZY_2uSlrTVu79mrt7oa5uP_uGjqQmDkdHZXjxmu
nDiQ3W61NsfQFPWt555zy8akxyveRsXzyBdv_hOk76Xe_PDdLRVFSIJbsw-wE8Il6yh83BvjW7_HWsdXm7RIDCHlFr4pYbhtXt3mruRgjvVrRd_mW_r1QpXy
Rb_uFbFh1Xg2Vvp-efBpjQUv_U6cmUlx0_u6o-p-4FpZzDVfvxfXs1y2AJgYhHlO7-mDGVeewmRsXq43TmrUNKMXapJxWx71t-qFZ4zrTNy8umPai6we-yFP
GDO6h1lF-uFO6zfrGzyVu8kz0Rfay7VxWxq1wqRBF-m3XWQi6mf_lmy4s_uGad5_Y6dOqAuRzlrXr81rmx0_HFY3Xk2i-qFxFJfemD_WFBq_YB8_P3GekYYy
TN_8Z8P-tHZm6tK-z1ZFm-rpQDUDzCJpu_x0N_i36hoRtH_43VO7Z_sX_oeDCk8JwV_Vx_S7D92a0PydzmS9tyTB6EmFM3UKI5j0TNzWw_wmyTN6qyPPFlmz
jlr1t7tyUVPpEjdsXz6wWQkSpy1_RN_mCICbqX--p-Fz0Vgu0USZnMCV4FWglubzV_X9im-8maEVRoZWjqBF-mCkgw5XQd_0kc5lQFQ7TBS_5EZsXi7-iElY
LiBvQN-0lj1GhhwoRgmtm5VMZVK6-5WttWkh-yEx3V2XlnafrSTbVJd27p-u_r1-vLT-1m
}

