sprite $SQL_Server [96x123/16z] {
xTg7ckig30HWcaJnll_ptWWpNiM4u93azZcz_IFRhDcFxvWFvV_uh-eXnXY-DtlS4xwdVwt1C-nlD3Y-9NwhmOh-jGPBuB_HOEaM_bQ33PKdrlaC3nrvr43c
dOG0lx-6ztKVQaY7TMpxUzckws5m3KhFy5Vq_XhkT9VoWk_0ZneSTE7XNzSbJngygR4nBVXMy563rZc1XtzP7pT0DnJJopxqSSEl3lx5-TtJ1hNF3Ftr1kYi
-5TyEseGtDjZdubdlrppVHWsGBV4R_X4f1e6-WF-eXz80ikTTKF4gpxc5-BKO5NxW7zbVY78e04wkZ_ZTnk78_gaBm1fVSAl-2c7feSmyxSbF-VJ5ZpWrtrN
VGgpyL_m-O5FobVyiX-rFnl_RN_-T9Vy37_6N_TfoT_UyoUByqMVEtyw_fAV_an_p7zm_l7urttmsf-C_xO_7V-wBuenZZk_uzTz8Iqf_yhj-RdgIuByvH0l
-Tk2pv74PVWNnh_k0mhsYh-j-ZjIu0_up_ZpyJ_ZQtxTTuxk_VdJVSclY_EQlwtuJ88wFlm1l-YBn44Quim7_wel8MS8_e1Vy1MLHPhwuA_x4RuWJ_rjtK_Q
duv_tLVZJ_rjnOyF_Pu_-xu1mNt8r_nswBAstTnFlG--zpS7dMz1mml-qwURRNV2wwVpWn_wuA7Rkca7w9xPNVU7uoTz12kk3KtdmLt2g3DVUDQw95WZElRm
oFwotu_FTyUObNVgCKl8zJxuYK-OtQAXwdw_1d_eWVs2Zt_ZSEZagkv-ByFlt-kxrFi5_ebtJTV7Mg8BZuQgzy-15J_qxmuQ3zzAr-wtGkBMGDfFdTyV9Ua6
AvHtQDXrJ_ve47t95y7M7e7t1h_h4hzN6fqx7ZvuxGkdhYAWGVH0BVvmNMn-clbbzua83NWECZkkPlS3z9IJylCLNt9_7cjhLst4CJNq_DG_yUBRwbjp60uV
3w4rU8F4VE_dYRyfdvYileeWyLRTTpVoo-5hllFLOURlGVAXnzJvUU9lcz5-tR2CRd3G-SOtlnn-lkwpnQSMpZWqGAzyzPFsDGzVyV2D8sBjopSLvuqN7ZwR
g_vM_Tfmv-SSmw4JtVbipJDVyV2j4qRy25yIcavCuijWpiZpzmmVrC3Vcjys9xhtItiqVFX9HlTvIy_ytFcERmbrsA4lFDMFtx9Tyil9PskgTopoqdoklkWI
uSz-6VZRoMUo8chVmHVT9s_opDVZdtrydgFzOyloCUURltL-6VZR0xyrq9tlctxsqzWldHyTzkjzBJLVTE75Wl_JV5Pyxs-7RuNNVbrC8Oll1QVcb-OVhwWu
zSb8GlE5p_Nv1gDUFJS___hPcoCsbTx7xO5kgo9-EloI2Ng4NyGNtUgNKtxe2y_7XFj4-_ZDBoM3JyftCdC2ZWRjO_ogO-VWK37Xgryaybl2DxyKSMtw-O6F
XDxdxhy1sThmq6VnIrrO_FC3lsk03nq9rNU6R6rm9XNbfzqNtJfJjAz3lxwCsldosacrGViUlkXnyoDVmjLNklQnjxBRPu4lVAPw9TisyX6HeMi_ISINnFhQ
L7vziyQoJNnavcTdd3JawYUoCXELvcyBld4nfQpyb6IvrhiYEhEXol_iFfcNOrdOofVwV7D0D-Ui_OtCMkoTZmRU7mbL_kPxivvG-NAtFfFsitapBfUJdt_z
x9PTtT3xHVnapMTYUpyP3_qZeSCduR6XVBWXDv_CDn9ozQ5_8GvlgxzX_iyV
}

