sprite $SQL_Server_Sm [96x111/16z] {
xTW9Ukig30NWWX0IvEl-j_iISK24qhXrtJVhZitm7nbiFBpzxUl_YYdyeXvOH3ZyfYw_bH0IT2HShMVGLoT0lzUISDrC4pEtW7nn0dIhtIPSiSDtdhFLnNeo
7uM4goOu9AjDWklnP_e-OUYawQnEhYy97BikfPppGoJuNgiUHOlvPtIhNGADnKYrdF93ZERl4cOT_Xd-amJgqvf49_-Q1DT9H3fVuPz9e5xFUWO__0iIXXvP
P6x_ktwYNKBN0sVmftrcMgR1zPIp--MidpdE2S7NQV3krpF-lBw4IUVixRlFPtnV7rtdJVlVzpkZcjPpZBT_YJyI0Z5lsZ_feqqZr8OcyIT-_QbVtDyCptbV
Ld_V_ZN-flrBVNhP_ksxVlwyV_3N--lmb4lzbyFpNJz_y9VsB_1bv-_RF-DJ0WD_s_vvdt3rKU1lsl-HRry8-PNl_AdnfvRWlW_F5Nw_SyZmNxH_rXTDxY_j
N-83wlw-_NE-GwklHtwCNzf_0i_-PkdP-v55SZpq4tPFzryCJwL9jpf8oBXh3ddnTyDJXXx6Ll9htwIMeCFVjwzF4ba2nuDvWCJtX0H_txu67vaKsh_GiqYc
rxugayBVBJsoF3r8uSCyq6lVfDK7pqytiMn5quCM98Ij3sdrTRoQbkS7ANd_de3-Z_sb_Q67u0a1_uizWKqFB7Jip-q_Zqn4a5y38o50VnIjlcxydjdrzQul
-Fqz-JX9AphsyPfYrCTzPHo-5RR0YcmUyZBJdThu1RudD3q4Jy3un778IOQ-yUlU3qY0JYbH_n-IcCSXbnbwztNdw-mRXme-3wZG9o9DC9N-F_0Rlmm_CRYm
tDzZTrqJafRNlgu-zX9FWEu9paVLyigVbuRcS_Ef9_XCn2cX9sOjgr-UVTtxEIC1kgb8W4xvXL-tFYwupFT39yGn4TCDluZOPKYf1pvuzvdwWPtSHm8DtNnP
VF3kwqS_v-4hk75Gzs6tDvjV3tpmd_aXXvuGCLosM-pzulpU3vJDRyB3B-Lf3IF6kzhyYcKN_M_yCdm8gzyIeFFYcuw2ll4hV1y1zwsKe3FIrVnaG_TrFsGS
hDa8zulS7UERh-O_YhHqV-RXWtS_vsG9TEYdfjVRDtqJB67oAtpClkBGu5fV-ywxBttz8Tduyl3xkCkTTz_vGn-N867sYHdlMhZUlw07ldxqHSmN1IJFlcHC
Jodctrxw4tyployxjeDW6EmWpUsKonWuBJlV-MFV2ejqBkP3nsRNXtyxzi6R_vRWDxxqzIVaXsyw4TeQFdTVZ_sta1Q_54j0KHRu5RvCxoRmMr_6fznFM7_Y
q4Ki4-kcGX-L5t_X8uUdKr7griC9RTblVZK_s7VcW21R7nr66VkVpM7gbislc6-lZQT_KT-Bw-sLoM-yccw-gY9XxsltEPXrU---5nNtNM_ezEoOfC1oN-5Z
JCgTXxyamAyL-_ZY2_R5lMzwbAsFucA-wQlFZmthxnXlVX91kkctkr3Uztw_KdPzwT_EMQb1vdFt6NDukrNt3sljlxJ2qwZkDzsMvND-4FTnmuS72kOdhDd6
3v-_p6FXdVrGSX_9s8OhJNvzltr7nshfVhCaU3fUkw5_qq_Kx3yIg9y9ofqCzGR_T2NtMzq3Kblskr_fF8_reRf_drhM0jyV3_qiOUDNypM-NL6HdlpnW0Nw
9LLMdzwkBIxkryBXxV9AfVjyFOwfVlY_f6Ev_JlN__K7
}

