sprite $Switch [96x97/16z] {
xPg7hgmu44JfO0lO___VPRgGPJCUry3rnlUEuasdQheHINUPn6z42hF5Qdx1J6MAMts0wS_avXpJ2NA2ocsxSvv7g3_0hWaky-n06dsIcNOWbJu9c_lp14a7
CjiE1Fftl_eiKizlq-nTlrFCz8MPKzxzpDoM4PPI_6ophVaQCWmGtjxasMagjNvYX-ZcsQJo2-zkEMUxTpPCCZuoQq7AWIuV6Fk9Fig393S-WGm6Q9VoBC46
_h7U4_m5d-0l9JK5kS78VBY__5awoItwpI4gdxEhyls496Guj3_AymHEFrdJ6val-flTQodF4kp1pOu98Yy1WqLJtii37i3Nq1vULkOrDQ7Ugq0_2BY_Q2Wj
x0TUGmA0yO0eeGRk9oWDG7iIy7WDTlXl9kGBFaomGrv6z3I13Ga9puUKZMtvfqDIua_sD84l-HJemo5XEeC4IwVWxXggydaTz2-_dUJsaE9ZwxPHVuuwxQ9v
GFn-tgW_7tfWDuOKvMqxsCT-s4_eejloeT-tp_xARJaGEgHIVjseto6560c9hy6Y_Add_KjnINaz86jmYV95_yUt_WDV0nrS6L2-qe_yabg_hk3p6b2-qW_y
ONppPoHqrw0eN-dX7s4NlmXMvsz3ihFynR_3muuYFVzOog6dU2G5A2-vrSFFa9nZwF37DyAmrcj0-LOVn7MGeD4hmNzW6nnb3IZVQV_wVV65OlZRnhyVO0rH
lgStNALiuJZ-klXLr_rWqtE67NqkzwxA_LZUXaLZlKXOKRxIRw6FP7CWL5_skjhBlqSbnupG7dxezoYlNe21eI5OyxR3hyNVw7VirJeFNmo7ekylQpUKhwbA
1bPJLqX5KVaRVKRv3tvXBsSaxozovQ_r6yfVaR7VcaNZqBJYh_JvmoEm3lssj5ZCAFlLlvurzPxVUelU0VpGe_nz_z8ZrVvIVfeVYuO_zBQ0AVC1ki9VZuRk
Dtd3-0HbM_XNQtET-_ad06wBv8NfK-LFvDKjmtoqGaa8U9gXtY5PwsyIU0X_oxqq_lJbsta9S3Rq0Kal_kHJiQNspmv8q1S_cD--zlky05awVbl4fkkB__oc
pXrzyLjrI4yi3mJVd161dXnHy_ieiPAC2NAImSzFypFiePgVAKr5_kN_ml6RFm4
}

