sprite $Tablet_PC_Sm [96x129/16z] {
xTDPsgig44PX6WaKnZt_uHvty5zFI5EYoEdhFk_wagZvvzp_z_yvxyVgwxb1klK_vqRnOmjkNC5QExJWfycFB4phVIhOgtm_hC3-OGNy_e9D8Zj-2Ey5ryhd
PLdidd--41V5XpzTi7EBVxuG5is7fs0E5kOMNo_OtVcpKVnG1svRmUuNc1zKlxxRUiftQ9YF3nzZvLEmQa6VRvxud2LM_AU2Ep0VFqp5fu3VKiZAV5FMb_qI
VmheCSQzWjVccu8NFnbN2hTdVoqufQ3FDo5CJxwXWAyKjFduvV3hGkJ2ju8mlyKlXLGA-1Jg5y8gypMVmkPJi6y5vX_pASIT0iz-iy_vzq9AwQN0mzFewuMK
gWBpxGc_Bk3N1NduoPtqAIJuhR05olp9UtVMfr1yRZBhfJAVr-6KJw7oPItOvN4J3wlgf-8hXMT-lIGFFXfBuB3FJV9Jm1SU7W9jlbx0dxVvwta2pRvUOFuY
NWt0t_3t2bcUviyv9wy4VdJyjWBpy--BJu4tl-Wt_BO2yqlWwnVOSFpc0lCVLvuX1yuLc_tD1UQNcum1hwxOx6yzErVp-QWB8Em_uuTjFlUxwKACwHe_Cn_V
Xd2Pxva_mcV-69_vjU-ABxq-y-NDN_bkd_afZVBbuRjHlYlppI4_Hlp6-KVy6F4RvulvucTJNUJm6-T_zgNNP_wxlnhzVYhpH_cM-MFyoFmHFlF7-Cp_walk
yktC_7T_9VfyvW_pcJ_ITwe_z_YP-MDyMURaD3_t-S4RxfClPtrEyzDVwii_mf__GZz7r-TBVlCd_9GpXLD--kJR3NySXGx_RkhRQANGv_iKqTSJ2gVy6P_p
s6gXtTS35EnnF-DNPuDMQFS5lxdGxLEulGOUXPizwD-BhnJmALpXKu0l0GfD_eol5uIZiEjxVBq0_rxGVSduQY5AVGK8jiFN2X0K5F-Elrk0VofSvLF0fg3v
Ctx3kSZwkg3xlnfe2ld3IVZYP_psGb8AcjzVqFt-mlJ9l-CVAiZ7WYX-Vu73BpyF_h7pCiodCCodCCodeFft_FE50RvUm9_nBo_W_yBlAupokUcRVpVcsW8-
F_-00duqPa01FrndKy3FpWouiFaEVKJ1_9Fk__l__W
}

