sprite $Teblet_PC [96x130/16z] {
xTQ7hhCu44Tnuuv9tlzrbpMZd0L_ZkPYittKR_cTVwGqyv-v_y-64EoZUdYmu8ESN_u5XRcizsvve83_J07_kG8-XULJi9DyRhZWGi-NCoE5fRpVc_lcXo25
9TmeXFT-wOjVmVk5el072kwjzDk2NpJpkpxyZGBpLNw_e9h_Nhf-k5pK5vYVZTQF-ubeAMZduyF772z-Mx0TVkdCD_2XbBB6awylPEP_yob4hYcev-E7wbF0
rnIOtnnysEcmIk7ifxQWd6z45z-O88_XxAVlXSJyrW_11_nV5bAzQs5Hp3T13jyiaG9yfz2PZ--lFeLyyNEcmDiIytNxsyVmuVTBxb9Wlje_FmRyJe7vMb-0
T1GI--LEXS9yfKyXI-7YhzdnTOdvIhyjhBdo-2k5VFXUvxVdLYdabF4fR9Kl8TXxFeLyygKGt_LY21IKFkSfm1y5cI-4lULJM0-V-pnvl20tVGfddoUF189L
-kq5ARJplI4G_4sVjrPkg_nMSZS07_5L1UQNSWxOkpvlI-VvHm1CuMiAp9U0x--F-De2y-ivOspxJVMZHwNFMolpwmLZZBVjypzMNUtpniVyUfbVkfE_Ny1N
NpZFvyCrP596x1j-OVvnn_GGqzcFz_n5vdDLt_avVcO-lf_bCx_rSrx7VURFzvc_DdwSuwVAfqTyvY-j7zEmptppYC_yPtpcDxuyVSPyvhVxumIV-Ur-yPSX
N-R_q4zQFyhyN_gfuoUzlybydIzwJFYw-Hr_vyz-Ycd74xvsVjyl-4bElJymN-N7Qklt5-Rhz-lzHUPt_3Jg1-RFzjcVJCUFmxxPXE_ubH_nGp3cbf_n5VTt
ytD-pC-_Nth8F-pQcE7dnZ_c7tv9TjIl_8OFdzT2OPeVyoLGudBVJutlCqTXdc_1cy8CtyHhG0epV09jOGst_Us5prE8Mvk2tg_pyGcWrpiAVeflNFeZdmbG
kELpDWdEKHZmELVrJa7hP_ps7FYru7xal_2rXUnKlin_ur_EzmjsrEyN2WMrVwUGx91FeVNbuZB3fm1FOO9F0Px2Dx_o-DykD3o5SPy20XV6V0hmvrl3e4-X
T0f-pATGkeKXduj5S-A_y2SLy6K-llgM-AXFORvF8JthKvZlKr3wCmluEuz_zsp-vh_n9nNc-nJc-nJwlk7c5V2ZcNHslVhxq-SLvk0KyBVNXZxdt8fV2lhK
WlZe3nJCV-h-lzy
}

