sprite $Tunnel__angled_ [96x66/16z] {
xTS7hZCX30JW6MC3rkR-r_tBQqigAnc__gMfUfHX6tW_H1vgS-z6v51_KOa4rNUAvSn7NR1MyRuF__zQMnBxDSKwfT_G2bQf_QRAd7fsHYp0Tbz9dj-gvCpV
XKjYRGzLHOpM6K64rAbOILRdD930KkSiKXBLva8bYTgSXXBiW18fgUW1afx0q48VK4BBa5wIb0D29PK393y10N90x2zyZWJY-oRyBaFPVvXzoP0VVicWPDyQ
M089F-RsLcmkbl097iM84EhiKPWa8cZtn_FbUiAKROc2-e896oiR3s74qDeLYks88AdjdD46Yh3Ipb3RG74bM1BQoB02QtzLwIF56gNrPoO-8bRH_aJ5HxWI
B4bb6nXMakQkt7PEhAMzOJkzseZLM6cdLu8K_ZpTYHmKtxm9yf34k_aB
}

