sprite $Tunnel [96x20/16z] {
lTF50O0m40J0FSVwRnVtzyBadUGKlv0Pd4fnaMuOEf5gc0e77LQgHPLoFR-IBAh0gXjs9Scbc6bt4WygnoowKwXpOLRTgSIuC6ik9Seb0EhZzwDEyKLzh4xw
HNybJWWkny9Yf_pzMfcxBGTPL8wThM15bJY9ga0RgiIBCod-CG4
}

