sprite $Tunnel__angled__Sm [96x66/16z] {
vTS5SWCn30NGBx8SkFzvEvxnKYaWgVY2IsR4dy7AA4Ds6WmrzBIGik0dPsJZqu4X5_NJgP-cFbwAJDhVI2qaxvFtJICaON-V8eVwHwGuV6zS5lva9UNVncV-
LKIr6nWnscumGeYrMnGXQZSn8gWy1bQxHP4MWnxVupC8GaHlOaIGw4s42DAR125SNKXW4VtaDQvID8PR627q1J7S52sadn03OigpGF-Ya3Yda6H-pU_3d-eE
_GL31iNdXlbPlu-_N3zo__G9L6-Zwa8IXCZtB_QK4CBsAS9KKaW2W9cfQDV0Qrz73DdxmPDEWY1khVdnhM1RKVxU4x2D88pCznHsE4h0pJT4lcD88Rw2z1r3
4lC9rdSKMQZreS7x3XBn2DdWbuqZbVRJCNn6BceDUbafqZ5mkKwE4Zg3DrJfbqit1FmhBm
}

