sprite $Users [96x138/16z] {
xTZhVXif30Lm96uISTx_TTSmFWO2m-3Mthk-xBOT_-4dQpWavlFrVn4xQ_bJEZldl0yXEFg0JZRpsOynyWVurXVtCJxx8i8VuElsHUNDNoru-BhJ8ThaQUGr
Nivo-O2tkvDP-Egdgu-WdU5wXKFl-SJRq-QlV3_myFUcpM_u0Npnqz8VfiskVHUWLpxHUUyhlpVDjkZW3rzVcZQxzAdW7P_2-MuAt_lXea6jhcdTdgBtV5Ap
hf3nbZyV2UgdRSCdOoXsUXApzi57ZCDgc3td1RJX8otzEcxuldGTAvdpJrszMTN1z-CGpNeSg6oi-EBfOXY6OSRNjLY1JIbws9OkfxdbzUHnvdeQKlFNtdj7
osdkfosSdx9SNqfBP8ZO-LABazrBpwivyujQLm2zM87oNmPffqtfr4SNpbRWGNVbxtp32sq7ADbX1HgFjhm0nuT-7TH4p5NviOATxS0UQuNWFL_gDdEu5685
DsiFPXV3XdBUxjmAVNzTyK3Sqt5r1KiGtEae84Xnr8QsqHQdZKZrdUFsmcJRJl9rJeUIPUsB5g9qVjqfZyD6bxV2t8geaHw43nFV1qUpSHxVUJi6QLPKDPFs
M5Pqy4FmPolGHKuxOqZrMAVuqlZ8nL8qUM66xOFlRftomzUP7sFWoZJDgMlCBftPYeUFzfpukMnT0UDMfvocjy9yU3M-h7mHSTsRnr6ayyTRuUYdwhSxGWRu
DjTQt_ZnLjZs1-svy5K3bM5vFEylSpgR3rya_stlXzxFLVZoVElRC0PfcS_EJqjVuVlHD_qk47JkuQCzcpxQsVWClRiLnkhBdf_WYsWXKAxNI_UjTdvANxqV
rlwJPrSMq9z16k6ZFJC_3ZxQyzIFqB427PSO2l2FzdoT-jBwQ4zxzjWofGUlaS5mh7ww-r-l-yY7v_yTE04ghraKxNtmCn_JLa1pQ0yNHVq9Y-tVDltoVF7h
QLUlRsGHGKi_xFaE3jdJa2C_z_lnWOzfW-yNArWqJ3B_tVZXrCSqjC7YkGkoyQxXYd-33pw0l_3lrQumvZJF_TZxAVkOjY679jSP2v0pl-TZ6YOvv_hREQRt
wN__fX-bkSuGJZuF_oRm2H-1hwslrVT3JeV3XHFbuT-4Xr-qWEzyl2odEHgvsUNJ5zCN_R9_Bvj9157n4uq__CQvhzNVpcaoGzd1Jm-_yDyREGf_MXRymj_F
wRMlZQ_mTtEwf9btstxXRxgLq_19N_DrEwUlV9dwj9-ZvQx2InzyyUzyObFziEDJEl6b-Zuy_EOYlP7JIVB-h_sxofhdayoUZw0uV7_kQwbs0qJJ77tT5tRu
JFN9A-tdzDedOwj_g4vKQJ-dLxuKN-6xl4OG-EkSZhk-LjzZw6Wtf-5_pNmPV0pTZe-WsFFJ-tqPVBG7ld7NEVrzvik6R_Wofr_nqPusJVsLhtFVTNw2Bpzz
kypfs-j-_bZZyqLE7_vjn_TJ_oIdTSVNXvyE7-tl_5LEt-w-lE8B_CsSJfxCkQyJ7_cubQC2x7lffuSVN_Nnd4vzdVZQ-ykS5dhaHRhDV1rzl3Iqo6csXwzi
IeKoHgElJp_j-iYvUFUVOCpyhgyxVZNoS_AoVnjyOVQ3Jr4lVRxxwUa_pwp19yCrHna_jJ_ys-_wqllMas7aQFQ_Ltvw-a5quMlrcvn-tS-Fzxw8CFmsfr_t
Cx_sq-XdFj6l-pBuQ0zyNBYlV8NFZIzNVlwhNR_mAt_CQJRJiZC_dVfNEJqMHzNK-N7VhpcwNE5JFifIvuF_fX--SfjpRiZfHJM-F7mXi_Rn6-4TtpZjVUYD
hyhpd6QpKrwhhppDKHvo5Fxk2iLlq-ETlg6Glr_eOqxpFAS7Vx_6dD3qv_dw0R_9EUJqP_oQe_yaFpM-VjP7Jd_Cp_m_sDSF--3VuVE7_QCTYtl0xnTv7VqR
_7SKKUTZ-yZ7TnGF_fStxooEtJq3-XkBfVgUp0UAvV25p8VAvladyr-j_-iF
}

