sprite $User [96x233/16z] {
xTZhSkCW30LWxaXaylwFkpSccf23iOnns-pa_4u-7GlljjIyVpxvn3eVGloJu9rThZl_Hwz--Xjl5-ilVivXsGJhWK_vJ_ooyjMl0uJFbEngllKfsnMy-57y
okE0UHxNJpXWdlTGl_gK5l1ONtpci937-iniPtdRuz5FI-h7i56VsPsh7uRrvnz0z1s-y7pzW3pwnSzjlzMnllXnngywybY_q8mFEcxduPS9tebUUMnFmXSx
uOiDxOKNtqtuNHstSzvFo8jVJljfm9_qa-03VlPyZS2W0yzc8W7qBRxa6Ty_wS2tVfpnBUh8u_7g4yNUuTbCnQ6EFAv7dmXwbozsqhU04tVuQ6RZnHxmREOJ
XtgDDoUINdJaqnpi7aSmrakUqqC8Ck091vvcTHbW4kgIFAVNE5CJjlGIP_LsWCjTdTnaUua0da3dSDZ62Tx8XDpef-wcDaYUI_gOYPae1MVEHlmTonsOPMt_
ryzHZHYZUe8BtdOFmc_gDS7gV5a7JEW8hkeuOUp7hGdUYM5i_UZp1A_owtSSlaoO-38WEbr_R6Ct1xGZWbFrhscFMlaCmIdxuvdvi3aZmfSs_VPA4U6eDHD6
VWpF_kG4h-nV0nFs1qItuSVGzg-1bsbtH1ZUwF3YefeWstMx-yThL_jUZ9v1TFI5Hp_dg7fThVh6YvUNtQFs3MVr_Mk8ycY2Q_18lkC33vSllp71lkZKyMFO
yN62hOknZVFlezpnT_lNHDjCS8tYSmPVtR-TWB5UFZdJNyASR4UlDy9QVyTFEpvpTlXrzFNzyIP3hdtvX1_vo6_wB8WF8RRrr_Ybc5h-Oh_bh_TvuAjUdzRt
5_kkivwoiZ_K_pOV-O5V7dvdFIC_HVH9xpFuqF-7-RYUyNvE-VoJ_ApoOJr3F-tuFFJvH_eqz64z8pzD-5Y_H8sV3_aqzaLN-aNypdfke_xpFWzymITzKlY3
-YCVrzFnjVK7Fe_z52TzgNzDVrnFpqV-gCzZFmthZtsfl-sdUCWls_wjxwUJFklzyVhHb_fN-17MSyodtVwudlkkdzL-XFhlvkDwq3Ss0Zy-Nl6XVlKXVbnV
xz_5XqUOzNdON-A1L_Ym7kWFZm2ysg-y-9We_06VzRvJh0TyuVTzA_p0BmF_FlODrD_t-P2V9tpXB_VlU_uUZpvVx0k_oY_R_ls8JogVmRzbjz9lrrC0L_gi
yG4V-7JS1_sydvxuP5RuvRM_-5RXg-jZ_sIky1yyEtF49xqFLzxrFZapwICVZB5Kn8Vou-pM9_Ct_idFrYpqG_sSfST-l3aIvD6lgMwqPe7Fu6CywNpXS-Zm
PSDtcVcWduon8SBhqzU9zJw9_oUA_ZOIiTudXH-iaVXCo_poy8ENrSWDGEUJpe_HFjrFMUqJ-jptOt0-vmlzsFxjIkNJq2yFl_9hVDxt-UryNF-at_3Ym_ed
_Aps-OJFt-FZUixxvPjylj2dTNvfV5ZFPJw_XrzQ7zTpM-cdB_FvFVpI-BtrlAVFQ_ootEUXZ-ivvPSjdsTzljRdiG_hEUUNNVzsp6UbptC-VwrVm8Vr7FBv
MfzV_89-RprtfSzVx9UE3-lH-ppfttK-7_3vkC_WbxvFN-4BF--N3H_glvKFwvdmwHjzNCzx-R2UY_txUf_VtHV-Uly-uPUnpzVxvOnVbFvjpYzZ7zQZzKdu
QtpZIUaBZ_uudhciz35njp-ivv1lREIbFiQceIyy-EgugFJlwEkZzukxp4TT7-hxxVgBDzC9lErN_XPdRPo0lkZpiH5yuRCr2s9JtqTzVWBwvCp2kDJwxCtY
kFpmGLyKHzNdQ2vANRar_ta--UIJtm
}

