sprite $Vista_Terminal [96x144/16z] {
xTa7ZkCu48LXCLIWq7F_wwueF-mGVeH5qzH6_uqmyIirgYPg-xVqxLkKE_KaH_c-PqVvDl_c2Vd62V7c2Jc7koR0nuGWjqp8PrZqsWdmRvi07oMiOUK4-2Zo
X8M-7F2w2Um_L3eboKjzS77PX2U-Fo6jyji9QSa4qclAnofftVEBgaQU42TzVlopIASaQSwN-a6-Ig15IvpnWJS-aktZ2QUUcKSufVa9q17vPZYbsGbFFFiV
Jf3VMN45t_WrEYMUSEthVkGgnDV2n0JsQzxrJJkd9772tulrV7EXKw89rpucC6_kdh5ecZ3ibxAVkR5VIyCJsBVg1jqnWVqpd19D6FItBVf-LboD_F49xElf
7wM22SoVMU-K90m-Votp16zJd19D6FIttsle-gK85aqJnlns3SnxESel9x2ly56p1kV7FqkTHUU-hwBaDsjmzizmIdqTFdZsspMKlbySVuGsUdpozTJ9Hz5e
0do4OnNemSgJV-BiyngOFzkb-Np5_Ca_O66_luQUlnzbw2BAFkhxg5a3-xLO7oDF-2WqQo0VlszLVi97oJ41RjUN2P_MG7px_3xXyneG--PbmkSrhFPv3Ojz
NiCEVg7FQsXz-T3dDJpxEkttrm2-yNtEvmBvwV3Dohs-bx9tVLDxqqVNFlIRVE1gvhVuzi3jBX_w2b_xlgtp_LxVAZ_bV_slhtQtxvT-oP_ubN_brppUvLlP
ponC-VdATyU0NPO_lzUF8qmeUVNpkoDCy3Jh_ppxWAqPKBEun3zbs4yJz3s_yXsVuZMC-_krZm6qXadVoAOrJFee-SK4dVPHzdw5rZ3cS_9Y0DOmwlzKdmhA
k9TQRmrzt_i-2aO340WD5txbuNUB_FG8Qv1fdqy9Ce9IyhIFCl48ZiTf7mbq6e0qpFeeQEa7giWB_-1_RLS5U-5Z3PC-YbwubeiTlvGT_a2fmxVPl8yoyTIi
ZtICXo_iZozwN-n7l3483dxO_pNY9n71X0X-pF-1FyAB2avfhG--UK6Rn_mT_WZ_z89Mr_cnuctfSKghVEZq2ZZu4ZyHNyCfNVk_hdpIKU15i_zpwMVMaT8f
JVYHS7f1gv_uqhF17sMSKjVVh_q4c7E4KvhqzPMES4epVhZ0smbfqVCxLt2iv5V-fHy7y3F5AGtxA15DF9AjPkINiBqg4SmwoZYbrl_9sqLfH4S9f_IdRzjr
QH2lR7cSKZbzV6rcm8k_ZJvEgVfv6onTuD2HRM-NoExpIBPt2mhw2aTvUxViGphoDF4fJEhp4_PrEa_Or-ee2EmRT9IjRnTNqkUAMeZESLjQp6Bb8QUmtHNa
s_lsxGy
}

