sprite $Vista_terminal_Sm [96x139/16z] {
xTg7Tjim38LXWHEadVT_tIgCxf5GWGb2Kvtwp-xuBctAdLd-cUxkxYZwAtaVr_ob-cKB50-vAmPyF4JtWeIrQ_0qpGy12quipFClMe3lZmj-wWBEtrrmq_mO
WCrRmFlJEc8J7rRQzERh2vvcl3-8j8NNV1nVBj2K1Rm_XzBC1Vh0mq5FQSe2_FZJsvDQSTBl3hJgaez9BhZHXnN-YKTXmW89Umqu5eO_3l03z58hu_Wegmj3
vwyjbloQ7rsGVgeVbIm7nXTq7mlWkmjknCU2z9cpqnP6VIna-6jP-qZJe8-5tUyiUFgUpsLVu6R3xovyomzBhAS5tajOY7B1xY-KnCBkomLdMo3m2VvvWKKb
BUS5zxcVTh_byZvGM5PAYSh3Idq_IR_bMLyegwykUEhuAJO-2x-_KBR2lW1SossdF_ee56K1_hu0N8qQdgBYAml2hyKlek0Ll-7Q-VM5ibVhSS7dp1q_QJwY
M8yBXG_-Mg7jASb3_kdZ01n-JUylCepw-W9uwRFcEyLNSbptpduSzv4N2sQVZ3uU9LJglFFh2rFFZs9H_SQFdbyMh_AHE_jnfazZFl_vVhtEpvVx_3lzdF9b
_chdbA_psy1r_ag_VFxjyUdx-MMVVxj_-u-l_JZkLujVCmtu-KkVuTUQQC3dhj_iZ-z7SRBVEWwKEC_djMsY71R2J1_f2tO_g7vlWRtTRxpcUqQeAWlZFkNJ
GAbxsNt3VyBNNu6-aCZWCtorO5WOyr7yTA74OHzHEW-e3slVVoX-_wBBwkiBkb_XztEIRoaFQzT_mk_cXQujw3uRVLmq-DD2TiC-IbnmVYGu6lTnqN3rXQpx
3ukFYrPzfFaLlYrlvAN_1jzG4Bp5Vy8tbWG_tyT5r_c-S_j5r_c-t_z1rb_WU_4Fii7WRu-FpVVuJx28YpRvrlExkCholxye6_oLD_cmvGBFyXrav77HS_oO
JZbnqRh_4Bxz-FczHDjspwzcFqeT9V4ewVwRmNSIHymSST4T_sdoexIXj_1V9-K57x3K4HwbUJvaX4TfYizAcSH53_hSgvIISD57_s7r6UbwIruq_9LdmvyS
FjKHBhh0Vpy-a-MtzQukmqLN-8gkbWnuNIkuwERZsWtrSUXRULaGT4jEjv7yQ8qKL1cwB8mCf6B1nry2iH6lx9UXV6I9wyLbF8U9saayawCJiDItPaPUs-3a
B_ZIKmJxDtLtT_S3
}

