sprite $Vista_client [96x124/16z] {
xTY9ikCg30HG18Z5gVd_ttqq8P42BdBDuBVtBBLTdtOiZJE5-Llc_z2zEZEx6tdFV7C3tzXWBVwwhy5wZ_4wQTZkrmQwgS7v6deFckt--o_oNGsk-SnULedj
Nf_bsLjfsEs74A2whGqEUlCHqWtRVKG6lQF1iUR71hh13wnMYMc7dt9KVenUhHBJx_l7SMJbbpZzuMY3hnfYZTtGq81GS3GanQSKPT3B3RxonMUA-0X9-JiQ
77Y6RunDQ8ZYbmGqy7g3XnwgN-8p6hIVCsELbXjyuSKtnA-6rFmIhmVDL_qWFa811LbunBw_u9pvJVyr1kKZpq539xVeIrn6W_X8elRnqk_wCWRj7qUi7s6B
tyPmABx46iySD_WoXhjy6KFdXsq-md1lz0r5m9LlVjheonZs-v8iFXS_N_Bv9pxo9_bnoOz_5pzSzsE8yKQ_u5VyTBUVix_NF-xquxAVw4w_63dGLp-i-Wb8
zZ_n7qj-UZROBtvQyTCp6L2alNv8AbKADFFpgYyDsS_yuvflR5UWnZ3wyQgFECsNW8gqoqTOU4IDOVGV2xwX83mYOzZX8nIXI-1br_jfqKT85-WnQ3-l-eWR
2Z06xMEylzPymaxwtiSOTlZacTbYqCBhQ9-NT8Jge8NVuvFZ5-zHGKdumNzSzXqhFWGqMF0Jto_eu0DI6roU-J7wAwTx7hm3tuAh_PcVy-DNzN_KOA6t0ayK
L1nMwSG_cYyDKrqAh675Fqz_A4vyQPZe4cErNbDNQU9F6gphU2A5w_Cbcp_yH_Ed3UGGpMEusjQdFovFVMaGlUN3ZuZe-lJ7Jtnf45-Ydq-FWqSyLadxRl2T
qiyRd26XHPVJdrJzCjvSXF7kdUnDto05FIuXD5IVyJRKEjSHiVY-DjX9GOTZlcYmrWJSAaSMlRqFjJysk5QWRQsh_x5OHbuDJUzyPguDJkLP44PTWfldnjS6
-Jxg_TP0dmsEZ4kTBadM4AiurANsS-BpA-6amHhLSFIwOqbznRQdUUgtjwGq-Fe7sn0RFj49DoAyyeNN3VeXaQ4WVax1qQTUboOgVlJ3EtPS9Ki6O4Y17U46
HZsa3_uXlkYJ1cS9C6YyQjcBZgNXrF6FeBvlG-V7G7q3EZoQMjZxjsuu3RpoGvzO4ePLwiCeS03Im7_pvmqIWx6E_Dn_lvFvIqCRwy3FVVtEzsPiq3h74txk
2pzhW6uudl4pFog-NPOmGjirO6bydF6FUEeZ_NN9TWssNZNbVual1N7WMzB7knjFxFd3ftmh4DyGArtpalXUfJhMyENkI-1BGuWZ7pzU-xMXwQUyzai3YouD
chV69k5BM8wdlzvz9jF7AXqXOC8ZLXxbxDbhNSTh_has5BJFnd_bvTx740jVydoBfigBVygBd-d2iGER4ixA7tZakouXTLtxrqjH_0al-ZnM_BRvnh_zCxxv
Fp-6PkKVU4ZqylcKlwGZ5FJcPqxY3uil-iBPpA43V-IF1HsneYj_u1Trn9_umzr3NquOVSsBlXgAeo-ywEkXDFYDXxuZDd_wUtN4Ax_ntcnDUFlRTHaq_Fsw
31g-wFjZYo_w__a_Vm
}

