sprite $Vista_client_Sm [96x124/16z] {
xTW9agiw38LXMvObcQxiVxlFGHo8OrDf4kVD_vq7laCrcSDN-h__ew_gCUVynOMKr-AtVCeUXt_YGceMqdIVsSs4XUd-TnUO-mMQxdF-qW9ycDCNmEzcvEp5
wRv8iy3J_0p_QI7DyJE3tnTeri9s-cO27mjvoiAgvx8iYucdjMQ1Fl6TMDOC_iG5-9x1DzCuPG4-CjryBAIynl53tzG7Yi4ta_2uyA4VoB3WVBUGFlF3my9U
-MG1lhXVIyyBfPJyiC1l-2BkUwaq2-NUgaPc2fUhUjvyn5ZO_MNXWE8rN-x1HxnWeRXVItuwQl4J7-N5Wr_ZkfjraX-Y70lBL1-HBcYoZyXwt-RvM6ZzCiT7
wSj-Q7pzhf_VzFMRljQ-vwjUygtyq_tbYxx-9trJguUNz0lVBljcbRSLC7hjbyk-MgqiM7Zf_rpqjnOilF2Nwtwxe76sZyhYIPpe1nuiv2a-ogE5eM_mhnMr
7oWyyWlyYz7XbtQXzIiF__82-6F1qWmV9V0rc4OpV9JBte9iYeyKV1_ysti--LkJQE17VddNZyURApBm8__d7J_onXFX7TA9lxpZfmmURzHvYW_TMtaHoUln
CibFp1bVdInUzWizzc_LZvekwBuGGf8z3ZKgvxx-Pe6uvZod40HfpHVE_TSBbExn5avVaVc5Rltb1puMNkY94todFRld2pBqKJhLaI-a45hTYw6cO_zy8OB6
mE6RMfFYJLxhYuhkKJUGdhlxDgYK8hWfhNxbRw7wFW2_xvclFlUwn-i1EFzydvDxAaETQB2GA0JfyEQZ3Qv-IS5v3FYVjV6PQN0LOeWD3jsZi4TPfBsZbyPF
N8ku5Hs5G8tjEYeHUatoerxAy_cF5_3y2BpD24yJMTRlSN--Mtf__oIDcakGjBSznhbl2tGyNo-jdvmVBCHGIpBGDQuwSfrmBaz-HYAflIaH-IBRSbGaHJyC
-Ot6m9_vKiF24GNVG16N5N6enUQ5XerysUhl3fk98gLy5EwfWJ_r1QalnDH6-8q_GNZRPRM6__dfVJbItHPSHB3n3BVhoPxvrcVeEt-smFVlcDXqifvl_IGz
RsOI-mNtlUINjUCxduTyBGSiz1C9RtGQ_gMly3qUFpj0ro5_xcl3do_uPTKXt_jfpEDW_pe_wxJ_lvRtIdWiEjxnEDZ1HptYlmtvsmq-8XdgEDYs1UXPnsUF
t6zApxmaEGx6mdPPJtYS_Ms9eO-RazSx9mz7QyI9T7pPU4HXM1JWnsrVmDV4B-ihFeNJI6sF-i_yKmWl-VpoJJKIB4Zdz_nh7R7jH-yBslXZ7lhh10SV2thu
fxnU-EIXx4Vx0iCVygvVATbnjDO5Wp_YeL-AsqySu0zvY-6DP6bol-UXNu-izpiU-bjHxxTyWVvktFdWeN-Qjlx15mfJYlRWWuS-9IgxNxPIc1gtVWxJ4_ZG
fsVkGvyVLH_wFx__-xy_
}

