sprite $Web_server_Sm [96x107/16z] {
xTc7ijku4WHG0jqJuFV___iAGu432QG3UJUxAsm-tOHmjInx-xldTuhW3zNDJF57wRGzYZz4ry3_e0Pgpn_GaFeVrW09-WzgW8Y8dZLeVQvNIcHjK7o5pl3N
Xg_G2oDd3Hm3y5XV6rAtnhiwKlzeO1dV5juQd-bhmw7JlTtpImLmrf3wHlExVkWuhHWN7bs_wvU3nxbUrUp5V-EzuyySEeOk5lpitpyZubqlNS_vl-pN_8oF
J3fLWx_jaoSDuz90Wt_aYyZWohjUHTFV-Nk-JWqrzOc_xujqnpZOr4MN-VTzCxxTLv5b_aFV3TF_mTRvZtrtg-Deql-O_xydVhEuyfDlN-wlyotvBzd_tVbt
_71o_zNyntvR_6N-5_d9__7-p7-Td_nZNnV_OlvTduj_CV-UZsr3GEalyn_u-yiVRF6N-JTzbHeD7xvzcQ-cqU33Np_T-_wGaFx5_6U-cxNTlvmVgNTzRuk_
plUoPKgffVpOvrR4FFtho_cDynitAH7Kx_i8zD9FtevtIH80UDm4hT_nBLPLIp_voV-6eOCz08EFVr5nrH1KD63na_ysnXVYvHFoqYt-7d3bZmOR_Zf_d3o4
dI9wPDTLGH61IZtnRLWYkV_YhQT8To8L5MfcIW3nP-ZDrtvGip_Fb_4sBI8T9D5z2PmanKmWRlWftpvyZ_5KZO9E2f7f1Via0kN23shsaszbNn_fFlV7g7E1
zG34cU-plyp7nAkyGWPTHu6OUVU9Sx-j_dmwLNKfOFUFWkv7KVsXlyulQcj1y54GxkwBIFc-_t4vOxwOsU6dNifKSFZuzFt2p_as-VhYIoHzTG6Zjwn-OEbx
ppp_hI3v-G544RuIavzy-lDyZlbPaFhx0tHU88qiF_0z_VwlmjzyeWQG3p3xgb2PVJ_rvqzNVIuGbCvdmV1bzq6pz1DBtp-Enzs3DWl-oZS1kN_RbVJzktwD
u_7nDRdpLxuh87s-o-5x7i_X9zzU4mWGe9gYbak_AzhdkwK_-FGzVNiT3_SdftBoovaFnhxo0p-_-6SV4dmqhFVJn_pl-v-_6b0dd-5dPbywGbhtMqq_-VJ7
tq3_UDElGCs2Z-klq_mcr_xyLbAxB-xsMe_FWldxBUTxqyblr_xMVK3TbRlUSyfBHo0xtppzv7S_-TqN0jPBSHJKrD_c-udVhltzRPaYWBihiY23URv1yqrs
Jplns-4ppby8wJmPsihd3zVmDVtamyVyJYkxBmBJO119VV0QYaDidoS_vyS3XKz7tGiooSjB8NttSUqFllj-l3f09IIUw1H_8GhT_P9-yka7tzF_bV09sxL0
Km_-G1ePl6_N_ZJ_TO6wBn2TLuD7R38CciVJKotvz3iVmNv0fYOGLugQcMBIrTyc2jIDPSlWshSolQCArFUO7WSV-kmt0WW_8sts1nzwH3zzCuAY5lZC1wBg
QKUAhhxLVCBm5UPP8A1_y1dPFbCi_VYpeUS32BnD1GhQ1T-sarHF_qqVxrnactrJGZpvAVM43tdt3pqZtPUs541zqMFbUN3rEup5pCFFWj50KRMPRsNxzS1T
kFXcAWI0kO3RdPWRT2tG29cyRxTIt0NYfmL2f5-sUw6xWhwUa0feyzM_NT2CQu4gc5T8j_ifrfpKzGubp-rHf3d1TvzvUVAjxS4ZVFmO2tJmMhRd8NI-Gpnu
I_rPAdNYBV0swSzJAaJLJ46FwTY-FALKW6xAklqzypl_1m
}

