sprite $Web_server [96x116/16z] {
xTc7UgIw4WHWf8vYt_zzxpQelXuq0kC9DzT93fo_MXfsa3yldyd_K-Yhl9WPVLMFqFVqhpKmwAyqaFxDTngWVwS1-jSQIFxcQmrLzkXPGtrVdrHyPFZ2eETh
W5vVr9EVDd3NlRsaH-GferwijHTyOcJQ07rHR_1VqkTha7wTkBVV-nJXYuhKN_09EHHmwgLVv-1_urVeOyEWL_CN_9BsV9DgrzNCtvz_hEXwKJlmA_oN6XYX
helQuAytvOirG5z4THp_hiz29mtG5zRWN_P5i8QZVtpEW7_1dpL0hm9-6FytVXYuJGPTFkMR5ZIaVig_u1iQyZdpGTysGKlgZxmE_Ak-Dydtwc7yZ_ZzRON1
Vy4l_J5voR_lorVzorVtLT_J_tdyFpVzpbpxoQV_vrt_UlptVFcmRuD_oR_ltnd_lgzpVtvpVjgVZ__lvAkATB-bVyd_qeyx9fXl-TlZdIpzqrVt1NzJXBO3
9lmRuz_smV1VM4T_uD_npPKT_kNul_OjRy-l-sluLppyzQuFwAQ_sKPtRFXnYBLGu5_Ud2lEadVzRPWgJxvDVLrwIYcLg9PIhloyEHUsdttlirSY769KXUkb
7z5OXAK_vHijaR0fmYAuakg9RprkN7_mVH-Tm-VmePkg49Kh7qxwJxpqWozjVhJqgqoZZD5mon_7xtj38W7J5jbrsNTAI8HEVV3f3toDuKN2HwHlJFyuYkMk
RuDF6wzH45pVfTtcY9gGc5AP-lw3h_X9iY-0OMV1zdymSRdXZxmlUoiAMEIfGCpSuiCN_DXywJx2pCS2DTVuY4O_-VJdknCv-hKI2YJy-2-T-cltX_5BF3oH
B22gaLp0vej8IT_EV4zVzZdW9r_geK3Wy-3xu0_Zzzy3P07uKWu-6_SRgppxxTGdNAP8uC6Z0Bx4-D51btwTZvy56145M03jlZFLHzylVUrNPK6-Lpxx4lEJ
wDHVuOFlsrDzm-4prV1HCFZ4n6Qu8Fc9ZvjJt2tcKjjvZ7zO0FUzxszsyCslVO-Bt9aYqlapVx-CpTpW-yG7ts_-ucv4n5i1vpCzUVYjnIGIyntzDlEn_Uok
U3SMeXf-cVaQwoMsyEkply9__5fDdoaIO8c4VlJZ0CAa5YZTzFlBE_6VUFOSlp5yK8EFh_Lhc0Z-bjJJbuVnczpor_rFRsmGKdiwdZphew_mav_vlfsdn5re
Q4WUleVVjwVPfGz-cr-s0bDKq9JFkyS7lrtuQ_X2fFiAU6YWvDatN_Rnqqy-VV3mXRY_n4nZm5lR_Jwnm6-NVdpEKI3TvnDUsjnlF_WrV1KcaoxDUUy-zntX
tVUvdr-X_HS0Gcp4mbi6FVbrPUf-7Vprn9T-Tc0IUL21Tnx6QjIhoeMV_7xerxr0fREWeLiIZKdnr8EVsEZZ1bApA13F9sGMg3yIpiHcJ5V-uUT5MXQoo5OG
sJ_6gNCKzcTClUd_-QFzm1936Nmp8LBRSGY8g_fozDTpVzkW49Kuz2nWd_3ZJx5sug_mOuFg3ggF1OEEuEv1mphnmQ-rBu396_oXO1qYosEgZtwElr8V8lpM
ZWLCnEhFV5k6r7RY4wuG-CSLxESHjcC5Bq-XDlZZCisPB0kiHsK_j_cQiMKMVlHdcwZ4FYc82F7muiuRqeUUuLxWFO--CjQFFPr7kW_z4Cs2OG72bBukLx7m
eG_HfiGsAM0IprlpzN1J8h5nXvWCUgFbdLHt9aB1C-zbUJFQX0mxDF1DblTJYHo-7tWhoqTInBA0mNjTFfVA1bu3DoxBXrCgiH29gT1hml_p3m
}

