sprite $Wiki_site [96x94/16z] {
xTZhSkCW38PXIO24VVyNl6WjvnjYCWv3zjY-V_ROHsCPjqdep_STrmzb_6juDFAjrkqZDRyC_CRl4rNrwhvl-hEz_SvhIAssxYVoyhuhUTpvzL_tl_qYdkwx
YPSc_BN-d5_rKedojNHDZbxvLYwzm6GOH-j-ad4yxyzDMFNl1ypxqpkQzr4fkRGmuDgK3rTRPhNMhPKV0yZZRi27V4yeuYM_j9m__TrzRJ4zyZ-NMR-0Tzzv
pQbKzziSevR44DPjIxD-mNBKcc-naTJAIPmtAnp6r7umG1zyPOhuN7yoCysu3RqlBtsKmHT2yl3LJ1CcmFVV5hxnSpbqNxw3dB6Em-Viro1qXFFFrIlmNsGM
V7MvOE5q-4qgXh_b4ZwbwhtbLszpGS-5ms-97XEmTPPZGPNl_1fjuMii7BwNj9lBASK0klL3F_sCXSDlPSnrFWRmlR_znE5t2oz6PvZBtVUF6pzm-Ft2cH3x
9JWVoOo_x_2nyAT4US3V-gx37omSNVWxVp-23wd4mli4_3i-el0Hnsr0BES0MlVF6vtvwTmxJxpgNsuqphqGiScDhtT-b2rkT7VkxTxNUnytMhgJyvRl0_Jw
V0qI5V29tlPrx0yl0lo4hyFzRFkMBtpsKauquNi3dzBp1CvHeac_wCNtCYQ0Rn5bcV6zaOy9FU-NnZD-VSJm-mdWZpj14tuTdqzCI4_yxFuHmKSyvEVzby-l
b2ZJf6_Q1PyqZ_Xf_sd0uFa2NuZyRAOPlpNoSN9wteZANjEKRw_EJzuswNYsvfDkUvLrtsC2ZvTQt2RmXE-DpsV7Xp_rV87l_34FVsR_qSYNWdExwAjTVL7m
USttUfyxdlWDlmvzrFazxuKlB_nItuZ3l_3morQ6FitvUaPFFljpFV8fsvj-EjRa1Gy_ldCm_DdKc8I9zE2Vz-zbemK_4wVa0vpdkc-bzxq5lpIenVwxyuLA
-Q3F9CbZycA2BVk8K_WefG_wWbVWw7C-kyxqotpdVSelyYK9-matJKDVUCddnACtfl2JvXLVA6B5XCxtAuE_43w1W8_tUii-tlfsFdQtxkEjBtnScQpx-8m3
FYR0NubZuV0nuHC-5dxws1tJUbXuFdpqAHuBfrzNKlY_QaAXlx3lVW
}

