sprite $Windows_svr_New_ [96x115/16z] {
xThRbjiw20PW2uI0JFF-hxkDgvhn8DCeQkxst_FfWo1IQzQQxP_a_vJwKPwOkNvKvuzLgEoXp-WVgu2jCN-i0ZPBLc5T7rUeopeGKKigb2MzaEM-0gxfjH8b
5UgYRg5n1TSBlQyd5VweJTixlC59XLCNVST7jqSLg2yDYUWRFgBxiSAfeyWxFknyLi5ruysVrfCANGUMT_m209XKE7MMjtr0kAa0_I_P-Zjl_cm575H0VuXT
sd-Olr3XXzxOVPtoAznKS1sRy_C-qPyASAtWUeljp_YnWkj0RStlR_zh1TS3BmS_sRy9u1M-FsR6xK_t7nzwfj-rF-btGhvNg3JqTSKNvU9wzvrVz_lx7enF
nhFYYtUVZ6VHhtzj_sl9JzjVzocUxehVXdxU_gJFqpul-ldfViJNV-ZdxK_vxKLV5tq9llEBFWS_RN_6DwTI7yy7_7xjhXS_Fzr9lz-yeQM-BlYDMpskWEud
xS_wtR4NSU_hii_2RCWFNyR-hrdV82FCJySpx_FVVLtoArtz5zgVcezTfhWZGrzN_D-hirM--foTxfpFVDnlWRkVj3_jc-Fx_xelB_gcT8cR-_dflkNx-RxG
_dFMxtpty_RVy2NuMVlxpnLXmK-My_Z9S--_8EAY7_dz-r-M_lyduZ_sBK8LZq3PDe3STzxzzBbejcVNyNN_uVwuVS4GgDD-EDspVOe-uRP1xhD4VpnzZ273
8LQ0gw-l-7hZXme0iBalqH-VRejyfM9x2cPwJ2wPFnvF7Oz_0qGypFWQBhpxm_OVj-D72q0vyG9OiQH-R5z6lY7e0SinE4GhP5Jq9VZ9Tcu5Gym7ypiV_C1d
svdu5odtTSBlundxyNHljxFsyOVGTr-37zhFjdFimwqVsfyVVxNjj5nvzsFxOXxh7gRJJyVJVNtDxxP5LIbkPnnFxb_vm_ImieydzJNuuyUwJRM97ZU8BoKW
hGJfU2pglFkZqsLIavz7lkpE3OGb6K_cn-cxlVz0_UQm8mYl-O_SV_xQSzuSuBmv2CE8hrWIF_3c_xWvM0NSI5WfyCo8suHlesb10Ieaie5SAx3QPe7xdGh-
fVqdnZGKQVtZ4cKYukCdLIf2IVqudiV89n42i0fGTvpxwQZITgRpqNVUniEH9seYOBWrM-1t49ggv7vi_rd7uv5YUBdS72JqRrJkDunfLQG1-gnTh6KxKwCV
7kjF6FbDn9Vr3AagNWhI8_EbREqB1ZpkVi4pVVmegWBRDItwdHVhJ7de7-C9KLM2UCqT-WgRvObtsnbz6pUMBOOl_ZTzy_67xSGG6mzkenIv-3v4KRZRpcmy
CKLzFh2T-KgsCyItSnHGywyB0AFnL1iFnlXstiJawr_esqaimXIsCuwVOPkACjZPgt0J6s2TtyxSVtmfkK2FHxtTJXfkPvvM_xmzonu0g0-b6iQJRMSUW1yT
0UNRkHuORsUrxGIYigs6TZ_mm3P-f0hBVci5fOss4xUAopoqOiSWuejb9owarljwVfzuWSfoXgkL2VnI2bZdrMGBhEZvPw_iYLlp7m
}

