sprite $Windows_router [96x109/16z] {
xTZTbhCw20RW024XplJ-RtStc9QFXTXnZNEstvFviJuWZLfRRiZ_8OQ_rFipVrO1f_vd5R1r2yCVwlTNm3RpLnM0coPMk5Mt2lPd_RLUUVbMWQupkJxJNEfj
FDNA72fGAHXJD7YGN9_XK05BgStY3wgsaEC2g7geaFXa-qN_L8yLek_FXFhHHoAgMGNr-T_KueFiWa7Nn0g6LS-7dFX0bbYXGWa-X_EXfZxWCsc5gMk8JmO4
zMG-g25Br56NhW-4fM4ntoeGXWguMkzaVa1EDnNujm9Px4NOUlGrj0l-eD0Vs_ez7iDRR-hhVcvCoy5Ga9pFNDsKlCxAgqy4hwLiSGUDx_NeV6wkWjVDjxrZ
ZBUORzSgGBlw0JERluTHwvxoqLVZNS4sxBxT5L76uAm0bCEeeeXGiH2pjRyEWCUCQ0Fv5J_tvLs1AckKryZShlwswQjoFlTNSrHVlFcTa6NdDpxmuMV-w7fA
H7z_mwtz-ExcVWi-k_7O-i4-1cPBzAflxUjRlpUeWy0Fwny8eY-7VZT_xH_uK03ft3VU_7Nz2LTBm5ej16lxZtpZXLuiWlFyvTEsc_zsp3S--l7wVBW5h_ZY
_OZWPT_6OpxxL0XtTyjdlta_4BMuKEgtn3VU_C1RyBC_pEVsmGyFIfJuJwO2jToNbny-tbh2Lk_FyYtw_THlx9u5KtzchYUeilpO_b0_X4BpqL-IlbQStxsV
tnEHGehtrM5wzz-yFqOhrsE-EZR_sFuOTACVsfyH_MFFm6i-BoVwylQtPxuqtz_VTCcd0hNlZFdzFb_N3lMtdxM_BVwQhvH-46xcv-rVztTf7eG4t_ZV-J9Z
_Nze_t75Tuq6FxI_2HEMd-SjZU1By0S7-fg_gP-DXyiAhlpKbyJtxO-56sibhlZdxMi04170gftwalb--WUV3wT-Ni0axyVsXyEj1C55_tGy5C9GJYfuoNo9
uybyF7mNu88_-Isx5xAjgeE5PPBtG_izQv-Mlfx2m9yO2aK_Ndee7u_-Mqqm6a5_bSGFbvvqFF1w7aEmuIEkYiQRVzI-d8x7LkkCVNhn_cR-jV4WXLIYalZv
U20VV_JH_E7yA-EfTOq_-f3xiNqkCvoCFnzFCTxyq7vsykRZOSBWRxa_0XzMP-wFuNqv6KyVUteOJno_nlZWX_7qfyiBxfrFnqDb-IFuiVrDkz-RPcv2Y4Yj
y-Vn5y-h7zllQpmiszVZ6MqFiBKv1Jpq8VTz-tRoZcbFlMZJEEbP9X_FP_zBeztpjBy7uRgreng25DC8Wx_blfwyZ_xO6bdskrQLmLVzm_7Get6yirTXy1M8
nn0YEFVZUFgWa8OYTVzWBvM8AiyzMoDhlnXlllt3nlFL3tmMML_8gInwY3p4-DotzdaA3mmySvTP6rwttVts8cFGgJ-6z-Vkl4M_aKX7dDLN041tBnRZpVVZ
6Vgoe_5KaHg-Mgt3pQUqtBVfbmSTZt_TsUtM3Z96SnMXBzvyQt-rGeziFFRtkh6FCIeK5vH3N_KzNOvz3l-kXrycuF2-_ZxiCB_uU3ongkZuOsXut_IprGda
e-DXxri5yvr-jZgF_FI1eBvzfv-lJfysXb19m-g75vojJXzRdHUYgxDlUmQ_nsD-6C-bz3xqkLt3OvCFg_EolpNtwRXjxNHrNWxO5M06KEJIwhmUp5SdqXqL
wXf_N9qezGQV1LauZfyHAztWToo5H9hXBC_ewhmXe3C6Oh4mXPlD3NNq8SQ-xhW_W2jnCly1
}

