sprite $Windows_domain [96x83/16z] {
xP99aiKm24FRZj3zRzoJA-gH7r4Ek__AQuJyUBcH9vFe73z8piRv8CdHkZuRVoZ8pWAJYsYQpvFP95SqoHLeaYj6bzmsnVp9R5fVjCXjKmp-OJIitwKu-0-p
IQvekCsM0c32w94hS9lSO8jYoOs8BiLh_EVhA33NzXf_i-B1DLyHDoj6Clwc7neQdsN4zcrcurLWNsuIiQrOSXyrmBRSYuYnBRT5iUHUPimjkKQ57RbE13RM
jngC3RbEH6pSPiQEOgrlLwZV9W7uFuIwN001ky4etcPWuJP0KIuMVeDPaml0Qw13gig5Lu5dXLcIwmUemAZ8zGDuIe2zFlvWEPubkVKl2lisHUsCfhK-_YMS
Fngbswp_4MovzGJdHfVS3AD0rEJM6qnBRhs10cfowmtWowq7I74czpXms0c-Ogr_M04FI1MFjRuNWBfYa3mMk4oeATPj7YVN0IWg3Z8qVJSW4hdc_ahm5Kjk
8QEWM79B5G9U0ScjHhYAW-H_u-kM5O14RlcJyX_AvGfO3NB5-Vf-0YuAZ6nz6CIrOh05AMOR-luM923doHi
}

