sprite $Windows_server_Sm [96x113/16z] {
xTY5ajum30HWoxPaABp_snOINpPoTMfmyBOC-NPpdlaf_3zV-KeIIU_fKSgVlDL0N4OalgCZJ0_hMKJAFaAFwclAA_UGUF2FDa1d-2X0mssTFs_8Z-XpmqFh
OuO-DzpNAO4t6ZZUrPTyqi1f-uybNz7JwhDz3z2vjNnUNv9JjkzXqmFNTjvVTJHm_aJFjPxtaqwUxY7JzXzBFUz7oDOzG8-b3lw4JvgUZm4wIN7yKmseYEgf
OF3m3oRQ3NbthANi_NxE3sGsG1V57_S9l_jSJwj-oSzWoDQ9vH-_7_QPsMgWlQxvqxv8n45FUXOn_7xItpLGX1uoiy6VzDU5JFPpy5qV10ULoFoPto_vjUwk
eVm9VzAFUtzhe9pPcN_PRqqKpnP_tM-jbULW_VaN_3BvlFV1m_zss1V3T-Q_weE_vplycpxuuxwulkOF-YaUykMQd_0sIldrW0yU_gpZHJpyOlWMx_ju8aK3
dV31stvQha3IwdC8MVlPFbtVJsCI6dZz-gI5LFkT-PQlZqmcNo9UTME_yz2pX67F3rWo-QE16FlTqvtzX9VQwaB6cQmD6ViDN_7VX-yKO7yfQqFSV8ktVJJC
1V1NHNBrVCrlFerVveBX9_ZxypLusySBJ9eAPFCppxuSyS6EXZWLvBz_j_n2Si1NFFm57Gq91SDFwo-1f3Ru1k_x8d5gWByz4lc-vk4FRMl8em1-6Gsnm9zv
tvSrj6ja7lxkqJGwVdTy6IcwOVZ34GePll7G0rxxilbuaPms7qxxu_JXJ_DzNqhlTPkKjuO4VoYsR_4_Dbz4Ql-Jjbqo6hBZA_w8Fnh69IcC7FCrR_hIbePQ
rYigARzE_l_dppw5F1h65OMUyzjVFtmqj0OAVdDyWxTytT1x_V0n4pxumpuQ-WdVvdz--77rmmWQu5VJz-TZFtpTeFtc-DtVNyhmaGOVpkHN-3El_EBwsVSR
V3t_g9yqF_icVyglbW_-hfyjdzs7deMV_KBU_ZRjT-URVkz2vdur7_lzqvtyshfkwDflZc_msgz_CneA7VJz-OPVrJrelpc-nQlzWMJu3Gsct-5xyx4V3TeG
Kdvp_6xjXuy686lWDs-_mSDt6k2taTdtJnV-t33l1p_v_lnErcSbYlVzvlaz1ZEn7FFzXvwU83eDsk_AT-Rt3CrfkEX_KxhNuFis_usX-0tmmSEtvy-wt-3x
ceT-fc7dT-tFyw6V2HtsePzEgk3XWuT-DTdreL-FjDa7NoZS3nNRxz1l9XRjGtyggId_IHsls-6N69uFV_WbXLT2UV5pU3zV-Sfl
}

