sprite $Windows_server [96x112/16z] {
xTY7TlCg40HWSu1b8UNzt_OMhC5xjS9Z5Fds_NlHDoD1o55kVyxyF_6jUf1ISdYZtkSz2I5t_5q9MGGw4gxLHTwMaEGnroUad86xU_Yv7dCViND90dICuKr0
l4Rtzt21dfBL_Jsad-bzvWdGHK_e8M5oEWp0kcQjUbP7mduUUbIjotw8CQRuB24C7VwQxWBIWHwqyuj-nCpk8MvwKU8J_VWUujWqkkn3dqSClPG7t_HKVOpN
Sm7lVRwuVdQwb6BhSvydnA574TdLVz47SPY0VyB11dx5JzabEDtxxMNVRhyZFJj-pK_zP06tqs-vyxx-Kl-E19CGXcvzFUtVhuSwai2x-kTyHGBqgT_E-Vf8
2Fa9VzwljNGzvSpgVvppQyIcslbwfP_fu_buqSyJdzR_gETzKd_LbmKV_7f_zRxZrttmpYVrd_afhlgwuATIYaJYaytfVFSsA87ufFwX7v9v2ydmnVcall6T
RW9ANFN1zsbxVLm3F-_zUkmhyQ7l0wHJ8Z4wdzUtVjWVYBQ_I5ztvvFwdyCFCQNa4k2BR9_Tqrte_gI-zr7V1rXVxk_aKObl-UvZZkx0-jk7N8Bl-BaVaE03
u8CHrtzIt_ef8i45x7sjyFdgFloKyCfg0eXFZXxhTpEvVGg__ohWZS_gm-_YSG9yRF_Xp-jxV_y661y1y7jsAiG7F_5510a8W5-sxI_mwURqllG9I1W-dFvL
aLmRV5eVVZP-AKX8y8sJWy0dgzldu-5BCOTE60TgwbJfFfJkaytfV6rDPKXvsqftlmo_Ulz9_Qy_-gqfe94GXw_Ujpptesm9gYQ1-xw-zqLg2xTRRgtLSO56
ufFL_Hg-RFwM06bBG4ymyDdgUjyaTB-rtzzLTlNXq_ex_zO72PjVvxwlptqar1xH7huwdwtkrzJ7FRHdFZbwUi3tvWjyEs9zTJxVdDOlnVdH-U3XJ-k3_u9V
3lnaVFK-tvpeptqzzEVrqT_wZVlL-cnpNk2prTtv-HM_mQUh2nzTsYuX3n-Eyrdzxy_Dl_z7ay1zNl_B-Yw1-dnrXo-gBi7vu9q_v-7VeldVI22-hlX8W56p
ywlpoUh2nuHoDv0WoxxbJN-J01y3t_3msT4pV3iH5t2VFNtuFg4v7xppAtayORWsmVlWZSzNzpE2d2N0hyJtZmSwII3-lFvN1aKIhD-SFwaFdIGGVxeveVC4
-E2Dx-jl8qRW2K_ywdody_cTgXFVhIxqnG7_r8T-OWIyzTtgGZypnVkx-aHd4tJlL-iN2l24wdpmUhjaOZtqDLoY8m7-naE_Ai7uqA-TD7peLq---z3VCA7_
-4VC__Ch
}

