sprite $Windows_router_Sm [96x109/16z] {
xTY7Skig483XxG9Yl__hNb1P2uI8D55k_wV7vtoGzRfCu1_G_o72RwRJPFYBUkctJf39CtnUDtF--HFOIjK9YW_hVeAfpF53kghQfqdXoKYNp7jShqyGU2mK
STrFO02mGmGbL3k40xsa-yvyWZMvwYFBbkxh-LfDz9BFphSd55-h1Af4gx2dbwHx0aBhCpJHm7UzVm82_DGdzjeJ4DQ6y-7XV93hn4Fmf0bX-DYL4mW6Xd2r
r5NW3KwW7Ur-vm2MJunS-OCJFhhPvlEAkTRm203K-3k9EZgRsIJBXc5p2s6gBkLYyzHN9rGwcRbFpItQ2BQmyTLsuav7DVTtqP1la-AR4RIXgYwyVxoW8UJm
Ek_-r9o0ilB5dn1A6cEK_g-0CFOBObXDpQzV8W0ACPSCIaXL01Vy40rNNPnV7YaFeCv-fEE828U-RNwC23aHRQw_ZJ_ps9qFNVIfvmU5DTAp3QBxlhalnGIF
k_cCaB_ns-i7dL4QyluuyJNVQdzxlo7POX52bXBNxqTTFxXVNzzzVt_qDizZ5EdwqxaVtAzoXgIfzQthM-EFFr_k-ywllZRn-SUlulU-VUCJxADpN-tSdqvz
QC9JNyn4Qx-wVjyNgEF1_GK0fUTFUz-sr4gLWMfLjQzGOeiTFvIY-_ka-XGT-6Q2opzptoxu_Yk8ZVqYpUk6xjTyjF9W9vZh_xpsSuAo-TRu0UxN-iMf_EdZ
H_cPF_LyvqicksxwYgILRqS_pNtbNgyNtlC5SZpLVit73t_VDuOIs-_uXTBPPVVzsNN-HtxE-BF_m-kdO73FBtp1B7pygVli9XFmRlf5Shzx_VBW_NJb1twQ
Yx0FuMBLzTFgzwulcqmvH2ezwAVU7qE9hlcXyhlFhe67H9mZGW32-_utusc-cTCbFvxwQUdqo-S5FzH-x_e1vf3Rb03eef_SFniF7NtiFCz48x_treC-dewF
k1VdlKNtdNU_S_ruEXuk8i-hj0Ob1BpW-_LrD7vOD-aJ8hFxeVKxxvmu6Z_wiYuHSGvMtwsUdwhnG6Sys3kLXUdefzK_Njz6u-dxkFFZTpwDntFVhvSp-NWk
-ieC7p-E_F5u2aCzduv-ElXfzMMydJqVOMqAiUFN7-lWuzSfvYQzF1wOuhT-W2MRQH7LQJb26GVZ6VZnE1xCkd19YB9favvkfp4U_UH-Enxq3nQBwVMAMG14
igduEXZ_qFVhHrYIy7g_tmcNJSLo889rV6E6eLzVNw6a4J8VSGcWu8WXSC-d2twgnaFl85_gioP280IBISVZTpzz_Fhw2Khs5guZ50j1GwnFY34mmmtVe9JU
t5RuG40XHbj_KFvRLAQZdrhVnqEGmtVYjcdn0P0jbe8fitzLkkBxUEHjHp_a00W1qBzoQKmfNF1JFPxmbgvlHQTF459A2hlK-QF_bHCelRxwuv7sZwifnx0F
fv4li6udDz4yddMJ_8Wo_eXGXo6rVgg_TDfR--DXZtBCHJA4DeeTt-VOtKujur5kYituFOvxVzMzi-taDZTEJd3Vm1ji9pTP9WB2IRBvbJxQpjvu3CwJugCX
r7sTRMTlF09ty-rinqDSfxwTL_Fjj9YMefoDnxVpRY4woomnsTbs-jhTQzqJoY4HSKWosixx8I4YU4XH1zlvG2YdsqbAyFEqF_wOc08_u5i8PCt-Mumf8Z8z
u6SUa2sOR7WPM4o6y4IK-HoMFLqouvm9F99HvwyHX0WFjOTm3Vxy_W
}

