sprite $Windows_domain_Sm [96x84/16z] {
xPA7LG1124Hzm6x_7Plr6xa36VCl02PT_23-SPUUZxstyBpjQuGEzYqc2t_VePClDH3x0LcvzxWc7J2DVD381zDi4pJomJNR156ve4a7J2CVDFB1DTi4aNpG
R1DCKoveqW6Vah_M4XbuEBys7o1cjhbk45IC_7STJ6nptJDRCUN26nOcqe79Yf6VEh01-Qc3WMsc3dn4FWmP2CuVM8Y1SbCBDf1Ewc10Vkh01-Id3dhRZ8Zq
GR_YX_EnJdwmnZOZKWEhdP0zo2yuy7AvSUO1TEJpuTX1bCk5KpkrmZP9fr12K_xf6NbjctK7hN8BCuf2EhKFLDoGNoYX8h-JaPUs-Pg6WKH-euEyuk1yzu4T
bkiUtlb0GdawxXufZOgHlzpzOmwEvNSTv1KxvviEyehlouL8gIOKo3_bO4N9W24VfWnGBZHAeE9icxqAyeGeTyX1iisEXzm0yhiESWDii-iWhvXjTYta2Mq9
oDyIZFGbX5e_0OK0pdyT_rm1
}

