sprite $Windows_svr_New_Sm [96x113/16z] {
xTg9Skig30PWX8G4JlF-htjHJEJniU3QEBdh-RjldpH2qz9EmxyWluFmLLr46BwcixoIlb8XDlqx5I9hlbKX9cuH2y77T5BvAnLCzolWRHqerVWLEDxMKNc_
mdqz86dy2lY1mMks2gxESLP7bVqAfbCfSLBN-1N8z5pc_8WjTAnWIu-IY_aJkbk1tXnmpbC-6EzKsEcvpFcnLy7q9EBuDoiOHAByX6yv5i2u_o5Z_3KVEXKC
YRpovY-NV2IlWX6GbBVsh_ja-st7iDVl-ud9m5XZvOWttlnbmcVUAjYuCAMzN-RzumycJ2j_EDr9Vry1AIM__Na_vtS584hVy4kXrxjgklmzNvgVFkcpw_kd
-r7VR_-1j_sawRL_tn-tVzrllFdfo_wHpnj_qQ_I2RzyqkykvunFYPCTh_dzzg_wbGy1-OI_JFirkFE7xVzSz3d1Mk5RFaj2VPNCzqzttXTX_IBpX-rVzHl4
c9hljt_NtyvttFvrd-XRlkqdYJhDxtxhcVDvVPbLCR_R_cM_ChI-Phv_klD-gm3czzkVyZLw2br_kUihnM9-ltrzBM7DMT-ebpFszSNFp_DbMua9tpjTpJeU
-_wCEEUxxIywdaTXmXRG2d39NyntbxCmxWC1y9IVTxu__O9UJllbptpnT8u1ubNVNnvoVSMZLm7CDsleB-ZwoXmhWBt3yztJpIwFeMrHtCJs6oYORxpvpdXu
u6DykIqs83ZZswMjF_wsg_l4zYwbzZvuxHUFJwG4jaHeDG0gJcrrpHhxCXYF6_Etziq_dEveEw7dnvxltcazWg6D_vZqFX6pDjzfVxITFJ_qVATzlkv7yutl
-UFjz4A4qFMF_EBo1CFnc5_6lcqdCNDonZFjsxM1aCiMDh-tdPGmcc-y-OVnb5A4x8kboCleRoSZmjilFT_QVtTCB995Nq-5RJmTF_Jzmws74Rai3qrvdIeW
oykFFJ-QRrRVpwK-UzOiQYAzP2NOzvDjvyYtqzLxJ-L_CaBxibS52CpeHX23-MQPls__vrdrHzweg4KKa2BplhLV6ozy_DCt1TOzI0USSauOpSzccRzhl_he
9BBaB05paJrUIYPhV-JRU1wUBvHpPZrd7O1mIYnAvQH-tFna_EPllFhi-ZeT0j0AI99p5avOeruoNJaU-SlZYQwl9BmlEc1xklsLOGlAmM-dkt1y5ezdpZMe
UAo1cgY1K6gmmHOihiyXy9FxuxThYVfDSdmDbPs_wZNbYTtnswwkiNNFCJX9Ux_TBFtjGULp_ENcepCgDGp13Pjldu9FwOx7-mYfJw4JaDNV6f0dzRVJ-u2D
tm-ipooZxOnuJDRjZE5ieBETb3j-gKdXTCRRUKponjFFU3jlZgU_dSIZyJ2SrMqxYKMO9hVJZssdBA_xIIxrPJcndVdA-Cl-btPU7ZIxdRwld2Pgb2mBod0x
2SBvGFjfRe58ItSxsRRpJW37snbZk9dXTaQHcmL0jrEwsoc4ztpA6G9deL_ujfrmTpwIuVrF1MIsv2majfrtag6TCx7a5c7K9BhF8_Z_LsAh_Cd0MYD6r_u3
}

