sprite $Wiring_hub [96x65/16z] {
xTQ7iXiX38LX2IHQtlzzOy7P2NS75tOX_KnDuVl7kDAA_PyBoZlr-9XkqsrMa4qw0XiAJg7lA43VLN1g_AZWb-YsFGNehmh1tzKt5Q1lApY1-L71JUkFwPu2
z4q5w9SAFAVF5vGdzFK59rxaHY6-Bh3tyF_8WjXVkjb2U58O-BAq80DVwb_wFGKH5TLz1UD5Mu5V5FHYGVMOHq5M5FpPjxc51GJW7qVnKhfTEFJ39y7_Mr8G
CnBtFkF_eE2l5g1polcBxpG4qNPtIZSAX_xL5nT2m4zb57Y-q1uyHzDBQRxJO6MjFWK4ebmgcAwvyV299BH5OOhAsW9flc2WfeF_1X-5M6_URaOgdz9CeTV1
mqV1TDoyQxxDuSNwlk2gtlFmZqdd9o51WJyfGEzv-8D22FLc9BL5l1rU51pXlqCtVk1tDwzs09UKtnHyVS5tlEb37m-o1IG5uj0E1IDG6Ebnm8zzOXIYfeSg
nvNgKHZgGpxHU1mIvaYo20foBa1Nw2U-lZ3U5eAnqawU2z1F_3iTXOX3XZAEbjoz7NnxEuruwEyAsGO_SIgsn2Xq-lbr6Q6_csl7KWov928jFmfLZoT-JaUX
hfWl9RT2n3jbn2lDJH8UU68fmjeIJ3habUOd6VUYHOWY_Cf31r-WNoi0EFmp3_rc8Miw-U2XtojWlT_q37rPWQdZeT-VdlsbEWhmT-Wem8U-VA7vq3UCW_a9
-fO2aIo1_kyx
}

