sprite $Wiring_hub_Sm [96x66/16z] {
xTDdmjiW48HXsCA2Sl_x1XXRV0fkAfl-_d7b6TVm9_G_4ayzQaf97NKaZZeI7zrh8KgQ4mVTOI6AAZYN1TPMybc0xhK0tMi1-eSBl5yNKNLROAbvBK1tMo11
FWl4WbmMY6kE2v7vzrb8UnTmBp6Q1aulYFWkI8tmJbmMH7mN1ESbuek-V64zAk72XSaV2tJwxp2_VX4yzue5w5kV0syUvECBqW4jTrzRqdr4PnRqfY_31yfj
cJGbiuIVqew5LUydfInBzn7ZeRujLlst2petTCvbWRyc2JK_YBNmFcd7Wb8_OQNptnRGsmMkVc3hoQu5w15wvU6FeYImRSmG5lYJ1Uw6bfNV-dZqYnzPBMVZ
pnRmD2s3d_qQ9QifArPopV2sNov0bpnu-0_YP3tuATSpzkR7AZYOo-1HU1WRekhNZL9BhxxelawsuL_v-7PppgBLvr9UB0mTFFHRDiHv8RTAyzLAw-5F2T-D
vfod5vzZU9NM8xcOIE50M9X-IdH_vimRz1V5L6fW2QUn41bXJlBClzUnODtNxZFdUXnlcePk3tWBdqPOo5QMwcaJS9X2YuSEVfU-_LLpHPUUhkDvvZNiJN3O
gFefzUlITDtmNSVqWOMbPTBWfSKXsCH3FvGkI8V_XLyVEr42KdJZWuT-icWBklc3Xtu-iX_y0hv0lsu1FdZebqNvxeE7VcLSRZvqXwJ0pnASaket_N__-mu
}

