sprite $Workstation__client_Sm [96x108/16z] {
xTW7kjig50HWOKu1hBV_vTvoZ3M0CCBjjNZI4-cV-OHps_8_oYUVkDDRUL8LUjl8awY5t5CwCNEdmR58Bb0-FQgVY2sxZIGvQf7JOpeHvr3zQ10qFA0JeM83
704l6-YkGoM4wuTqOcc3exvlFL8rEBhLmCyqMEY4XYOuYCSRS18dVhJ1tMp0KQ2XoSHHUpfDD0mU4xi3dqODT70GLZtAXPXiQ1yJjW_sisNKGFsZndRl1liv
t-uF6d3KrEYYxc3_H0DL1r7fEl8PaVa6wA93dvZW_sJSO1TJgHiV9lTRgDk0k48_zgdrLTMZOQ0p-3c_UBD2_OPJuU1DH9ZnGn3u_GRetYyELy_ucb8A1Q-X
RO3kY4i_pFhMSEL_KpHKEc--tk6hDS2l6g0JPn_yb1yN9xa1VWpSwERBG_woDS2FrW3TUFF1J_jRGmpmVqBsBvwklZpkem7yvP_0Pn_yoEV6HyDDNtP-lCT7
GyTd-E0d_608ujGQIXzywyT3Nx2_REZjb-o3F_P5i1-9Ev-vvySZNtZa9_Ws7twOyOsVyvaB7_oXB_E-tEsBpFdK-k37_kH-y4F_yVqCNtzyyC_vgV2bs0_-
vRxgUtofVV3ffRwsVdh2J_2byJ4_wT1NqP0IJ_hQ-dO9ZVoV_5x3GrzsVeIVpebk-AfsIzmQuAVA1nzAFrtySx-1BpeQQZyD_6h-9TJnaO26dW--z1FyTLs3
Qtm2ZuQn7yplp5-ZxtrnglH3qM2tDhwsVe8VVdKd-mOgV3JSyiF5R-Uh-wLqFTUuTsZ0crnhg7tEF7pCXxwslYWxcmV-9njT-k1RNpPz_MldQsxmfH_Zb0_T
XzNudO-lEg8XMXeVVEb7Mg3tzrl4vmRuyT2_wl5ypdftloMW8VPzyF7YXqqtVkJRRPeRvlpWDntpR_WXHmaDxVClhekqEDCf9l2t_L346fpi_79-z4lMZSVy
dX_QiBE6riSEiGl8BiWy_BNnGwWRuazomyw7ldZJc_bTlzP3j1ZYE9Q-yPItLs-N1px6Oxv5SmDyqw-7qvy_zi7R_Mgdo77R3xsPF-t703vT6oYOxnVelVaZ
7pfyIp3LOdhllUAqt_1jWnTSqfa_yB4UFXBzfeF7_2aVzwfdyENhFpH-dq--wsEzn-k-yG_dGqSSWxS4Rt_RzyTyX5urc8wdhsXe_CvyyC71t3TKPuk6mX_E
NzNqOGDyD1J-xTScz46el1qDy6_F5-ZZ1joEXhZv_VbdMQRZmvL7WsPVk_FFD2UZ8LLHILU_Cpz1VxW1VZi_Gh-lGOzyq_rOcM-0Z_a1-aDnCl3F2ltn1cxy
ZLVtd8o6sF45-eiQuAS8_KMX21_wQnkoJykRulDFa_daaq--0G
}

