sprite $Workstation__client [96x109/16z] {
xTO7bkeu48LX52f8CFlVxXmBsRxbiXmQNf_KTt9utwz6f0ViRt-BwP_oMKHo-FIC8o39UnG_qJFHxeCGI9RnJmifKrlSFJmktST3ohdvlX1PtD9zlQq7KbZ_
K-PfbhztrN7MiR3yHshyJe7YNHyREQwtpcq-mPyLKaxsCVhW8cp1tqJYUTyeO297Un72TwuwXSk5yKNaiP-pBGmU9diHzYuIUju_AsHp4I5X0FMndsbOm4IU
hvfuQO1-v1DbK_29dQjcr4Cwz6yNijL9wDZtXL5YPb5d6Vd0C_F5GjZeB1TzPZA5GI9PdUNG9_HPJWiR_SodR7qvBdYTvTWtF8li5XBgVVXBzDZdKWHyqTq2
lDrF_nduiKzjMcjj1UbJvMq1zKJMrv5FYzyAu6yALgVLbwj-Am1l2bRV-dh1p_GkAFXQe00w-7BLJuym5y0lfX1IfXrVh_cFjR3wK0XnVRLmz-MExmgbBxR_
1EybnjVBFXR0hxazXS3dxiibdtdreL0sFfmUVJq_F_gjmBNDdz_wSibd1jyMZ0_7RpxmHpuJ-hRmvcS_t_UR3ZwkR7pacmzy6VfCLttQ-CYF_CRVy_cUpp_s
WV-Ypz_swyW7_di-_vuF_9bVhlZ8ozVyUkQNKr-k-SXFlbxrMNxa8rzrw8l8vDEf3xptguHzNwRV9aNJiP-8hO_yD0uxlhHfdQRH-nNE3xppsyWLH6mX7VZ8
Tz_op-UJmyRlWyB8J-XhypjV5lxvsXG40wKNmA_-_EBy2lwh4lg91mNl9pn-y_tnKVS5LON2m1VZs-ENjnvj8VB2Go4U-DhyxV4rlJbzhNPO2jfyBDHvw0lw
UFokf_9wWI-q57HT_qKZNxqlSTMDBqAn5z370lhY_AQ7Hb1jklNNGY3qoz3Nxi_7vxUUkkvz4JQ5qkTzyJxDPtyk_7_MRrShgHTEVGKVTE3Hxxn2OUpBngV7
h2EFvs_uFCcFjgm7lYu-zVFqb-x--LLD0WjrwulnLxrQ7lrkmoZqWlCxZuybh-yymAFlLkP2qXtVw5Ht-DUnNwOn59pFiTzggU1VF7_fwqXKwozwu5BAY3_s
-sGkeDz_i2ZkOmNviL_MrJeNPFO9zUOx_l3yoEDxReYDxPSYxcFbzSJZZ_rYV2oqTLtBsV7H7_DzcgskS7pdk_EFU5p9g9yV7ttFfq3Wu_DVsyuV_MSolkMb
lJ3BZa-67nxVVX6FWlgq06yiP_xJ7R_4MSP2mT6xGCxtVDqSNq670XSxXiAHt_bv6b0T5sg5dm5zpqD0XlgR0hvYOUnVrx5G-qh_-1FmaKUVGJyg0ByMokmF
NbfFUbnU1hyNm3__kd-_m5fdV_Xr_wD2jRx_kdz_INVzpV5BkkjYOU3Z1yD7YthaQtnyl2ZUnw_xtojOdq7_T86tFkXVAg1Fe7-jGDq7_SkB_K-_jh_zxNy
}

