sprite $Writing_Sm [96x96/16z] {
xTb7UaD120HX0Hg-kV-57PiNzfGZxI2j_bAEZo_VB7BlC8xVdmkMtydukMj61RWBo6w1VZxy6kZdunf8WBy6Wk0hWF4Lm7W545vpZDUCvuUl6SPh1lBc2c2N
lG8Khm37Ay3n2d2y0XYl0C1J0VunvtbVEn-td-yxzSCFF_pmmo_zV1phvjTQJ_qjWh-DvhsNztv--E67pu-V-ktcysqhQmIlBPRFly8FBn_ZDITvKu3YGm7e
mebGWE4jAi3n2Y2tdBW4eCzS520MWGQSuB_-qd66D_J45-yFQAuJ3ysaKzFrIit14wylFicveNo33cmsUmK
}

