sprite $Writing [96x96/16z] {
xTHLGWG130JHqCd8_I-CDwnxhQQGpzVZSVswckQfE7t-RXB3JxEZ_Ngy4v0765-P2mCJm2yE5C1x0BWy-Pi7Yk4zGF4UG7W7ywdc_nF5EuntwBNt0CHx0E8z
WF4Um7WFOBm7ADu33EyUxOjPML__llu0lhxuhty_VvVclz1_7JZwfQx7Dr-lo3VV_B1SyyqVrDjmbtpppO_BNPx__pNF7ptFDpyslyF7U0zWl0T0FkK1X5Tw
0E4ZqmCKxm62LouEA833zm2HaXt8_yJo0IJuwgFw_-47b0yUvODAFdWewzpX1raAvHNtMDTz
}

