sprite $Writer [96x98/16z] {
xTY7ShKw30HWISYL-_xFUq7iEFYqZDlVDxrzgr5E0UXl2ulmEbrKdVTULyskbn-2VFEB_Rmx-HW_219YZ8wxU8mVKwGtuH2lQAD_yUR7c9A-vn5fulcBDp_H
wxZYX-QRpftF_6r1asyw-CFFMUWvmlS2RlEzyHZ_fI_RXeBs_IZu23xBA_vUe4s-cFx5fzSy2Z1-Iw23p_uDNmgaqPTB1v_u7Oy2fTRegOFF-eP7GMj4XKYX
l-O72bYFoA64Im_on8_uQ13xw5IPfl8i5tA3nJcTmcFsqY32BEeiCe67Zt7n68sK1XxXuJkl_BP1HdXYyxptZb6dMlae0D_l--2bQe2E0l0Z_f6l1hFOem1y
h-_Xru-xukrPYb40ljLtjP-I4dGVp1Sh03_1jmPnxkHJePdc-U5wmYo-5IpqHmguuekFzS0NckrZ_6o-q59VQCptrVhX6sy-qm8Vu-yq6YvyyVDKtx_qZP_i
H_Wvmi_xx-23htsivx_9VhhxUP_WaoxsIGf_yx6U6JvnxMVuUP_aawxsmvEFzKpqmHS_xylzgBJAJuSVQLBKUFZP_6aymo_ZHpK_RNDuT_cn-4paY3nDua_V
7RvLN3wowGGUVeo1fF8b91tdxpwdCvc9j-jqMCTv-B7o1GSdEixxLJuE79pthtqSg0_nxkHTxUVJzpx07-4H-F79pph4h_GPzfEVpJSU_YWFFptvUTS1VfqF
llRJvMVu4Vum3p_LFWxU_30Ftp_x1mz_a9URd-Vwu9zz7BoDxWTyyVFTttjyje8G4F2l_DpbRq8eyEUhq4j_w_Lbkmg21JpyTFTj_Sq-RniAm7_mzmvVjb80
_gsVEtms7WNWP_g6ew2EffJllgs_rPVjVG7xsizxiy-VhvAA7_Jb_VH8xNUFp-z7Y3U_yvyhz2cQpCzxu3PUe3Dz4qs77zlqiXscHH6iPb4OmwyAXb-t7U65
F6zCAoFqA-PV_kL_
}

