sprite $no_title_1 [96x97/16z] {
jThHMkiW40JWGdS1qlh-htlCruX3dGmjdEwLglwpm4OLlRnJmJmbZvVrudewoZwWHqzGza6T9wphdqg8O7eqaR2iX_ujwmdsH-S9wxer_Jyb12E6JbZNBUSe
4jRqO7clvOI0unwxpAmImliFK-mprnEqFauOw4dh2sjWZ-gX0x-GmFNeUwqdcD1rmlM513Bke2yaADtCV2a1taJqerOIOlzwRFfrbnSIG2JZ3lfgmYLoNIVu
omdH7p54NqiuDiQX-LtVQpOXGG8i0TgFrwDM4b8uD3pcFi7crv027wDMOMeDg7C_GCBK6b0FnBUeru354hpfLetvPd5s3QZ7MizyTmjJQp3elPxwlbUN85V1
z5BtsgZlFv_nUzI39LYlnrAKppRp4lKQEhtnrFTMRpnoi3F0CpyYJn981FIUoyWFFP-_Iu_h5VIEb_sZdxFzUUIQVcdw_h78Qp-XNmf_850_UFHlfpxon-Tv
UDwb23hXbP_wzX-LCA7NmGUU-yXtVgdvDm5qu5_p4_ThhP1mw2vuxYV6jq-j9QBkIVbE_EJItoistLNxlFyqvEjMTXu7WVAyV-0XWFZ8J_Yez_u6lk2rdtdx
w6FxX9S-wChNxTzF_IpyhVc2b_rdmOC_sfqxxJzZ5UK3F-cNpFZ37_DZlypxT-4Jdlkw_I_f5yxtlkArN_BOrxlpHNt0AO--tfsxy0dFVR4xP_sNNY_8Wwzs
H_YbF0US-NftzkA-u8dF-Bs4JtJY3ziV-vMq3xxWNzoVlljAVJxwPtv8R7AQ0Vwu_LjuzlSA_kCJ7lnp_j0V7FW6luLKogElHx-6xjRDdk_5aEU-cfsowyX7
kEwZ2Hlp-UwWtdRUoOrjvZpt6vzHFynlZDuufyOJd_2tkxFhpd1-s-yu-RsF_556xiBRZaJ-LpC3NFceezJzF4yJOgL-ps-cRlTRyia5TntuDJBTGOS4UX3v
sGU-XA6ETPAGUh_nNBV0QBs5JlpqfgwFsYhws-RDCQMF4-2ecx_vPKxNmnJAmpUkS-kze-wwy3bT7xLuL9SIJ8LF51kcTnwcsQFM-dh2igw7YOxxUiK9VU6e
fRwUO7F09_x_vny
}

