sprite $no_title_0 [96x68/16z] {
h9G7aWCX30IHDCF-_yKNADc8wC3EdRFTZK9jUXq5cOSGfkaeeWOmRqF0L3uchx5haHp0xrFCuKGVBhwtXIl7Nn2w_BfXyWDRzkMhkVaUHCMiJy9j8wNFM4nK
iF-Sw_h4m7oD8KpM2gOGgwN5ggtP_skQqadJoGJhEJ4SNS7_v3RN9lMtndhMYAS-lW1wlbGeem0DNU3qhnJGQd21nd4eIeuKSM74dp3GpnHkg5n_2FHpXJq5
gbv6nAyLkNFiIf1oSlZnrGmrnrN02o1zp5O2t5N5Op43_oF5gohad-_HoZzLHBx6AuKrmQaYnwiQqY0uL9IDHEK7mRcYu4T-Khj9mPHc_2HcToWiZNnLB-5O
yTkEUQL92CCm6CiOfn3kVzoT4hpu6reMtdRqDFKNFRBwDmYUZqdhFboowEksw_J1dpAPGvE5z0QV2NbQuPTITw5zBogyIajPvvSnqC82fotu5uuubct-c9EB
9xJgiWIx54QQyxZFppc5bOH7pWbOILWqf9JFy1-AGes9Nc9Av_afnX06fbDe7aA8CRNo7rBLnxSCeXKiWHy4LGtX0hzcz7ekKK-3JG1tyu7_nl_ol_mllolt
yelbvvg7kDp9Bppd_zu2xfrydkDjJvRGaU_YPzXSIZP8FgJtyBLpOw_O7dH8r_a97j_HCkGYf2lyf5X6M-eM1ZA_Yt_bAyzXml1cu79wh-tyWLqTOtWpzCqM
YvxdgtmMG68eDmi8NB4cHtnXq5g5rs_tRy9huH2CfUYXxTvqBVxv-X1Tas3mbOrtpPOpeMCoLRH9q5AmYgnMeOHN-ItILk1wYrKlaRO2-dh3RV364oQdqMsN
WwzkzsnihhiaVphjX9_J3m
}

