sprite $no_title_3 [96x105/16z] {
hPg9jgCW44Jf5VJ_FtYU9tqCMCY8eSuo-xsThWpobdGV4ZLtKw6KreVDp-XwWtgJnGOolyHaBHvZl8mF-BLBKh-Bhi2JtyTuvVYcB7erqAhjnpP8rzP0i6nu
EyalVFP8DIRRkXea60Qbh5cIudknNmEBgghmJtpbrDQ0CQKV-Ae4guCe_S1N8VX3YF9xlgh0aZ36x_bQZSVt1ddFDwXXMCGytqpXlJfd86Qc6xuT0fFBabJL
7bRDWNMpBZ_2rPACyBLWrTZPbIya9xzw-V6J9mPr7_3vc3RuDyymmVaK3lm1FmnkjySp0qG1F-27mV-ISxP1Wo1G7_9DkLr3FX8rQFoaNuJ0qnpvPismuZaY
nx_DfMIh3T8W2CT7lhRBqFmrU2v_sRBSLAtr-CPH4yxVX3IVAHz16A1ggyuIk_ufyj7mmVy9jgAzwoL_rqDNF_BHK8vi4IEuWaXgfcqCm4T3oJ5-nEElLbIF
N21Ym0U3rVD7ihGdEF3F2FBH4El_Pj-rlKFPy4g6V3Hi3Nxtfe3liVo8h-1Yl_1pKu28Zr-0USMNVKiGzeQ_jGz1ylODAfS9tRtcxwaJpXL_fxfWmzkuyYG_
385l2xPlrS4H3SCCFmp8zwYYgZYkEsE-MiVGvvEt5VFdCaA1j1wVzfqJH4gFd_HIyO6l3O_vYRjygDYiDJpcKvUF5HiOVk5ZnIVVNMdCjqB_vMF50O-bZVZR
hl_ZzojsyxYEEF_AnuhFwNFEbS6sTtoisEs3z_o91E4bF-crudFut1XUyh7Y61uCB_b9hXLxnkXhFbPSyT70UPAF5MkNNtB5c-5ZnTx5bp3Cy-bozMIaHxA-
u6F51louRrRNpVoOZ-SSNUW77Ywq8e_vuug37jUrol2OZnK3FGHWUCR7Yc4x0GV3CpvMV1q-fgyCCi7lLbpEuRS2-6tV2q_mEnNZvk5A-u0F5SSVMQdm1V67
O88F5IUsXWxJ1_817oiEGxxRJV3pOpvM78RWNmMH2Nxy6LnDSdVwY3xYOyKk0yF-JPxYqytd7BKWFlA4ZnMZeQ8t0ftY9uLFfe5XRvBd-6H-Qx20jtd8Hm4Q
o3fy7VCnElZ4B3dmyom_iGqCdA-2EVwyGQVuyuOyoO_8o23big0UVzfWcde6EMvRa_o0ZBvG8Lkre3pWlpReTYv8Nl8JAHYuCGHuG_uYGom8-OiCjkrqBAYa
ccz0UMqWEoOlyNg0Fs_0OsdmDMJ8v7_fDWRFrrK6_7J3UeFwn7hcZoLr67-9GG2lwPU8NwFCwe1VOy1O-Zca0tmiVvq1yQiDY5zlGFnwWwRLOQtel98y_dQv
Vm
}

