sprite $no_title_4 [96x65/16z] {
xPW7jjmW34LL4CBiVy49RZA6u-WR9lt-NkPTz4Pd6epp7wGMn4dH74I2T0blBOX8nE547Wc1YVmYfD11dYInl3E-27ShnA70lPDNYhWhdj8t0liLhIC6wgRp
XS0ZKqJX_jc75KPje0BFLTJnEpCLJNpNCB1HpQsBo-5NK9C_D8K__yNLBHq5DVqFAHe3mkC0eqjBzStnx2a832m6dAeWgC392eGxE55H7Lx81AOOC112WMJF
psep34_121kQp_oSoGm3KrWuKCxNV1l1fw2EWj4YDD_obqKHZ2zFGGWdf4kkyZV1aXWgN8hxGn-KfT2S_xiWfHG9MZRD3Ip03GmffJs-FNyHgAhrs04V_XHK
DQs2N9_VufEkYCti0qcqaFhdBrI26AC8eyE2o28nHbKJzFe_-x7ymhhLr5HzFlwLWkNtpzyK5FMQ7vZPhbCyLYTqydNBp_tzQSxlpzTTu3Z_YtnF_oFdz_Ul
u_ttzxy8nljFFw7_vJFzE_VdW_sdFw1_v-tF_Fst_Pnz-yDx-lJR7uQD-9d-8nn8kp_Z_GiOCd__1QvGMgRU_YI26zBa3-oFG0l5IVb92BgWwFZ-HuO7MCRw
3mW_Wa9yrqyC23wGHRwMByBuufL9JtvWGdZF7bZbsq_mU_EVRm
}

