sprite $no_title_1 [96x138/16z] {
jDOBcgGm20HWI56axt_Y_HgZn4rmtjdtJln1knmYlx9WKFcZfPrXA_qlQlG9RVxRUhDeNPjgr37zLTxQMsyDxsKG4U0NUMZmfs-cyN-_jHGYgfeygIB-QxuF
FlqeOCzDkPFqtZxImnby-XIXr0kPOUCdsc__yzv4scEOSn6FlehC_F2j_WIKyNjSSKJ37dXcChDzkfU-OgGjmwQi_IxIiFAkmh8XkQKD8gqz-JDlmOUFQd_m
wHDHz4FVWa_Vjib9VabpxQ-y5prnvP_JR28wS6Fot7--AaVQslrvggXK2oAsy8xzBVUCpXm7YF31Rw7Fl1UlbukiOSwxhGg0lFE8LjV58csnlVR5PZtwQLfy
MZS-_V9jR_1Hm9El0iTzsbZv6W_pxI5v95-asUwyM-btEmleKO68PrQdkUtJfaMQrGaWr6iJMCQvYTWkRTXkFbZsh12wcJtVm9As_UFHaxMeGCQ5i5ZjupHF
QTlVB81s114TkHugQ1mkxc7MAlqADJSep5rrhG1TBZZ3Ha--J9iIKv9KkprMKCTxlK6rKs_om1z_g8QYBjfvhz3z_a3Z7iFK1WDKQXwGQVRgc4tkwRzkLrAl
5sREhz7QXwV2aSX-nHLWZylWrmKsAX0m7fU3NA9GdGeXedR6rNjSJoSl7n7dwnwDzX05hdFQHA3TfjSlrkm37XLOXgtcoIRYPEVr6Yz-x8mEy5p1rbDXKDRe
yMm8n7_wvQT45XLoxvsVJvsCDxvXxzknI8su6dAnutbE7z_7XnzyqVzHU8JfqZK-ivpJsCxfRZVVtVVzZziLZJ3rsALqV3IdlVQN0eFZaJauoSNFtNS_-CMt
6q_cCpSQq_ToJjzzzrxt7ykZUNBinpgdUPlJvEhN_OyRDC1kVXFHpPnkyNc5RyQDZvslmYjjDesvtPosbdxmlK--sRFliw-sEHMIJpuMtuTlOp_cWy1DZzhG
o-Vgc-7Y5__EgxKeS3zqAfb-yCNpgVnfJfk6zz-fKEtmiVCDLlHlDzyPpx9DnqxJSv0gm-VEjzg_lulqkDlmsZW2gULS4Lny-eQF_DWx7TdcymcP0qBJVqs-
VSe7fWb4ecaxn_HKuSdduWz--40vWGnN188l-t_s0UPnfZXsAj_yj_eFwgp0fO8UO0l_zUJxyETtCILwo-FCL67aJ0kVd_3FhPlZJ7ULqt_zgF_OcN6DzM8y
6XH-sN_mVJ-dhxXQnvYawVFqzL-xzQ7aAWn3OLZ2LfdA-x_jNP19EskZJCpjPtlXc_IVyiAZx-73Aucs2tqxvso-2zF3bZYadlkOqIQnn6CjVA7dCTuyuGT_
y-kteTZq8qHrqvHV_3qxjUlxuPTHvsv-wCpFLq0auPT4Hs5zF_ZcvpjT17sfNT_XylSw7JvxGLzau0jqgDDHstr57_dmxMi2vnbpVKvqDE7RkhgWhqpWrrxd
UluY8hv-pTf1PljnPeMmqoBl-dpugmTF9CRKKfBkTDnNR0D_zVsOOCl6ElXIEvqR-hR6mZ_chkXBmeVRNymV_PqjhZhD5oRnrJLyaTOlz6kdStsVmz-_7du9
9_nafxrt-T7Ny5KDBlziFzzfFxzzzF3hYq-9JeykF_hox1E7NoVwgXP-h0mwdVDrw2_ZZdxenorqxdlVrmS_-F0JdRlSzmc-Z7mjJ6dV1FppJWUMz8D7t-rx
dzhaFTyPEw7eIvEg-MU-H-N2b_1D5zfNpVnZVv-sJfUzqt52E_RrnGyUVUpezX-w_v-yxVkhh-WJiPkEVTMaBwB-uDk6gOastzENNti-q-9kzmwnYfpwgkXR
-ACEHUVEVUtu7dwse-5Ny3Ndywc_ySePV-V3ptTQGC_xuuustnR0Hxx3vHzt6lICF-oeFVczSKNVqEUiZsDvzbs33t_mEWYTwurd-pZqNPx-_g5FHMw-RRxm
-vqUhppueUSxdLjflkA3cSUTowvinu6Uw6XsyQ-pVLowezVxFilNYNwset-4F-xq75z_lgzgr_j-cUypVPRPFWO2V9lbnqgYq_dbEsrCquQ-5Pevha-T1dtM
GodyIbUC9VpATD5OY9JfNzt__G
}

