sprite $no_title_2 [96x164/16z] {
x9LNSiKm30D30FJzRvpUX37uQdemuzzT5akw-QtvptyWV2Yzkp_CKEgd21z6_oX3iTS87q3_80EbrfwXhaH_mAi_n00zvmDwCFhLUu0a5-Xg1aYUR3YTJYa8
MXStKAIee721S3hz8H8LqhgOJf5YWBy9JgQ3V8iuzy3Jr-eH0rr6hpg7ddjWBNHjE94-JscjbhrjE4ZF1XV0w7s0Nm10C4QCTFG3Vk8Ndl59eQTlbwvU-8d-
ffY7XDrNUOlymX8YACJ7f7VJ-4vtGOZzD7gZx_DXiJsCT4Yz231MxmhY45tgK7yqv2dPMjTRT0lysK0aEYKhF_FdAI7J9Jd_906V3GWFfvMV-BE1AADJhvdu
nJh2OFGYIT7Bt-Sp6pBToX_v4iSfkTukqhlsp7EzRHW8WY9H_VuFd1uUFE1gWVHY_5P6y-qTLw13V2D_xiA7fCUF3-rBUSAV-z3GXztCm9ClVYsEcNwSOPzK
-bNmv-kTe3Dzwejyn0KIWJ4UfZFd0v4aw1SS_4bVyClryva47lfgEvK_2bpGfRxqZu_61yj9EgujIh_TyeclhPNhCXdyI4VhL-D_QHnV-MV4e_EftZ_VyaSy
_0NUv0F-HxoVRebqTlYShgyUpS-6lrOzs_wWc-hvhlnzzKW-rmV-hdgyly_7LqyJV7nM-Nlzwlqh_RUgn_k7YV3FNh-VxWRSPd-x_E7VZJ_ujdg8l_Kl8d-X
Bwf7yxFmDzK3VSbFIV2NjpFmD_pZUhSddtHJFO9__VN0-RlgQLtwVpmfFWj_j_pF-N7rJ7lvqFwUNt8PlW7-APthrTDl-Q___dSKuM-QK_BvDy03_dYuZBxm
7xzXu1lzyDVyCcxRns_88v_w7a_-7AVWg-gn_a_vfxdra3xpZRyfVfVFn_ZJuqY17_bRrIFufNn6tVdFyUlgqNpK3_YkUZm_NSDm-HHPFHV_PUOFzPE5F_dp
iolvg9yClfkkv-E_81BuU7Q5lkN7Q-FCzzCDlEP_-OOJVCHZyFI7KZbJ9J-hxMbh_bG2tqmNTCDls4_ec-fPzIVVBsVelwGRVXt_3Vc-UkAeVBZG9_XcEPr_
4Vwe1XTFb_bKmpVFhk5Nha-_-6lLe_E14_nTzJ1ziVyL-S1_TRhAlqf_dRvAXtonqU2RwWbzyi_NwN1_Tgf7-DSn7lfdNps8PyzVwaiy_GCl_DLuYLV-jK0V
_glBAVoX3tzNFTw_tiNV9tzVFSA_6l_TwTAVUEQ_hg_zETqU_dwwt--_iZoIx_tNgyVdGt_4W_Gt_TliVtib5_g6tqJ-PhhhVFep7xSyci-fXV-QlkKpdV1V
klLuFkE1ltzsr_txwE_YyVa0p_otqlTyxi_ISbf-m_Q4VyaUl-JVblpRVZwX7_3mzxUUoRyyvdnuu6zkFQ2JtsR_3d_pimuw-TnDxJ_X9Jtu7_6rYVpzyfDE
VeC_zcUrUkhnK7oETdn_zDL3-imd7VDrBroaau-3vzU_SBKJIEVVX_nDSu8k_26F_0LUqNq-o5zNJqk02Jvs7_aZVKEt_XtvJ_4qI-S3FCAP_ym7tPyqqZlp
9rxJzSdqZ_ndVKtNvoZNxYD_ubisA3C6v8zdrz3j9lN87tn3Nnqqyn_n-R04F-Z87_nYwUk3fh-XRm-Q_fQ-lqh1j_JzamP-EHy_uUGlVD3_ZFDstixRUGy
}

