sprite $no_title_6 [96x136/16z] {
xPYB3jos4aDNCnhb_x_utdQh4Ei3K3PMLT_6UuqSSaYFbEJrJtYY7SNN67LG8SQlJntZz_7Rqy_nV_nuA-Gv_bI8O_ofKEqKNmgd-0gfd-Ehw5Dy5NsChw8F
yQNG3_5Pz3vV0aTgo74HW4BxVSvFFqBjyqTVAlHjVkOX1V6dWgqXTlaHMIk5Qfl-urPXcn_HnqgXR_DRh6l8R_aIk5E8FNwqrcA_QE___UJkHfDF0Igmw6t-
g-qKJNvFyINmQhLVjFWSuFrcisZFby9c3U8p85cx2Qb_ovT2vbODuakWnIU_vTsXDDeJVayMt2O_moYOeZsV0Obl55mDdf-M7pSrv9hF0HHGIub-KRJXox_u
K-5X3PwVtB1s5Rqf-XbV0Ks-1k3Tu3UQV0cmu0PHA9YYFPy2BIbWQh15U_whYNzTxFPutyGtNv3uE5flRf_o_0J8dTpFQY2V0LtuL7XsDuZFWEXVUFpBn2Zq
1_pfdxzAOdbaXFYZEWk8YO--720NvsfT-6R5hloW_xGAOumLNwJ9nmeqyTtzfeiDV7n1eH-T_pHtmnZvmIyJ4FWGq0iglFbT_B81YP-6h_kD8Nb-NlWOG0M0
tr03-6Nvgm4kBwQ2zS-0mESN13xk1l3j0D4PaFKF1UQpukDN2IG5TFiu_mmeg2h_pV3dtG2-sG3m6L1UxU1-y_uJ_jqXcfXCWqM1xmBAYohzNrvWzJxFX_6K
3z3gy1WZa0zHBSGtAm1bqS5t0yY_EKJ1N_klNkJBlyd1yBr_eiZdX-8c0ry36BuPW7plttv1uDEdJSxuXzMtVyI6_Fq0zS7t1MIj0kg-0FPh0W8V0pY-oxyC
tmtWTyFvPm6f7uaXV-NV1zGB1USp_-qbVXkBW7en8FBT6IJ-Qom2wleL1NW-_R_A2C0_3j4r_zD_pe0CVz6mUG7_hox_N67F3yDlvAi1vKE-_u9w-Tt-v3SR
KA_L0AZ6vAE81WEQV3i0NbZ_-ez210J_yFcChoSA0kBRW5Q71_ZwKAy1zR4A22-q6k13WVooPuJUMFzyMl-f8Fxm0LMP1iXdqVNp3_In2iW8B_Wwi7kV_490
u3_mxsgO_aULuKJvW3nV-rOz4_dZ43NDj03Vrf0rHWsx0fhikN_k6_81tpL3lg_XBU6-82b_mvU27w3Uoj_ojMzsWB83tFDvi39e-kSNHBv_GWBaABel_VDW
PK2hm-yvN_TRaLD32bjyxHiuMkvjllRj4j0OPGVm_FiQm4S1N_gNWZY1vTlqhtsh2L8-6E1xlegUV1Mmp-VzDld2x_DPGxg_UESUN_TR3XImpUUn9u6g7RxV
js5MO9Eleh41ktn_lstwz_jclY3mTukUTCVVh-6OVzK0WGs-kz-EyNNi7UFhVfE0uM_NS8ulXMDytM-d-2hw75_7tcXdyAhXTV29UEB-l-V_
}

