sprite $no_title_0 [96x81/16z] {
xTK7Sjj038LXb0VivFuNpe2x54XO56jw_bJRcWzRL6Y__udvpOnfE_C70ct5_aYVbjzkvovF-A38MwD8MdEDlBdZp_V_-oQHjoOHMdD4k_xT7lUzzDb7JMei
t2EcTvtrzQilhm5ysrTHgN7kuBwlTGABBBPmsvSoeDu1Fx5-tRdcEtw4AJEVQWrITl2yNvv6btryyLltWPfSyA58VkMtB-6A7-jFVlZszXL15_n82vy-PnVE
FxF8Yz-RUURBlY9rRokVonFrulhTavzzBvdfVRzj-12YsC5pViQI1D_oErxzpkjmtUII7_YsRzDt-mxej6-jL7rfaTD8tM_xQdEOVL0aYBtwFLy5xHM7xn84
wtnJEEZNT2IwF9_NqZEvvaDH1Z0bdZM_uDSjfAumyzBbzQFhCO0YXlLy5GxxDaAD8ic7-2evwBVtzIE6KAwXJE1Zlit1wkSjJyU0ZGcswzls9ND_fMfCsHg0
NTys9WHBcCvOYGGR4sJNpm7rRCJTc1WMCp2g0tZVD--LVUlqZyH3c0YZkWKxuBUQzhD1VrrP88oD2TZtwoqpaVIpxOyO6ybM0sJFZ-ghojqv-J5hOmkyvzS9
unrJaBvJ3gWJx8FlRmVGrCpCnopl1vX-yjqxqBCUbhxtb4ZVtPqGVVAZZRUUvVB7VPHIt_3x-VaY6uLlIpv6CjOnqG4_KLjTWG5BlvKhq31PTlmom5R--50K
xOSeHAheJQwWwRvV1wGVXBbpI360Oe02sdNpTi2l4zO-oUIp2AODYAhmqBsjV7MtJR_EUVdSro-AZactpBtwv2UAX-VwEVskptmJokIaxtZdioBvR-5deaSR
sqNuCl7TrppMuCE_cazXxGUVot_0z-vZ-8L_nf-MRxEVf_ECtrP-Bl-kZy77-Z7xXG__UkYIJiltxkVfH4xtqkglbkzCjnDlgdZvoJVGCubgyCK7FTV2xxmh
FPikVHDwFfrzCFsW84IWtx7_VGS
}

