sprite $no_title_5 [96x49/16z] {
jTTLjeL044FH96Tb_aD-SjsrQ_zJ1hJe1GuWqIqh1HAjq2tiGFxP0Ve7AT67GXk7n7SaTlyGlOks4ByWq5PlIOdVa5ZWrq8t_aJQeYTeYJyKMfv5zrTeTL_n
0efkGLuZhQwaU9LGT8xYXIuJjF5IQIV3sscqH-C1slECC1f-FwBY8LGIzPWY5O-XIZseeHu4PJp-92KUbCgJg38RdteGk1xKJF-_ol3we-BH3I2DPsYBpbM_
vQsv4mGP3I-QmV3pvpSfRIOELqSjNYAwBSZVcRzXq39y_teY_JW5ZLv1O-VTodLcNHkXVx3Uj7_EkHyP94hq8STI_m5s2F_YT0kj4Fv9T2iIYVM2Nm
}

