sprite $no_title_3 [96x165/16z] {
xTY7ajj030DGYzpY-Fy_E6DbCmUT81YyCjLCRuzOIg8rkLtMkzwLFNvL7ttq-3NzMR_L8VhYhGvr7SllKDVN6SRFTOZMMpzrw3_KOMiDTFSClhuNda2VeQwh
3leClkwVeQx_oXcs9BmyGrslT8YoNkcGbV145nsgUcIsKeS61xVqKeFsOURONklvlq4Q7L2FCS3dEfJJ0VK-m1SwDcXfwtreVmFPEqF0Wzx1bxeuWzQLlqK-
lz1Q3RI-ugEFUWJmz1H4XpSAzBc-lbxWnmO9UkiG7tpKLwKQKhRCanxxCt3XeuujhlLywXleo3C_pfNwIcpdpnxmHNwZGQCwy7B-Bwy3whbqCHyrf9qFIvVv
_SiGUDDW0N_qjuHMeQU4UX8U_80hX1t4a89-iY6F-S4_TDY2rMUT-uFdtqjro8ZJXcqo_iJyhpjiHrt7n_peTvpIXHwBn_omscJ-u-lBnlG0NSQVmVnZXwNZ
hnFYAtzU-cDWXwCU2VbrV3wVzTVYvKTRqmscoBzNyEMNRlph_71_eLw9FsN-LNC4w2I-lBhQnn4Y7yQpLVNZ2_4TVvpo9tzsRR-B_BNuNvk_6x-Ulnw_xgTi
WF6bFupyAlxNyxkhf-uND-VNvYFZEtvNVjRkdlfyxDMpwgxouuggnzS-oQ-VtT5P_9fVZs_FfxOvbtxoWHVpr_5nFBNvfFlI9doHl_pitec_HRlqrNWwyC9_
_dBBLtvwySz-No_dqQhvFR_rtcBzyfDVvrd-tZyw9F6TrIFdq_6_01luzVWd7__wVeX4ttrsnNoEpqhRUV3T-3m_YOD-CVwT-12V-5vywQlyQlLu-Nlh8dyn
FlEVbSttMyd_nn_MpmI_k7fM_G6_xJwi7ypFuilDoVCVryyy-UdTd3J__ygrG_jvFchwc5_veuzrY83v-7SFwd_GnmF_EqGU_MQl7fb_LOkj2v_mEZyFXBuL
7_axyGVtAy-kct-2hrUFdt-CVkMRyP7tvoF68-vEbd_m_FNLSoV-w1U-lthi_9Fu8ZxZqOVqBB-CF-bus7mg-LdyUOZ_07-FB-PZFxkO_t6Spn3vgpV_AJ_4
5xuRVo_Cp-EZNu__G7z0_9e_yEBYrSNyG-UlnZ_bHrlcjnwkFVv3v9_CzpVRQb38pnhegwlcCsb-7T_t_VcW3thPj_XL7xe_7pqUdR_kEzFVUTltNjhmuihv
J3P__wrdpozzbf_7vwld-QNi-wyDYx_mvuNVxF4yz7pc8BuN7tZXJ-4RgwS-dyBgMRZoHNvpzIX_alaKLqyvlnXFBJ_gqjUhv-I7pbzTFTNyjTS6uS-Ippzs
PVuvXEziJkJp1ZxgsjUxWUWm7-5xhyn4z_Bh-FXQjNIi8EcT_A33wcaVCEIV8h-EZ-DVEii_fvo_vBcE-IUa9xwrUXxznYi0LxwU3kWa_np27w_lphu1MCwl
UT1vVX2vhySpGEV-aBwEBtGt_s3vKTSLBtmQd-kyKlgNyKVSt6hA9ppHTMrDp8UCX-gwGzVvqPUwU8vDN-YwOaXVP7ShNldfERe3ztLsl_8glynUxu2-rklL
mBVq-kC0lgVNEoo_tNwdjdqzYko_M-zwrry
}

