sprite $no_title_17 [96x97/16z] {
xTbdZXmn34JXWHZa-r_OEGZLrFDeYSrJlnlVQz3UVFj0U-onI7i-V4J-c3sh_cFZkNGgz7KeD7NXfT3M8wZGrwdGrv-jOFzaACHewCzG09qAVPqBf_gp5HnO
BdXFxnU6_rYpm7g_O1lU_lBTmdY60kZzWkhFLZ2GcmNHQUD91GFGsWKZSPZr2gfdgjyf-4NFMVXc0me7UkK_kL3fEGk_BjpA0kivjxwREnLGZ_o__sDO07tX
nL_U_iw2FX6vy3lV5cN0fush7Yc-5xxRGaJOhd3L8uJVt6VrTmNLNVdz-ujV5LItM7ZqNVcweBhuS-zRmMF1GdZoNQw_pa4NVkyBBxleorF25xxmvOPytiFN
_o8-NEUl4cFHbuSg_k83_q-v_HhnjNy7BpvVX_sQN_tWwv0Vz_XUyUmpBpvVvzXFyVawvCUPdmS-yE8pV-md-igJ7sT-7lZ4gq_yiP_WAyz-dFZy-ke33pxm
uZElllBFuVDrr0SUVE351xxsyrdzcWSVUF259vzvzVDvVU35rty0vkV5d_3wCaEUVUK7_38OUFLhVefU5ofU_LduUUDPpRClP-UD3I--yAfpeU3Lr-lesNbs
u8CE6yAlllBU_QFH17-YplFQN_dkNs0MRF55xnNcna_GZ-Rgozdx6wl_WxU-gMVwvyDXEljpaRlqnnvxx1i
}

