sprite $no_title_5 [96x115/16z] {
xTfRakEy3WDWYm19vT__WazBTC9OhRWT9pvFWvUvVs3HzwfPlfD_4RbKDtUJAtNtgngA_SIpuGBzieQYWL_KaFeL3KpuWWQgckqqVAohxZJm8ntDtcduNDyh
q2LIJkcIzBnXYT3aGptpMuVP2Lz8wbx3kXAn5ZcXSwz1ddNpz_n2ShVWhgkbVqQVDyXuGtANC_gy0Kk4QYVymbbckchowN_MmEVBpjxpCy9P1lsKBtiDPRZi
aZ_i0zcmemT_ofyrf5weltn_qoUpOTJ9vC_xsV3h5_eTduccpgdlf_nOIaOuuS_xGScWptn_rzzGfUlWBz--usldiJF-DRuDVdtRr_IJ_uBFjtp_XdzW_8jy
F-thnDyP_x3Frxx-ttt_sBVqTyQ_oFVplixz-VYV-_FnJ_gbv7hItnl_kD-azg35wEltVA9qzG_Vp_aHQMxwU-EVyUCzbhRZ-qT-9FsTyK_uElYpyQ_nxONF
vRWlmi7VFxh67Fw8_o3jjP_ZQpacfz_7AHZy-VXs7rr4GAgIaFA7hnfNcAx-w_6nj1GXWCvh_rDZsVTLANd-lnfVGmT9WW13xrk3xFWHshwFq056e7UT983o
Xsyl_NmZX194XA6xnhQWdFiw-hFnhG-lsZ667pfQp1q4v8GVu-Udtbq7BIP7GzorjSXhtzAVV-x2p5IL8IB2rLTtSpV86txoN7dJA50bxorPu4vGHb-dVl8M
oozcZm9LrR0b2veFaFAk7zjHouBmsVmiqDNNClNjbH_ReGs-ikcI1RpxUiYtzDllkOy5ZS-21dLVLV7iwuwVuvjdmMFwKhO5Rc3F0J_7jnX_upFuNf2-0Mp5
a3VyFhxxfg3hov85uHDilYjA-blU1pzE7lYcW35W5cnzGsw8ElF7zNXzBj2yLQOFT5-L8CoF-7bqQtKtgdLVO_oPJv1nuyEUFrvRKgkn4UfzUYbpNnqzvbNJ
t_237pTEhPLWDxppfSpzsysCKFTQTtrBN_jwAa36CmII_d1yzVOJm9fV3lhyKPgVzyhkb-JJjn_UOlmgHtn_-8m2TbzAPdFzvlYLwMlouLlwZdvugpOWd2Oc
_-m_ZL_rWE-hxxLw9yBlILs0NB_2mhVmTT-FqnDQgpqAv3dZUWWFt__sVVN1Ng0QFYPwdZqC_bRJJ_w5hxsWSlKnvUaRtm_wQBuINgqfM9FwPlmA3VvcUtxo
phYUmMgTmIGCVkFh6xwP4URTuPoFxVnNmTLd-2EVlaSqtamKS8R4ET_z_mZl_0q7_RP7Qm4L86OuDQR_YK73BmVz6gy-ReHgic0cTXy5Dy0QNvVNFf9th-YF
HtC3jBhs463glkez5T1QLGxw_KPIObC4Qq_y71qtp-6ZeE-mf9zy-Zb-Vr9O543lVhoDctSy-5OGSLKxw3VjyVv0UDqKf1vufZ4zPUwxf_zu_m537mfo-emi
ZyWVVdnQn7hIZmBMbP-Cdv7a1p_q5ck-rR40wZbzfYpRoE3xcgP7fFbUnu9uufXl2spv5SvyB1cD-TEFcB9tr2V-jip2z0SzuWxuf61ztxqD1tSIVVYfPsHU
O3r4VV2wl8pTVIw_mriMfE_1f-_BNgpvNARHLc2J0eAU_Fb8Ar0VDqJOi9opALu9QFe3VvFJTEvek8oPl2-VfmoNCQ5tNPRlXFxmaxzX-Lu4jk5l5_pNE058
qDrOJWd_yZy
}

