sprite $no_title_1 [96x164/16z] {
xTZfLYKn20JWcn30UVy7dZKkNNAhQt1V-AqV5OZfSxnyrlgkxve-NrAFp8pvOleV_gKw38y8fKDVtoLrwElFVmQFG-Npdc4553j3NyVAVORn5DqsnZhuQEiU
8JGW7GITL-uE3TtTGwdEcgVlEjSZUhhMeQElBKiTrd_g0tJUmRiwbg2FSQeRgBI13tW2vmblQorVOWS_QcilckcxX3EWRd2HY2wTmGezSaewFu87wjDZrnHr
VWQxycNBd5pNpb1ysPW_GUL7ADUw-Us3pelh7k3psV0pe3xTW_lOWP_1K7UCN-ztI6UmufKAxkiTIXtZew-lsGQi5NZYAsiez2e--iE6qc723m7FVBFJCrZr
uTHzCxfeNEi27_ZADqXeLtK3NlINpN98rUnu_DelTbXSoKLuwiCT93UhvyEmsTyU7q_jmsLXEe_FysC7lB0yFl7XdPoe2xpikxi_N3Hqv_5hVzdZtx_JWL_0
Aturtd7da_6e-Pc_jF6eleClnk_xMdpcB-8J_gty6-Ox-CiKFzj-8pxwg-yZt_Vr-DJtZfyDFxWVkhyKNn_Fy_kf-qvyBRxeX-wdufjj0tt6w_uVp4X-VJor
lz-oZf-IlyiS_KRymb_ps25aFmKVEw2lnwzzxE2wdvAF7QWVVTztXm1V70_rD_AdWyb-QZuYuClnkU-I3tp73_21R_W6ZuFg8q_V1rDyu7L_Tq1VZazzWyT1
ybFpyVa1NupFVEZWn4TUzztlEXZumFVyvVST3huy7ku_-EVcKFpi-UxJ_86lnLVzhGX-oZxmu9FuFJyqd_0_di7FP_Vr-9NlrEVnWR-XVe2lnyVyVPzFl-U7
F9xATy5NnqFz8BuKd-GdlXY_dr_VRkNxcQzlb_kX-3H-t-VnT_LyFNxfk-1hswtp0my-nETyozSlvqlv_Vp2U4177tZY2_5bF-_yq5_Ebg-_d1qVuZVoUzCl
TE8Z3xuGl-VhyNk-VZcVm-SyzuFusjEZ-ybyFN_V9th3r-9pFmIVtttTJ_GnFkNNfUMpyOFUyldqKKS_cC_Z5phta_WaFkYQBySFS4LVZ1_ZGltWVlBBdw1p
FtMVwxfFukSakE2J-4Jl-u8EFlBWGtnPx_keyvgAZtokYrv6V8nFT59su8bFT5v-nOVuNETx5lojzsfM_e4dkjQ1-wuOlDPrtuTeyFAZh-fwZNZiXwJhQpZu
kgvtUE37x1cyrlQ9_dRrNT_rNRy
}

