sprite $no_title_19 [96x157/16z] {
xTZjagGe44PX4ZAfcFk_uGrqJcoZ-JgrTB7V6VFxEU3Ob5h-9lF_r73RgOznswXJsCF_cONFshQvOAsMCUrheNtIRviA-6DiHm5_Qm6VWd-kWB-hWB-X87mA
DXNgD_rT1VnT1VmD1UqpHHG-v7DEMuZ2ztnlLggRAdpVz-5xknUyVY3WFtttLZOKyC_vNi7iNd1y2ki_quE-5jov_anRB01Jm7VyRnPWAS3ZVxi0Ia7vwmLy
pfoJnryeIBzoBsK-KqNXFP-hfFs8hF2-tsev2zAFu5535xJF9R3SFx1Qaa9xrwUG-85Vewh2iuzKHI3mGnIU_I-KKRZo-1GyAKY_GQLx29zyMT0-anLWyDyi
LErJa3u5_I100LyMuF7VBHW5V558VSPk1Rky7rLyNPXzMM3v-9oSLVdShTQqtpi5TAi5dm9-lWCAmgTW_DrDFdlGldcbW3_p54udhhuV1QlIZw2WV0h3kFe3
uV1NFWNyYMU687nTYDEdK4po-D7nqQU2yYcO2r-itvyAWK_1AC2_jNvT2FofK5txyTLtA548_5i1_jd7cGg5GkvJUCSN9yAnXy7ZYyAl_PRwjPq5wLFm9x-0
ttpUZwhZoqBaFZkGlbCG_d1ReO3l-0y5V8-ZODgFKcmKX6_SYxaV4MUXUCuFFvn2uhjJ43wF15NwlNS__Yj_z_iNFodW1rCfN7Xy2hdl5AJF7fG_fY5wJFwj
W0-V5E3nAMYVtrZjKn0-1UbpB-73tmhcy3U_F_fS9UbJQ4DOyIaCFyJOMLZpAHJjrt8M5dqAviBd_SXyrTS5_4uXzxlqvq9rvNSAQ-iVBeN47nA5jVL7o08-
XU8NVop_nVcV-f0KX4_1NFkeYIyA-7D1-XJm7Pxn-VUburyAaVgSEVZmSw5ytGD-KaXyNg-apw53eUFV2pKo_sV1yE4dttXU4pxl5fbFeJpvFElW9-DMYl2d
5sdXKy0N1U7poUJ1fr2igtaTVazzPmyFVdIkqfCVmgSW_S5IIFdR-gkxA0XV5_2FvT_MpmI5n4TKXTUl_Q5G4BukFFlm5AnDFhmkl1A_NdmALYX8dyAZRxVb
uzTA0Hz755wJttxbDrxLXKzXA1N-vXUhDnu_A9n-puVt5-5JW9zy2hKOVE9pbMOVd4BgKtZsEuNJxr_ywauXKf-2-PFVALnzuqom9dr-85tw0tmTXTD_uNF_
Kn0-7sL2-0EaaFeKfAyFDVop8FseXKBYfmS2_l2O9zygXQilZXnySEdpZSef29_2rQUW_FZf1uNPJmw4FxZ-mASWVTwZwtk-mUDJAFNEuzVZAZNjw-j3uKXB
ltSAYT-l_d3mcMOKu6UV3nhl-UatGlOWV0et_-1_uBDy_7j1-1IaJq3x59HFmOLFGViKfF_gbOBmAGY_KqZzGHvxC1S-1U4FX4BkZq8h54gf5vz2waEMGW4V
VYhaFgDzBrOff3u5Jtsc9Zn-3mhuy4olmn0-1Urt2lZmbuBXvzDkF3w5Kl2JGkBBGh_v53nTVdB_Y8BqUSyrr_x1uyi2FFxzYyQIpvYdFaDXoQVmu5DOzIbe
dyAYJq7vmwAmvbD8_HEZiEXJq3u5N_CfnDMV_s8fBFWK7dtsiEGpSUVnkKg-v3Crj4-X3t_modykm2S-XKMVWlOf55lrARnodyAwJo7pcUzT7mhxV0gxVARr
RJw5VJw5VJw5RJxZcVy3_nEpt_TzFeNDVZ7VwrF0Vy5_j82Flg4mVFGTXV7lRpB_psy
}

