sprite $no_title_6 [96x233/16z] {
xDO7bXin30DGGGIP-vyuPOliuRCr6AGdYrUtVM8fsPxnz-SZ7m7cjqJC2VnuVRucPhna_XJz5TSdwFfglqBYn_3pbhZdoVYnV3IUvCzi_vAVrNxbfxOdap-r
VMQ6p-Eq_RVy03uslByXeVrBODQNslid8BNtJm1IUtz16k-ViCRx2zBvSdpeV9Nbwtp1y5NUzfk-uIrVv7rVvsiO4NdVr_bqV9ozQ6ibXXEPBrZ-LFaQLg3o
CRnCZQ_X9YIUjW-5h-4dplbF6CDFx7b_E--jpjgdftDzfkxRfwlV7WhY1xS7ssDPYBlNzJO0RBpxjjEt4Mlg0pw65pnyC0CFVBRkxevu-3PVlnS2Ba_OMqZe
wE5NgJoyyigg4CT_F7OJLeNA8bJ_sOGkz4jBqNy-8GdS_MP_pyXG_Ju1AKIQW5YPRHFQ16Y-Fu6G_RucUOBkin-ra4gAFabw4qBpWo-n9YZ-ohnyNNdkypvn
vJ9f-o7D2T3EbptITIN4-yyMwQXvvBR-WmczNkpM7XLN-xyepoQW7L1j_0tVUsAj_VYzylq-eIycq_KVJ-Zwnj_nmaq4kVYz7rj_JUWwi_b-_tvf9YduAjyd
p2_jseToxI0CX648Q6M__mFVldEZmSOeY9owKzC-_pczsITI2FFb7rziVhXV6rzTldXyzFtgzvlyvRwwV1dm3T_nwsg_1FZgwXUFZxvVNJxCgnIh_8_cv77v
Cj1l-8xlpFVx9S1NLxyC-8Rl-CwJvpQ-kdmPy0tVyPtvj_39RuE-ZFWc_zJtvj_49p_eYyT7ttVctyGdF-YBnqUaZvluv0TzyVY8zF6TVcrEdZ5VFFsm_Zxb
m_PRVmlqRR-wV77qDoTFwwTSXlDx_aQ_tSUShutV-nV4uJSd3_rc7uvywvFl-ob_nSU8ppMysz-xVXxCjpxvQp-vVVXzcV3tAH-jR_Yxy6N2twTy7Flar_lx
T_XRpJrVdBuzUTJWFX-NFl55FlMUBqxVFEoPyd7bvuN-O7uIhqyUEStvwFdA-3K-uoFytwLYVCPF-VPZC-MJBpa5-coLVpw_4UppJJIZJ_ZWJi42hr_gk9y5
wlJhdyUaGtwkWD__z0rq_Ge4-oMRDzRY_Lfuql37Ek6ZzMlDvlbTl5zhBY9hV3wEZ_4nuEiw7ujy2V8nuEjZ-OQVz747lgxpCUdZn9SdylNhFYvyBFBbstpo
smFvXdzmd_mA7ujyUG1VndpoAtnq_RTl-7WVZ--JVqGVrjyVqIVlzt7bOyuNfxzx-zVwkEmtlDy_xbVwJNwCZo0VnxuUzMznlkrdVdn_U_BuV9pvMEghwISV
w8C-fdnu_Jt8rwM-cdxoVX_7llxlR_8ZVEXINw48yJ5q-f0FzFN4tqDyHO2VCldMD_tantskoA6l2F1v15V_JdzyjV5L4UYdNFlzvAtlEuBjrp2Vwvs_xScZ
USPNXNPywZFznZSdZz6zAzGRd_byPtdc27hQJtrcjUqdNrF8gkrdlkGKj5nR7zH3biNur8EFG1ybBLZ-nrAFNquliVVUU-yd
}

