sprite $no_title_15 [96x95/16z] {
xPX9jgim34HHw_pzR_Zp41G-72D3CBFSoMjpPQgKTXh03rRdr-Ga_eUyOnVVC1fl9w_GwOWOl-SdzLByBRzOMR0t_ApknSk23FCBzcab9l0GlwrsCGymmGVu
XP0Bm01xw5TUSp5lyQG2SXDKUaPn_du0ZfuoFI7aAVRWeTF-y9mlAo2s3S_vgWAs6XzTWTg1mHMOtHeWTnUJ381H5PXJv7zaI0My_hTQW-SLo7QrP4qULc0-
GzZG1aygO5mfDnFA9z2bR7JvJXa9DVYk0aECEeCTQl551UneLXUMHyzJxbOWY90r-3kDdNEl0aFqh2jHGSBr2dYFJpH01HaNAv1Zz85fB6d2bGh83j73Rv5G
IhS2teDZqGgRYOHIEXL85Jtqy6D9Cz8AkDBBKMycg20Zgq3NPfjwLD0Xgy2MPgNbHmLzsXM0KpsMj4U-fD8ejv5GIlLgFl53doIKJ32UMhIE3x2aNHJsr6zW
NrAzOAVfZ4GV5N1tWC1-r--sFZObTfvIChsvw_elkLqizVFPyMTaU-m-BrMyUEgF31IXr7udF7etOoSfCpr_LQD_FiLtlTjUabLmsBMKQ_w96FwPuk57GW62
mOST5_qn0VuO4KH2AvMTpJVznth-G1S_A3528huLsKgTAK_yk0QjzfW9zah_p2-HDUmKzc5-ZRZtKe_wvtwkFcG2k_wZgP_wVgpCJhdiL-xwjvUCBNtVRyez
luf1Vzy_mxdV4dtFRm4dVbiuq-T-ssdv2_p-lh-j_oU9tt9_2N-Y7-Jty-DdVilz1Vw6_hc_m9_eCxzTysVftF9xuc_ektwIWxxjzvs6_X_ddqVs_KawuKzX
wC_yQJeU-Wo-wuV-utJvSrLF_6tzns3lmkT-EKb7frkmtl4NcMv3ckLJwpsnPt1fdV-eTvw-XhtZBqRJ8yWQVkXr6e2M4xzCWv1I-qEFKWTDW7_HezHXiC6F
KiT26dw5VJJ4--ldz_dnupy
}

