sprite $no_title_2 [96x123/16z] {
xTc7agGm30HGb2pl_t_m1HLtNRE0PM6ekAem-NKJ9ssFpS_Ggxgw6xsenxoKeAsvlvOWBGO9p-kl9J3qPnEWlvR0Pd2VIu1kDaom1Pq27oIiwMes3cYqgWyJ
U7ych-cOKzsQb7bHLHicC4uQy0kw3XC4UiM7FamGd3JWL_HXWkAmBlkinxdGiIrSAleu0GUUjQ9F0AyI23fyN-gF0EZWuIyd_D_XxTFtEP-m_unqCV0bdsMG
8D3l-tAL8DWbCU2dVIIGdEXwuCk-wfw0dHKxxwdlHJ_w8W5fyC5N_Uzh16iB_9gFXF7P6lmjNurnn0tukW-Bztj7li_wa635cX_mx_k-x0_u1TzgVf_pTU3R
cU_hVbB_JHzyrJVu0xxgQztV-Qul-AY_qZ-lN-zlCpxuktuB_vH_tmTVyMaZEVW7_hulSKKBVY_v-yS7af32Jquz9H-V1Ed2Rm_uPa9RueEl-m71F_2BFgZS
xmLV1lwWVct_v8DlJ_eK-sRcWo-l7uuaWv_KhszVeRZU1Zxu6zlNB1O2_S4_uWSbqdA_t_61NVh-WD_WWt_VF-U_lfRylFuRVh_J7ppyl7v_r_zwiZzup9gV
rv_smSFFww_vUVqbFzyv7-oF-lVwsuVluMUhfnTyyF3J-cj-MlzP_rZ_jk_XPwUUWWz-paVzBel-ET-4KZNtp-ih9rpcE_plV8DTyGqy_6DzFVwcy-z9Plfd
X5TysABnT0oUrrIewADys8Qv_5zI1hxl_kUBOia9U1QXTF3RkOzrmpZFJaH8mPVnNs_jD4BdVVpUKObebFfOFGnzEa8FFZpuw5-D4FYe3n_RAlr_3_DHl-9l
95g9CDvot-4ZOIP2Gp_wVkr70kjCX13qtM-9Rp8R8V-gasM-ms_T6KiX5n6AvkpTzsjpVk-ksuOCbeyK4IOyhDvx-362rGyVVD_zsH_ynTtXn-YK7pD-yoLf
xl0n-jq7tpxzFwDCPpR9Zi37a9txZRU3Rp4gVuQPvS-enPpvI3ZpGx_m_uxictdWOxZ1H_Tr7yFme_jJFaOyV7H_oCTex6SRPjdFnsxuLl3vXYzROQJiwrOQ
yPBliXM7MiMdhJviaxwLo-FqcFfDqVrMXEgbhoeh-FVthpY1YiGrvhhyCxy1
}

