sprite $no_title_9 [96x105/16z] {
xTa7Skiy30JWe5A-_u7_mg6N80mn6Zs_dfsI_YrDMu8KV_p8VEKhz5rrSTVlra3YFKhVJ_zU3QI-nDxR0FrxFG2sxwQZ8UloXbrYDMLylkZfURYf_nyqa0Hz
nFYsReWk24tzVeFO6i5Ffdw_WQtYiVmK-TRrPq2IVYkSTHA39UOz9lEtUQV1K0N2kkgzZ4A3CVJYUIZr7Y3CGHzH_73LqR3NKqFGSqFIqR3JomReHGD1tpQG
vd2n_EfuOuMyFNjBeTSDBp_KQuS3Jnri-3Jh77vFjph2IKzVhdewDZOw2Q5XqVDcSTH784hGILPV14RKSqFIqP12vffyD41FaK979EbU-B61Ndagbuzmr0iV
1MYeTJHaVQJh9_wwpVIg4pvT6kB63hwT-pmvMNJEPKcdwRV2Lnr-t0vPzTGWKJVxn1VumKWw6X3evl1RzWSF7mRq7CvwxTVxWmRuHMZLpU6tmbSDFdB-23Zf
Tts4LXtH9m-_5RwMllMbvmReFU0B7zduP2PB0yslgF9R3wVNdnI-3Jys15s3x_2xBjKCoBx1ZvSzq4zzXvuRDZuQfgu6t-53hqBHj-IxAqLThV8nB-lvMFim
y5e8FdWFXalQJU7aM_8z-mRVHwRUccmk6tZmqP-2dlWIzDAFrmcV-mQ_qDjH-IX00tpV-WQDkhxp4Txw1j-N-JZuqi_paU5xzWs-Slnj7lpENsSB1Jxx70Zp
TjbV3jRADwmVka__EFMbkcbNh_rqyzKk-wyNuialT6_mZqzyGtGUuDd7rglxRT-MctRuomsC3Hx-yUhJnYT1m_05EqEl_k2FFB_E_N1qza_25IZ3Rwllu15-
-fByVDS3tRhYgr_fs81w_Jr2YsvcqM_meLSXhlmHfLKtXz-cN-eSLoUrZmPIE_KHvSLVvbVju_Ll8mw_PL-F1-zkUs_vHbD_57xHu1lVuHTwxI__nEl4LL-V
EXt7tf-HhU_mkmwfyzcNmNTVP3Oaly7twKFNYtwOBglVAXzwExh_EFDj-cPAMz_XGs_7tZVuUReO-EHhq9_-uwhldXhW3ru8UkVtlYM_4nRdTrjywD86VyFt
E8Act_LdVECZd7qlhkYrUVTDK0h_M7sCnxK1lWVVVJPWYFLYvzA7dXjgFyylwDxW7y4l9W0QXk_PTzSNlVQXbw7QxuRIgdlh_kGVOBOHyD4V3T2ZVuo0k5W0
luruVq62NtszyLxQ9R_Mzs4DVgly5locjzun7Nwh_0R_Q7BtFTahlaE_5sgLt-0ZlvYFiAy-U0V_hWRuEDZU5BB5Vw-E-G9VFxv7PFZoyRt27tzIllALVm4
}

