sprite $no_title_10 [96x130/16z] {
xTW7ekCu30FGa28fxVqFFCtA62iRAZ_Arc3Bz0Vuosdpm7poYRnNZnpwHlr7yhiQn2826_RhDHaQTkflQq0T6_Rh-nkIWxcz0VNz3Ue_4ztOQ_gWmUJBkZc4
y5_M1NJQe1jq2DTrKGUUDIJG8zPqir63eHuBlYGp6pNOvObfNUSD9gWVMT4nHA-f-gIlTfT6XpibnPabdHU0hdxgUSNd3Gbr3-RphpvDeuiv-fduAmr9K0UU
-8iDWgy8lmByq1To35Hl_TptDVKQXBmYhFY9DkZzi-hv_6zpVa8e3NJ7f-YOyysQXaP7tl5PLARy2kBF2TOrFhuwshHl9kInJUOVcV7XThdgz_xZ6PlUVstG
P1V_yleRa_ihb9fplftl2ApvpmQ1doU7Qy1ml-NTsvzt2DwRnVVxC3zAaLTyk_euNqifiSDlvrSqbn_H9T_Hf_CFqyhFv0dVY4_c6ymlnNRxzN2z70Nv5P_F
bvpX0ZRvEFy7Nmj6Vijp_tnhhld8JzzVyTlv5Oj3Fwv05lqWFjoR-SXHuI_u3e5xymmyoBWlec1rV3ddmnN4m4-_lctyrFfuRsBW0eXVhpgr-zlvTQVd9YKF
V1De2DWF_7blHhHyiO4F3U0tyxtEZwWDaAwF3OdxYf-xcYkmiU-_6lJq6zvW_lKAPEoxcwe7ymNcNmkS-UrR7FIlyyMT5CYox-ZNVVRh-tS5qV7beTp7mzNw
mxi2fJu-VkEtxv3VX-ky8FZ-Uj8TNyX796mmwflMxwFFvlC2vcC3-krySyorm3g-ruPquqUgzsODlGBf-Ewcn7_Uc-RUlmAdlXzHzHjVZ_dM5bmV2C9ydDJw
zfnlRjQ_0X_uSUVBvVMI5-YYZ_DhkgSSzxup7-TNlbzWgtwgXmlfVOsYvyUD3r-TgIkmDLzX_jmLtFXEV3ZS-G9RyE5m8OC7WipwV3xmrqDmviV5x_xrA2tG
ndVcfyUlo9-Z8YfAOcewvLkT_q96-zDUFzhzkiTtvjkR_J1jZ_RkPB_kNrzYova_dfdqO-0JVkWxy-FD_Xo_xkV3Zxr-S3-33_nsl_mh_8m-ygWl-p7XGpRw
-StxMxxryvgV6p_t_QAFBJxoLET-37tW2z7NVCQZlkxdIR_OOox6V7QwNEVxO-JZVDJt-qIdCUQJ-QYlxy_41tqnYZpwm6VGboCsz1jzlU7Up-YRFBuUTU0l
Fj6Nadf-47qfrlgvXkZB4MjyqFT40ln3ryVMQ80F-hxeqmTzR-puF-Z_mNpooNS
}

