sprite $no_title_8 [96x105/16z] {
xTZfbgme40HW8JVh_HzuDZCDZ4AESwlhNyVCtUjyeJGWzeRyvZVDNBwg_vilDVH3_r93B_ih3MBEaQ_ghbyOUjPLFgTLMqqTrd_WDjJCB1iqTO7-MKDJg_Hg
CDBHy86EXWRziuPc21emJXpzL3SJpDOFVGmEZq-VJzTZ1lH7T9TZkWZfMQhLmDSkZ-wYgwef6aZ7TEt6Ujt98g97J7iEjPcMZc39cOpwkg6LFZRqFjuADtJI
gO5qJfz_iJ5efAyQkawId-fJNrRBmVl64SAbZUtpgsyt2qB8BeNr9lax6YDyKOGQIATqrl-DeO5ruuQvBWqDfACXITADbXpqrk7BqD2Wew2UCilfsatee0GV
3QJJWY2T6WRTWtoHllAn7hfDqouw-Ui6wBSDdNIFcJyYcqocwxbjAEkLGv_wnqNsTcdWwKeDf6_jvDdNz4NxUheQbXoFUrluekadMGspwOebD-e6FoRN3tzi
89sMt4M77---ulgFZ9E9yBm7rjU-mgyi6nhhPfv-a5yy-wOqHbDTxO4lKz_egm0TCV3f1_kbatzCFXDQShGNFl3xohzkNZBgggFlwITl6zBwnBVoqK3FegcV
UkEFis_miu4-Jhx3Pxrsb1k_qaUTVKy_8evB4NnSjHhWsxllrajV-Ab7Z7urjAaFWTOQ_jtJtqedlnhAD_ZWsRU9Nthix6CdBlwvdwV2rCbllECqUVSTFdZu
fMzU_9sVzq2-B_rw2pZcpzh7itRXq_ghjm3u-wsFOUhmVUMNxl7CDxDgMFYM_gbxmD_N_hXQYoVVoYzzzFULJsyGVU3v-dlgoJ_skU7gasx9mzyV-I2sPkpZ
kEl-cO-NqVGxPfWC1ohuE_dRqgzjiockFtMpbJ--loryTpyR3l_Kooy--jQAvqUCh7ntFEMnGyrzwFn6TEDNXFJH3_Yb8mrRpi97G-dm0txfkZVuMWrhtutU
NlpTB_trklZLyD3d0rNvIUpxY_rXs_nZNqkV-tN8WU1NF-3pWUqybcWa3vysB1XFVUXR-rSdlr_yOPJyuWVvdlumCZtzryItzB5jakynzICyzTWNli4Vlg4m
-d7rFVrJZ_IJN_Xes6O-7QXAZptzryGtyl7mK_0tVjE8_-yFsoRxnKlgoQV_clX6Fgwl6eBzsb6Z-8LlTtwlyuVwnK-zjQsn_tha--dNjYaEFtMz7DZOtv2-
zF4zvlJxEMZzpI-Tdr-d3nv-vEauVqhT0_v-yNSjbnhay9rzR31RwNS-T4wxymFld8Fk0N-77pBNw_bLFFdOuBix-pjyw3Sf7dvSVG7FVjiUHEoH7-c3D_3h
T1lzUEIplawpqu-fpmSsXVwquRaVklr9TE47_AM-ZZpmPVieSpyoRViupTa_UUlRJwGP-wH_7Xrzskv-gW4-z9-CdBvkNqdEHLpwb_ERt_mD
}

