sprite $no_title_4 [96x107/16z] {
xTdfVfiw50HmIpDdeU__m3U8-Q6e0k8G--xJJzt-8nqfu3QFltl-Jp6yLOy8nxjq-aVUrj3qjpL0-3iQfB-j0IRrBGsmZ_X1mklFzMhAxEDLkl9olT36p7gf
hzDx0_UlPyTjdJmfOEctzgPVm2qsPT3btzALIzq3tzShbRcWxlVAR_YA_Ba1_LYLa7zx1ygWqsR__Waekmwpd_Zri07xiTh0Vz_7JjLPhsO_zuU6GUV4t_B9
sadk0oDVvaiT3tpcR_kzeUilyxd5-cGg-Nf_VzXKNF0_yesQpHjyc_o9l-VpTvzlzsV-_RxulEdRd-lF_5sVt_BpLVxCt_UhkA_zlEDNFUdVvt-aZlxCt_Tx
Wt_XvqsVsuDJ_Yb_tpTZ-ThFUxuyKlxbyhFSyULT-E9zU4UNMiepzwVWEJ_gJjSAhOkevTflQFTFnsFzxKy0eFvGXDSBdtWqzYjVHWMu1g3qY7JKSryDLVun
RrexiFfeFro_Im14FVNrOPmNlgubZ6ZO6lDOuuxLW5izzgq5y6DVl7wBsDFmhI_2GO0NlhdycTTmghiAs5JNPbOYWh1qdFj-xlisUVTMi95GrE2vXa3vqf_u
s4Rlkqyp5TIz83BJ0MBoxIk_QZWg8CsClnUOVDOBt-GFl8jNR0jRGwrLFaC-wtTyBRzuZBucL7k1hJv9Opdo_TZNyXdnMy6gbzgoRy3HD0o-pVwy_6Y-8hwi
wHkWf-bYbQTzBT_YSu4UclBt3PW3DC9PB_s13sZvlS2Dm0THMhhFLW8kP9byF_FRrHzzFV7L81_ouGPdz-tArtWyFXVO_gISDa0p61XnwS_ZoOsEQ7m_lz4F
WWJW4UL9l_r1P3fNmcCRpfcV1X2C27PVVFUdhzt8t5VcG3drbuyuF2BZIR_zGZOVQvmeQmxddwlVbfzPhlt-NXbzWox-p3TVoy-iHtuS-dNpsHJvokX_Mlw2
mVSplmv-Iwq3tttNyflFIr-yhezb1ZUx-VM0r_Z9nkVYp_dw7nRFTAfYpQwBdyQpv84VpQyxBzy8h6kAxlTqFZxuX4NavFknh_dG3DZUVWSDa6_zyg-3YkTy
jFaROIjFj1pnpD7tQpz6tuXmiD-XReltPT5y6h_OxCViP_i5SpCmeO8fRDDf8UNZqWybNHVA2RSLuZ6V6__BuPjVkcz-vkVsdFAj8B0NSD3fY_XV2zZuV5pv
iVjPzE4X77HqjUDaBE8_ud2DHoaqyPEVUaxLM6EmT9gtBibQlFWMmZDG7ZtLJdtTWb21vvfMe0QBN4P_8QRFwHZzK9hUtx---Ye8WXODxxpYxXf_3sRV-XuX
Fx8Nc4vov1LsMIdS_LtlyLKcSkb-EE0d_F8uI77vkzvJLvLSvAk0i1nvfJuE0sz-rtjiywU2jK5wJrv-iwJCxNe7juT0zzK0S_TXEkNn_K3htpUWwDzuFXpk
dKGwV2xm5dAOpfsKJ9sdV4KVgFiPbCUzS5aSZ7b2Rf_dOpTv5I3c2O5zzVwudv9B0ZxVePpEzcPiIOBZ1jY7izJRSjy2E4p8EX-F5uJmptU8i4LwURmcbPxA
Ffn5-cjIAimzme5iE1ulJocrWfdE-lXxvl_y0G
}

