sprite $no_title_0 [96x165/16z] {
xTY7ajiy40DWSybTwjx_WVyQtS0qP1WUfWVJKpv0nRnokyoV_4cl-9hw_2TEWwz_jOQeV-8q-3espDYiGu7HuEhxhw41lFyQMXQFqU3g_ZNuUictLUkf_9hr
TaF-5zrmfYozV-5VleQmTQDXTbjt6Ynz9CqcFHPMDYGU8ytNCKAlQbgt6jfoI3MbwppHQrxxCKOEfm7rBE77-99N2_0uE7NqkJvUlGZGEtxC6jMNIBqJ7Nok
YslGUatmGQTvHG-mgTy8BAu1z5pvrU_ZUPxhAVrRg89neRTSUEhh1lJRUi8I7dpp6cBHXUyy1gPp7lqUBpS4EGErtpkv1g6FQvxuTmrNFEh3zR4Xb4vuxOzu
qh1yqiLyxe_BXiURbuv_yXSDRT75VEwFFdX3e6xuVFyYTcmJlFH90z7bVExV_-VHLhqBNlZu_pENXi1wFL_l_o_zKoVy1ZyJhcufqFo1FkUpmTyItl7xKxyB
NlhZUl-Ryz-_F-duUhytN-_FHx_R_e4-wDmNlF3rVd--iL_nscVpVN-A_SAtNaxJnmYU-iFRh-TV-ybypU_t1V-Udrlz8hxWgKy0yEtRO_hTug_zMt3Vdi_z
M7zgo8BzX3VzSNupilhcVExZTuN1VEHzdpIG_OhNVfuDFRDMtvY_-aZqVoi2VCRxFX8HANp12pyJVC7lzndl-mM-_N9oFuKlUE57YFtEV7x-nA0-vtqVZvyI
lkBHvuS3-hd3py-6JlOhVlK_7dpugRGjlZcV-_ZxwW2VyNe-yS_qTkksVoW_CGK-uNVx_krvxXVw_ilf-_xyrK_Vfxpl-q_tux1yVxxONyn7tlTJ-DRJtUqV
6tnZll9B-6e-kVyfVFVf-hx1VsU_Y6yyNUQdwoE_mJUEdYq-ykx-8hunt_VLqzNt9v_vtjDr_7dkDrvEt_UE7kdNer_2L_jJ-pwl_VbjVEVfQhyS_zZfw_cU
FwL_BDdj4rtvHNn__dxVtp_Hzv-kx-kZH_kbV3tVz-tv-tr__sJ-X2W-RhQlvwDE_AA-DnzrtqSUi-ZIdvQFUWVOyFLyrBbVx_f4jttzT0j8uK_qzVm3zFq-
sKxzuhwUZ_f-d-ZAd-YBfwjqtx_JsqrduPdFvq-YauJb4rsc6pxNTGFow1EUw3hzPP_hEddbJmZeTbfA_vXXizXmQk0ZBtNTG7oXcucwyFjjK_gThtK_7Nn3
DrBW6xgHEdr3jzB-ymrzR_xaJ_u6
}

