sprite $no_title_20 [96x155/16z] {
xTY9bfqg44RX1ghmvFqVE8EQ3UfVBfPUxboPfszpDCt1_lhRpF-JfkhPtVCqFVasQOvk_diiJGhyOmlCh4BESrz3BeM2gy9xVr81Vr81Vr81Vs81FowKzDQV
LC2VLC2VLC0VB3prrO05XVS-azyLKkZdzCSKSkIRJIhWpohWlo_aH47uxmkvg8BXloYWKb1-NCY3_hLW-DT26IpWioNmQyD_NS0dy9M5_w0WVGhITzU5OPz8
LlwAsPSgZFg5WlAD_vUYCEYtGXBBnnU5GT_Cykz_VlGDV-WgQT_CP675yNsaeFrZ8L5mw_tnmi57knGGyBk2tHNIsMTAAxZRmQSmShXF-D3dWZEzFrxGVd-d
bQyBffvVqgyVZL7tuUgJx0ypqVEBy4K1NnSitJs_5DF3PJJjrreDSOEQlywUpRBWl-ZV1UqV2iNzxBT2u6VFUm6_vociWjUh7nTyytql29zPGUd71SUda2H_
xw-MAhZXjqBkUH_pTS5PVr00n_U33wyBRlYg08zlWQyBxeul2gE-sDUsWXk-B8pvyYDs1_1r8Ndi4x1peJzP2r-y1kMhJG6_jFk07nHAu5FGllbU27sSSl1h
yoaetvn2adnrXABzd2bS_DMWK2BV4WNXYzqVdtSFNQYRxzNtWWbV7zZqiIOLxLSAqhyMy9b2eUVnMo6R7tmp4mLyKP0-XHJutRaRFoWOVFFvLRxn2mNyi52h
upFusc-l0Zyir5eV-1GElZwkFV4f450-EwVsQ-oBWl2vIlxCzw20xnGU-URcKS5saR_mm8-t7VokaFpYBzrTAis7rmLymC8xMFCTdyBPPyJcZ2yAmgU03wyA
-AAWVCxTmjS5VCOf23zRRY7uq_0XZN-Ql6FAjxrmwrFGVdKCuLD8y1U_7TxnPK7xPjo7oES-uEj2ygfyQ_kYzli7PnCwxo-HprNAfls1mhtFLSgXNok56t-9
VASG-g8WV0zyfv2KlpEoeFrouhj2LhueZA-VVPD2y-55ON3zphJyrMUSmiN_0AIUjzxdDU33g8Bs-rS0lekSktU_Yh6lhh08dm8yVhlJkoyApR6wR7x5xmhQ
xme5_EAtEotyH47u57H0FL_Wu_8chlrMiD2l58Hlee0l2ifV2_ZBqUyBsgUGBFINnLFecrFGlbSAsbz-ZKU-UtSk5_vAK13-iatWSzwaW0-l2_Yrzpyddy-R
SjJHVYjuxxFyqBVTTmgzhuvhoSTzph9oSsu-8eNDXuzymrT7JdXyep3YxoX-Vp3NFljcMlsbzylgrzut_3Qv5QhmALpyVFQx9GV7PkctWftMl_H-AWTV5xHF
8NldPtmAsjSR6_wnKENwAGXV5l15GQwVWl35WH1V5jJwAMJj7sway7-jkXKs_uD_6itNofvXqcy5xJCM-tbl63xyLYZtldwugFY5Dq3jKyZuSlAHz-RNLZZn
5FAzh_PDV74WX6VazT45UFnhOQd2NuGl2jhl3-RW0xugrDutUMn-ubCGwnS5wN-JlYxWwyAJzJF5pzU7MIYS_G_h7oc4_j8AptmAN9-ZtnSU-HJ4-dSGnvxu
pAsVABpmquN7hqxXWSzOwBVx8Fm71NZyhc3u3mlQfv2V-npzuV4fFBy-5F3mcNVNXyAj_ul7VrgOvbEOvLFmQJw5QJw5MJw5MJuptqy-owTG3_utxRyliFvF
UiVf0dx-cZ6vhlwowpCAl1l_1-R_-G4
}

