sprite $no_title_12 [96x65/16z] {
xPQ7aUGm30GrWcF-2PzbZV2_3ZnXowe3w1R9CxETvm9o2z1YXgZV4j-u6olhMX5LysS4CwOYgCl5Vl42GLnHSEzg6QzGJe3obKGKJx7Jlf1W8uX9tKwMdYAq
O3-Ly7yB-arlmf7qfAFW36HzVy9vzwGpuI4t_jv4zlSdw8UItWJo0_GdPEePQ4nGpq1dWde2qTQ4OICyGbz2ibbHECB4z7N2P0fr-eVDqYvw-XIAARD1_nWu
biYPWWf5OsJ_iEEfbq-HvHCRsV-38ISAZOTon1Yt_X61ZTGYl-OTsm4iugu_lZ7SB2tiTqCY-mxW_m4I4O_y4qydlMtXnfda7l7Q7-wkR1JvdQbHy_zYjVKA
27zlr_n4UTNfeaJLo3c_sV6ewQcjpQzlyL_-ot_vBp_UvUTIUO_VyfhezzjseFr-tJA8NZ-d3j5ElsstmBhyXaS3fi5liZr1x9JV2xi9-aU_2UfhpDRytCzr
8A8Llygg-dO_t_gvdnl1fCzuyGa
}

