sprite $no_title_13 [96x65/16z] {
xPK7WkGm20HfQ93__-BJfGd2EwEq5rqFg6f7oN_F1G1LCvBkpegfAe1bhxbxlC4Dq-vAT475W5hD7uXEQEYHqpFHYslNJLb94F8HQVfSmj5nPvOIAXbB-eK4
yvrdPL_2qOo_iIjXJxU-iZkXQVxU1DF-lGbDztzhmjC3tffmaHJOc71fWN4naNvpkR2QIFPKM4uGajXt4UVJYQV2RCAUD9GRvGZ88sE9B1V4KHxzHotCtoYg
I6C_MlzHYagRiFU9VAnhASUPlq982s3d6JC380rWAH_wAq78DB0evQM_4c6Ob5TxZxz23CePbNv_nHMzSe_Ag3--lnp02p5WT8-OzN-7j1D8_ycYttd3Z3Us
-NdkztzY_xN_sX-ViJ_aXdx6VfKxiNz_o2EnUt_8Cx5tVqWBT-wdP7JVVfKp47ls1rwSqglxWv1NgA_iTvNtAEVskq7wWFheVbSP131Zsf_yD0Da7W1cHZi1
WFpVN7m1
}

