sprite $no_title_3 [96x76/16z] {
xTY7hlCw30DWYLezx__2zzg4qxWdNQZpRs9rVbGs4f5_GIREqpLxS98UEO8JTCzzi5gFYBtlItaFPkYnLBUufklQAdsH3ezzg5kcBz9RTZvu5ApnuIEtUfOl
6vy9wXgvo6VCHxhkiT0tkpROjYUHN-Cxs32AEay_blZE1kfNlzRvtAoO-BL-WFmq_XBVPp_EywVnL_fnuDSf_Zp-vJo_Lla--VFuItmJdEgxGK1_tZalQ_oc
ckVmymm_OlPheM_muS_ZhveVeZxxjTIFSBNcprjtcK-MViv-dkBNyByU-vQ9vtvi_ZJ-Kn_PWxVyUVm7FYAJ2Ntk9_rf_4S-E5IBoSFespx_mwIhgEEH7vjl
SSCV-shkJjxr-KRU-VcIRzuJuU16hgVpv_3dhNliYx91HJJoVN-CN-660rnx0xWPtlOvVa3bC8qsVcVEVzRRllKlODu6Z70twCxtyARtRr_oS_Prkr_ANHnN
F_Jgrrj-LUxsxxaYkE_J9_-wNyCVr_cZ2kr-R3xvoyi-rqxp3ole6ttoh_Wv-U0wFgXmxUjVyAa_6gOAK_xU7J9yyg_urVtgVXahHaUue-5eNsY7LSa_zqM_
-vSAV3-k_fUCwsVuvEa_28PVBTBygWpePiD8zVd3D5Gx_zndiFcGuIUFt74SxVo8lFeN-i-2vYT4Nl6J_XZ_2_92L5Ja1J_eRwkd7F9U_9vVEllRgG60jG3G
LmeEVMB3x-D7i-tcDENsj0EHt_mqVhNpmRVCcm_kqE3kjnXdef_37qyh3YfKti-jRwBUSbHXd_lb8d0_h71Puu_rE3UOoWT-PfPgLhdmSTTSOUY_MkB7fJYh
Zl1K-CcDEMQ_AgVLePQVtlXRywj29QOZtNYaVEoBXcf0PBa_vtpVxlekIn9t_915GHxuQR8ki9ZyCCZow8ZyulaF
}

