sprite $no_title_18 [96x97/16z] {
xTXBZkjG28HX7m8Sxt_5L_r8q2sHGiXXrAv-P9JljyWinn_PlNltn5q6TVEloQGUXG4z9aDwJ0RqaOBOrmOAeGyKG1yeX3vJ44NzUW7rWGBe0uNGHmgYNnie
X3vG07sW07wZWFv00VI1GkW31T0d2bAHieuZjde5WVSc_kFHA53TFVSR1Qhxplr6WUZK_nelrBflvgigBrIwxy8l2xbkNlZ1Vwqge1uyyuFWXOMwUTitK9WU
_cO-7W6aTphost8V-QIGw1qV-Q_z9wAEFFCL_2WG7NZc0my5rDLwFl2u1NhACrzpFmG1FUEvZpmAn_SU-hKvd_3CPppuX2S-uT6tQP_p9_4J7dqZFF4v7txz
-DTyA_dJCv_puIldkM-rNpr-o_V4vppn6Hy-vRblb_spvJlnWIzzmeFFUERRPVzi-Kvyv6kVyE0JdlXM-hlmJ-hNVFW9t_MzxP_WmvPoVuTVy5kET4iO7pw_
ZeEU5hpd1s_hu9FSt-6_vxU6GmgQyU5d_8Qpyotj-d3sSak01n_uRUleJf0F7tbjqbZWlbpzvdyd_lwTWzxTqjJldfr_r6zy9Nfhuk33OJvJ2B_M-riMlian
iAK_hnyv-xrxz-xz0m
}

