sprite $no_title_14 [96x95/16z] {
xTW7SYGn28LX2VJGxFqFxD2K1mgtK0VDvdzp-hG6JIYNFw7_4RyGhomYU9NE8Xg_P31YxVtnAtrglVFBV9R-MLtcjs8Hf6jotu_RhKssz00iy5kDzycTm3Tz
a5-f-EwlW3WypcBtLs0h7THn7syoxkwZe38axyuA25kITtak-4hIS8a7V9B5LoOJaoGwxJSWjcm5B9_VuNjhLl39k0dv5go0dXylOwUxAs3tqMAtMok0Vp6f
sEtw2iX6MVqbZLrS0TiWkLMzfOEkh00snlRHO0NP0VFPR6fjdt6OKEpS2fgDa9fMmoMDdLa1_EY_qeDnvWHAPYFLU3kW8ajYuzb0Hsy1f1FAcg-WskYKDn_v
XBJ92iWDZW8FkwH9-GgQ7ttqOPSqArt1SsWjy5jsITEI5P1xK4K_h20fMO4ERC33NTAy_65S1toyfFCJGEM47oQKvzxDvpvmzW0Rvba_lwJnx-L-vCzSKahq
n4ycbEYfZzZp4OBzTAcvd_7sof3hbFkbUb_Czo_BuwLoxnFVpq0UNOptJr5XxAPFVVt9b__HTeJ4bsP0QsJ_klU3lfwWlXuXtryzmzZHjRclDVFr23yXZNS-
7V6uwEi9wjUeYqXVualPujRSKiNpftmC_59tFfMY_18_wjBDbsK-GI8_znkbyxVXC21NV3IQ-4rrO8__CV7rCPdxQ1ZnSr-Zr7Ty_EzFV5WxVXVtLd6VptqS
yKUy-hZkT_MpwUG-JlgHl-Ttvqlm7mlzP3gh_SZdVcc17_Z9T7A_K3lW9zC9Vdw2JFp8QsHM_YYGaIzZ_y7bG9LJVyWBbQCnPEP7Ncev4-EKZt8wGkPxFXbx
6Wzzp_TCpyFS5oftuZtVUDLlnJtungCiYMJNvxAi2kTll71P6qFCLtrr9Eg3oekg-jrVql_-zmu
}

