sprite $no_title_11 [96x130/16z] {
xTW7cYCh30HW0vBeT_y3Rv1xN1uNgC7WbslpXByaT_gyjtzK_ayo_QXUV-LZ3LhT_r23cfdx7saGkmSDQRlE3Vlr_Gq5xlO6rhbXILTL-rX3Liz5WwKbFMvO
r-E6lAeZaQvpkYY72mgkZpgX9n7HTZgwaH_hSjqWtw-FEgd73T2pUUgW3pngq6ST_hWUDwGlNS7NIHtfwSdrOJz3Z1fmmgk29v_rCAGBUFYB3T2Bwh2F50a3
NObtVwcXq8rfmY-N3QIhWh_sowCXnJhnetx93wIhYpRy8cD-aNP3mc8jFjrkPT0NRi17H9g-BsU3_ai3zJNy-sT7V9eul-Z4u_5eGpurGE-FxydZFXgWX-Fx
2Q1JFcx2kPJ0zyVCyNk9L8_81my87--ExvCVn-y_PAkFSpCTn-4lJNtFby3tC-VubTz5PT5dlfpZ-m9nc3_zw_4zik8pZtFpEBFLn_ZrozVt_A7nFIdqYR_q
rSUl3zys-tvDrOg6jE0pxvTMzPn-dVGjz6_tUzfpWxpjCrym_j02nCE_6XyLiitFz_71tmjcV8DFl1zwgrIWePzl-TB7-08V3IdoVUcYv7V6DtCNYHPuUkZc
Ip_v-Cs2rFTHaGK-yUUbPVUy5jJ8HuEezNt_-9TlBmKI-ewL5Fe5usC1vDBtm6-EhsgFq09hlfzbIWN8W8z1YTVx-461Hhw6FiRtT0fI__hAL_FBEJvuBj2-
VpR0Vnq_dH-ZYei5SExxBS8wlf-RYWyeV8DlRHzlShFYH4HGsInuYlHyLVKbIjlFU9SNlqHTtvDvVeUqSSUpPe44lbFmUNpm_GtUy37-wmRA1TBqbNqUtwCe
Q5y8QTeNVauZrA2Jlbd2-E46XWKwlhNy4lxd9Hy3Or_PvuDB6_GkPPdnpuDB2Ow1pVWqFct0Dmlf-4O-nf_Q87ttjUzZVDv0klSA6VLnRdB0yscK1dt1-CqT
UfUojdnZ_xQSnlZruSi_spShwKp-_IEdtCoOR-JppVVuoX_FUTEtBJw_FA4FVjrdVi6t5_zo_Ft-yOxFBu_xuVZ_0B_5h_Wsw3CV-pG-VE8_xeFVxnzBynlv
u-FRX5yl_OFr1PzvqlVwCpfy8pyQ7_fsd_GvluxwDTtMVUOFw3E-3VZWZqpAlDyTlqAVzkk5Zzbt-XWV-d2auzFuqASRxDg7Ff-auE63XxxG4FZG5nh81mzz
9RddGrzjQFdbjZ45VlN8RNC4FlIjqTE7lZl-vBZI_y__-Ga
}

