sprite $no_title_16 [96x97/16z] {
xTa7Zjmm34PXqwOav_u7JcCARJtarmGqgeco_Nk4DDktl_FEEzwxFwht_bJ10eT2jLvViDQdyM8T2kLwVS5Q0x-giBUOaWBhZnMEfDSNFD2Q0kkr1TRh2mPw
NS7StLjHWVMg0kkF5VQirnV2h2lO_FbQL62T2peXzE82wsPqpUi5rit_F7SSiY1crll8VaMXPRrV_Ll1FY_Sz3ukVimk2kjw7vCV8mjQ9nyAufEQzVQN7-ox
7oO-gOKUFFh1hHLOrtxCKi6pdddqCwyBTptpqe_P__afb_NWfJ-j20NKONtmwP3v4sBBUl3QzsFYeG0wh8_-pCTaq2yvvjbtyA6GTE25ZtoCJNfw5-BFv6k-
zMPP5_paE_fNebdIy-betm_1n_ZVp-Qcrh_wWWTVyTdtJ_tCQr_omWSUVC4dNwv_LldCiw_vy9TE9_kxuAVznVh1V-7zjI_Md_rTyzbVvC4dddrzEict__M1
9tyNFFYQpxxYsU_e1r_YCyy-y-phoqLVyoDyUJhdei_xBvmE-dhzjByu7V0N-F1X_L9VyUnhFldYTC3NFFkZtXVyx6-sm2U_eqyy5PWdNryk5xIl7veqBdZm
wGl3wU8lvi2Jp-iF4_zFMFU13rqKW0SVrYTT5mRuTFWTTHxN_ertXdHXi9_N1tsvCC2_ywphiILVwA8m-_2GAYe4bddR2iO7-ptqcaBsGIye91_rWei87owr
g10-w_NppZlV
}

