sprite $no_title_7 [96x138/16z] {
xTQBegGe30HG0acm__-7TtF5wcu44tPrdrFpdf4ZZHdhfkVpAvH_3psb6rui-GcTm1TcUfPdfYTv2pt9MsxrJxn8zZTb2V5qveM3QoBpFE15mWUQNN_4AuMV
L_7y4QyKvVqRZ7YbXMdBWVr3ttbTchPhdmQyBaoREyq3dkFJvaypdNYbfMaJxmdt_7maQ3XjLxXjjUFbukeHhrVN_pmTbqT6lCvrkuPicNCuo8YNoqVRvgli
bqAVX0RJbfs7Uw1q_1MbUSwypaQDtYjoGlBrH1D7fotZYuNCp2LJ8ihICZ-dx4yRV1G4OH5IXeTZFtay_8RFxf1F-dxNp14-GO_UWVcOXT9ueRMUxkvGXiFp
hW5iCzBJ44QR1zDN8ea8nNiQT-2s2DRtiD7nTla9h_LqFlv0h08V7tCwR7vFv_wZgyBVGyueE3tDE9XiW9vyTkxWz7HkTPIPXpvRQ3Xi8kJtD3M_ZT78j-JJ
i4c9zNJpiVsnZt78p9ywkJtDbpv_v20_FeworzFms_7KkIzIwBjfvSCVyRslZY_2T7ZxzUpsTE_NldWH38tf3D_fQMb-EvwP3zwk9amRUprDzllcQzZ7DB3N
q_dAPy-lxFMqD1_7C_FbsnVu5ptTjjzyNVIr-UZfVEAJNFdi-RKoUfhRq8B76CCtVfluWkZRgLMQF-zfEdnTz1N-gQVfwzsKPUopvrVufbptz74ysmP_mfil
dpxb9Wvwck3heg_mwQgd6TooN-5RtAy4I8r_TVwPDnzF2pvwEarxElzHl-_fCkvfMlCh_61Fa_6TF-3DnpJ0zteQ_clTd_SqeQSFtrQqb4k_clyQ-I8yx6dQ
Dg7q4HhovhVjmm_rD67lICmVlsbptzDKKvyyyzlnm8_qDAMnBnD_Wn_iQTVNYSzt--ruuCTwkkIHBnD_ssgX1D_lQLB7rszVC89-JykQNosf9ThJL4U-J7o9
zxJlWwVSV4eBFHtsxGAnTGbnUixpfVUHJ25VVPz-Vj4ldqIZVeLV9dxARtzNMRNIKe-EVJdvXN_--dPVuPkYSR_UuViz6lVRqDthwzIFztJSL_WhFRsj-iYV
zlNju_yynNjwqTVU9wUdR_RrLj_lwNNVbj5AJuTz5j6JJv6Upgz5Vx6d9UvN-D6U9gxRah_1Z_GqsuAWh_3TdWOeng_wqPvUzTjKKx2dFL-_VRopADxJvh_M
_NXFotQJt_UexsllD_u1lqvylwV5UA70_kNQrwbllmvyxVOlMkE-mhUbdb_X6x_aGr_rupqzJX7NztlkCkNmw-wtohlDJvHwVpD_Is7V3PtyhIpqj1yIhH--
wRwl4H-4ldrEwKOVYEw-K8hwDUQ3oIanBdTzzDnQehx-wttqz7hydcl7_vYl_p9VUxyT_ms-qzF_2bzFVdtAh_2DlyEdwvw-8KKUy_sUlYdazFHYrdlQptfF
tnsIhgTl3tKzVMlGquNI_pM_yXi
}

